ALTER TABLE "Driver" ADD COLUMN "idExpiry" DATETIME;
ALTER TABLE "Driver" ADD COLUMN "licenseCategory" TEXT;
ALTER TABLE "Driver" ADD COLUMN "licenseIssueDate" DATETIME;
ALTER TABLE "Driver" ADD COLUMN "medicalExpiry" DATETIME;
ALTER TABLE "Driver" ADD COLUMN "employmentStatus" TEXT NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "Driver" ADD COLUMN "joiningDate" DATETIME;
ALTER TABLE "Driver" ADD COLUMN "tripWage" DECIMAL NOT NULL DEFAULT 0;
