"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

type Option={id:number;nameAr?:string;name?:string;code?:string;plateNumber?:string};
type NoteItem={id:number;itemId:number;quantity:number;weight?:number|null;description?:string|null;materialGrade?:string|null;orderNumber?:string|null;item:{code:string;nameAr:string;unit?:{nameAr:string}}};
type NoteRow={id:number;partyId:number;noteNumber:string;noteType:string;noteDate:string;status:string;stockOwnership:string;transportMethod?:string|null;party:{nameAr:string};items:NoteItem[];trip?:{tripNumber:string}|null;invoiceNumber?:string|null;orderNumber?:string|null;referenceNumber?:string|null;truckId?:number|null;driverId?:number|null;carrierName?:string|null;vehiclePlate?:string|null;driverName?:string|null;driverIdNumber?:string|null;driverPhone?:string|null;source?:string|null;loadingPoint?:string|null;unloadingPoint?:string|null;notes?:string|null;recipientName?:string|null;recipientSignature?:string|null;recipientSignedAt?:string|null;purchasingName?:string|null;purchasingSignature?:string|null;purchasingSignedAt?:string|null;warehouseName?:string|null;warehouseSignature?:string|null;warehouseSignedAt?:string|null;accountantName?:string|null;accountantSignature?:string|null;accountantSignedAt?:string|null};
type Data={notes:NoteRow[];options:{parties:Option[];items:Option[];trucks:Option[];drivers:Option[]}};
const emptyItem={itemId:"",description:"",materialGrade:"",orderNumber:"",quantity:"",weight:""};
const freshForm=()=>({noteType:"RECEIPT",noteDate:new Date().toISOString().slice(0,10),partyId:"",stockOwnership:"PARTY",invoiceNumber:"",orderNumber:"",referenceNumber:"",transportMethod:"CUSTOMER",truckId:"",driverId:"",carrierName:"",vehiclePlate:"",driverName:"",driverIdNumber:"",driverPhone:"",source:"",loadingPoint:"",unloadingPoint:"",notes:"",recipientName:"",recipientSignature:"",recipientSignedAt:"",purchasingName:"",purchasingSignature:"",purchasingSignedAt:"",warehouseName:"",warehouseSignature:"",warehouseSignedAt:"",accountantName:"",accountantSignature:"",accountantSignedAt:""});

export default function NotesClient(){
  const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
  const [showForm,setShowForm]=useState(false),[editingId,setEditingId]=useState<number|null>(null),[expanded,setExpanded]=useState<number|null>(null);
  const [form,setForm]=useState(freshForm()),[items,setItems]=useState([{...emptyItem}]);
  const [filters,setFilters]=useState({q:"",reference:"",status:"",noteType:"",partyId:"",itemId:"",from:"",to:""});
  const load=useCallback(async()=>{setLoading(true);const p=new URLSearchParams(Object.entries(filters).filter(([,v])=>v));try{const r=await fetch(`/api/notes?${p}`,{cache:"no-store"});const x=await r.json();if(!r.ok)throw new Error(x.error);setData(x)}catch(e){setMessage(e instanceof Error?e.message:"تعذر التحميل")}finally{setLoading(false)}},[filters]);
  useEffect(()=>{let cancelled=false;const p=new URLSearchParams(Object.entries(filters).filter(([,v])=>v));fetch(`/api/notes?${p}`,{cache:"no-store"}).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error);if(!cancelled)setData(x)}).catch((e:unknown)=>{if(!cancelled)setMessage(e instanceof Error?e.message:"تعذر التحميل")}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[filters]);
  async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);try{const payload={...form,partyId:Number(form.partyId),truckId:form.truckId?Number(form.truckId):null,driverId:form.driverId?Number(form.driverId):null,items:items.map(x=>({...x,itemId:Number(x.itemId),quantity:Number(x.quantity),weight:x.weight===""?null:Number(x.weight)}))};const r=await fetch(editingId?`/api/notes/${editingId}`:"/api/notes",{method:editingId?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const x=await r.json();if(!r.ok)throw new Error(x.error);setMessage(editingId?"تم تحديث المسودة":`تم إنشاء ${x.noteNumber}`);setForm(freshForm());setItems([{...emptyItem}]);setEditingId(null);setShowForm(false);await load()}catch(e){setMessage(e instanceof Error?e.message:"تعذر الحفظ")}finally{setSaving(false)}}
  async function action(id:number,type:"SUBMIT"|"APPROVE"|"POST"|"CANCEL"){const reason=type==="CANCEL"?window.prompt("سبب الإلغاء"):null;if(type==="CANCEL"&&reason===null)return;setSaving(true);try{const r=await fetch(`/api/notes/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:type,reason})});const x=await r.json();if(!r.ok)throw new Error(x.error);setMessage(type==="POST"?`تم الترحيل${x.trip?` وإنشاء ${x.trip.tripNumber}`:""}`:"تم تحديث السند");await load()}catch(e){setMessage(e instanceof Error?e.message:"تعذر التنفيذ")}finally{setSaving(false)}}
  async function uploadNote(id:number,file:File){const body=new FormData();body.set("entityType","DELIVERY_RECEIPT_NOTE");body.set("entityId",String(id));body.set("file",file);const r=await fetch("/api/attachments",{method:"POST",body});const x=await r.json();setMessage(r.ok?"تم رفع مرفق السند فعليًا":x.error)}
  function edit(note:NoteRow){const next=freshForm();Object.assign(next,{noteType:note.noteType,noteDate:note.noteDate.slice(0,10),partyId:String(note.partyId),stockOwnership:note.stockOwnership,transportMethod:note.transportMethod??"CUSTOMER"});for(const key of Object.keys(next) as Array<keyof typeof next>){if(key in note&&typeof note[key as keyof NoteRow]!=="object")(next as Record<string,string>)[key]=String(note[key as keyof NoteRow]??"").replace(/Z$/,"").slice(0,key.endsWith("SignedAt")?16:999)}next.truckId=String(note.truckId??"");next.driverId=String(note.driverId??"");setForm(next);setItems(note.items.map(x=>({itemId:String(x.itemId),description:x.description??"",materialGrade:x.materialGrade??"",orderNumber:x.orderNumber??"",quantity:String(x.quantity),weight:x.weight==null?"":String(x.weight)})));setEditingId(note.id);setShowForm(true);window.scrollTo({top:0,behavior:"smooth"})}
  return <main dir="rtl" className="min-h-screen bg-slate-50 p-5 text-slate-900 md:p-8"><div className="mx-auto max-w-7xl">
    <header className="mb-6 flex flex-wrap justify-between gap-3"><div><Link href="/" className="text-sm text-blue-700">الرئيسية</Link><h1 className="text-3xl font-bold">سندات الاستلام والتسليم</h1><p className="text-slate-500">إنشاء، مراجعة، اعتماد، ترحيل، عكس وطباعة مع فصل الملكية.</p></div><button onClick={()=>{setShowForm(!showForm);if(showForm){setEditingId(null);setForm(freshForm())}}} className="rounded-xl bg-blue-700 px-5 py-3 font-bold text-white">{showForm?"إغلاق":"سند جديد"}</button></header>
    {message&&<div className="mb-4 rounded-xl border border-blue-200 bg-blue-50 p-3">{message}</div>}
    {showForm&&<form onSubmit={submit} className="mb-6 space-y-5 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">{editingId?"تعديل المسودة":"سند جديد"}</h2><div className="grid gap-3 md:grid-cols-3 xl:grid-cols-4"><Select label="النوع" value={form.noteType} set={v=>setForm({...form,noteType:v})} options={[["RECEIPT","استلام"],["DELIVERY","تسليم"]]}/><Input label="التاريخ" type="date" value={form.noteDate} set={v=>setForm({...form,noteDate:v})}/><Select label="العميل/المورد" value={form.partyId} set={v=>setForm({...form,partyId:v})} options={(data?.options.parties??[]).map(x=>[String(x.id),x.nameAr!])} required/><Select label="الملكية" value={form.stockOwnership} set={v=>setForm({...form,stockOwnership:v})} options={[["PARTY","العميل"],["COMPANY","الشركة"]]}/><Input label="رقم الفاتورة" value={form.invoiceNumber} set={v=>setForm({...form,invoiceNumber:v})}/><Input label="الطلب" value={form.orderNumber} set={v=>setForm({...form,orderNumber:v})}/><Input label="المرجع" value={form.referenceNumber} set={v=>setForm({...form,referenceNumber:v})}/><Select label="النقل" value={form.transportMethod} set={v=>setForm({...form,transportMethod:v})} options={[["COMPANY","سيارات الشركة"],["CUSTOMER","سيارات العميل"],["EXTERNAL","ناقل خارجي"]]}/>{form.transportMethod==="COMPANY"?<><Select label="الشاحنة" value={form.truckId} set={v=>setForm({...form,truckId:v})} options={(data?.options.trucks??[]).map(x=>[String(x.id),x.plateNumber!])}/><Select label="السائق" value={form.driverId} set={v=>setForm({...form,driverId:v})} options={(data?.options.drivers??[]).map(x=>[String(x.id),x.name!])}/></>:<><Input label="الناقل" value={form.carrierName} set={v=>setForm({...form,carrierName:v})}/><Input label="اللوحة" value={form.vehiclePlate} set={v=>setForm({...form,vehiclePlate:v})}/><Input label="السائق" value={form.driverName} set={v=>setForm({...form,driverName:v})}/><Input label="هوية السائق" value={form.driverIdNumber} set={v=>setForm({...form,driverIdNumber:v})}/><Input label="هاتف السائق" value={form.driverPhone} set={v=>setForm({...form,driverPhone:v})}/></>}<Input label="المصدر" value={form.source} set={v=>setForm({...form,source:v})}/><Input label="التحميل" value={form.loadingPoint} set={v=>setForm({...form,loadingPoint:v})}/><Input label="التفريغ" value={form.unloadingPoint} set={v=>setForm({...form,unloadingPoint:v})}/></div>
      <div><div className="mb-2 flex justify-between"><b>المواد (بدون أسعار)</b><button type="button" onClick={()=>setItems([...items,{...emptyItem}])} className="text-blue-700">+ إضافة</button></div>{items.map((row,i)=><div key={i} className="mb-2 grid gap-2 rounded-xl bg-slate-50 p-3 md:grid-cols-6"><Select label="المادة" value={row.itemId} set={v=>setItems(items.map((x,n)=>n===i?{...x,itemId:v}:x))} options={(data?.options.items??[]).map(x=>[String(x.id),`${x.code} — ${x.nameAr}`])} required/><Input label="الكمية" type="number" value={row.quantity} set={v=>setItems(items.map((x,n)=>n===i?{...x,quantity:v}:x))}/><Input label="الوزن" type="number" value={row.weight} set={v=>setItems(items.map((x,n)=>n===i?{...x,weight:v}:x))}/><Input label="الوصف" value={row.description} set={v=>setItems(items.map((x,n)=>n===i?{...x,description:v}:x))}/><Input label="الدرجة" value={row.materialGrade} set={v=>setItems(items.map((x,n)=>n===i?{...x,materialGrade:v}:x))}/><button type="button" disabled={items.length===1} onClick={()=>setItems(items.filter((_,n)=>n!==i))} className="mt-6 text-red-700 disabled:text-slate-300">حذف</button></div>)}</div>
      <div className="grid gap-3 md:grid-cols-4"><Sign title="المستلم" name={form.recipientName} signature={form.recipientSignature} date={form.recipientSignedAt} set={(n,s,d)=>setForm({...form,recipientName:n,recipientSignature:s,recipientSignedAt:d})}/><Sign title="المشتريات" name={form.purchasingName} signature={form.purchasingSignature} date={form.purchasingSignedAt} set={(n,s,d)=>setForm({...form,purchasingName:n,purchasingSignature:s,purchasingSignedAt:d})}/><Sign title="المستودع" name={form.warehouseName} signature={form.warehouseSignature} date={form.warehouseSignedAt} set={(n,s,d)=>setForm({...form,warehouseName:n,warehouseSignature:s,warehouseSignedAt:d})}/><Sign title="المحاسب" name={form.accountantName} signature={form.accountantSignature} date={form.accountantSignedAt} set={(n,s,d)=>setForm({...form,accountantName:n,accountantSignature:s,accountantSignedAt:d})}/></div><Input label="ملاحظات" value={form.notes} set={v=>setForm({...form,notes:v})}/><button disabled={saving} className="rounded-xl bg-emerald-700 px-6 py-3 font-bold text-white">{editingId?"حفظ التعديل":"حفظ مسودة"}</button></form>}
    <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4 grid gap-2 md:grid-cols-4 xl:grid-cols-8"><Input label="بحث/رقم" value={filters.q} set={v=>setFilters({...filters,q:v})}/><Input label="مرجع" value={filters.reference} set={v=>setFilters({...filters,reference:v})}/><Select label="الحالة" value={filters.status} set={v=>setFilters({...filters,status:v})} options={[["","الكل"],["DRAFT","مسودة"],["PENDING","مراجعة"],["APPROVED","معتمد"],["POSTED","مكتمل"],["CANCELLED","ملغى"]]}/><Select label="النوع" value={filters.noteType} set={v=>setFilters({...filters,noteType:v})} options={[["","الكل"],["RECEIPT","استلام"],["DELIVERY","تسليم"]]}/><Select label="الجهة" value={filters.partyId} set={v=>setFilters({...filters,partyId:v})} options={[["","الكل"],...(data?.options.parties??[]).map(x=>[String(x.id),x.nameAr!] as [string,string])]}/><Select label="المادة" value={filters.itemId} set={v=>setFilters({...filters,itemId:v})} options={[["","الكل"],...(data?.options.items??[]).map(x=>[String(x.id),x.nameAr!] as [string,string])]}/><Input label="من" type="date" value={filters.from} set={v=>setFilters({...filters,from:v})}/><Input label="إلى" type="date" value={filters.to} set={v=>setFilters({...filters,to:v})}/></div>
      {loading?<p className="p-8 text-center">جارٍ التحميل…</p>:!data?.notes.length?<p className="p-8 text-center text-slate-500">لا توجد سندات.</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-100"><tr>{["الرقم","التاريخ","النوع","الجهة","الملكية","الكمية","النقل","الحالة","الإجراء"].map(x=><th key={x} className="p-3 text-right">{x}</th>)}</tr></thead><tbody>{data.notes.map(note=><NotesRows key={note.id} note={note} saving={saving} expanded={expanded===note.id} toggle={()=>setExpanded(expanded===note.id?null:note.id)} edit={()=>edit(note)} action={action} upload={file=>void uploadNote(note.id,file)}/>)}</tbody></table></div>}
    </section>
  </div></main>
}
function NotesRows({note,saving,expanded,toggle,edit,action,upload}:{note:NoteRow;saving:boolean;expanded:boolean;toggle:()=>void;edit:()=>void;action:(id:number,t:"SUBMIT"|"APPROVE"|"POST"|"CANCEL")=>void;upload:(file:File)=>void}){return <><tr className="border-b align-top"><td className="p-3 font-bold">{note.noteNumber}</td><td className="p-3">{new Date(note.noteDate).toLocaleDateString("ar-SA")}</td><td className="p-3">{note.noteType==="RECEIPT"?"استلام":"تسليم"}</td><td className="p-3">{note.party.nameAr}</td><td className="p-3">{note.stockOwnership==="COMPANY"?"الشركة":"العميل"}</td><td className="p-3">{note.items.reduce((s,x)=>s+Number(x.quantity),0).toLocaleString("ar-SA")}</td><td className="p-3">{note.trip?.tripNumber??(note.transportMethod==="COMPANY"?"عند الترحيل":"—")}</td><td className="p-3"><Badge status={note.status}/></td><td className="p-3"><div className="flex flex-wrap gap-2">{note.status==="DRAFT"&&<><button onClick={edit} className="text-blue-700">تعديل</button><button disabled={saving} onClick={()=>action(note.id,"SUBMIT")}>مراجعة</button></>}{note.status==="PENDING"&&<button onClick={()=>action(note.id,"APPROVE")} className="text-blue-700">اعتماد</button>}{["DRAFT","PENDING","APPROVED"].includes(note.status)&&<button onClick={()=>action(note.id,"POST")} className="text-emerald-700">ترحيل</button>}{note.status==="POSTED"&&<button onClick={()=>action(note.id,"CANCEL")} className="text-red-700">إلغاء</button>}<button onClick={toggle}>عرض</button><Link href={`/notes/${note.id}/print`}>طباعة</Link><label className="cursor-pointer text-blue-700">مرفق/كاميرا<input type="file" accept="image/*,.pdf,.xls,.xlsx" capture="environment" className="hidden" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label></div></td></tr>{expanded&&<tr><td colSpan={9} className="bg-slate-50 p-4"><div className="grid gap-2 md:grid-cols-3"><p><b>المرجع:</b> {note.referenceNumber??"—"}</p><p><b>السائق:</b> {note.driverName??"—"}</p><p><b>اللوحة:</b> {note.vehiclePlate??"—"}</p><p><b>التحميل:</b> {note.loadingPoint??"—"}</p><p><b>التفريغ:</b> {note.unloadingPoint??"—"}</p><p><b>المصدر:</b> {note.source??"—"}</p></div>{note.items.map(x=><p key={x.id}>{x.item.code} — {x.item.nameAr}: {Number(x.quantity).toLocaleString("ar-SA")} {x.item.unit?.nameAr}</p>)}</td></tr>}</>}
function Sign({title,name,signature,date,set}:{title:string;name:string;signature:string;date:string;set:(n:string,s:string,d:string)=>void}){return <fieldset className="rounded-xl border p-3"><legend className="font-bold">{title}</legend><Input label="الاسم" value={name} set={v=>set(v,signature,date)}/><Select label="التوقيع" value={signature} set={v=>set(name,v,v&&!date?new Date().toISOString().slice(0,16):date)} options={[["","غير موقع"],["SIGNED","تم التوقيع"]]}/><Input label="التاريخ" type="datetime-local" value={date} set={v=>set(name,signature,v)}/></fieldset>}
function Input({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <label className="block text-sm"><span className="mb-1 block text-slate-600">{label}</span><input type={type} step={type==="number"?"any":undefined} min={type==="number"?0:undefined} value={value} onChange={e=>set(e.target.value)} className="w-full rounded-lg border px-3 py-2"/></label>}
function Select({label,value,set,options,required=false}:{label:string;value:string;set:(v:string)=>void;options:Array<[string,string]>;required?:boolean}){return <label className="block text-sm"><span className="mb-1 block text-slate-600">{label}</span><select required={required} value={value} onChange={e=>set(e.target.value)} className="w-full rounded-lg border bg-white px-3 py-2">{required&&<option value="">اختر…</option>}{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>}
function Badge({status}:{status:string}){const color=status==="POSTED"?"bg-emerald-100 text-emerald-800":status==="CANCELLED"?"bg-red-100 text-red-800":"bg-amber-100 text-amber-800";return <span className={`rounded-full px-2 py-1 text-xs font-bold ${color}`}>{status}</span>}
