import {Prisma} from "@prisma/client";
import {authorizeRequest} from "@/lib/api-auth";
import {runWithDataScope} from "@/lib/data-scope";
import {createPdf,createXlsx,type ReportTable} from "@/lib/financial-export";
import {prisma} from "@/lib/prisma";

const boundary=(value:string|null,end=false)=>value?new Date(`${value}T${end?"23:59:59.999":"00:00:00.000"}`):undefined;
const sourceUrl=(type:string|null,id:number|null)=>!id?null:type==="SALES_INVOICE"?`/sales/${id}/print`:type==="PURCHASE_INVOICE"?`/purchases/${id}/print`:type==="DELIVERY_RECEIPT_NOTE"?`/notes/${id}/print`:type?.includes("VOUCHER")?"/accounting?tab=vouchers":"/accounting?tab=journals";
const selectedIds=(query:URLSearchParams)=>[...new Set((query.get("itemIds")??query.get("itemId")??"").split(",").map(Number).filter(id=>Number.isInteger(id)&&id>0))];

export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){
 try{
  const partyId=Number((await params).id),query=new URL(request.url).searchParams,kind=query.get("kind")==="inventory"?"inventory":"financial",moduleKey=kind==="inventory"?"INVENTORY":"ACCOUNTING",context=await authorizeRequest(request,{moduleKey,action:"READ"}),includeDrafts=kind==="financial"&&query.get("includeDrafts")==="1",from=boundary(query.get("from")),to=boundary(query.get("to"),true),format=query.get("format"),itemIds=selectedIds(query),documentType=query.get("documentType");
  if(includeDrafts)await authorizeRequest(request,{moduleKey:"ACCOUNTING",action:"POST"});
  if(!Number.isInteger(partyId)||partyId<=0)return Response.json({error:"العميل أو المورد غير صحيح"},{status:400});
  const result=await runWithDataScope({tenantId:context.tenantId,companyId:context.companyId},async()=>{
   const party=await prisma.party.findUnique({where:{id:partyId}});if(!party)throw new Error("العميل أو المورد غير موجود");
   if(kind==="inventory"){
    const itemFilter=itemIds.length?{itemId:{in:itemIds}}:{},dateFilter=from||to?{movementDate:{...(from?{gte:from}:{}),...(to?{lte:to}:{})}}:{},where:Prisma.StockMovementWhereInput={partyId,...itemFilter,...(documentType?{referenceType:documentType}:{}),...dateFilter};
    const [openingRows,movements,availableItems]=await Promise.all([from?prisma.stockMovement.findMany({where:{partyId,...itemFilter,movementDate:{lt:from}},select:{itemId:true,quantityIn:true,quantityOut:true}}):Promise.resolve([]),prisma.stockMovement.findMany({where,include:{item:{include:{unit:true}}},orderBy:[{movementDate:"asc"},{id:"asc"}]}),prisma.stockMovement.findMany({where:{partyId},select:{item:{select:{id:true,code:true,nameAr:true,nameEn:true}}},distinct:["itemId"],orderBy:{itemId:"asc"}})]);
    const openings=new Map<number,number>();for(const row of openingRows)openings.set(row.itemId,(openings.get(row.itemId)??0)+Number(row.quantityIn)-Number(row.quantityOut));
    const balances=new Map(openings),summaryMap=new Map<number,{itemId:number;item:string;itemEn:string|null;itemCode:string;unit:string;opening:number;in:number;out:number;closing:number;value:number}>();
    for(const row of movements)if(!summaryMap.has(row.itemId))summaryMap.set(row.itemId,{itemId:row.itemId,item:row.item.nameAr,itemEn:row.item.nameEn,itemCode:row.item.code,unit:row.item.unit.nameAr,opening:openings.get(row.itemId)??0,in:0,out:0,closing:openings.get(row.itemId)??0,value:0});
    const rows=movements.map(row=>{const balance=(balances.get(row.itemId)??0)+Number(row.quantityIn)-Number(row.quantityOut);balances.set(row.itemId,balance);const summary=summaryMap.get(row.itemId)!;summary.in+=Number(row.quantityIn);summary.out+=Number(row.quantityOut);summary.closing=balance;summary.value+=Number(row.totalValue);return{id:row.id,date:row.movementDate,number:row.movementNumber,type:row.movementType,itemId:row.itemId,item:row.item.nameAr,itemEn:row.item.nameEn,itemCode:row.item.code,unit:row.item.unit.nameAr,in:Number(row.quantityIn),out:Number(row.quantityOut),balance,unitValue:Number(row.unitCost),value:Number(row.totalValue),referenceType:row.referenceType,referenceNumber:row.referenceNumber,sourceUrl:sourceUrl(row.referenceType,row.referenceId)}});
    for(const [itemId,opening] of openings)if(!summaryMap.has(itemId)){const item=availableItems.map(row=>row.item).find(candidate=>candidate.id===itemId);if(item)summaryMap.set(itemId,{itemId,item:item.nameAr,itemEn:item.nameEn,itemCode:item.code,unit:"",opening,in:0,out:0,closing:opening,value:0})}
    const summaries=[...summaryMap.values()].sort((a,b)=>a.itemCode.localeCompare(b.itemCode)),opening=summaries.reduce((sum,row)=>sum+row.opening,0);return{kind,party,availableItems:availableItems.map(row=>row.item),selectedItemIds:itemIds,opening,summaries,rows,totals:{in:summaries.reduce((s,r)=>s+r.in,0),out:summaries.reduce((s,r)=>s+r.out,0),closing:summaries.reduce((s,r)=>s+r.closing,0)}};
   }
   const lineWhere:Prisma.JournalEntryLineWhereInput={partyId,journalEntry:{status:"POSTED",...(documentType?{referenceType:documentType}:{}),...(from||to?{entryDate:{...(from?{gte:from}:{}),...(to?{lte:to}:{})}}:{})}},openingLines=from?await prisma.journalEntryLine.findMany({where:{partyId,journalEntry:{status:"POSTED",entryDate:{lt:from}}}}):[],opening=openingLines.reduce((sum,row)=>sum+Number(row.debit)-Number(row.credit),0),lines=await prisma.journalEntryLine.findMany({where:lineWhere,include:{journalEntry:true},orderBy:[{journalEntry:{entryDate:"asc"}},{id:"asc"}]});let balance=opening;
   const rows=lines.map(line=>{balance+=Number(line.debit)-Number(line.credit);return{id:line.id,date:line.journalEntry.entryDate,number:line.journalEntry.entryNumber,type:line.journalEntry.referenceType??"JOURNAL",description:line.description??line.journalEntry.description??"",debit:Number(line.debit),credit:Number(line.credit),balance,referenceNumber:line.journalEntry.referenceNumber,sourceUrl:sourceUrl(line.journalEntry.referenceType,line.journalEntry.referenceId)}});
   let unpostedRows:Array<Record<string,unknown>>=[];
   if(includeDrafts){const dateWhere=from||to?{...(from?{gte:from}:{}),...(to?{lte:to}:{})}:{},[draftLines,sales,purchases]=await Promise.all([prisma.journalEntryLine.findMany({where:{partyId,journalEntry:{status:{notIn:["POSTED","REVERSED","CANCELLED"]},...(from||to?{entryDate:dateWhere}:{})}},include:{journalEntry:true}}),prisma.sale.findMany({where:{partyId,status:{notIn:["POSTED","CANCELLED"]},...(from||to?{invoiceDate:dateWhere}:{})}}),prisma.purchase.findMany({where:{partyId,status:{notIn:["POSTED","CANCELLED"]},...(from||to?{purchaseDate:dateWhere}:{})}})]);unpostedRows=[...draftLines.map(line=>({id:`J-${line.id}`,date:line.journalEntry.entryDate,number:line.journalEntry.entryNumber,type:line.journalEntry.referenceType??"JOURNAL",description:line.description??line.journalEntry.description??"",debit:Number(line.debit),credit:Number(line.credit),status:line.journalEntry.status,sourceUrl:sourceUrl(line.journalEntry.referenceType,line.journalEntry.referenceId)})),...sales.map(row=>({id:`S-${row.id}`,date:row.invoiceDate,number:row.invoiceNumber,type:"SALES_INVOICE",description:"فاتورة مبيعات غير مرحلة",debit:Number(row.totalAmount),credit:0,status:row.status,sourceUrl:`/sales/${row.id}/print`})),...purchases.map(row=>({id:`P-${row.id}`,date:row.purchaseDate,number:row.purchaseNumber,type:"PURCHASE_INVOICE",description:"فاتورة مشتريات غير مرحلة",debit:0,credit:Number(row.totalAmount),status:row.status,sourceUrl:`/purchases/${row.id}/print`}))].sort((a,b)=>new Date(String(a.date)).getTime()-new Date(String(b.date)).getTime());}
   return{kind,party,opening,rows,unpostedRows,unpostedIncluded:includeDrafts,totals:{debit:rows.reduce((s,r)=>s+r.debit,0),credit:rows.reduce((s,r)=>s+r.credit,0),closing:balance}};
  });
  if(format==="xlsx"||format==="pdf"){const table:ReportTable=result.kind==="financial"?{title:`كشف الحساب المالي — ${result.party.nameAr}`,subtitle:`${query.get("from")??"البداية"} — ${query.get("to")??"اليوم"} · الحركات المرحلة فقط`,columns:["التاريخ","القيد","النوع","المرجع","البيان","مدين","دائن","الرصيد"],rows:(result.rows as Array<Record<string,unknown>>).map(row=>[new Date(String(row.date)).toISOString().slice(0,10),String(row.number),String(row.type),String(row.referenceNumber??""),String(row.description),Number(row.debit),Number(row.credit),Number(row.balance)])}:{title:`كشف مخزون العميل — ${result.party.nameAr}`,subtitle:`${query.get("from")??"البداية"} — ${query.get("to")??"اليوم"}`,columns:["التاريخ","الحركة","المادة","الكود","الوحدة","وارد","صادر","الرصيد","قيمة الوحدة","القيمة","المرجع"],rows:(result.rows as Array<Record<string,unknown>>).map(row=>[new Date(String(row.date)).toISOString().slice(0,10),String(row.number),String(row.item),String(row.itemCode),String(row.unit),Number(row.in),Number(row.out),Number(row.balance),Number(row.unitValue),Number(row.value),String(row.referenceNumber??"")])},body=format==="pdf"?createPdf(table):createXlsx(table);return new Response(new Uint8Array(body),{headers:{"content-type":format==="pdf"?"application/pdf":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","content-disposition":`attachment; filename="party-${partyId}-${kind}.${format}"`}})}
  return Response.json(result);
 }catch(error){return Response.json({error:error instanceof Error?error.message:"تعذر إنشاء الكشف"},{status:403})}
}
