import type {Prisma} from "@prisma/client";
import {authorizeRequest} from "@/lib/api-auth";
import {runWithDataScope} from "@/lib/data-scope";
import {createPdf,createXlsx,type ReportTable} from "@/lib/financial-export";
import {prisma} from "@/lib/prisma";
const boundary=(value:string|null,end=false)=>value?new Date(`${value}${end?"T23:59:59.999":"T00:00:00.000"}`):null;
const sourceUrl=(type:string|null,id:number|null)=>!id?null:type==="SALES_INVOICE"?`/sales/${id}/print`:type==="DELIVERY_RECEIPT_NOTE"?`/notes/${id}/print`:type?.includes("VOUCHER")?"/accounting?tab=vouchers":"/accounting?tab=journals";
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){
 try{const partyId=Number((await params).id),query=new URL(request.url).searchParams,kind=query.get("kind")==="inventory"?"inventory":"financial",moduleKey=kind==="inventory"?"INVENTORY":"ACCOUNTING",context=await authorizeRequest(request,{moduleKey,action:"READ"}),from=boundary(query.get("from")),to=boundary(query.get("to"),true),format=query.get("format"),itemId=Number(query.get("itemId")),documentType=query.get("documentType");if(!Number.isInteger(partyId)||partyId<=0)return Response.json({error:"العميل أو المورد غير صحيح"},{status:400});
 const result=await runWithDataScope({tenantId:context.tenantId,companyId:context.companyId},async()=>{const party=await prisma.party.findUnique({where:{id:partyId}});if(!party)throw new Error("العميل أو المورد غير موجود");if(kind==="inventory"){const where:Prisma.StockMovementWhereInput={partyId,...(itemId>0?{itemId}:{}),...(documentType?{referenceType:documentType}:{}),...(from||to?{movementDate:{...(from?{gte:from}:{}),...(to?{lte:to}:{})}}:{})},openingRows=from?await prisma.stockMovement.findMany({where:{partyId,...(itemId>0?{itemId}:{}),movementDate:{lt:from}}}):[],opening=openingRows.reduce((sum,row)=>sum+Number(row.quantityIn)-Number(row.quantityOut),0),movements=await prisma.stockMovement.findMany({where,include:{item:{include:{unit:true}}},orderBy:[{movementDate:"asc"},{id:"asc"}]});let balance=opening;const rows=movements.map(row=>{balance+=Number(row.quantityIn)-Number(row.quantityOut);return{id:row.id,date:row.movementDate,number:row.movementNumber,type:row.movementType,item:row.item.nameAr,itemCode:row.item.code,unit:row.item.unit.nameAr,in:Number(row.quantityIn),out:Number(row.quantityOut),balance,unitValue:Number(row.unitCost),value:Number(row.totalValue),referenceType:row.referenceType,referenceNumber:row.referenceNumber,sourceUrl:sourceUrl(row.referenceType,row.referenceId)}});return{kind,party,opening,rows,totals:{in:rows.reduce((s,r)=>s+r.in,0),out:rows.reduce((s,r)=>s+r.out,0),closing:balance}}}const lineWhere:Prisma.JournalEntryLineWhereInput={partyId,journalEntry:{status:"POSTED",...(documentType?{referenceType:documentType}:{}),...(from||to?{entryDate:{...(from?{gte:from}:{}),...(to?{lte:to}:{})}}:{})}},openingLines=from?await prisma.journalEntryLine.findMany({where:{partyId,journalEntry:{status:"POSTED",entryDate:{lt:from}}}}):[],opening=openingLines.reduce((sum,row)=>sum+Number(row.debit)-Number(row.credit),0),lines=await prisma.journalEntryLine.findMany({where:lineWhere,include:{journalEntry:true},orderBy:[{journalEntry:{entryDate:"asc"}},{id:"asc"}]});let balance=opening;const rows=lines.map(line=>{balance+=Number(line.debit)-Number(line.credit);return{id:line.id,date:line.journalEntry.entryDate,number:line.journalEntry.entryNumber,type:line.journalEntry.referenceType??"JOURNAL",description:line.description??line.journalEntry.description??"",debit:Number(line.debit),credit:Number(line.credit),balance,referenceNumber:line.journalEntry.referenceNumber,sourceUrl:sourceUrl(line.journalEntry.referenceType,line.journalEntry.referenceId)}});return{kind,party,opening,rows,totals:{debit:rows.reduce((s,r)=>s+r.debit,0),credit:rows.reduce((s,r)=>s+r.credit,0),closing:balance}}});
 if(format==="xlsx"||format==="pdf"){const table:ReportTable=result.kind==="financial"?{title:`كشف الحساب المالي — ${result.party.nameAr}`,subtitle:`${query.get("from")??"البداية"} — ${query.get("to")??"اليوم"}`,columns:["التاريخ","القيد","النوع","المرجع","البيان","مدين","دائن","الرصيد"],rows:(result.rows as Array<Record<string,unknown>>).map(row=>[new Date(String(row.date)).toISOString().slice(0,10),String(row.number),String(row.type),String(row.referenceNumber??""),String(row.description),Number(row.debit),Number(row.credit),Number(row.balance)])}:{title:`كشف مخزون العميل — ${result.party.nameAr}`,subtitle:`${query.get("from")??"البداية"} — ${query.get("to")??"اليوم"}`,columns:["التاريخ","الحركة","المادة","الكود","الوحدة","وارد","صادر","الرصيد","قيمة الوحدة","القيمة","المرجع"],rows:(result.rows as Array<Record<string,unknown>>).map(row=>[new Date(String(row.date)).toISOString().slice(0,10),String(row.number),String(row.item),String(row.itemCode),String(row.unit),Number(row.in),Number(row.out),Number(row.balance),Number(row.unitValue),Number(row.value),String(row.referenceNumber??"")])},body=format==="pdf"?createPdf(table):createXlsx(table);return new Response(new Uint8Array(body),{headers:{"content-type":format==="pdf"?"application/pdf":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","content-disposition":`attachment; filename="party-${partyId}-${kind}.${format}"`}})}return Response.json(result);
 }catch(error){return Response.json({error:error instanceof Error?error.message:"تعذر إعداد الكشف"},{status:403})}
}
