"use client";

import {useCallback,useEffect,useMemo,useState} from "react";

type Option={id:number;plateNumber?:string;name?:string;tripNumber?:string};
type Row=Record<string,unknown>;
type Data={odometers:Row[];tires:Row[];batteries:Row[];fuel:Row[];maintenance:Row[];receipts:Row[]};
const types=[['ODOMETER','العداد'],['TIRE','الإطارات'],['BATTERY','البطاريات'],['FUEL','الوقود'],['MAINTENANCE','الصيانة'],['RECEIPT','إيصالات النقليات']] as const;
const today=new Date().toISOString().slice(0,10);
const initial={type:'ODOMETER',truckId:'',driverId:'',tripId:'',readingDate:today,reading:'',sourceType:'MANUAL',correctionReason:'',vehiclePart:'TRACTOR',axle:'1',position:'FRONT_LEFT',serialNumber:'',brand:'',size:'',installedAt:today,installationOdometer:'',cost:'',supplier:'',specification:'',warrantyExpiry:'',transactionDate:today,liters:'',pricePerLiter:'',odometer:'',referenceNumber:'',maintenanceDate:today,maintenanceType:'PREVENTIVE',issue:'',workDone:'',workshop:'',nextDate:'',nextOdometer:'',downtimeHours:'',receiptDate:today,quantity:'',rate:'',vatRate:'15',calculationBasis:'QUANTITY',notes:''};

export default function FleetOperations({trucks,drivers,trips}:{trucks:Option[];drivers:Option[];trips:Option[]}){
  const[form,setForm]=useState(initial),[data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const load=useCallback(async()=>{const params=form.truckId?`?truckId=${form.truckId}`:'';const response=await fetch(`/api/transport/operations${params}`,{cache:'no-store'}),body=await response.json();if(!response.ok)throw new Error(body.error);setData(body)},[form.truckId]);
  useEffect(()=>{let cancelled=false;const params=form.truckId?`?truckId=${form.truckId}`:'';fetch(`/api/transport/operations${params}`,{cache:'no-store'}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);if(!cancelled)setData(body)}).catch(error=>{if(!cancelled)setMessage(error instanceof Error?error.message:'تعذر تحميل سجل الأسطول')});return()=>{cancelled=true}},[form.truckId]);
  async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage('');try{const response=await fetch('/api/transport/operations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)}),body=await response.json();if(!response.ok)throw new Error(body.error);setMessage('تم حفظ العملية في سجل الأسطول مع الاحتفاظ بالتاريخ السابق');setForm(current=>({...initial,type:current.type,truckId:current.truckId}));await load()}catch(error){setMessage(error instanceof Error?error.message:'تعذر الحفظ')}finally{setBusy(false)}}
  const rows=useMemo(()=>form.type==='ODOMETER'?data?.odometers:form.type==='TIRE'?data?.tires:form.type==='BATTERY'?data?.batteries:form.type==='FUEL'?data?.fuel:form.type==='MAINTENANCE'?data?.maintenance:data?.receipts,[data,form.type]);
  return <div className="space-y-5"><div className="flex flex-wrap gap-2">{types.map(([type,label])=><button key={type} type="button" onClick={()=>setForm({...initial,type,truckId:form.truckId})} className={`rounded-full border px-4 py-2 font-bold ${form.type===type?'bg-amber-500 text-slate-950':'bg-white'}`}>{label}</button>)}</div>{message&&<div className="rounded-xl border border-blue-200 bg-blue-50 p-3">{message}</div>}<form onSubmit={save} className="grid gap-3 rounded-2xl border bg-slate-50 p-4 md:grid-cols-3 xl:grid-cols-4">
    {form.type!=='RECEIPT'&&<Select label="الشاحنة" value={form.truckId} set={value=>setForm({...form,truckId:value})} options={trucks.map(row=>[String(row.id),row.plateNumber??String(row.id)])} required/>}
    {form.type==='ODOMETER'&&<><Field label="التاريخ والوقت" type="datetime-local" value={`${form.readingDate}T12:00`} set={value=>setForm({...form,readingDate:value})}/><Field label="قراءة العداد" type="number" value={form.reading} set={value=>setForm({...form,reading:value})} required/><Select label="المصدر" value={form.sourceType} set={value=>setForm({...form,sourceType:value})} options={[['MANUAL','يدوي'],['TRIP','رحلة'],['MAINTENANCE','صيانة'],['FUEL','وقود'],['TIRE','إطار'],['BATTERY','بطارية'],['IMPORT','ترحيل']]}/><Field label="سبب التصحيح عند قراءة أقل" value={form.correctionReason} set={value=>setForm({...form,correctionReason:value})}/></>}
    {form.type==='TIRE'&&<><Select label="الجزء" value={form.vehiclePart} set={value=>setForm({...form,vehiclePart:value})} options={[['TRACTOR','الرأس'],['TRAILER','المقطورة / الصهريج']]}/><Field label="المحور" type="number" value={form.axle} set={value=>setForm({...form,axle:value})}/><TireSchematic value={form.position} set={position=>setForm({...form,position})}/><Field label="الرقم التسلسلي" value={form.serialNumber} set={value=>setForm({...form,serialNumber:value})}/><Field label="الماركة" value={form.brand} set={value=>setForm({...form,brand:value})}/><Field label="المقاس" value={form.size} set={value=>setForm({...form,size:value})}/><Field label="تاريخ التركيب" type="date" value={form.installedAt} set={value=>setForm({...form,installedAt:value})}/><Field label="العداد عند التركيب" type="number" value={form.installationOdometer} set={value=>setForm({...form,installationOdometer:value})}/><Field label="التكلفة" type="number" value={form.cost} set={value=>setForm({...form,cost:value})}/><Field label="المورد" value={form.supplier} set={value=>setForm({...form,supplier:value})}/></>}
    {form.type==='BATTERY'&&<><Select label="الموضع" value={form.position} set={value=>setForm({...form,position:value})} options={[['MAIN','رئيسية'],['AUXILIARY','مساعدة']]}/><Field label="الرقم التسلسلي" value={form.serialNumber} set={value=>setForm({...form,serialNumber:value})}/><Field label="الماركة" value={form.brand} set={value=>setForm({...form,brand:value})}/><Field label="المواصفة / السعة" value={form.specification} set={value=>setForm({...form,specification:value})}/><Field label="تاريخ التركيب" type="date" value={form.installedAt} set={value=>setForm({...form,installedAt:value})}/><Field label="العداد عند التركيب" type="number" value={form.installationOdometer} set={value=>setForm({...form,installationOdometer:value})}/><Field label="انتهاء الضمان" type="date" value={form.warrantyExpiry} set={value=>setForm({...form,warrantyExpiry:value})}/><Field label="التكلفة" type="number" value={form.cost} set={value=>setForm({...form,cost:value})}/><Field label="المورد" value={form.supplier} set={value=>setForm({...form,supplier:value})}/></>}
    {form.type==='FUEL'&&<><Select label="السائق" value={form.driverId} set={value=>setForm({...form,driverId:value})} options={drivers.map(row=>[String(row.id),row.name??String(row.id)])}/><Select label="الرحلة" value={form.tripId} set={value=>setForm({...form,tripId:value})} options={trips.map(row=>[String(row.id),row.tripNumber??String(row.id)])}/><Field label="التاريخ" type="date" value={form.transactionDate} set={value=>setForm({...form,transactionDate:value})}/><Field label="العداد" type="number" value={form.odometer} set={value=>setForm({...form,odometer:value})}/><Field label="اللترات الفعلية" type="number" value={form.liters} set={value=>setForm({...form,liters:value})} required/><Field label="سعر اللتر" type="number" value={form.pricePerLiter} set={value=>setForm({...form,pricePerLiter:value})} required/><Field label="المحطة / المورد" value={form.supplier} set={value=>setForm({...form,supplier:value})}/><Field label="الفاتورة / المرجع" value={form.referenceNumber} set={value=>setForm({...form,referenceNumber:value})}/></>}
    {form.type==='MAINTENANCE'&&<><Field label="التاريخ" type="date" value={form.maintenanceDate} set={value=>setForm({...form,maintenanceDate:value})}/><Field label="العداد" type="number" value={form.odometer} set={value=>setForm({...form,odometer:value})}/><Select label="النوع" value={form.maintenanceType} set={value=>setForm({...form,maintenanceType:value})} options={[['PREVENTIVE','وقائية'],['CORRECTIVE','تصحيحية'],['OIL_SERVICE','زيت وخدمة'],['TIRE','إطارات'],['BATTERY','بطاريات']]}/><Field label="المشكلة" value={form.issue} set={value=>setForm({...form,issue:value})}/><Field label="العمل المنفذ" value={form.workDone} set={value=>setForm({...form,workDone:value})}/><Field label="الورشة" value={form.workshop} set={value=>setForm({...form,workshop:value})}/><Field label="التكلفة" type="number" value={form.cost} set={value=>setForm({...form,cost:value})}/><Field label="التوقف بالساعات" type="number" value={form.downtimeHours} set={value=>setForm({...form,downtimeHours:value})}/><Field label="الصيانة التالية" type="date" value={form.nextDate} set={value=>setForm({...form,nextDate:value})}/><Field label="العداد التالي" type="number" value={form.nextOdometer} set={value=>setForm({...form,nextOdometer:value})}/></>}
    {form.type==='RECEIPT'&&<><Select label="الرحلة" value={form.tripId} set={value=>setForm({...form,tripId:value})} options={trips.map(row=>[String(row.id),row.tripNumber??String(row.id)])} required/><Field label="التاريخ" type="date" value={form.receiptDate} set={value=>setForm({...form,receiptDate:value})}/><Field label="الكمية" type="number" value={form.quantity} set={value=>setForm({...form,quantity:value})}/><Field label="السعر / المعدل" type="number" value={form.rate} set={value=>setForm({...form,rate:value})}/><Field label="VAT %" type="number" value={form.vatRate} set={value=>setForm({...form,vatRate:value})}/></>}
    <Field label="ملاحظات" value={form.notes} set={value=>setForm({...form,notes:value})}/><button disabled={busy} className="mt-6 rounded-xl bg-emerald-700 px-5 py-2 font-bold text-white disabled:opacity-50">حفظ في السجل</button>
  </form><History type={form.type} rows={rows??[]}/></div>
}

function TireSchematic({value,set}:{value:string;set:(value:string)=>void}){const positions=[['FRONT_LEFT','أمامي يسار'],['FRONT_RIGHT','أمامي يمين'],['REAR_LEFT_OUTER','خلفي يسار خارجي'],['REAR_LEFT_INNER','خلفي يسار داخلي'],['REAR_RIGHT_INNER','خلفي يمين داخلي'],['REAR_RIGHT_OUTER','خلفي يمين خارجي']];return <fieldset className="md:col-span-2"><legend className="mb-1 text-sm text-slate-600">مخطط موضع الإطار</legend><div className="grid grid-cols-2 gap-2 rounded-[30px] border-2 border-slate-300 bg-white p-4">{positions.map(([key,label])=><button type="button" key={key} onClick={()=>set(key)} className={`rounded-xl border-2 px-2 py-3 text-xs font-bold ${value===key?'border-amber-500 bg-amber-100':'border-slate-300'}`}>{label}</button>)}</div></fieldset>}
function History({type,rows}:{type:string;rows:Row[]}){if(!rows.length)return <p className="p-8 text-center text-slate-500">لا يوجد سجل محفوظ لهذا النوع.</p>;const columns=Object.keys(rows[0]).filter(key=>!['id','tenantId','companyId','truckId','driverId','tripId','truck','driver','trip','attachmentUrl'].includes(key)).slice(0,8);return <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-right">المركبة</th>{columns.map(column=><th key={column} className="p-3 text-right">{column}</th>)}{type==='RECEIPT'&&<th className="p-3 text-right">المستند</th>}</tr></thead><tbody>{rows.map((row,index)=><tr key={String(row.id??index)} className="border-b odd:bg-slate-50"><td className="p-3 font-bold">{String((row.truck as Row|undefined)?.plateNumber??(row.trip as Row|undefined)?.tripNumber??'—')}</td>{columns.map(column=><td key={column} className="p-3">{format(row[column])}</td>)}{type==='RECEIPT'&&<td className="p-3"><div className="flex gap-2"><a className="font-bold text-amber-700" href={`/transport/receipts/${row.id}/print`} target="_blank" rel="noreferrer">معاينة / طباعة</a><a className="text-blue-700" href={`/api/transport/receipts/${row.id}/export?format=xlsx`}>Excel</a></div></td>}</tr>)}</tbody></table><p className="mt-2 text-xs text-slate-500">{type==='TIRE'||type==='BATTERY'?'يُحفظ الاستبدال كسجل جديد ولا يتم مسح السجل السابق.':''}</p></div>}
function format(value:unknown){if(value===null||value===undefined)return'—';if(typeof value==='object'&&value instanceof Date)return value.toLocaleDateString('en-US');if(typeof value==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(value))return new Date(value).toLocaleDateString('en-US');if(typeof value==='object')return'—';return String(value)}
function Field({label,value,set,type='text',required=false}:{label:string;value:string;set:(value:string)=>void;type?:string;required?:boolean}){return <label className="text-sm"><span className="mb-1 block text-slate-600">{label}</span><input required={required} type={type} min={type==='date'?'1990-01-01':type==='number'?'0':undefined} max={type==='date'?'2100-12-31':undefined} step={type==='number'?'any':undefined} value={value} onChange={event=>set(event.target.value)} className="w-full rounded-lg border bg-white px-3 py-2"/></label>}
function Select({label,value,set,options,required=false}:{label:string;value:string;set:(value:string)=>void;options:Array<[string,string]>;required?:boolean}){return <label className="text-sm"><span className="mb-1 block text-slate-600">{label}</span><select required={required} value={value} onChange={event=>set(event.target.value)} className="w-full rounded-lg border bg-white px-3 py-2"><option value="">اختر…</option>{options.map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label>}
