"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

type Truck = { id:number; plateNumber:string; truckType?:string|null; model?:string|null; capacity?:number|null; status:string; documents:Array<{id:number;documentType:string;expiryDate?:string|null}> };
type Driver = { id:number; name:string; phone?:string|null; licenseNumber?:string|null; licenseExpiry?:string|null; status:string; documents:Array<{id:number;documentType:string;expiryDate?:string|null}> };
type Trip = { id:number; tripNumber:string; tripDate:string; status:string; quantity:number; weight?:number|null; transportRevenue:number; totalCost:number; netProfit:number; profitPerTon?:number|null; profitPerKm?:number|null; profitMargin?:number|null; fuelLiters:number; fuelPricePerLiter:number; driverTripFee:number; maintenanceCost:number; administrativeCost:number; roadPermitCost:number; otherCost:number; estimatedKm?:number|null; actualKm?:number|null; notes?:string|null; party?:{nameAr:string}|null; item?:{nameAr:string}|null; truck?:Truck|null; driver?:Driver|null; note?:{noteNumber:string}|null };
type AlertDoc = {id:number;documentType:string;expiryDate:string;truck?:{plateNumber:string};driver?:{name:string}};
type Data = { trips:Trip[];trucks:Truck[];drivers:Driver[];alerts:{truckDocuments:AlertDoc[];driverDocuments:AlertDoc[]};summary:{trips:number;openTrips:number;completedTrips:number;revenue:number;cost:number;profit:number} };
const money=(n:number)=>new Intl.NumberFormat('ar-SA',{style:'currency',currency:'SAR',maximumFractionDigits:2}).format(n);
const tripFields=['transportRevenue','fuelLiters','fuelPricePerLiter','driverTripFee','maintenanceCost','administrativeCost','roadPermitCost','otherCost','estimatedKm','actualKm'] as const;

export default function TransportClient(){
  const [data,setData]=useState<Data|null>(null); const [tab,setTab]=useState<'trips'|'trucks'|'drivers'|'alerts'>('trips'); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(true); const [selected,setSelected]=useState<Trip|null>(null); const [showCreate,setShowCreate]=useState(false);
  const [truck,setTruck]=useState({plateNumber:'',truckType:'',model:'',modelYear:'',trailerType:'',capacity:'',fuelType:'ديزل',fuelConsumption:'',fuelPrice:'',maintenancePerKm:'',notes:''});
  const [driver,setDriver]=useState({name:'',idNumber:'',phone:'',nationality:'',licenseNumber:'',licenseExpiry:'',passportNumber:'',passportExpiry:'',driverCardNumber:'',driverCardExpiry:'',notes:''});
  const [document,setDocument]=useState({ownerType:'TRUCK',ownerId:'',documentType:'',documentNumber:'',issueDate:'',expiryDate:'',attachmentUrl:'',notes:''});
  const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/transport',{cache:'no-store'});const x=await r.json();if(!r.ok)throw new Error(x.error);setData(x);}catch(e){setMessage(e instanceof Error?e.message:'تعذر التحميل')}finally{setLoading(false)}},[]);
  useEffect(()=>{let cancelled=false;fetch('/api/transport',{cache:'no-store'}).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error);if(!cancelled)setData(x)}).catch((e:unknown)=>{if(!cancelled)setMessage(e instanceof Error?e.message:'تعذر التحميل')}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[]);
  async function create(kind:'trucks'|'drivers',payload:object){setMessage('');const r=await fetch(`/api/transport/${kind}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const x=await r.json();if(!r.ok){setMessage(x.error);return}setMessage(kind==='trucks'?'تمت إضافة الشاحنة':'تمت إضافة السائق');setShowCreate(false);await load()}
  async function saveDocument(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/transport/documents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...document,ownerId:Number(document.ownerId)})});const x=await r.json();if(!r.ok){setMessage(x.error);return}setMessage('تم حفظ الوثيقة وتفعيل متابعة انتهائها');setDocument({...document,documentType:'',documentNumber:'',issueDate:'',expiryDate:'',attachmentUrl:'',notes:''});await load()}
  async function saveTrip(e:React.FormEvent){e.preventDefault();if(!selected)return;const r=await fetch(`/api/transport/trips/${selected.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...selected,truckId:selected.truck?.id??null,driverId:selected.driver?.id??null})});const x=await r.json();if(!r.ok){setMessage(x.error);return}setSelected(null);setMessage('تم تحديث الرحلة وإعادة حساب تكلفتها وربحيتها');await load()}
  return <main dir="rtl" className="min-h-screen bg-slate-50 p-5 text-slate-900 md:p-8"><div className="mx-auto max-w-7xl">
    <header className="mb-6 flex flex-wrap justify-between gap-3"><div><Link href="/" className="text-sm text-blue-700">الرئيسية</Link><h1 className="text-3xl font-bold">إدارة النقليات</h1><p className="text-slate-500">الرحلات المنشأة من السندات، الأسطول، السائقون، والتكلفة الفعلية.</p></div>{(tab==='trucks'||tab==='drivers')&&<button onClick={()=>setShowCreate(!showCreate)} className="rounded-xl bg-blue-700 px-5 py-3 font-bold text-white">إضافة {tab==='trucks'?'شاحنة':'سائق'}</button>}</header>
    {message&&<div className="mb-4 rounded-xl border border-blue-200 bg-blue-50 p-3">{message}</div>}
    <div className="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Card title="الرحلات" value={data?.summary.trips??0}/><Card title="المفتوحة" value={data?.summary.openTrips??0}/><Card title="المكتملة" value={data?.summary.completedTrips??0}/><Card title="الإيراد" value={money(data?.summary.revenue??0)}/><Card title="التكلفة" value={money(data?.summary.cost??0)}/><Card title="صافي الربح" value={money(data?.summary.profit??0)} accent/></div>
    <div className="mb-4 flex gap-2 overflow-x-auto">{([['trips','الرحلات'],['trucks','الشاحنات'],['drivers','السائقون'],['alerts','تنبيهات الوثائق']] as const).map(([k,t])=><button key={k} onClick={()=>{setTab(k);setShowCreate(false)}} className={`rounded-xl px-4 py-2 font-bold ${tab===k?'bg-slate-900 text-white':'border bg-white'}`}>{t}</button>)}</div>
    {showCreate&&tab==='trucks'&&<form onSubmit={e=>{e.preventDefault();void create('trucks',truck)}} className="mb-5 grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-4"><Input label="اللوحة" value={truck.plateNumber} onChange={v=>setTruck({...truck,plateNumber:v})} required/><Input label="النوع" value={truck.truckType} onChange={v=>setTruck({...truck,truckType:v})}/><Input label="الموديل" value={truck.model} onChange={v=>setTruck({...truck,model:v})}/><Input label="سنة الصنع" type="number" value={truck.modelYear} onChange={v=>setTruck({...truck,modelYear:v})}/><Input label="سعة الحمولة" type="number" value={truck.capacity} onChange={v=>setTruck({...truck,capacity:v})}/><Input label="استهلاك لتر/100 كم" type="number" value={truck.fuelConsumption} onChange={v=>setTruck({...truck,fuelConsumption:v})}/><Input label="سعر الوقود" type="number" value={truck.fuelPrice} onChange={v=>setTruck({...truck,fuelPrice:v})}/><button className="mt-6 rounded-xl bg-emerald-700 px-5 py-2 text-white">حفظ</button></form>}
    {showCreate&&tab==='drivers'&&<form onSubmit={e=>{e.preventDefault();void create('drivers',driver)}} className="mb-5 grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-4"><Input label="الاسم" value={driver.name} onChange={v=>setDriver({...driver,name:v})} required/><Input label="رقم الهوية" value={driver.idNumber} onChange={v=>setDriver({...driver,idNumber:v})}/><Input label="الجوال" value={driver.phone} onChange={v=>setDriver({...driver,phone:v})}/><Input label="الجنسية" value={driver.nationality} onChange={v=>setDriver({...driver,nationality:v})}/><Input label="رقم الرخصة" value={driver.licenseNumber} onChange={v=>setDriver({...driver,licenseNumber:v})}/><Input label="انتهاء الرخصة" type="date" value={driver.licenseExpiry} onChange={v=>setDriver({...driver,licenseExpiry:v})}/><Input label="رقم بطاقة السائق" value={driver.driverCardNumber} onChange={v=>setDriver({...driver,driverCardNumber:v})}/><button className="mt-6 rounded-xl bg-emerald-700 px-5 py-2 text-white">حفظ</button></form>}
    {tab==='alerts'&&<form onSubmit={saveDocument} className="mb-5 grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-4"><Select label="المالك" value={document.ownerType} onChange={v=>setDocument({...document,ownerType:v,ownerId:''})} options={[['TRUCK','شاحنة'],['DRIVER','سائق']]}/><Select label={document.ownerType==='TRUCK'?'الشاحنة':'السائق'} value={document.ownerId} onChange={v=>setDocument({...document,ownerId:v})} options={document.ownerType==='TRUCK'?(data?.trucks??[]).map(x=>[String(x.id),x.plateNumber]):(data?.drivers??[]).map(x=>[String(x.id),x.name])}/><Input label="نوع الوثيقة" value={document.documentType} onChange={v=>setDocument({...document,documentType:v})} required/><Input label="رقم الوثيقة" value={document.documentNumber} onChange={v=>setDocument({...document,documentNumber:v})}/><Input label="تاريخ الإصدار" type="date" value={document.issueDate} onChange={v=>setDocument({...document,issueDate:v})}/><Input label="تاريخ الانتهاء" type="date" value={document.expiryDate} onChange={v=>setDocument({...document,expiryDate:v})}/><Input label="رابط المرفق" value={document.attachmentUrl} onChange={v=>setDocument({...document,attachmentUrl:v})}/><button className="mt-6 rounded-xl bg-emerald-700 px-5 py-2 text-white">حفظ الوثيقة</button></form>}
    <section className="rounded-2xl border bg-white p-5 shadow-sm">{loading?<p className="p-8 text-center">جارٍ التحميل…</p>:tab==='trips'?<Trips trips={data?.trips??[]} edit={setSelected}/>:tab==='trucks'?<Trucks rows={data?.trucks??[]}/>:tab==='drivers'?<Drivers rows={data?.drivers??[]}/>:<Alerts docs={[...(data?.alerts.truckDocuments??[]),...(data?.alerts.driverDocuments??[])]}/>}</section>
    {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><form onSubmit={saveTrip} className="max-h-[90vh] w-full max-w-4xl overflow-y-auto rounded-2xl bg-white p-6"><div className="mb-4 flex justify-between"><h2 className="text-xl font-bold">تحديث {selected.tripNumber}</h2><button type="button" onClick={()=>setSelected(null)}>✕</button></div><div className="grid gap-3 md:grid-cols-3"><Select label="الشاحنة" value={String(selected.truck?.id??'')} onChange={v=>setSelected({...selected,truck:{...(data!.trucks.find(x=>x.id===Number(v))!),id:Number(v)}})} options={(data?.trucks??[]).map(x=>[String(x.id),x.plateNumber])}/><Select label="السائق" value={String(selected.driver?.id??'')} onChange={v=>setSelected({...selected,driver:{...(data!.drivers.find(x=>x.id===Number(v))!),id:Number(v)}})} options={(data?.drivers??[]).map(x=>[String(x.id),x.name])}/><Select label="الحالة" value={selected.status} onChange={v=>setSelected({...selected,status:v})} options={[['OPEN','مفتوحة'],['IN_PROGRESS','جارية'],['COMPLETED','مكتملة'],['CANCELLED','ملغاة']]}/>{tripFields.map(field=><Input key={field} label={labels[field]} type="number" value={String(selected[field]??'')} onChange={v=>setSelected({...selected,[field]:v})}/>)}</div><div className="mt-5 rounded-xl bg-slate-100 p-4 text-sm">سيُعاد حساب تكلفة الوقود، التكلفة الكلية، وصافي الربح على الخادم عند الحفظ.</div><button className="mt-4 rounded-xl bg-blue-700 px-6 py-3 font-bold text-white">حفظ وإعادة الحساب</button></form></div>}
  </div></main>
}
const labels:Record<typeof tripFields[number],string>={transportRevenue:'إيراد النقل',fuelLiters:'لترات الوقود',fuelPricePerLiter:'سعر اللتر',driverTripFee:'أجرة السائق',maintenanceCost:'الصيانة',administrativeCost:'تكلفة إدارية',roadPermitCost:'تصاريح الطرق',otherCost:'تكلفة أخرى',estimatedKm:'كم مقدّر',actualKm:'كم فعلي'};
function Trips({trips,edit}:{trips:Trip[];edit:(x:Trip)=>void}){if(!trips.length)return <Empty text="لا توجد رحلات. تنشأ الرحلة تلقائيًا عند ترحيل سند نقل بسيارات الشركة."/>;return <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-100"><tr>{['الرحلة','السند','التاريخ','الجهة','الشاحنة/السائق','الحمولة','الإيراد','التكلفة','الربح','الحالة',''].map(x=><th key={x} className="p-3 text-right">{x}</th>)}</tr></thead><tbody>{trips.map(x=><tr key={x.id} className="border-b"><td className="p-3 font-bold">{x.tripNumber}</td><td className="p-3">{x.note?.noteNumber??'—'}</td><td className="p-3">{new Date(x.tripDate).toLocaleDateString('ar-SA')}</td><td className="p-3">{x.party?.nameAr??'—'}</td><td className="p-3">{x.truck?.plateNumber??'غير معيّنة'}<br/><span className="text-slate-500">{x.driver?.name??'غير معيّن'}</span></td><td className="p-3">{Number(x.weight??x.quantity).toLocaleString('ar-SA')}</td><td className="p-3">{money(Number(x.transportRevenue))}</td><td className="p-3">{money(Number(x.totalCost))}</td><td className={`p-3 font-bold ${Number(x.netProfit)<0?'text-red-700':'text-emerald-700'}`}>{money(Number(x.netProfit))}</td><td className="p-3">{x.status}</td><td className="p-3"><button onClick={()=>edit(x)} className="text-blue-700">تحديث</button></td></tr>)}</tbody></table></div>}
function Trucks({rows}:{rows:Truck[]}){if(!rows.length)return <Empty text="لا توجد شاحنات مسجلة."/>;return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rows.map(x=><div key={x.id} className="rounded-xl border p-4"><h3 className="text-lg font-bold">{x.plateNumber}</h3><p className="text-slate-500">{x.truckType??'نوع غير محدد'} — {x.model??'موديل غير محدد'}</p><p className="mt-2">السعة: {x.capacity?Number(x.capacity).toLocaleString('ar-SA'):'—'}</p><p>الوثائق: {x.documents.length}</p></div>)}</div>}
function Drivers({rows}:{rows:Driver[]}){if(!rows.length)return <Empty text="لا يوجد سائقون مسجلون."/>;return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rows.map(x=><div key={x.id} className="rounded-xl border p-4"><h3 className="text-lg font-bold">{x.name}</h3><p>{x.phone??'لا يوجد جوال'}</p><p>الرخصة: {x.licenseNumber??'—'}</p><p>انتهاؤها: {x.licenseExpiry?new Date(x.licenseExpiry).toLocaleDateString('ar-SA'):'—'}</p></div>)}</div>}
function Alerts({docs}:{docs:AlertDoc[]}){if(!docs.length)return <Empty text="لا توجد وثائق منتهية أو ستنتهي خلال 60 يومًا."/>;return <div className="space-y-2">{docs.map(x=>{const expired=new Date(x.expiryDate)<new Date();return <div key={`${x.truck?'t':'d'}-${x.id}`} className={`rounded-xl border p-4 ${expired?'border-red-300 bg-red-50':'border-amber-300 bg-amber-50'}`}><b>{x.truck?.plateNumber??x.driver?.name}</b> — {x.documentType} — {new Date(x.expiryDate).toLocaleDateString('ar-SA')} ({expired?'منتهية':'قريبة الانتهاء'})</div>})}</div>}
function Card({title,value,accent=false}:{title:string;value:string|number;accent?:boolean}){return <div className={`rounded-2xl border p-4 ${accent?'bg-emerald-50':'bg-white'}`}><p className="text-sm text-slate-500">{title}</p><p className="mt-1 text-xl font-bold">{value}</p></div>};function Empty({text}:{text:string}){return <p className="p-10 text-center text-slate-500">{text}</p>}
function Input({label,value,onChange,type='text',required=false}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean}){return <label className="block text-sm"><span className="mb-1 block text-slate-600">{label}</span><input required={required} type={type} step={type==='number'?'any':undefined} min={type==='number'?0:undefined} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-lg border px-3 py-2"/></label>};function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:Array<[string,string]>}){return <label className="block text-sm"><span className="mb-1 block text-slate-600">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-lg border bg-white px-3 py-2"><option value="">اختر…</option>{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>}
