"use client";
import { FormEvent, useEffect, useState } from "react";
type Row=Record<string,unknown>;type FormDef={action:string;title:string;fields:string[]};
const configs:Record<string,{title:string;endpoint:string;forms:FormDef[]}>= {
  crm:{title:"إدارة علاقات العملاء",endpoint:"/api/crm",forms:[{action:"LEAD",title:"عميل محتمل",fields:["name","companyName","email","phone","source"]},{action:"OPPORTUNITY",title:"فرصة",fields:["name","leadId","partyId","expectedValue","probability","expectedCloseDate"]},{action:"ACTIVITY",title:"متابعة / مكالمة / مهمة",fields:["activityType","subject","leadId","opportunityId","partyId","dueAt","notes"]}]},
  assets:{title:"الأصول والصيانة",endpoint:"/api/assets",forms:[{action:"CATEGORY",title:"فئة أصل",fields:["code","name","usefulLifeMonths","assetAccountId","accumulatedDepreciationAccountId","depreciationExpenseAccountId"]},{action:"ASSET",title:"أصل جديد",fields:["name","categoryId","acquisitionDate","acquisitionCost","residualValue","location","serialNumber","creditAccountId"]},{action:"PLAN",title:"صيانة وقائية",fields:["assetId","name","intervalDays","nextDueAt"]},{action:"WORK_ORDER",title:"بلاغ/أمر صيانة",fields:["assetId","planId","workType","priority","description","scheduledAt"]}]},
  documents:{title:"إدارة المستندات",endpoint:"/api/documents",forms:[{action:"CATEGORY",title:"تصنيف",fields:["code","name","defaultRetentionDays"]},{action:"DOCUMENT",title:"مستند/عقد",fields:["title","categoryId","ownerType","ownerId","effectiveDate","expiryDate","confidentiality"]},{action:"VERSION",title:"ربط إصدار مرفوع",fields:["documentId","attachmentId","changeNotes"]},{action:"PERMISSION",title:"صلاحية مستند",fields:["documentId","subjectType","subjectId","canRead","canUpdate"]}]},
  approvals:{title:"صندوق الموافقات الموحد",endpoint:"/api/approvals",forms:[{action:"REQUEST",title:"طلب موافقة",fields:["moduleKey","entityType","entityId","entityNumber","title","amount","dueAt"]}]},
  portal:{title:"تهيئة بوابة العملاء والموردين",endpoint:"/api/portal-admin",forms:[{action:"IDENTITY",title:"هوية طرف",fields:["partyId","email","permissions"]},{action:"REQUEST",title:"طلب بوابة",fields:["portalIdentityId","requestType","subject","details"]}]},
  treasury:{title:"الخزينة والتوقع النقدي",endpoint:"/api/treasury",forms:[{action:"ADJUSTMENT",title:"توقع إضافي",fields:["forecastDate","direction","description","amount","probability"]}]},
  integrations:{title:"مركز التكاملات",endpoint:"/api/integrations",forms:[{action:"CONNECTION",title:"اتصال خارجي",fields:["code","providerType","name","baseUrl"]},{action:"WEBHOOK",title:"Webhook آمن",fields:["code","url","eventTypes"]}]},
};
export default function BusinessModuleWorkspace({kind}:{kind:string}){
  const config=configs[kind],[data,setData]=useState<Row|null>(null),[message,setMessage]=useState("");
  async function load(){const response=await fetch(config.endpoint,{cache:"no-store"}),payload=await response.json();if(!response.ok)throw new Error(payload.error);setData(payload)}
  useEffect(()=>{const controller=new AbortController();fetch(config.endpoint,{signal:controller.signal}).then(response=>response.json()).then(payload=>{if(payload.error)throw new Error(payload.error);setData(payload)}).catch(error=>{if(error.name!=="AbortError")setMessage(error.message)});return()=>controller.abort()},[config.endpoint]);
  async function submit(action:string,event:FormEvent<HTMLFormElement>){event.preventDefault();const raw=Object.fromEntries(new FormData(event.currentTarget)),normalized:Row={action};for(const[key,value]of Object.entries(raw))normalized[key]=["permissions","eventTypes"].includes(key)?String(value).split(",").map(entry=>entry.trim()).filter(Boolean):value;const response=await fetch(config.endpoint,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(normalized)}),payload=await response.json();if(!response.ok)return setMessage(payload.error);event.currentTarget.reset();setMessage("تم الحفظ");await load()}
  async function decision(id:unknown,action:string){const comment=window.prompt("تعليق القرار")??"",response=await fetch(config.endpoint,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,action,comment})}),payload=await response.json();if(!response.ok)return setMessage(payload.error);await load()}
  return <main className="mx-auto max-w-7xl space-y-6 p-5 md:p-8"><header><h1 className="text-3xl font-black">{config.title}</h1><p className="text-slate-500">بيانات فعلية مع عزل الشركة والتدقيق والصلاحيات.</p></header>{message&&<div className="rounded-xl border p-3">{message}</div>}<section className="grid gap-4 lg:grid-cols-3">{config.forms.map(form=><form key={form.action} onSubmit={event=>void submit(form.action,event)} className="space-y-2 rounded-2xl border bg-white p-5"><h2 className="font-bold">{form.title}</h2>{form.fields.map(name=><input key={name} name={name} placeholder={name} type={/Date|At/.test(name)?"date":/amount|Cost|Value|probability|Days|Id$/.test(name)?"number":"text"} className="w-full rounded border p-2"/>)}<button className="w-full rounded bg-blue-700 p-2 text-white">حفظ</button></form>)}</section>{data&&Object.entries(data).map(([key,value])=>Array.isArray(value)?<section key={key} className="rounded-2xl border bg-white p-5"><h2 className="mb-3 font-bold">{key} · {value.length}</h2><div className="overflow-x-auto"><table className="w-full text-sm"><tbody>{value.slice(0,100).map((entry,index)=>{const row=entry as Row;return <tr key={String(row.id??index)} className="border-t"><td className="p-2 font-bold">{String(row.name??row.title??row.subject??row.documentNumber??row.requestNumber??row.assetNumber??row.leadNumber??row.opportunityNumber??row.workOrderNumber??row.code??index+1)}</td><td className="p-2">{String(row.status??row.stage??row.description??"")}</td><td className="p-2">{String(row.amount??row.expectedValue??row.expiryDate??row.dueAt??"")}</td>{kind==="approvals"&&row.status==="PENDING"&&<td className="space-x-2 p-2"><button onClick={()=>void decision(row.id,"APPROVE")} className="text-emerald-700">اعتماد</button><button onClick={()=>void decision(row.id,"REJECT")} className="text-red-700">رفض</button><button onClick={()=>void decision(row.id,"RETURN")}>إرجاع</button></td>}</tr>})}</tbody></table></div></section>:value&&typeof value==="object"?<section key={key} className="rounded-2xl border bg-white p-5"><h2 className="font-bold">{key}</h2><div className="mt-3 grid gap-2 sm:grid-cols-3">{Object.entries(value as Row).map(([name,entry])=><div key={name} className="rounded bg-slate-50 p-3"><small>{name}</small><b className="block">{String(entry)}</b></div>)}</div></section>:null)}</main>;
}
