"use client";

import { useEffect } from "react";

const dictionary:Record<string,string>={
  "الرئيسية":"Home","حفظ":"Save","إلغاء":"Cancel","حذف":"Delete","تعديل":"Edit","إضافة":"Add","بحث":"Search","عرض":"View","طباعة":"Print","تصدير":"Export","تحميل":"Upload","اعتماد":"Approve","ترحيل":"Post","إغلاق":"Close","فتح":"Open","إرسال":"Submit","التالي":"Next","السابق":"Previous","الكل":"All","نعم":"Yes","لا":"No","الحالة":"Status","التاريخ":"Date","الرقم":"Number","النوع":"Type","المبلغ":"Amount","الإجمالي":"Total","الرصيد":"Balance","العملة":"Currency","البيان":"Description","المرجع":"Reference","العميل":"Customer","المورد":"Supplier","المادة":"Item","الكمية":"Quantity","القيمة":"Value","الحساب":"Account","الشركة":"Company","المستخدم":"User","الاسم":"Name","الهاتف":"Phone","العنوان":"Address","المدينة":"City","ملاحظات":"Notes","التفاصيل":"Details","من":"From","إلى":"To","نشط":"Active","غير نشط":"Inactive","مسودة":"Draft","مكتمل":"Completed","معلق":"Pending","معتمد":"Approved","مرحّل":"Posted","فشل":"Failed","جديد":"New","متوقف":"Stopped","متراجع":"Declining",
  "المحاسبة والمالية":"Finance & Accounting","المبيعات":"Sales","المشتريات":"Purchases","المخزون":"Inventory","المصنع":"Factory","النقل والأسطول":"Transport & Fleet","الموارد البشرية":"Human Resources","المقاولات والمشاريع":"Projects & Contracting","التقارير والتحليلات":"Reports & Analytics","مركز الاستيراد":"Migration Center","الموافقات":"Approvals","مركز الإشعارات":"Notifications","إعدادات المؤسسة":"Organization Settings","المستخدمون والصلاحيات":"Users & Permissions","الإعدادات والأمان":"Settings & Security","المساعدة والدعم":"Help & Support","العملاء والموردون":"Customers & Suppliers","الأصول والصيانة":"Assets & Maintenance","الأعمال الخارجية":"External Business","التصميم والهوية":"Design & Identity","المهام الخلفية":"Background Jobs","التوأم التشغيلي":"Operations Twin","التنبيهات الرقابية":"Control Alerts","المرفقات والمستندات":"Documents & Attachments",
  "إضافة عميل":"Add customer","إضافة مورد":"Add supplier","فاتورة مبيعات":"Sales invoice","فاتورة مشتريات":"Purchase invoice","طلب شراء":"Purchase order","سند قبض":"Receipt voucher","سند صرف":"Payment voucher","قيد يومية":"Journal entry","مركز التقارير":"Report center","إعادة المحاولة":"Retry","لا توجد بيانات":"No data available","جارٍ التحميل…":"Loading…","جارٍ الحفظ…":"Saving…","تسجيل الخروج":"Sign out","أمان الحساب":"Account security","بيئة مؤسسية آمنة":"Secure enterprise environment","فتح المصدر":"Open source","عرض الكل":"View all","الفترة من":"Period from","صافي الربح":"Net profit","إجمالي المبيعات":"Total sales","إجمالي المشتريات":"Total purchases","قيمة المخزون":"Inventory value","العملاء النشطون":"Active customers","ذمم العملاء":"Accounts receivable","ذمم الموردين":"Accounts payable","التدفق النقدي":"Cash flow","الضريبة المستحقة":"VAT payable","لا توجد حركة":"No activity",
  "فواتير المبيعات":"Sales invoices","عروض الأسعار":"Quotations","الفواتير الأولية":"Proforma invoices","أوامر البيع":"Sales orders","فاتورة مبيعات جديدة":"New sales invoice","عرض سعر جديد":"New quotation","فاتورة أولية جديدة":"New proforma invoice","إرسال للموافقة":"Submit for approval","ترحيل المعتمد":"Post approved","قيد الموافقة":"Pending approval","مرفوض":"Rejected","ملغي":"Cancelled","مركز الموافقات":"Approval center","القيود المحاسبية":"Accounting entries","سندات القبض":"Receipt vouchers","سندات الصرف":"Payment vouchers","الإشعارات الدائنة والمدينة":"Debit and credit notes","مساحة سندات القبض":"Receipt voucher workspace","مساحة سندات الصرف":"Payment voucher workspace","طريقة السداد":"Payment method","الاستحقاق":"Due date","النقل":"Transport","بدون نقل":"No transport","نقل منفصل":"Separate transport","النقل ضمن السعر":"Transport included","قيمة النقل الداخلية":"Internal transport value","بنود الفاتورة":"Invoice lines","إضافة بند":"Add line","الوصف":"Description","الدرجة":"Grade","السعر":"Price","الخصم":"Discount","حفظ فاتورة المبيعات كمسودة":"Save sales invoice as draft","كل الحالات":"All statuses","مسح الفلاتر":"Clear filters","قبل الضريبة":"Before VAT","الإجراءات":"Actions","إلغاء وعكس":"Cancel and reverse",
  "العداد":"Odometer","الإطارات":"Tires","البطاريات":"Batteries","الوقود":"Fuel","الصيانة":"Maintenance","إيصالات النقليات":"Transport receipts","الشاحنة":"Truck","قراءة العداد":"Odometer reading","المصدر":"Source","يدوي":"Manual","رحلة":"Trip","إطار":"Tire","بطارية":"Battery","الجزء":"Vehicle part","الرأس":"Tractor head","المقطورة / الصهريج":"Tanker / trailer","المحور":"Axle","الرقم التسلسلي":"Serial number","الماركة":"Brand","الموديل":"Model","المقاس":"Size","تاريخ التركيب":"Installation date","العداد عند التركيب":"Odometer at installation","بداية الضمان":"Warranty start","انتهاء الضمان":"Warranty expiry","التكلفة":"Cost","سبب الاستبدال":"Replacement reason","الموضع":"Position","البطارية 1":"Battery 1","البطارية 2":"Battery 2","المواصفة / السعة":"Specification / capacity","التاريخ والوقت":"Date and time","قراءة عداد جديدة":"New odometer reading","تاريخ القراءة":"Reading date","ملاحظات القراءة":"Reading notes","إضافة قراءة":"Add reading","آخر عداد":"Last odometer","المسافة":"Distance","حفظ في السجل":"Save to history","مخطط 12 إطارًا — اختر موضع الإطار مباشرة":"12-tire map — select a tire position","رأس الشاحنة — 6 إطارات":"Tractor head — 6 tires","الصهريج / المقطورة — 6 إطارات":"Tanker / trailer — 6 tires","أمامي يسار":"Front left","أمامي يمين":"Front right","خلفي يسار خارجي":"Rear left outer","خلفي يسار داخلي":"Rear left inner","خلفي يمين داخلي":"Rear right inner","خلفي يمين خارجي":"Rear right outer",
  "الملخص":"Overview","سندات القبض والصرف":"Receipt and payment vouchers","التسويات والاستحقاقات":"Adjustments and accruals","البنوك والتحويلات":"Banks and transfers","التسوية البنكية":"Bank reconciliation","الإقرارات الضريبية":"VAT returns","العملات وإعادة التقييم":"Currencies and revaluation","الميزانيات":"Budgets","المصروفات والإيرادات":"Expenses and revenues","القيود والفترات":"Journals and periods","التقارير":"Reports","مسودة / غير مرحّل":"Draft / Unposted","الرصيد الرسمي المرحّل":"Official posted balance","الوارد":"Inbound","الصادر":"Outbound","رصيد أول المدة":"Opening balance","رصيد آخر المدة":"Closing balance","إجمالي المدين":"Total debit","إجمالي الدائن":"Total credit","نوع المستند":"Document type","هذا الشهر":"This month","فتح المستند":"Open document"
};
const arabicDigits="٠١٢٣٤٥٦٧٨٩۰۱۲۳۴۵۶۷۸۹";
function digits(value:string){return value.replace(/[٠-٩۰-۹]/g,char=>String(arabicDigits.indexOf(char)%10));}
function translate(value:string,english:boolean){const normalized=digits(value);if(!english)return normalized;const trimmed=normalized.trim(),exact=dictionary[trimmed];if(exact)return normalized.replace(trimmed,exact);return normalized;}

export default function LanguageRuntime(){
  useEffect(()=>{
    const english=window.localStorage.getItem("netaj-language")==="en",root=document.documentElement;
    root.lang=english?"en":"ar";root.dir=english?"ltr":"rtl";
    const visit=(node:Node)=>{
      if(node.nodeType===Node.TEXT_NODE&&node.textContent){node.textContent=translate(node.textContent,english);return;}
      if(!(node instanceof HTMLElement)||node.closest("script,style,[data-no-translate]"))return;
      for(const name of ["placeholder","title","aria-label"]){const value=node.getAttribute(name);if(value)node.setAttribute(name,translate(value,english));}
      node.childNodes.forEach(visit);
    };
    visit(document.body);
    const observer=new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(visit)));
    observer.observe(document.body,{childList:true,subtree:true});
    return()=>observer.disconnect();
  },[]);
  return null;
}
