"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Direction = "SALES" | "PURCHASE";
type Party = { id:number;nameAr:string;isCustomer:boolean;isSupplier:boolean };
type Item = { id:number;code:string;nameAr:string;unit:{nameAr:string} };
type Currency = { code:string;nameAr:string };
type Note = { id:number;noteNumber:string;noteType:string;status:string;trip?:{tripNumber:string}|null };
type DocumentLine = {id:number;itemId?:number|null;lineType:string;description?:string|null;materialGrade?:string|null;specifications?:string|null;quantity:number;unitPrice:number;discount:number;vatRate:number;item?:Item|null};
type DocumentRow = { id:number;documentNumber:string;documentType:string;documentDate:string;expiryDate?:string|null;neededDate?:string|null;status:string;referenceNumber?:string|null;salesperson?:string|null;requester?:string|null;department?:string|null;costCenter?:string|null;priority?:string|null;currency:string;bankDetails?:string|null;paymentTerms?:string|null;deliveryTime?:string|null;deliveryPlace?:string|null;deliveryTerms?:string|null;notes?:string|null;subtotal:number;discount:number;vatAmount:number;totalAmount:number;party:Party;lines:DocumentLine[];convertedDocuments:Array<{id:number;documentNumber:string;documentType:string;status:string}>;deliveryNotes:Note[];salesInvoices:Array<{invoiceNumber:string}>;supplierInvoices:Array<{purchaseNumber:string}> };
type Data = { documents:DocumentRow[];options:{parties:Party[];items:Item[];currencies:Currency[]};pagination:{page:number;pages:number;total:number} };
type Attachment = {id:number;originalName:string;size:number;uploadedAt:string};
const labels:Record<string,string>={QUOTATION:'عرض سعر',PROFORMA_INVOICE:'فاتورة مبدئية',SALES_ORDER:'أمر بيع',PURCHASE_REQUEST:'طلب شراء',PURCHASE_ORDER:'أمر شراء'};
const emptyLine={itemId:'',lineType:'ITEM',description:'',materialGrade:'',specifications:'',quantity:'',unitPrice:'',discount:'0',vatRate:'15'};

export default function WorkflowPage({direction}:{direction:Direction}){
  const initialType=direction==='SALES'?'QUOTATION':'PURCHASE_REQUEST';
  const [data,setData]=useState<Data|null>(null);const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');const [showForm,setShowForm]=useState(false);const [saving,setSaving]=useState(false);const [editingId,setEditingId]=useState<number|null>(null);
  const [attachments,setAttachments]=useState<Record<number,Attachment[]>>({});
  const [filters,setFilters]=useState({q:'',status:'',documentType:'',partyId:'',itemId:'',from:'',to:'',page:'1'});
  const [form,setForm]=useState({documentType:initialType,documentDate:new Date().toISOString().slice(0,10),expiryDate:'',neededDate:'',partyId:'',referenceNumber:'',salesperson:'',requester:'',department:'',costCenter:'',priority:'NORMAL',currency:'SAR',bankDetails:'',paymentTerms:'',deliveryTime:'',deliveryPlace:'',deliveryTerms:'',notes:''});
  const [lines,setLines]=useState([{...emptyLine}]);
  useEffect(()=>{let cancelled=false;const params=new URLSearchParams({direction,...Object.fromEntries(Object.entries(filters).filter(([,v])=>v))});fetch(`/api/workflows?${params}`,{cache:'no-store'}).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error);if(!cancelled)setData(x)}).catch((e:unknown)=>{if(!cancelled)setMessage(e instanceof Error?e.message:'تعذر تحميل المستندات')}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[direction,filters]);
  async function refresh(){const params=new URLSearchParams({direction,...Object.fromEntries(Object.entries(filters).filter(([,v])=>v))});const r=await fetch(`/api/workflows?${params}`,{cache:'no-store'});const x=await r.json();if(r.ok)setData(x)}
  async function create(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage('');try{const payload={...form,partyId:Number(form.partyId),items:lines.map(x=>({...x,itemId:Number(x.itemId),quantity:Number(x.quantity),unitPrice:Number(x.unitPrice),discount:Number(x.discount),vatRate:Number(x.vatRate)}))};const r=await fetch(editingId?`/api/workflows/${editingId}`:'/api/workflows',{method:editingId?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editingId?{...payload,action:'UPDATE'}:payload)});const x=await r.json();if(!r.ok)throw new Error(x.error);setMessage(editingId?`تم تحديث ${x.documentNumber}`:`تم إنشاء ${x.documentNumber}`);setShowForm(false);setEditingId(null);setLines([{...emptyLine}]);await refresh()}catch(e){setMessage(e instanceof Error?e.message:'تعذر الحفظ')}finally{setSaving(false)}}
  function editDocument(doc:DocumentRow){setEditingId(doc.id);setShowForm(true);setForm({documentType:doc.documentType,documentDate:doc.documentDate.slice(0,10),expiryDate:doc.expiryDate?.slice(0,10)??'',neededDate:doc.neededDate?.slice(0,10)??'',partyId:String(doc.party.id),referenceNumber:doc.referenceNumber??'',salesperson:doc.salesperson??'',requester:doc.requester??'',department:doc.department??'',costCenter:doc.costCenter??'',priority:doc.priority??'NORMAL',currency:doc.currency,bankDetails:doc.bankDetails??'',paymentTerms:doc.paymentTerms??'',deliveryTime:doc.deliveryTime??'',deliveryPlace:doc.deliveryPlace??'',deliveryTerms:doc.deliveryTerms??'',notes:doc.notes??''});setLines(doc.lines.map(line=>({itemId:String(line.itemId??line.item?.id??''),lineType:line.lineType,description:line.description??'',materialGrade:line.materialGrade??'',specifications:line.specifications??'',quantity:String(line.quantity),unitPrice:String(line.unitPrice),discount:String(line.discount),vatRate:String(line.vatRate)})));window.scrollTo({top:0,behavior:'smooth'});}
  async function action(id:number,action:string){setSaving(true);try{const r=await fetch(`/api/workflows/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});const x=await r.json();if(!r.ok)throw new Error(x.error);setMessage('تم تحديث حالة المستند');await refresh()}catch(e){setMessage(e instanceof Error?e.message:'تعذر تحديث الحالة')}finally{setSaving(false)}}
  async function convert(doc:DocumentRow,targetType:string,transportMethod?:string){setSaving(true);try{const r=await fetch(`/api/workflows/${doc.id}/convert`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({targetType,transportMethod})});const x=await r.json();if(!r.ok)throw new Error(x.error);setMessage(x.created?'تم إنشاء المستند التالي من البيانات الحالية':'المستند التالي موجود مسبقًا ولم يُكرر');await refresh()}catch(e){setMessage(e instanceof Error?e.message:'تعذر التحويل')}finally{setSaving(false)}}
  async function noteAction(note:Note,action:'POST'|'INVOICE'){let invoiceOptions:Record<string,unknown>={};if(action==='INVOICE'&&direction==='SALES'){const selected=window.prompt('طريقة النقل: NONE بدون نقل، SEPARATE منفصل، INCLUDED ضمن السعر','NONE');if(selected===null)return;const transportMode=selected.trim().toUpperCase();if(!['NONE','SEPARATE','INCLUDED'].includes(transportMode)){setMessage('طريقة النقل غير صحيحة');return;}let includedTransportRevenue=0;if(transportMode==='INCLUDED'){const value=window.prompt('قيمة النقل المضمنة داخليًا (لن تظهر كبند للعميل)','0');if(value===null)return;includedTransportRevenue=Number(value);if(!Number.isFinite(includedTransportRevenue)||includedTransportRevenue<0){setMessage('قيمة النقل غير صحيحة');return;}}invoiceOptions={transportMode,includedTransportRevenue};}setSaving(true);try{const url=action==='POST'?`/api/notes/${note.id}`:`/api/notes/${note.id}/invoice`;const r=await fetch(url,{method:action==='POST'?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action==='POST'?{action:'POST'}:invoiceOptions)});const x=await r.json();if(!r.ok)throw new Error(x.error);setMessage(action==='POST'?'تم ترحيل السند للمخزون والنقل عند الحاجة':'تم إنشاء الفاتورة والقيد المتوازن دون تكرار المخزون');await refresh()}catch(e){setMessage(e instanceof Error?e.message:'تعذر تنفيذ العملية')}finally{setSaving(false)}}
  async function upload(documentId:number,file:File){const body=new FormData();body.set('entityType','BUSINESS_DOCUMENT');body.set('entityId',String(documentId));body.set('file',file);const r=await fetch('/api/attachments',{method:'POST',body});const x=await r.json();if(!r.ok){setMessage(x.error);return}setMessage('تم رفع المرفق فعليًا وحفظ بياناته');setAttachments(v=>({...v,[documentId]:[x,...(v[documentId]??[])]}))}
  async function loadAttachments(documentId:number){const r=await fetch(`/api/attachments?entityType=BUSINESS_DOCUMENT&entityId=${documentId}`);const rows:Attachment[]=r.ok?await r.json():[];setAttachments(v=>({...v,[documentId]:rows}))}
  const parties=(data?.options.parties??[]).filter(x=>direction==='SALES'?x.isCustomer:x.isSupplier);
  return <main dir="rtl" className="min-h-screen bg-slate-50 p-5 text-slate-900 md:p-8"><div className="mx-auto max-w-7xl">
    <header className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><Link href="/" className="text-sm text-blue-700">الرئيسية</Link><h1 className="text-3xl font-bold">{direction==='SALES'?'دورة المبيعات':'دورة المشتريات'}</h1><p className="text-slate-500">تحويل مترابط دون إعادة إدخال أو تكرار أثر المخزون والمحاسبة.</p></div><button onClick={()=>{if(showForm){setShowForm(false);setEditingId(null)}else{setEditingId(null);setForm({...form,documentType:initialType,partyId:'',referenceNumber:'',notes:''});setLines([{...emptyLine}]);setShowForm(true)}}} className="rounded-xl bg-blue-700 px-5 py-3 font-bold text-white">{showForm?'إغلاق':direction==='SALES'?'عرض سعر جديد':'طلب شراء جديد'}</button></header>
    {message&&<div className="mb-4 rounded-xl border border-blue-200 bg-blue-50 p-3">{message}</div>}
    {showForm&&<form onSubmit={create} className="mb-6 space-y-5 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">{editingId?'تعديل المسودة':labels[form.documentType]}</h2><div className="grid gap-3 md:grid-cols-3 xl:grid-cols-4"><Input label="التاريخ" type="date" value={form.documentDate} onChange={v=>setForm({...form,documentDate:v})} required/><Select label={direction==='SALES'?'العميل':'المورد المقترح'} value={form.partyId} onChange={v=>setForm({...form,partyId:v})} options={parties.map(x=>[String(x.id),x.nameAr])} required/><Input label="المرجع" value={form.referenceNumber} onChange={v=>setForm({...form,referenceNumber:v})}/><Select label="العملة" value={form.currency} onChange={v=>setForm({...form,currency:v})} options={(data?.options.currencies??[]).map(x=>[x.code,`${x.code} — ${x.nameAr}`])} required/>{direction==='SALES'?<><Input label="الصلاحية حتى" type="date" value={form.expiryDate} onChange={v=>setForm({...form,expiryDate:v})}/><Input label="مسؤول المبيعات" value={form.salesperson} onChange={v=>setForm({...form,salesperson:v})}/><Input label="شروط الدفع" value={form.paymentTerms} onChange={v=>setForm({...form,paymentTerms:v})}/><Input label="مدة التسليم" value={form.deliveryTime} onChange={v=>setForm({...form,deliveryTime:v})}/><Input label="مكان التسليم" value={form.deliveryPlace} onChange={v=>setForm({...form,deliveryPlace:v})}/></>:<><Input label="مقدم الطلب" value={form.requester} onChange={v=>setForm({...form,requester:v})}/><Input label="القسم" value={form.department} onChange={v=>setForm({...form,department:v})}/><Input label="مركز التكلفة" value={form.costCenter} onChange={v=>setForm({...form,costCenter:v})}/><Input label="تاريخ الاحتياج" type="date" value={form.neededDate} onChange={v=>setForm({...form,neededDate:v})}/><Select label="الأولوية" value={form.priority} onChange={v=>setForm({...form,priority:v})} options={[["LOW","منخفضة"],["NORMAL","عادية"],["HIGH","عالية"],["URGENT","عاجلة"]]}/></>}</div>
      <div><div className="mb-2 flex justify-between"><h3 className="font-bold">البنود</h3><button type="button" onClick={()=>setLines([...lines,{...emptyLine}])} className="font-bold text-blue-700">+ إضافة بند</button></div>{lines.map((row,i)=><div key={i} className="mb-2 grid gap-2 rounded-xl bg-slate-50 p-3 md:grid-cols-7"><Select label="المادة" value={row.itemId} onChange={v=>setLines(lines.map((x,n)=>n===i?{...x,itemId:v}:x))} options={(data?.options.items??[]).map(x=>[String(x.id),`${x.code} — ${x.nameAr} (${x.unit.nameAr})`])} required/><Input label="الوصف" value={row.description} onChange={v=>setLines(lines.map((x,n)=>n===i?{...x,description:v}:x))}/><Input label="الدرجة/المواصفات" value={direction==='SALES'?row.materialGrade:row.specifications} onChange={v=>setLines(lines.map((x,n)=>n===i?{...x,[direction==='SALES'?'materialGrade':'specifications']:v}:x))}/><Input label="الكمية" type="number" value={row.quantity} onChange={v=>setLines(lines.map((x,n)=>n===i?{...x,quantity:v}:x))} required/><Input label="السعر" type="number" value={row.unitPrice} onChange={v=>setLines(lines.map((x,n)=>n===i?{...x,unitPrice:v}:x))} required={direction==='SALES'}/><Input label="الخصم" type="number" value={row.discount} onChange={v=>setLines(lines.map((x,n)=>n===i?{...x,discount:v}:x))}/><button type="button" disabled={lines.length===1} onClick={()=>setLines(lines.filter((_,n)=>n!==i))} className="mt-6 text-red-700 disabled:text-slate-300">حذف</button></div>)}</div><Input label="ملاحظات" value={form.notes} onChange={v=>setForm({...form,notes:v})}/><button disabled={saving} className="rounded-xl bg-emerald-700 px-6 py-3 font-bold text-white disabled:opacity-50">{editingId?'حفظ التعديلات':'حفظ مسودة'}</button></form>}
    <section className="mb-5 rounded-2xl border bg-white p-4"><div className="grid gap-2 md:grid-cols-4 xl:grid-cols-7"><Input label="بحث/رقم" value={filters.q} onChange={v=>setFilters({...filters,q:v,page:'1'})}/><Select label="النوع" value={filters.documentType} onChange={v=>setFilters({...filters,documentType:v,page:'1'})} options={direction==='SALES'?[["","الكل"],["QUOTATION","عرض سعر"],["PROFORMA_INVOICE","فاتورة مبدئية"],["SALES_ORDER","أمر بيع"]]:[["","الكل"],["PURCHASE_REQUEST","طلب شراء"],["PURCHASE_ORDER","أمر شراء"]]}/><Select label="الحالة" value={filters.status} onChange={v=>setFilters({...filters,status:v,page:'1'})} options={[["","الكل"],["DRAFT","مسودة"],["PENDING","قيد المراجعة"],["APPROVED","معتمد"],["COMPLETED","مكتمل"],["CANCELLED","ملغى"]]}/><Select label="الجهة" value={filters.partyId} onChange={v=>setFilters({...filters,partyId:v,page:'1'})} options={[["","الكل"],...parties.map(x=>[String(x.id),x.nameAr] as [string,string])]}/><Select label="المادة" value={filters.itemId} onChange={v=>setFilters({...filters,itemId:v,page:'1'})} options={[["","الكل"],...(data?.options.items??[]).map(x=>[String(x.id),x.nameAr] as [string,string])]}/><Input label="من" type="date" value={filters.from} onChange={v=>setFilters({...filters,from:v,page:'1'})}/><Input label="إلى" type="date" value={filters.to} onChange={v=>setFilters({...filters,to:v,page:'1'})}/></div></section>
    <section className="space-y-3">{loading?<p className="rounded-2xl border bg-white p-10 text-center">جارٍ التحميل…</p>:!data?.documents.length?<p className="rounded-2xl border bg-white p-10 text-center text-slate-500">لا توجد مستندات مطابقة.</p>:data.documents.map(doc=><article key={doc.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="text-lg font-bold">{doc.documentNumber}</h2><Badge status={doc.status}/></div><p className="text-sm text-slate-500">{labels[doc.documentType]} · {doc.party.nameAr} · {new Date(doc.documentDate).toLocaleDateString('ar-SA')}</p></div><div className="text-left"><b>{money(doc.totalAmount,doc.currency)}</b><p className="text-xs text-slate-500">قبل الضريبة {money(Number(doc.subtotal)-Number(doc.discount),doc.currency)} · VAT {money(doc.vatAmount,doc.currency)}</p></div></div><div className="mt-3 flex flex-wrap gap-2 text-sm">{doc.status==='DRAFT'&&<button disabled={saving} onClick={()=>editDocument(doc)} className="rounded-lg border border-blue-200 px-3 py-2 text-blue-700">تعديل المسودة</button>}{doc.status==='DRAFT'&&<button disabled={saving} onClick={()=>action(doc.id,'SUBMIT')} className="rounded-lg border px-3 py-2">إرسال للمراجعة</button>}{['DRAFT','PENDING'].includes(doc.status)&&<button disabled={saving} onClick={()=>action(doc.id,'APPROVE')} className="rounded-lg bg-emerald-700 px-3 py-2 text-white">اعتماد</button>}{doc.status==='APPROVED'&&<ConversionButtons doc={doc} direction={direction} convert={convert}/>} {!['COMPLETED','CANCELLED'].includes(doc.status)&&<button disabled={saving} onClick={()=>action(doc.id,'CANCEL')} className="rounded-lg border border-red-200 px-3 py-2 text-red-700">إلغاء</button>}<label className="cursor-pointer rounded-lg border px-3 py-2 text-blue-700">رفع مرفق<input type="file" accept=".pdf,.jpg,.jpeg,.png,.xls,.xlsx" className="hidden" onChange={e=>e.target.files?.[0]&&void upload(doc.id,e.target.files[0])}/></label><button onClick={()=>void loadAttachments(doc.id)} className="rounded-lg border px-3 py-2">المرفقات</button></div>
      {!!doc.convertedDocuments.length&&<p className="mt-3 text-sm text-slate-600">المستندات الناتجة: {doc.convertedDocuments.map(x=>x.documentNumber).join('، ')}</p>}{doc.deliveryNotes.map(note=><div key={note.id} className="mt-3 flex flex-wrap items-center gap-2 rounded-xl bg-slate-50 p-3 text-sm"><b>{note.noteNumber}</b><span>{note.status}</span>{note.status!=='POSTED'&&<button onClick={()=>void noteAction(note,'POST')} className="text-emerald-700">ترحيل المخزون</button>}{note.status==='POSTED'&&<button onClick={()=>void noteAction(note,'INVOICE')} className="text-blue-700">إنشاء الفاتورة والقيد</button>}{note.trip&&<span>رحلة: {note.trip.tripNumber}</span>}<Link href={`/notes/${note.id}/print`} className="text-slate-700">طباعة</Link></div>)}{(attachments[doc.id]??[]).map(file=><a key={file.id} href={`/api/attachments/${file.id}`} target="_blank" className="mt-2 block text-sm text-blue-700">📎 {file.originalName} ({Math.ceil(file.size/1024)} KB)</a>)}</article>)}</section>
  </div></main>
}
function ConversionButtons({doc,direction,convert}:{doc:DocumentRow;direction:Direction;convert:(d:DocumentRow,t:string,m?:string)=>void}){
  if(direction==='SALES'){
    if(doc.documentType==='QUOTATION') return <button onClick={()=>convert(doc,'PROFORMA_INVOICE')} className="rounded-lg bg-blue-700 px-3 py-2 text-white">تحويل إلى PI</button>;
    if(doc.documentType==='PROFORMA_INVOICE') return <button onClick={()=>convert(doc,'SALES_ORDER')} className="rounded-lg bg-blue-700 px-3 py-2 text-white">تحويل إلى أمر بيع</button>;
    if(doc.documentType==='SALES_ORDER') return <><button onClick={()=>convert(doc,'DELIVERY_NOTE','CUSTOMER')} className="rounded-lg bg-blue-700 px-3 py-2 text-white">سند تسليم/نقل العميل</button><button onClick={()=>convert(doc,'DELIVERY_NOTE','COMPANY')} className="rounded-lg bg-slate-900 px-3 py-2 text-white">سند + رحلة شركة</button></>;
    return null;
  }
  if(doc.documentType==='PURCHASE_REQUEST') return <button onClick={()=>convert(doc,'PURCHASE_ORDER')} className="rounded-lg bg-blue-700 px-3 py-2 text-white">تحويل إلى أمر شراء</button>;
  if(doc.documentType==='PURCHASE_ORDER') return <button onClick={()=>convert(doc,'RECEIPT_NOTE','CUSTOMER')} className="rounded-lg bg-blue-700 px-3 py-2 text-white">إنشاء سند استلام</button>;
  return null;
}
function Badge({status}:{status:string}){const style=status==='APPROVED'||status==='COMPLETED'?'bg-emerald-100 text-emerald-800':status==='CANCELLED'||status==='REJECTED'?'bg-red-100 text-red-800':status==='PENDING'?'bg-blue-100 text-blue-800':'bg-amber-100 text-amber-800';return <span className={`rounded-full px-2 py-1 text-xs font-bold ${style}`}>{status}</span>}
function money(value:number,currency='SAR'){return new Intl.NumberFormat('ar-SA',{style:'currency',currency}).format(Number(value))}
function Input({label,value,onChange,type='text',required=false}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean}){return <label className="block text-sm"><span className="mb-1 block text-slate-600">{label}</span><input required={required} type={type} step={type==='number'?'0.01':undefined} min={type==='number'?0:undefined} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-lg border px-3 py-2"/></label>}
function Select({label,value,onChange,options,required=false}:{label:string;value:string;onChange:(v:string)=>void;options:Array<[string,string]>;required?:boolean}){return <label className="block text-sm"><span className="mb-1 block text-slate-600">{label}</span><select required={required} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-lg border bg-white px-3 py-2">{required&&<option value="">اختر…</option>}{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>}
