import assert from "node:assert/strict";
import { after,before,test } from "node:test";
import { copyFileSync,mkdtempSync,rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { PrismaClient } from "@prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import { analyticsRange,createEquipmentReading,loadExecutiveDashboard,loadLegacyReport,upsertFactoryTarget } from "../lib/analytics.ts";
import { createPdf,createXlsx } from "../lib/financial-export.ts";
import { legacyReportTable } from "../lib/legacy-report-export.ts";

const directory=mkdtempSync(join(tmpdir(),"netaj-analytics-test-")),databasePath=join(directory,"analytics.db");copyFileSync("prisma/netaj.db",databasePath);const prisma=new PrismaClient({adapter:new PrismaBetterSqlite3({url:`file:${databasePath}`})});
let itemId,partyId,driverId,truckId;const range={from:new Date("2031-09-01T00:00:00.000"),to:new Date("2031-09-30T23:59:59.999")};const suffix=Date.now().toString(36).toUpperCase();
before(async()=>{const unit=await prisma.unit.create({data:{code:`A${suffix}`,nameAr:"طن تحليلات",nameEn:"Analytics ton"}}),item=await prisma.item.create({data:{code:`AN-${suffix}`,nameAr:"مادة تحليلات",unitId:unit.id}}),party=await prisma.party.create({data:{nameAr:"عميل تحليلات",isCustomer:true,isSupplier:true,createdAt:new Date("2031-09-03")}}),revenue=await prisma.account.create({data:{code:`REV-${suffix}`,nameAr:"إيراد تحليلات",accountType:"REVENUE"}}),expense=await prisma.account.create({data:{code:`EXP-${suffix}`,nameAr:"مصروف تحليلات",accountType:"EXPENSE"}}),asset=await prisma.account.create({data:{code:`AST-${suffix}`,nameAr:"أصل تحليلات",accountType:"ASSET"}});itemId=item.id;partyId=party.id;
 await prisma.sale.create({data:{invoiceNumber:`AN-S-${suffix}`,invoiceDate:new Date("2031-09-10"),partyId,status:"COMPLETED",subtotal:100,vatAmount:15,totalAmount:115,functionalSubtotal:100,functionalVatAmount:15,functionalTotalAmount:115,items:{create:{itemId,quantity:10,unitPrice:10,vatRate:15,vatAmount:15,totalAmount:115}}}});
 await prisma.purchase.create({data:{purchaseNumber:`AN-P-${suffix}`,purchaseDate:new Date("2031-09-08"),partyId,status:"COMPLETED",subtotal:50,vatAmount:7.5,totalAmount:57.5,functionalSubtotal:50,functionalVatAmount:7.5,functionalTotalAmount:57.5,items:{create:{itemId,quantity:5,unitPrice:10,vatRate:15,vatAmount:7.5,totalAmount:57.5}}}});
 await prisma.stockMovement.createMany({data:[{movementNumber:`AN-M1-${suffix}`,movementDate:new Date("2031-08-15"),itemId,partyId,ownershipType:"PARTY",movementType:"DELIVERY",quantityOut:10,unitCost:5,totalValue:50,balanceAfter:-10},{movementNumber:`AN-M2-${suffix}`,movementDate:new Date("2031-09-15"),itemId,partyId,ownershipType:"PARTY",movementType:"DELIVERY",quantityOut:5,unitCost:5,totalValue:25,balanceAfter:-15},{movementNumber:`AN-M3-${suffix}`,movementDate:new Date("2031-09-10"),itemId,ownershipType:"COMPANY",movementType:"DELIVERY",quantityOut:10,unitCost:6,totalValue:60,balanceAfter:20}]});
 await prisma.companyStock.create({data:{itemId,quantity:20,averageCost:6}});await prisma.bankAccount.create({data:{name:`بنك تحليلات ${suffix}`,currency:"SAR",openingBalance:100,currentBalance:100,ledgerAccountId:asset.id}});
 await prisma.journalEntry.create({data:{entryNumber:`AN-J-${suffix}`,entryDate:new Date("2031-09-10"),status:"POSTED",totalDebit:140,totalCredit:140,lines:{create:[{accountId:revenue.id,accountCode:revenue.code,accountName:revenue.nameAr,credit:100},{accountId:expense.id,accountCode:expense.code,accountName:expense.nameAr,debit:40},{accountId:asset.id,accountCode:asset.code,accountName:asset.nameAr,debit:100,credit:40}]}}});
 await prisma.factoryTransaction.create({data:{transactionNumber:`AN-F-${suffix}`,transactionDate:new Date("2031-09-11"),partyId,itemId,transactionType:"PRODUCTION",quantity:10,manufacturingFeePerTon:10,manufacturingFeeTotal:100,totalAmount:115,status:"POSTED"}});await prisma.expenseCategory.create({data:{code:`AN-C-${suffix}`,nameAr:"مصروف تحليلات",accountId:expense.id}}).then(category=>prisma.expense.create({data:{voucherNumber:`AN-E-${suffix}`,expenseDate:new Date("2031-09-12"),expenseType:"FACTORY",categoryId:category.id,description:"تكلفة مصنع",amountBeforeVat:10,totalAmount:10,costCenter:"FACTORY",status:"POSTED"}}));
 const driver=await prisma.driver.create({data:{name:"سائق تحليلات",idNumber:`AN-D-${suffix}`}}),truck=await prisma.truck.create({data:{plateNumber:`AN-T-${suffix}`}});driverId=driver.id;truckId=truck.id;await prisma.transportTrip.create({data:{tripNumber:`AN-TR-${suffix}`,tripDate:new Date("2031-09-13"),partyId,itemId,driverId,truckId,quantity:10,weight:10,transportRevenue:100,totalCost:60,netProfit:40,status:"COMPLETED"}});
});
after(async()=>{await prisma.$disconnect();rmSync(directory,{recursive:true,force:true})});
const params=(report)=>new URLSearchParams({report,from:"2031-09-01",to:"2031-09-30"});

test("نطاق التقرير يحافظ على الشهر المختار بصرف النظر عن المنطقة الزمنية",()=>{const parsed=analyticsRange(params("monthly-comparison"));assert.equal(parsed.from.toISOString(),"2031-09-01T00:00:00.000Z");assert.equal(parsed.to.toISOString(),"2031-09-30T23:59:59.999Z")});

test("لوحة المالك تحسب KPIs وأحدث المعاملات من المصادر الفعلية",async()=>{const dashboard=await prisma.$transaction(tx=>loadExecutiveDashboard(tx,range,new Set(["SALES","PURCHASES","ACCOUNTING","INVENTORY","FACTORY","TRANSPORT"]),60));assert.equal(dashboard.kpis.sales,115);assert.equal(dashboard.kpis.purchases,57.5);assert.equal(dashboard.kpis.netProfit,60);assert.ok(dashboard.kpis.liquidity>=100);assert.ok(dashboard.kpis.inventory>=120);assert.equal(dashboard.factory.netProfit,90);assert.equal(dashboard.transport.netProfit,40);assert.ok(dashboard.latestTransactions.some(row=>row.type==="فاتورة مبيعات"&&row.document.startsWith("AN-S-")));assert.ok(dashboard.latestTransactions.some(row=>row.type==="حركة مخزون"&&row.href.startsWith("/inventory")))});
test("تعطل delegate اختياري لا يسقط لوحة التحكم أو المؤشرات الأساسية",async()=>{const dashboard=await prisma.$transaction(tx=>{const staleClient=new Proxy(tx,{get(target,key,receiver){if(["unifiedApprovalRequest","backgroundJob","controlAlert"].includes(String(key)))return undefined;return Reflect.get(target,key,receiver)}});return loadExecutiveDashboard(staleClient,range,new Set(["SALES","PURCHASES","ACCOUNTING","INVENTORY","FACTORY","TRANSPORT","APPROVALS"]),60)});assert.equal(dashboard.kpis.sales,115);assert.equal(dashboard.kpis.netProfit,60);assert.equal(dashboard.alerts.pendingApprovals,0);assert.equal(dashboard.alerts.failedJobs,0);assert.equal(dashboard.alerts.openControlAlerts,0);assert.ok(dashboard.latestTransactions.length>0)});
test("الفترة الخالية تعرض حالة صادقة بلا خطأ أو أرقام معاملات وهمية",async()=>{const emptyRange={from:new Date("2035-01-01T00:00:00.000Z"),to:new Date("2035-01-31T23:59:59.999Z")};const dashboard=await prisma.$transaction(tx=>loadExecutiveDashboard(tx,emptyRange,new Set(["SALES","PURCHASES","ACCOUNTING","INVENTORY","FACTORY","TRANSPORT"]),60));assert.equal(dashboard.kpis.sales,0);assert.equal(dashboard.kpis.purchases,0);assert.equal(dashboard.kpis.netProfit,0);assert.equal(dashboard.latestTransactions.length,0);assert.equal(dashboard.monthly.length,1);assert.equal(dashboard.monthly[0].sales,0);assert.equal(dashboard.monthly[0].netProfit,0)});
test("ربحية المادة تربط الإيراد وCOGS والمشتريات وربح الطن",async()=>{const report=await prisma.$transaction(tx=>loadLegacyReport(tx,"material-profitability",range,params("material-profitability"))),row=report.rows.find(x=>x.itemId===itemId);assert.equal(row.revenueExVat,100);assert.equal(row.cogs,60);assert.equal(row.purchasesValue,50);assert.equal(row.netProfit,40);assert.equal(row.profitPerTon,4);assert.ok(row.source.movements[0].href)});
test("تحليل نشاط العميل يكتشف العميل الجديد والمتراجع",async()=>{const query=params("customer-activity");query.set("inactiveDays","30");const report=await prisma.$transaction(tx=>loadLegacyReport(tx,"customer-activity",range,query)),row=report.rows.find(x=>x.partyId===partyId);assert.equal(row.withdrawals,5);assert.equal(row.previousWithdrawals,10);assert.equal(row.declining,true);assert.equal(row.isNew,true);assert.match(row.href,/parties/)});
test("المقارنة الشهرية تعرض MoM وYoY والمتوسط دون قيم وهمية",async()=>{const report=await prisma.$transaction(tx=>loadLegacyReport(tx,"monthly-comparison",range,params("monthly-comparison"))),row=report.rows.find(x=>x.month==="2031-09");assert.equal(row.sales,115);assert.equal(row.purchases,57.5);assert.equal(row.netProfit,60);assert.equal(typeof row.momPercent,"number");assert.equal(typeof row.yoyPercent,"number")});
test("القراءات الفيزيائية وأهداف الإنتاج تحفظ وتغذي التقرير اليومي",async()=>{await prisma.$transaction(tx=>createEquipmentReading(tx,{readingDate:"2031-09-20",assetType:"TANK",assetName:"خزان الزيت",readingType:"DAILY",unit:"L",openingValue:100,usedValue:20,closingValue:80}));await prisma.$transaction(tx=>upsertFactoryTarget(tx,{year:2031,month:9,itemId,targetTons:12}));const readings=await prisma.$transaction(tx=>loadLegacyReport(tx,"equipment-readings",range,params("equipment-readings"))),daily=await prisma.$transaction(tx=>loadLegacyReport(tx,"daily-production",range,params("daily-production")));assert.equal(readings.rows[0].closing,80);assert.equal(daily.summary.monthlyTargetTons,12);assert.equal(daily.summary.monthlyTargetVariance,-2);assert.equal(daily.oil.length,1)});
test("تقارير Phase E تصدر Excel وPDF حقيقيين",async()=>{const report=await prisma.$transaction(tx=>loadLegacyReport(tx,"customer-vehicle",range,params("customer-vehicle"))),table=legacyReportTable("customer-vehicle",report,"2031-09");const xlsx=createXlsx(table),pdf=createPdf(table);assert.equal(xlsx.subarray(0,2).toString(),"PK");assert.equal(pdf.subarray(0,5).toString(),"%PDF-");assert.ok(xlsx.length>1000);assert.ok(pdf.length>500)});
test("المطابقة تقارن الأرصدة التشغيلية بالأستاذ دون إخفاء الفروقات",async()=>{const report=await prisma.$transaction(tx=>loadLegacyReport(tx,"reconciliation",range,params("reconciliation"))),bank=report.rows.find(row=>row.area==="Bank ↔ GL"),inventory=report.rows.find(row=>row.area==="Inventory ↔ GL");assert.equal(bank.operational>=100,true);assert.equal(bank.difference,bank.operational-bank.ledger);assert.equal(inventory.difference,inventory.operational-inventory.ledger);assert.ok(report.rows.some(row=>row.area==="Transfers not invoiced"));});
test("Module Entitlements لا تكشف مؤشرات الوحدات المعطلة",async()=>{const dashboard=await prisma.$transaction(tx=>loadExecutiveDashboard(tx,range,new Set(["CORE"]),60));assert.equal(dashboard.kpis.sales,0);assert.equal(dashboard.kpis.inventory,0);assert.equal(dashboard.materials.length,0);assert.equal(dashboard.customerActivity.length,0);assert.equal(dashboard.factory,null);assert.equal(dashboard.transport,null)});
