import assert from "node:assert/strict";
import { after, before, test } from "node:test";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import Database from "better-sqlite3";
import { PrismaClient } from "@prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import { createBankAccount, ensureFinanceFoundation } from "../lib/finance.ts";
import { chequeAction, createCheque, createChequeBook, chequeWorkspace } from "../lib/cheques.ts";
import { runWithDataScope, scopedModels } from "../lib/data-scope.ts";

const directory = mkdtempSync(join(tmpdir(), "netaj-cheque-tests-")), databasePath = join(directory, "cheques.db");
let prisma, bankId, secondBankId, partyId, payableId, receivableId, partyAccountId, bookId;
const date = new Date().toISOString().slice(0, 10), actor = "cheque-test";
const create = (extra = {}) => prisma.$transaction(tx => createCheque(tx, { direction: "PAID", bankAccountId: bankId, chequeBookId: bookId, partyId, counterAccountId: partyAccountId, suspenseAccountId: payableId, amount: "125.50", issueDate: date, dueDate: date, description: "شيك اختبار", ...extra }, actor));
const action = (id, value, extra = {}) => prisma.$transaction(tx => chequeAction(tx, id, value, extra, actor));
before(async () => {
  const source = new Database("prisma/netaj.db", { readonly: true }); await source.backup(databasePath); source.close();
  const copy = new Database(databasePath);
  if (!copy.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='Cheque'").get()) copy.exec(readFileSync("prisma/migrations/20260921191000_cheque_register/migration.sql", "utf8"));
  if (!copy.prepare('PRAGMA table_info("JournalEntry")').all().some(column => column.name === "branchId")) copy.exec(readFileSync("prisma/migrations/20260921192000_journal_branch/migration.sql", "utf8"));
  copy.close();
  prisma = new PrismaClient({ adapter: new PrismaBetterSqlite3({ url: `file:${databasePath}` }) });
  await prisma.$transaction(tx => ensureFinanceFoundation(tx));
  const suffix = Date.now();
  partyId = (await prisma.party.create({ data: { nameAr: `طرف الشيك ${suffix}`, isCustomer: true, isSupplier: true } })).id;
  bankId = (await prisma.$transaction(tx => createBankAccount(tx, { name: `بنك الشيك ${suffix}`, openingBalance: 0 }))).id;
  secondBankId = (await prisma.$transaction(tx => createBankAccount(tx, { name: `بنك إيداع ثان ${suffix}`, openingBalance: 0 }))).id;
  payableId = (await prisma.account.create({ data: { code: `CHQ-P-${suffix}`, nameAr: "أوراق دفع اختبار", accountType: "LIABILITY" } })).id;
  receivableId = (await prisma.account.create({ data: { code: `CHQ-R-${suffix}`, nameAr: "أوراق قبض اختبار", accountType: "ASSET" } })).id;
  partyAccountId = (await prisma.account.create({ data: { code: `CHQ-T-${suffix}`, nameAr: "ذمة طرف اختبار", accountType: "LIABILITY" } })).id;
  bookId = (await prisma.$transaction(tx => createChequeBook(tx, { bankAccountId: bankId, firstNumber: 1001, lastNumber: 1010, issueDate: date }, actor))).id;
});
after(async () => { await prisma?.$disconnect(); rmSync(directory, { recursive: true, force: true }); });
test("دفاتر الشيكات تمنع تداخل النطاقات ورقم الورقة محجوز حتى عند الإلغاء", async () => {
  await assert.rejects(prisma.$transaction(tx => createChequeBook(tx, { bankAccountId: bankId, firstNumber: 1005, lastNumber: 1015, issueDate: date }, actor)), /يتداخل/);
  const cheque = await create({ chequeNumber: "1001" });
  await action(cheque.id, "CANCEL", { reason: "إلغاء ورقة قبل الإصدار" });
  await assert.rejects(create({ chequeNumber: "01001" }), /مستخدم/);
  const workspace = await prisma.$transaction(tx => chequeWorkspace(tx));
  const book = workspace.books.find(book => book.id === bookId);
  assert.equal(book.total, 10); assert.equal(book.cancelled, 1); assert.equal(book.remaining, 9);
});
test("إصدار الشيك لا يحرك البنك والصرف ينشئ قيدًا وحركة واحدة ثم الارتجاع يعكسهما", async () => {
  const cheque = await create();
  await assert.rejects(action(cheque.id, "CLEAR"), /يجب/);
  const issued = await action(cheque.id, "ISSUE");
  assert.equal(issued.status, "ISSUED");
  assert.equal(Number((await prisma.bankAccount.findUniqueOrThrow({ where: { id: bankId } })).currentBalance), 0);
  const cleared = await action(cheque.id, "CLEAR", { date });
  assert.equal(cleared.status, "CLEARED");
  assert.equal(Number((await prisma.bankAccount.findUniqueOrThrow({ where: { id: bankId } })).currentBalance), -125.5);
  assert.equal((await action(cheque.id, "CLEAR", { date })).clearingJournalId, cleared.clearingJournalId);
  assert.equal(await prisma.bankTransaction.count({ where: { referenceType: "CHEQUE_CLEAR", referenceId: cheque.id } }), 1);
  await assert.rejects(action(cheque.id, "CANCEL", { reason: "غير مسموح" }), /مرتجع/);
  await action(cheque.id, "RETURN", { reason: "أعاد البنك الشيك" });
  await action(cheque.id, "RETURN", { reason: "نفس الطلب" });
  assert.equal(Number((await prisma.bankAccount.findUniqueOrThrow({ where: { id: bankId } })).currentBalance), 0);
  assert.equal(await prisma.bankTransaction.count({ where: { referenceType: "CHEQUE_CLEAR_REVERSAL", referenceId: cheque.id } }), 1);
  const entries = await prisma.journalEntry.findMany({ where: { referenceType: { startsWith: "CHEQUE_" }, referenceId: cheque.id }, include: { lines: true } });
  assert.equal(entries.length, 4);
  for (const entry of entries) assert.equal(Number(entry.totalDebit), Number(entry.totalCredit));
  const balances = new Map();
  for (const entry of entries) for (const line of entry.lines) balances.set(line.accountId, (balances.get(line.accountId) || 0) + Number(line.debit) - Number(line.credit));
  assert.ok([...balances.values()].every(value => Math.abs(value) < .00001));
});
test("الشيك المستلم يمنع تسجيل نفس شيك العميل في بنكي إيداع ويتحصل ثم يرتجع فعليًا", async () => {
  const input = { direction: "RECEIVED", chequeNumber: "R-678", draweeBank: "بنك العميل", draweeAccount: "ACC998", suspenseAccountId: receivableId };
  const cheque = await create(input);
  await assert.rejects(create({ ...input, bankAccountId: secondBankId }), /مسجل بالفعل/);
  await action(cheque.id, "ISSUE"); await action(cheque.id, "DEPOSIT");
  await action(cheque.id, "CLEAR", { date });
  assert.equal(Number((await prisma.bankAccount.findUniqueOrThrow({ where: { id: bankId } })).currentBalance), 125.5);
  await action(cheque.id, "RETURN", { reason: "عدم كفاية الرصيد" });
  assert.equal(Number((await prisma.bankAccount.findUniqueOrThrow({ where: { id: bankId } })).currentBalance), 0);
});
test("الشيك الموقوف لا يصرف ولا يقبل إلغاء بلا سبب", async () => {
  const cheque = await create(); await action(cheque.id, "ISSUE"); await action(cheque.id, "STOP");
  await assert.rejects(action(cheque.id, "CLEAR", { date }), /يجب/);
  await assert.rejects(action(cheque.id, "CANCEL"), /السبب|سبب/);
  await action(cheque.id, "RESUME");
  const cancelled = await action(cheque.id, "CANCEL", { reason: "إلغاء أمر الدفع" });
  assert.equal(cancelled.status, "CANCELLED");
  assert.equal(await prisma.bankTransaction.count({ where: { referenceType: "CHEQUE_CLEAR", referenceId: cheque.id } }), 0);
});
test("الفترة المغلقة والتصنيف الخاطئ والعزل تمنع القيد", async () => {
  await assert.rejects(create({ suspenseAccountId: receivableId }), /حساب خصوم/);
  assert.ok(scopedModels.has("Cheque") && scopedModels.has("ChequeBook"));
  const cheque = await create();
  await assert.rejects(runWithDataScope({ tenantId: 777, companyId: 777 }, () => action(cheque.id, "ISSUE")), /غير موجود/);
  const period = await prisma.accountingPeriod.findFirstOrThrow({ where: { startDate: { lte: new Date(date) }, endDate: { gte: new Date(date) } } });
  await prisma.accountingPeriod.update({ where: { id: period.id }, data: { status: "CLOSED" } });
  await assert.rejects(action(cheque.id, "ISSUE"), /مغلقة/);
  assert.equal((await prisma.cheque.findUniqueOrThrow({ where: { id: cheque.id } })).issueJournalId, null);
  await prisma.accountingPeriod.update({ where: { id: period.id }, data: { status: period.status } });
});
