import assert from"node:assert/strict";import{after,before,test}from"node:test";import{copyFileSync,mkdtempSync,rmSync}from"node:fs";import{tmpdir}from"node:os";import{join}from"node:path";import{PrismaClient}from"@prisma/client";import{PrismaBetterSqlite3}from"@prisma/adapter-better-sqlite3";import{createBankAccount,ensureFinanceFoundation}from"../lib/finance.ts";import{createAdvance,createEmployee,createExternalWorker,createExternalWorkerCost,createPayrollRun,payPayrollLine,postPayrollRun,upsertAttendance}from"../lib/hr.ts";
const dir=mkdtempSync(join(tmpdir(),"netaj-hr-test-")),db=join(dir,"hr.test.db");copyFileSync("prisma/netaj.db",db);const prisma=new PrismaClient({adapter:new PrismaBetterSqlite3({url:`file:${db}`})});let employeeId,bankId,workerId,runId,lineId;
before(async()=>{await prisma.$transaction(tx=>ensureFinanceFoundation(tx));const s=Date.now().toString(36),bank=await prisma.$transaction(tx=>createBankAccount(tx,{name:`بنك رواتب ${s}`,openingBalance:10000})),employee=await prisma.$transaction(tx=>createEmployee(tx,{nameAr:`موظف اختبار ${s}`,basicSalary:3000,housingAllowance:300,transportAllowance:200,costCenter:"FACTORY",iban:"SA000TEST"})),worker=await prisma.$transaction(tx=>createExternalWorker(tx,{name:`عامل خارجي ${s}`,wage:200,costCenter:"FACTORY"}));employeeId=employee.id;bankId=bank.id;workerId=worker.id});after(async()=>{await prisma.$disconnect();rmSync(dir,{recursive:true,force:true})});
test("الحضور اليومي يحفظ الغياب والإضافي دون تكرار",async()=>{await prisma.$transaction(tx=>upsertAttendance(tx,{employeeId,attendanceDate:"2026-09-02",status:"ABSENT",workHours:0}));await prisma.$transaction(tx=>upsertAttendance(tx,{employeeId,attendanceDate:"2026-09-03",status:"PRESENT",workHours:8,overtimeHours:8}));await prisma.$transaction(tx=>upsertAttendance(tx,{employeeId,attendanceDate:"2026-09-03",status:"PRESENT",workHours:8,overtimeHours:8}));assert.equal(await prisma.attendanceRecord.count({where:{employeeId}}),2)});
test("السلفة تنقص البنك وتظهر كأصل على الموظف",async()=>{const before=Number((await prisma.bankAccount.findUniqueOrThrow({where:{id:bankId}})).currentBalance),advance=await prisma.$transaction(tx=>createAdvance(tx,{employeeId,bankAccountId:bankId,advanceDate:"2026-09-01",amount:500}));assert.equal(Number(advance.remainingAmount),500);assert.equal(Number((await prisma.bankAccount.findUniqueOrThrow({where:{id:bankId}})).currentBalance),before-500);const journal=await prisma.journalEntry.findFirstOrThrow({where:{referenceType:"EMPLOYEE_ADVANCE",referenceId:advance.id}});assert.equal(Number(journal.totalDebit),500)});
test("المسير يربط الغياب والإضافي والسلفة ويحفظ صافي الراتب",async()=>{const run=await prisma.$transaction(tx=>createPayrollRun(tx,{year:2026,month:9})),line=run.lines[0];assert.equal(Number(line.overtimeValue),150);assert.equal(Number(line.absenceDeduction),100);assert.equal(Number(line.advances),500);assert.equal(Number(line.grossSalary),3650);assert.equal(Number(line.netSalary),3050);runId=run.id;lineId=line.id});
test("ترحيل المسير ينشئ قيدًا متوازنًا ويسترد السلفة",async()=>{const posted=await prisma.$transaction(tx=>postPayrollRun(tx,runId));assert.equal(posted.status,"POSTED");assert.equal(Number(posted.journalEntry.totalDebit),Number(posted.journalEntry.totalCredit));const advance=await prisma.employeeAdvance.findFirstOrThrow({where:{employeeId}});assert.equal(Number(advance.remainingAmount),0);assert.equal(advance.status,"RECOVERED")});
test("دفع الراتب يخفض البنك ويغلق حالة بند الراتب",async()=>{const before=Number((await prisma.bankAccount.findUniqueOrThrow({where:{id:bankId}})).currentBalance);await prisma.$transaction(tx=>payPayrollLine(tx,{payrollLineId:lineId,bankAccountId:bankId,paymentDate:"2026-09-30"}));const line=await prisma.payrollLine.findUniqueOrThrow({where:{id:lineId}});assert.equal(line.paymentStatus,"PAID");assert.equal(Number((await prisma.bankAccount.findUniqueOrThrow({where:{id:bankId}})).currentBalance),before-3050)});
test("تكلفة العامل الخارجي تبقى خارج Payroll وتذهب لمركز التكلفة",async()=>{const cost=await prisma.$transaction(tx=>createExternalWorkerCost(tx,{externalWorkerId:workerId,bankAccountId:bankId,costDate:"2026-09-20",amount:200,costCenter:"FACTORY"}));const expense=await prisma.expense.findUniqueOrThrow({where:{id:cost.expenseId}});assert.equal(expense.costCenter,"FACTORY");assert.equal(await prisma.payrollLine.count({where:{employeeId}}),1)});
