import assert from "node:assert/strict";
import { after, before, test } from "node:test";
import { copyFileSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { PrismaClient } from "@prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import { createCompany, PlatformError } from "../lib/platform.ts";
import { assertFeatureLimit, assertTenantLimit, changeSubscription, onboardingWorkspace, platformWorkspace, saveOnboardingStep, savePlan, saveSupportGrant } from "../lib/saas.ts";
import { scopedModels } from "../lib/data-scope.ts";
import { initializeCompanyDesign } from "../lib/design.ts";

const directory = mkdtempSync(join(tmpdir(), "netaj-saas-test-")), database = join(directory, "saas.db"); copyFileSync("prisma/netaj.db", database);
const prisma = new PrismaClient({ adapter: new PrismaBetterSqlite3({ url: `file:${database}` }) }), suffix = Date.now().toString(36).toUpperCase();
let enterprise, limited, admin, newCompany;
before(async()=>{admin=await prisma.platformAdministrator.findFirst();if(!admin){const user=await prisma.platformUser.findFirstOrThrow();admin=await prisma.platformAdministrator.create({data:{userId:user.id,role:"PLATFORM_OWNER"}})}enterprise=await prisma.$transaction(tx=>savePlan(tx,{code:`ENT_${suffix}`,name:"Enterprise Test",moduleKeys:([]),featureLimits:{CUSTOM_DASHBOARDS_MAX:-1},monthlyPrice:100,annualPrice:1000},"test"));limited=await prisma.$transaction(tx=>savePlan(tx,{code:`LIMIT_${suffix}`,name:"Limited Test",userLimit:1,companyLimit:1,storageMb:1,moduleKeys:[],featureLimits:{CUSTOM_DASHBOARDS_MAX:1,CUSTOM_REPORTS_MAX:1}},"test"))});
after(async()=>{await prisma.$disconnect();rmSync(directory,{recursive:true,force:true})});

test("الخطة تحفظ الأسعار والدورات والحدود كـEntitlements مستقلة عن الصلاحيات",async()=>{const rows=await prisma.planEntitlement.findMany({where:{planId:limited.id}});assert.equal(Number(limited.monthlyPrice),0);assert.equal(rows.find(x=>x.entitlementKey==="USERS_MAX").value,"1");assert.equal(rows.find(x=>x.entitlementKey==="COMPANIES_MAX").value,"1")});
test("تغيير الخطة الفوري ثم التخفيض المجدول يحفظ فترة الاشتراك",async()=>{const immediate=await prisma.$transaction(tx=>changeSubscription(tx,{tenantId:1,planId:enterprise.id,billingPeriod:"ANNUAL",effective:"IMMEDIATE"},"test"));assert.equal(immediate.billingPeriod,"ANNUAL");assert.ok(immediate.currentPeriodEnd>immediate.currentPeriodStart);const scheduled=await prisma.$transaction(tx=>changeSubscription(tx,{tenantId:1,planId:limited.id,billingPeriod:"MONTHLY",effective:"PERIOD_END"},"test"));assert.equal(scheduled.pendingPlanId,limited.id);assert.ok(scheduled.changeEffectiveAt)});
test("حدود المستخدمين والشركات والتخزين تمنع التجاوز الحقيقي",async()=>{await prisma.$transaction(tx=>changeSubscription(tx,{tenantId:1,planId:limited.id,effective:"IMMEDIATE"},"test"));await assert.rejects(prisma.$transaction(tx=>assertTenantLimit(tx,1,"USERS")),e=>e instanceof PlatformError&&e.code==="USER_LIMIT_REACHED");await assert.rejects(prisma.$transaction(tx=>assertTenantLimit(tx,1,"COMPANIES")),e=>e instanceof PlatformError&&e.code==="COMPANY_LIMIT_REACHED");await prisma.attachment.create({data:{entityType:"TEST",entityId:1,originalName:"one.bin",storedName:`${suffix}.bin`,storagePath:"test",mimeType:"application/octet-stream",size:1024*1024,uploadedBy:"test"}});await assert.rejects(prisma.$transaction(tx=>assertTenantLimit(tx,1,"STORAGE",1)),e=>e instanceof PlatformError&&e.code==="STORAGE_LIMIT_REACHED");await assert.rejects(prisma.$transaction(tx=>assertFeatureLimit(tx,1,1,"CUSTOM_DASHBOARDS_MAX",1)),e=>e instanceof PlatformError&&e.code==="FEATURE_LIMIT_REACHED")});
test("إنشاء شركة ضمن خطة مفتوحة يجهز onboarding والهوية والقوالب دون بيانات تجريبية",async()=>{await prisma.$transaction(tx=>changeSubscription(tx,{tenantId:1,planId:enterprise.id,effective:"IMMEDIATE"},"test"));newCompany=await prisma.$transaction(tx=>createCompany(tx,1,{code:`CO${suffix}`,legalNameAr:"شركة تهيئة",countryCode:"SA",baseCurrencyCode:"SAR",defaultLanguageCode:"ar",timeZoneName:"Asia/Riyadh"}));await prisma.$transaction(tx=>initializeCompanyDesign(tx,1,newCompany.id));const workspace=await prisma.$transaction(tx=>onboardingWorkspace(tx,1,newCompany.id));assert.equal(workspace.session.status,"IN_PROGRESS");assert.equal(await prisma.documentTemplate.count({where:{companyId:newCompany.id}}),13);assert.ok(await prisma.companyThemeProfile.findUnique({where:{companyId:newCompany.id}}));assert.equal(await prisma.party.count({where:{companyId:newCompany.id}}),0)});
test("معالج التهيئة يحفظ القطاع والوحدات والضرائب ويكمل دون reset",async()=>{await prisma.$transaction(tx=>saveOnboardingStep(tx,1,newCompany.id,admin.userId,{step:"INDUSTRY",data:{templateCode:"TRADING"}}));await prisma.$transaction(tx=>saveOnboardingStep(tx,1,newCompany.id,admin.userId,{step:"MODULES",data:{moduleKeys:["CORE"]}}));const done=await prisma.$transaction(tx=>saveOnboardingStep(tx,1,newCompany.id,admin.userId,{step:"COMPLETE",data:{confirmed:true}}));assert.equal(done.status,"COMPLETED");const core=await prisma.companyModule.findUnique({where:{companyId_moduleKey:{companyId:newCompany.id,moduleKey:"CORE"}}});assert.equal(core.enabled,true)});
test("Super Admin يرى صحة المنصة لا محتوى أعمال المستأجر، والدعم يتطلب تفويضًا منتهيًا",async()=>{const workspace=await prisma.$transaction(tx=>platformWorkspace(tx));assert.ok(workspace.health.tenants>=1);assert.equal("parties" in workspace,false);const grant=await prisma.$transaction(tx=>saveSupportGrant(tx,admin.id,{tenantId:1,companyId:1,reason:"تشخيص عطل",approvedBy:"مالك نتاج",expiresAt:new Date(Date.now()+3600000).toISOString(),scopes:["DIAGNOSTICS"]},String(admin.userId)));assert.equal(grant.tenantId,1);assert.ok(grant.expiresAt>new Date())});
test("نماذج onboarding التشغيلية معزولة بينما إدارة المنصة تبقى خارج محتوى الشركات",()=>{assert.ok(scopedModels.has("OnboardingSession"));assert.ok(scopedModels.has("UserInvitation"));assert.equal(scopedModels.has("PlatformAdministrator"),false);assert.equal(scopedModels.has("SupportAccessGrant"),false)});
