import {cookies} from "next/headers";
import {notFound,redirect} from "next/navigation";
import NetajPrintHeader from "@/app/components/NetajPrintHeader";
import PrintButton from "@/app/notes/[id]/print/PrintButton";
import {SESSION_COOKIE,requireAuthorization} from "@/lib/auth";
import {runWithDataScope} from "@/lib/data-scope";
import {prisma} from "@/lib/prisma";

const num=(value:unknown)=>Number(value??0).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2});

export default async function TransportReceiptPrint({params}:{params:Promise<{id:string}>}){
  const id=Number((await params).id);if(!Number.isInteger(id))notFound();
  const token=(await cookies()).get(SESSION_COOKIE)?.value??null;let auth;
  try{auth=await prisma.$transaction(tx=>requireAuthorization(tx,token,{moduleKey:"TRANSPORT",action:"READ"}))}catch{redirect("/login")}
  const[receipt,company]=await runWithDataScope({tenantId:auth.tenantId,companyId:auth.companyId},()=>Promise.all([
    prisma.transportReceipt.findUnique({where:{id},include:{trip:{include:{party:true,item:{include:{unit:true}},note:true}},truck:true,driver:true}}),
    prisma.company.findUnique({where:{id:auth.companyId},include:{branches:{where:{isMain:true},take:1}}}),
  ]));if(!receipt||!company)notFound();
  return <main dir="rtl" className="netaj-note-print mx-auto min-h-[297mm] max-w-[210mm] bg-white p-[8mm] text-slate-950"><div className="mb-4 flex justify-between print:hidden"><a href="/transport" className="text-amber-800">العودة للنقليات</a><div className="flex gap-2"><a href={`/api/transport/receipts/${receipt.id}/export?format=pdf`} className="rounded-lg border px-3 py-2">PDF</a><a href={`/api/transport/receipts/${receipt.id}/export?format=xlsx`} className="rounded-lg border px-3 py-2">Excel</a><PrintButton/></div></div><NetajPrintHeader company={company} titleAr="إيصال نقليات" titleEn="Transportation Receipt"/><section className="netaj-note-meta"><span>Shipping date: {receipt.receiptDate.toLocaleDateString("en-US")}</span><strong>({receipt.receiptNumber})</strong><span>تاريخ الشحن: {receipt.receiptDate.toLocaleDateString("en-US")}</span></section>
    <p className="netaj-note-intro">نرجو استلام الشحنة حسب البيانات التالية:</p><Title en="Sender Information" ar="معلومات المرسل"/><table className="netaj-reference-table"><thead><tr>{[["Sender Name","اسم المرسل"],["Shipping Location","موقع الشحن"],["Responsible person","اسم الشخص المسؤول"],["Mobile No","رقم الهاتف"]].map(([en,ar])=><th key={en}>{en}<small>{ar}</small></th>)}</tr></thead><tbody><tr><td>{company.legalNameAr}</td><td>{receipt.source??""}</td><td></td><td></td></tr></tbody></table>
    <Title en="Transporter Information" ar="معلومات الناقل"/><table className="netaj-reference-table"><thead><tr>{[["Transporter Name","اسم الناقل"],["Document No","رقم الوثيقة"],["Car Number","رقم السيارة"],["Driver Name","اسم السائق"],["ID Number","رقم الهوية"],["Mobile No","رقم الهاتف"]].map(([en,ar])=><th key={en}>{en}<small>{ar}</small></th>)}</tr></thead><tbody><tr><td>{company.legalNameAr}</td><td>{receipt.trip.note?.noteNumber??receipt.referenceNumber??""}</td><td>{receipt.truck?.plateNumber??""}</td><td>{receipt.driver?.name??""}</td><td>{receipt.driver?.idNumber??""}</td><td>{receipt.driver?.phone??""}</td></tr></tbody></table>
    <Title en="The following materials are listed in the table below" ar="المواد التالية حسب الجدول أدناه"/><table className="netaj-reference-table netaj-material-table"><thead><tr>{[["S. No.","م"],["Kinds Of Goods","نوع الحمل"],["Description","الوصف"],["Customer Order No","رقم طلب العميل"],["Unit","الوحدة"],["Quantity","الكمية"]].map(([en,ar])=><th key={en}>{en}<small>{ar}</small></th>)}</tr></thead><tbody><tr><td>1</td><td>{receipt.trip.item?.code??""}</td><td>{receipt.material??receipt.trip.item?.nameAr??""}</td><td>{receipt.referenceNumber??""}</td><td>{receipt.trip.item?.unit?.nameAr??""}</td><td>{num(receipt.quantity)}</td></tr>{Array.from({length:3},(_,index)=><tr key={index}><td/><td/><td/><td/><td/><td/></tr>)}</tbody></table>
    <section className="mt-4 grid grid-cols-3 border border-amber-300 text-center text-xs"><p className="p-3">السعر / Rate<br/><strong>{num(receipt.rate)}</strong></p><p className="border-x border-amber-300 p-3">VAT<br/><strong>{num(receipt.vatAmount)}</strong></p><p className="p-3">الإجمالي / Total<br/><strong>{num(receipt.totalAmount)} SAR</strong></p></section><Title en="Receiver's Information" ar="معلومات المستلم"/><table className="netaj-reference-table"><thead><tr>{[["Receiver's company Name","اسم شركة المستلم"],["Delivery location","موقع التسليم"],["Location Type","نوع الموقع"],["Mobile No","رقم الهاتف"]].map(([en,ar])=><th key={en}>{en}<small>{ar}</small></th>)}</tr></thead><tbody><tr><td>{receipt.trip.party?.nameAr??""}</td><td>{receipt.destination??""}</td><td></td><td>{receipt.trip.party?.telephone??""}</td></tr></tbody></table><p className="netaj-transport-confirm">I received the full quantity according to the above information: <span>استلمت الكمية كاملة حسب البيانات أعلاه</span></p><table className="netaj-reference-table"><thead><tr>{[["Receiver's Name","اسم المستلم"],["ID Number","رقم الهوية"],["Delivery date","تاريخ الاستلام"],["Signature","التوقيع"],["Seal","الختم"]].map(([en,ar])=><th key={en}>{en}<small>{ar}</small></th>)}</tr></thead><tbody><tr><td/><td/><td/><td/><td/></tr></tbody></table><div className="netaj-reference-wave"/></main>
}
function Title({en,ar}:{en:string;ar:string}){return <div className="netaj-bilingual-title"><span dir="ltr">{en} :</span><span>{ar} :</span></div>}
