import {cookies} from "next/headers";
import {notFound,redirect} from "next/navigation";
import NetajPrintHeader from "@/app/components/NetajPrintHeader";
import PrintButton from "@/app/notes/[id]/print/PrintButton";
import {SESSION_COOKIE,requireAuthorization} from "@/lib/auth";
import {runWithDataScope} from "@/lib/data-scope";
import {prisma} from "@/lib/prisma";

export default async function TripPrintPage({params}:{params:Promise<{id:string}>}){
  const id=Number((await params).id);if(!Number.isInteger(id))notFound();const token=(await cookies()).get(SESSION_COOKIE)?.value??null;let auth;
  try{auth=await prisma.$transaction(tx=>requireAuthorization(tx,token,{moduleKey:"TRANSPORT",action:"READ"}))}catch{redirect("/login")}
  const[trip,company]=await runWithDataScope({tenantId:auth.tenantId,companyId:auth.companyId},()=>Promise.all([
    prisma.transportTrip.findUnique({where:{id},include:{party:true,item:{include:{unit:true}},truck:true,driver:true,note:{include:{items:{include:{item:{include:{unit:true}}}}}}}}),
    prisma.company.findUnique({where:{id:auth.companyId},include:{branches:{where:{isMain:true},take:1}}}),
  ]));if(!trip||!company)notFound();const items=trip.note?.items??[];
  return <main dir="rtl" className="netaj-note-print mx-auto min-h-[297mm] max-w-[210mm] bg-white p-[8mm] text-slate-950"><div className="mb-4 flex justify-between print:hidden"><a href="/transport" className="text-amber-800">العودة للنقليات</a><PrintButton/></div><NetajPrintHeader company={company} titleAr="إيصال نقليات" titleEn="Transportation Receipt"/><section className="netaj-note-meta"><span>Shipping date: ........................</span><strong>({trip.tripNumber})</strong><span>تاريخ الشحن: {trip.tripDate.toLocaleDateString("en-US")}</span></section>
    <p className="netaj-note-intro">نرجو استلام الشحنة حسب البيانات التالية:</p><TransportTitle en="Sender Information" ar="معلومات المرسل"/><table className="netaj-reference-table"><thead><tr>{[["Sender Name","اسم المرسل"],["Shipping Location","موقع الشحن"],["Name of responsible person","اسم الشخص المسؤول"],["Mobile No","رقم الهاتف"]].map(([en,ar])=><th key={en}>{en}<small>{ar}</small></th>)}</tr></thead><tbody><tr><td>{company.legalNameAr}</td><td>{trip.loadingPoint??trip.source??""}</td><td></td><td></td></tr></tbody></table>
    <TransportTitle en="Transporter Information" ar="معلومات الناقل"/><table className="netaj-reference-table"><thead><tr>{[["Transporter Name","اسم الناقل"],["Document No","رقم الوثيقة"],["Car Number","رقم السيارة"],["Driver Name","اسم السائق"],["ID Number","رقم الهوية"],["Mobile No","رقم الهاتف"]].map(([en,ar])=><th key={en}>{en}<small>{ar}</small></th>)}</tr></thead><tbody><tr><td>{company.legalNameAr}</td><td>{trip.note?.noteNumber??""}</td><td>{trip.truck?.plateNumber??""}</td><td>{trip.driver?.name??""}</td><td>{trip.driver?.idNumber??""}</td><td>{trip.driver?.phone??""}</td></tr></tbody></table>
    <TransportTitle en="The following materials are listed in the table below" ar="المواد التالية حسب الجدول أدناه"/><table className="netaj-reference-table netaj-material-table"><thead><tr>{[["S. No.","م"],["Kinds Of Goods","نوع الحمل"],["Description","الوصف"],["Customer Order No","رقم طلب العميل"],["Unit","الوحدة"],["Quantity","الكمية"]].map(([en,ar])=><th key={en}>{en}<small>{ar}</small></th>)}</tr></thead><tbody>{(items.length?items:[{id:0,item:trip.item,description:trip.item?.nameAr,orderNumber:null,quantity:trip.quantity}]).map((row,index)=><tr key={row.id}><td>{index+1}</td><td>{row.item?.code??""}</td><td>{row.description??row.item?.nameAr??""}</td><td>{row.orderNumber??""}</td><td>{row.item?.unit?.nameAr??""}</td><td>{Number(row.quantity).toLocaleString("en-US")}</td></tr>)}{Array.from({length:3},(_,index)=><tr key={index}><td/><td/><td/><td/><td/><td/></tr>)}</tbody></table>
    <TransportTitle en="Receiver's Information" ar="معلومات المستلم"/><table className="netaj-reference-table"><thead><tr>{[["Receiver's company Name","اسم شركة المستلم"],["Delivery location","موقع التسليم"],["Location Type","نوع الموقع"],["Mobile No","رقم الهاتف"]].map(([en,ar])=><th key={en}>{en}<small>{ar}</small></th>)}</tr></thead><tbody><tr><td>{trip.party?.nameAr??""}</td><td>{trip.unloadingPoint??""}</td><td></td><td>{trip.party?.telephone??""}</td></tr></tbody></table><p className="netaj-transport-confirm">I received the full quantity according to the above information: <span>استلمت الكمية كاملة حسب البيانات أعلاه</span></p><table className="netaj-reference-table"><thead><tr>{[["Receiver's Name","اسم المستلم"],["ID Number","رقم الهوية"],["Delivery date","تاريخ الاستلام"],["Signature","التوقيع"],["Seal","الختم"]].map(([en,ar])=><th key={en}>{en}<small>{ar}</small></th>)}</tr></thead><tbody><tr><td/><td/><td/><td/><td/></tr></tbody></table><div className="netaj-reference-wave"/></main>
}
function TransportTitle({en,ar}:{en:string;ar:string}){return <div className="netaj-bilingual-title"><span dir="ltr">{en} :</span><span>{ar} :</span></div>}
