"use client";
import { FormEvent, ReactNode, useEffect, useState } from "react";
type Row = Record<string, unknown>;
const money = (value: unknown) => Number(value ?? 0).toLocaleString("ar-SA", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export default function ProjectsClient() {
  const [data, setData] = useState<Row | null>(null), [selected, setSelected] = useState<number | null>(null), [detail, setDetail] = useState<Row | null>(null), [message, setMessage] = useState("");
  const load = async () => { const response = await fetch("/api/projects"), body = await response.json(); if (response.ok) setData(body); };
  const open = async (id: number) => { setSelected(id); const response = await fetch(`/api/projects/${id}`), body = await response.json(); if (response.ok) setDetail(body); };
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await fetch("/api/projects", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }), body = await response.json(); setMessage(response.ok ? "تم إنشاء المشروع" : body.error); if (response.ok) { event.currentTarget.reset(); await load(); await open(body.id); } }
  async function action(event: FormEvent<HTMLFormElement>, name: string) { event.preventDefault(); if (!selected) return; const values = Object.fromEntries(new FormData(event.currentTarget)), body: Row = { ...values, action: name }; if (name === "certificate") body.lines = [{ boqItemId: values.boqItemId, currentQuantity: values.currentQuantity }]; const response = await fetch(`/api/projects/${selected}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }), result = await response.json(); setMessage(response.ok ? "تم حفظ العملية" : result.error); if (response.ok) { event.currentTarget.reset(); await open(selected); await load(); } }
  async function postCertificate(certificateId: unknown, actionName: string) { if (!selected) return; const response = await fetch(`/api/projects/${selected}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: actionName, certificateId }) }), result = await response.json(); setMessage(response.ok ? "تم الترحيل إلى المحاسبة" : result.error); if (response.ok) await open(selected); }
  const projects = (data?.projects ?? []) as Row[], parties = (data?.parties ?? []) as Row[], items = (data?.items ?? []) as Row[], centers = (data?.costCenters ?? []) as Row[], codes = (data?.costCodes ?? []) as Row[];
  const project = (detail?.project ?? {}) as Row, kpis = (detail?.kpis ?? {}) as Row, boq = (project.boqItems ?? []) as Row[], certificates = (project.certificates ?? []) as Row[], subcontractors = (project.subcontractors ?? []) as Row[];
  return <section className="mx-auto max-w-7xl space-y-6 p-6">
    {message && <div className="rounded-xl bg-blue-50 p-3 text-blue-800">{message}</div>}
    <div className="grid gap-5 lg:grid-cols-[2fr_1fr]">
      <div className="rounded-2xl border bg-white p-5"><h2 className="mb-4 font-bold">محفظة المشاريع</h2><div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="bg-slate-100"><th className="p-2">المشروع</th><th>العميل</th><th>التقدم</th><th>الفعلي</th><th>الربح المتوقع</th></tr></thead><tbody>{projects.map(row => <tr key={String(row.id)} onClick={() => void open(Number(row.id))} className="cursor-pointer border-t hover:bg-blue-50"><td className="p-2 font-semibold">{String(row.projectNumber)} - {String(row.name)}</td><td>{String(row.customer)}</td><td>{money(row.progressPercent)}%</td><td>{money(row.actual)}</td><td className={Number(row.estimatedFinalProfit) < 0 ? "text-red-700" : "text-emerald-700"}>{money(row.estimatedFinalProfit)}</td></tr>)}</tbody></table></div></div>
      <form onSubmit={create} className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="font-bold">مشروع جديد</h2><Input name="name" label="اسم المشروع"/><Select name="partyId" label="العميل" rows={parties.filter(row => row.isCustomer)} text="nameAr"/><Select name="costCenterId" label="مركز التكلفة" rows={centers} text="nameAr"/><Select name="billingItemId" label="مادة الفوترة" rows={items} text="nameAr" optional/><Input name="startDate" label="تاريخ البداية" type="date"/><Input name="contractValue" label="قيمة العقد" type="number"/><Input name="retentionPercent" label="الاستقطاع %" type="number"/><button className="w-full rounded bg-slate-900 p-2 text-white">إنشاء</button></form>
    </div>
    {selected && <>
      <div className="grid gap-3 md:grid-cols-4">{[["الميزانية", kpis.budget], ["الفعلي", kpis.actual], ["الملتزم", kpis.committed], ["التوقع", kpis.forecast], ["تكلفة الإكمال", kpis.costToComplete], ["التكلفة النهائية", kpis.estimatedFinalCost], ["الربح المتوقع", kpis.estimatedFinalProfit], ["صافي التدفق", kpis.netCashFlow]].map(([label, value]) => <div key={String(label)} className="rounded-xl border bg-white p-4"><div className="text-xs text-slate-500">{String(label)}</div><div className="mt-1 font-bold">{money(value)}</div></div>)}</div>
      <div className="grid gap-4 lg:grid-cols-3">
        <Mini title="عقد المشروع" action="contract" submit={action}><Input name="contractDate" label="تاريخ العقد" type="date"/><Input name="startDate" label="البداية" type="date"/><Input name="contractValue" label="القيمة" type="number"/><Input name="advanceAmount" label="الدفعة المقدمة" type="number" optional/><Input name="retentionPercent" label="الاستقطاع %" type="number" optional/></Mini>
        <Mini title="بند BOQ" action="boq" submit={action}><Input name="boqCode" label="رمز البند"/><Input name="description" label="الوصف"/><Input name="unit" label="الوحدة"/><Input name="quantity" label="الكمية" type="number"/><Input name="rate" label="السعر" type="number"/><CodeSelect codes={codes}/><Select name="itemId" label="المادة" rows={items} text="nameAr" optional/></Mini>
        <Mini title="ميزانية تكلفة" action="budget" submit={action}><CodeSelect codes={codes}/><Input name="budgetAmount" label="الميزانية" type="number"/><Input name="forecastAmount" label="التوقع" type="number" optional/></Mini>
        <Mini title="تقدم فعلي" action="progress" submit={action}><Input name="progressDate" label="التاريخ" type="date"/><Select name="boqItemId" label="بند BOQ" rows={boq} text="description" optional/><Input name="quantity" label="الكمية" type="number" optional/><Input name="value" label="القيمة" type="number" optional/></Mini>
        <Mini title="مستخلص عميل" action="certificate" submit={action}><Input name="certificateDate" label="التاريخ" type="date"/><Select name="boqItemId" label="بند BOQ" rows={boq} text="description"/><Input name="currentQuantity" label="كمية الفترة" type="number"/><Input name="advanceRecoveryAmount" label="استرداد الدفعة" type="number" optional/></Mini>
        <Mini title="عقد مقاول باطن" action="subcontract" submit={action}><Select name="partyId" label="المقاول" rows={parties.filter(row => row.isSupplier)} text="nameAr"/><CodeSelect codes={codes}/><Select name="billingItemId" label="مادة الفوترة" rows={items} text="nameAr"/><Input name="contractDate" label="تاريخ العقد" type="date"/><Input name="startDate" label="البداية" type="date"/><Input name="contractValue" label="القيمة" type="number"/><Input name="retentionPercent" label="الاستقطاع %" type="number" optional/></Mini>
        <Mini title="مستخلص مقاول باطن" action="subcontract-certificate" submit={action}><Select name="subcontractContractId" label="عقد المقاول" rows={subcontractors} text="contractNumber"/><Input name="certificateDate" label="التاريخ" type="date"/><Input name="currentValue" label="قيمة الفترة" type="number"/><Input name="advanceRecoveryAmount" label="استرداد الدفعة" type="number" optional/></Mini>
        <LinkForm project={project} codes={codes} selected={selected} done={async text => { setMessage(text); await open(selected); }}/>
      </div>
      <div className="grid gap-4 lg:grid-cols-2"><ActionTable title="المستخلصات" rows={certificates} columns={["certificateNumber", "currentValue", "retentionAmount", "advanceRecoveryAmount", "netAmount", "status"]} onPost={id=>postCertificate(id,"post-certificate")}/><DataTable title="المقاولون الباطنون" rows={subcontractors} columns={["contractNumber", "contractValue", "retentionPercent", "status"]}/></div>
      <ActionTable title="مستخلصات المقاولين" rows={subcontractors.flatMap(row => (row.certificates as Row[] ?? []))} columns={["certificateNumber", "currentValue", "retentionAmount", "advanceRecoveryAmount", "netAmount", "status"]} onPost={id=>postCertificate(id,"post-subcontract-certificate")}/>
      <DataTable title="التكلفة حسب الكود" rows={(detail?.byCode ?? []) as Row[]} columns={["code", "name", "budget", "forecast", "actual", "variance"]}/>
    </>}
  </section>;
}

function Mini({ title, action, submit, children }: { title: string; action: string; submit: (event: FormEvent<HTMLFormElement>, name: string) => void; children: ReactNode }) { return <form onSubmit={event => submit(event, action)} className="space-y-2 rounded-xl border bg-white p-4"><h3 className="font-bold">{title}</h3>{children}<button className="rounded bg-blue-700 px-4 py-2 text-white">حفظ</button></form>; }
function Input({ name, label, type = "text", optional = false }: { name: string; label: string; type?: string; optional?: boolean }) { return <input name={name} type={type} step={type === "number" ? ".01" : undefined} placeholder={label} required={!optional} className="w-full rounded border p-2"/>; }
function Select({ name, label, rows, text, optional = false }: { name: string; label: string; rows: Row[]; text: string; optional?: boolean }) { return <select name={name} required={!optional} className="w-full rounded border p-2"><option value="">{label}</option>{rows.map(row => <option key={String(row.id)} value={String(row.id)}>{String(row[text])}</option>)}</select>; }
function CodeSelect({ codes }: { codes: Row[] }) { return <Select name="costCodeId" label="كود التكلفة" rows={codes} text="nameAr"/>; }
function DataTable({ title, rows, columns }: { title: string; rows: Row[]; columns: string[] }) { return <div className="overflow-auto rounded-2xl border bg-white p-5"><h3 className="mb-3 font-bold">{title}</h3><table className="w-full text-sm"><thead><tr>{columns.map(column => <th key={column} className="p-2">{column}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={String(row.id ?? index)} className="border-t text-center">{columns.map(column => <td key={column} className="p-2">{typeof row[column] === "number" ? money(row[column]) : String(row[column] ?? "")}</td>)}</tr>)}</tbody></table></div>; }
function ActionTable({ title, rows, columns, onPost }: { title: string; rows: Row[]; columns: string[]; onPost: (id: unknown) => void }) { return <div className="overflow-auto rounded-2xl border bg-white p-5"><h3 className="mb-3 font-bold">{title}</h3><table className="w-full text-sm"><thead><tr>{columns.map(column => <th key={column}>{column}</th>)}<th>الإجراء</th></tr></thead><tbody>{rows.map(row => <tr key={String(row.id)} className="border-t text-center">{columns.map(column => <td key={column} className="p-2">{String(row[column] ?? "")}</td>)}<td>{row.status !== "POSTED" && <button onClick={() => void onPost(row.id)} className="rounded bg-emerald-700 px-3 py-1 text-white">ترحيل</button>}</td></tr>)}</tbody></table></div>; }
function LinkForm({ project, codes, selected, done }: { project: Row; codes: Row[]; selected: number; done: (message: string) => Promise<void> }) { async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const body = { ...Object.fromEntries(new FormData(event.currentTarget)), projectId: selected, costCenterId: project.costCenterId }, response = await fetch("/api/projects/links", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }), result = await response.json(); await done(response.ok ? "تم الربط دون إدخال مكرر" : result.error); } return <form onSubmit={submit} className="space-y-2 rounded-xl border bg-white p-4"><h3 className="font-bold">ربط تكلفة موجودة</h3><select name="entityType" className="w-full rounded border p-2"><option value="PURCHASE">فاتورة شراء</option><option value="EXPENSE">مصروف</option><option value="STOCK_MOVEMENT">حركة مخزون</option><option value="TRANSPORT_TRIP">رحلة</option><option value="PAYROLL_LINE">راتب</option><option value="BUSINESS_DOCUMENT">أمر شراء</option></select><Input name="entityId" label="ID السجل" type="number"/><CodeSelect codes={codes}/><button className="rounded bg-blue-700 px-4 py-2 text-white">ربط</button></form>; }
