"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowUpLeft, BadgeDollarSign, Boxes, Building2, CircleDollarSign, ClipboardPlus, Factory, FileChartColumn, Landmark, ReceiptText, ShoppingBag, ShoppingCart, Truck, Users, WalletCards } from "lucide-react";

type Row=Record<string,unknown>;
type DashboardData={range:{from:string;to:string};kpis:Row;factory:Row|null;transport:Row|null;monthly:Row[];materials:Row[];customerActivity:Row[];alerts:Row};
const money=(value:unknown)=>`${Number(value??0).toLocaleString("ar-SA",{minimumFractionDigits:2,maximumFractionDigits:2})} ر.س`;
const number=(value:unknown)=>Number(value??0).toLocaleString("ar-SA",{maximumFractionDigits:2});
const monthEnd=(month:unknown)=>{const value=String(month),[year,index]=value.split("-").map(Number);return `${value}-${String(new Date(Date.UTC(year,index,0)).getUTCDate()).padStart(2,"0")}`};
const today=new Date(),initialFrom=`${today.getFullYear()}-01-01`,initialTo=today.toISOString().slice(0,10);

export default function DashboardClient({enabledModules,companyName}:{enabledModules:string[];companyName:string}){
  const[filters,setFilters]=useState({from:initialFrom,to:initialTo,inactiveDays:"60"}),[data,setData]=useState<DashboardData|null>(null),[message,setMessage]=useState("");
  const[selectedMaterials,setSelectedMaterials]=useState<[string,string]>(["",""]);
  useEffect(()=>{const controller=new AbortController(),params=new URLSearchParams(filters);fetch(`/api/analytics?${params}`,{cache:"no-store",signal:controller.signal}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setMessage("");setData(body)}).catch(error=>{if(error.name!=="AbortError")setMessage(error.message)});return()=>controller.abort()},[filters]);
  const enabled=new Set(enabledModules),effectiveMaterials:[string,string]=selectedMaterials[0]?selectedMaterials:[String(data?.materials[0]?.itemId??""),String(data?.materials[1]?.itemId??data?.materials[0]?.itemId??"")],materialCards=effectiveMaterials.map(id=>data?.materials.find(row=>String(row.itemId)===id)).filter(Boolean)as Row[];
  const maxMonthly=useMemo(()=>Math.max(1,...(data?.monthly??[]).map(row=>Math.abs(Number(row.netProfit??0)))),[data]);
  const quickActions=[
    ["إضافة عميل","/parties?new=1","CORE",Users],["إصدار عرض سعر","/sales?type=QUOTATION&new=1","SALES",ClipboardPlus],["Proforma Invoice","/sales?type=PROFORMA_INVOICE&new=1","SALES",ReceiptText],["فاتورة مبيعات","/sales?type=SALES_INVOICE&new=1","SALES",BadgeDollarSign],["طلب شراء","/purchases?type=PURCHASE_REQUISITION&new=1","PURCHASES",ShoppingBag],["سند قبض","/accounting?tab=vouchers&type=RECEIPT","ACCOUNTING",WalletCards],["سند صرف","/accounting?tab=vouchers&type=PAYMENT","ACCOUNTING",CircleDollarSign],["ملاحظة تشغيل","/notes?new=1","NOTES",ClipboardPlus],["رحلة نقل","/transport?new=1","TRANSPORT",Truck],["تقرير مالي","/accounting?tab=reports","ACCOUNTING",FileChartColumn],
  ] as const;
  return <main className="premium-dashboard mx-auto max-w-[1720px] space-y-6 p-4 md:p-7 lg:p-9">
    <section className="premium-hero relative isolate min-h-64 overflow-hidden rounded-[28px] border">
      <Image src="/media/netaj-industrial-hero.png" alt="منشأة صناعية ولوجستية متكاملة" fill priority sizes="(max-width: 1024px) 100vw, 80vw" className="object-cover"/>
      <div className="absolute inset-0 bg-gradient-to-l from-[#111c2e]/90 via-[#172235]/67 to-[#172235]/15"/>
      <div className="relative z-10 flex min-h-64 max-w-3xl flex-col justify-center p-7 text-white md:p-10"><span className="mb-4 w-fit rounded-full border border-amber-200/30 bg-amber-200/10 px-4 py-1.5 text-xs font-bold text-amber-100 backdrop-blur">NETAj · ENTER ONCE → EVERYTHING UPDATES</span><h1 className="text-3xl font-black leading-tight md:text-5xl">قيادة أعمالك من صورة واحدة واضحة</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-200 md:text-base">{companyName} — المالية والتشغيل والمصنع والنقل والمشاريع مترابطة لحظيًا من مصدر بيانات واحد.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/reports" className="rounded-xl bg-[var(--brand-accent)] px-5 py-3 font-bold text-[#172235] shadow-lg">استكشف التحليلات</Link><Link href="/search" className="rounded-xl border border-white/30 bg-white/10 px-5 py-3 font-bold backdrop-blur">البحث الشامل</Link></div></div>
    </section>

    <section aria-label="الإجراءات السريعة" className="premium-panel rounded-2xl border p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-black">إجراءات سريعة</h2><p className="text-sm text-slate-500">أهم العمليات في ضغطة أو ضغطتين.</p></div><span className="premium-eyebrow">ENTER ONCE</span></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-5">{quickActions.filter(([, ,module])=>enabled.has(module)).map(([label,href,,Icon])=><Link key={label} href={href} className="premium-quick-action"><span><Icon size={19}/></span><b>{label}</b><ArrowUpLeft size={15}/></Link>)}</div></section>

    <section className="premium-filter-bar grid gap-3 rounded-2xl border p-4 md:grid-cols-[1fr_1fr_1fr_auto]"><Field label="من" type="date" value={filters.from} onChange={from=>setFilters({...filters,from})}/><Field label="إلى" type="date" value={filters.to} onChange={to=>setFilters({...filters,to})}/><Field label="خمول العميل بالأيام" type="number" value={filters.inactiveDays} onChange={inactiveDays=>setFilters({...filters,inactiveDays})}/><Link href={`/reports?from=${filters.from}&to=${filters.to}`} className="mt-6 rounded-xl bg-[var(--brand-secondary)] px-5 py-2.5 text-center font-bold text-white">مركز التقارير</Link></section>
    {message&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{message}</div>}
    {!data?<div className="premium-panel rounded-2xl border p-16 text-center">جارٍ احتساب المؤشرات من البيانات الفعلية…</div>:<>
      <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4">
        <Kpi label="صافي الربح" value={data.kpis.netProfit} href="/accounting?tab=reports" icon={CircleDollarSign}/><Kpi label="المبيعات" value={data.kpis.sales} href="/sales" icon={ShoppingCart}/><Kpi label="المشتريات" value={data.kpis.purchases} href="/purchases" icon={ShoppingBag}/><Kpi label="قيمة المخزون" value={data.kpis.inventory} href="/inventory" icon={Boxes}/><Kpi label="السيولة" value={data.kpis.liquidity} href="/accounting?tab=banks" icon={Landmark}/><Kpi label="العملاء النشطون" value={data.kpis.activeCustomers} href="/reports?report=customer-activity" icon={Users} numeric/><Kpi label="ذمم العملاء" value={data.kpis.ar} href="/accounting?tab=reports&report=ar-aging" icon={WalletCards}/><Kpi label="ذمم الموردين" value={data.kpis.ap} href="/accounting?tab=reports&report=ap-aging" icon={ReceiptText}/><Kpi label="ضريبة القيمة المضافة" value={data.kpis.vat} href="/accounting?tab=vat" icon={BadgeDollarSign}/><Kpi label="ربحية النقل" value={data.transport?.netProfit} href="/reports?report=customer-vehicle" icon={Truck}/><Kpi label="ربحية المصنع" value={data.factory?.netProfit} href="/reports?report=daily-production" icon={Factory}/><Kpi label="ربحية المشاريع" value={data.kpis.projectProfit} href="/projects" icon={Building2}/>
      </section>

      <section className="grid gap-5 xl:grid-cols-[1.55fr_.85fr]"><article className="premium-panel rounded-2xl border p-5"><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><span className="premium-eyebrow">PERFORMANCE</span><h2 className="mt-1 text-lg font-black">الأداء المالي الشهري</h2><p className="text-sm text-slate-500">صافي الربح مع مقارنة شهرية قابلة للانتقال إلى المصدر.</p></div><div className="flex gap-4 text-xs text-slate-500"><span><i className="ml-1 inline-block h-2 w-2 rounded-full bg-[var(--brand-primary)]"/>ربح</span><span><i className="ml-1 inline-block h-2 w-2 rounded-full bg-red-400"/>خسارة</span></div></div><div className="premium-chart flex h-72 items-end gap-2 overflow-x-auto px-1 pt-10">{data.monthly.map(row=>{const amount=Number(row.netProfit);return <Link title={`${row.month}: ${money(amount)}`} href={`/reports?report=monthly-comparison&from=${row.month}-01&to=${monthEnd(row.month)}`} key={String(row.month)} className="premium-bar-column group"><span>{Number(row.momPercent).toFixed(0)}%</span><div className={amount<0?"is-negative":""} style={{height:`${Math.max(4,Math.abs(amount)/maxMonthly*100)}%`}}/><b>{String(row.month).slice(5)}</b></Link>})}</div></article><article className="premium-panel rounded-2xl border p-5"><span className="premium-eyebrow">ATTENTION</span><h2 className="mb-4 mt-1 text-lg font-black">يحتاج انتباهك</h2>{[["أرصدة عملاء سالبة",data.alerts.negativeCustomerStocks,"/inventory"],["عملاء غير نشطين",data.alerts.inactiveCustomers,"/reports?report=customer-activity"],["عملاء متراجعون",data.alerts.decliningCustomers,"/reports?report=customer-activity"],["فواتير متأخرة",data.alerts.overdueReceivables,"/accounting?tab=reports&report=ar-aging"],["رحلات مفتوحة",data.alerts.openTrips,"/transport?status=OPEN"]].map(([label,value,href])=><Link key={String(label)} href={String(href)} className="premium-alert-row"><span>{String(label)}</span><b>{number(value)}</b></Link>)}</article></section>

      <section className="premium-panel rounded-2xl border p-5"><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><span className="premium-eyebrow">MATERIAL INTELLIGENCE</span><h2 className="mt-1 text-lg font-black">ربحية المواد المختارة</h2><p className="text-sm text-slate-500">الإيراد والتكلفة وصافي الربح مشتقة من المستندات والحركات.</p></div><div className="flex flex-wrap gap-2">{[0,1].map(index=><select aria-label={`المادة ${index+1}`} key={index} value={effectiveMaterials[index]} onChange={event=>setSelectedMaterials(index===0?[event.target.value,effectiveMaterials[1]]:[effectiveMaterials[0],event.target.value])} className="rounded-xl border px-3 py-2"><option value="">اختر مادة</option>{data.materials.map(row=><option key={String(row.itemId)} value={String(row.itemId)}>{String(row.itemName)}</option>)}</select>)}</div></div><div className="grid gap-4 lg:grid-cols-2">{materialCards.map(row=><Link key={String(row.itemId)} href={`/reports?report=material-profitability&itemIds=${row.itemId}&from=${filters.from}&to=${filters.to}`} className="premium-material-card"><div className="flex justify-between gap-3"><b>{String(row.itemName)}</b><strong className={Number(row.netProfit)<0?"text-red-700":"text-emerald-700"}>{money(row.netProfit)}</strong></div><div className="mt-4 grid grid-cols-3 gap-2"><Metric label="الإيراد" value={money(row.revenueExVat)}/><Metric label="COGS" value={money(row.cogs)}/><Metric label="ربح/طن" value={money(row.profitPerTon)}/></div></Link>)}</div></section>

      <section className="premium-panel rounded-2xl border p-5"><div className="mb-4"><span className="premium-eyebrow">CUSTOMER PULSE</span><h2 className="mt-1 text-lg font-black">نشاط العملاء</h2><p className="text-sm text-slate-500">السحب والقيمة وآخر حركة والتغير مقابل الفترة السابقة.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr>{["العميل","السحب","القيمة","آخر نشاط","التغير","التصنيف"].map(head=><th key={head} className="p-3 text-right">{head}</th>)}</tr></thead><tbody>{data.customerActivity.slice(0,12).map(row=><tr key={String(row.partyId)}><td className="p-3"><Link className="font-bold text-[var(--brand-primary)]" href={String(row.href)}>{String(row.partyName)}</Link></td><td>{number(row.withdrawals)}</td><td>{money(row.value)}</td><td>{row.lastActivity?new Date(String(row.lastActivity)).toLocaleDateString("ar-SA"):"لا توجد حركة"}</td><td className={Number(row.changePercent)<0?"text-red-700":"text-emerald-700"}>{Number(row.changePercent).toFixed(1)}%</td><td><Status row={row}/></td></tr>)}</tbody></table></div></section>
    </>}
  </main>
}

function Field({label,type,value,onChange}:{label:string;type:string;value:string;onChange:(value:string)=>void}){return <label className="text-sm"><span className="mb-1 block text-slate-500">{label}</span><input type={type} min={type==="number"?1:undefined} value={value} onChange={event=>onChange(event.target.value)} className="w-full rounded-xl border px-3 py-2"/></label>}
function Kpi({label,value,href,icon:Icon,numeric=false}:{label:string;value:unknown;href:string;icon:typeof Boxes;numeric?:boolean}){const negative=Number(value)<0;return <Link href={href} className="premium-kpi group"><span className="premium-kpi-icon"><Icon size={21}/></span><div><p>{label}</p><strong className={negative?"text-red-700":""}>{numeric?number(value):money(value)}</strong><small>عرض التفاصيل <ArrowUpLeft size={13}/></small></div></Link>}
function Metric({label,value}:{label:string;value:string}){return <div><p className="text-xs text-slate-500">{label}</p><b className="mt-1 block text-sm">{value}</b></div>}
function Status({row}:{row:Row}){const value=row.isNew?"جديد":row.stopped?"متوقف":row.declining?"متراجع":row.inactive?"غير نشط":"نشط";return <span className={`premium-status ${value==="نشط"||value==="جديد"?"is-good":value==="متوقف"?"is-danger":"is-warning"}`}>{value}</span>}
