"use client";

import Link from "next/link";
import Image from "next/image";
import { useEffect, useMemo, useState } from "react";

type Row = Record<string, unknown>;
type DashboardData = { range:{from:string;to:string};kpis:Row;factory:Row|null;transport:Row|null;monthly:Row[];materials:Row[];customerActivity:Row[];alerts:Row };
const menu = [
  ["العملاء والموردون", "/parties", "CORE"], ["المواد", "/items", "CORE"], ["المبيعات", "/sales", "SALES"], ["المشتريات", "/purchases", "PURCHASES"],
  ["المخزون", "/inventory", "INVENTORY"], ["المصنع", "/factory", "FACTORY"], ["السندات", "/notes", "NOTES"], ["النقليات", "/transport", "TRANSPORT"],
  ["المحاسبة والمالية", "/accounting", "ACCOUNTING"], ["الموارد البشرية", "/hr", "HR"], ["الأعمال الخارجية", "/external", "EXTERNAL"], ["التقارير والمقارنات", "/reports", "CORE"],
  ["المشاريع والمقاولات", "/projects", "PROJECTS"],
  ["مركز استيراد البيانات", "/imports", "IMPORT"],
  ["التخصيص بدون كود", "/settings/configuration", "CONFIG"], ["منشئ التقارير", "/reports/builder", "CONFIG"],
  ["مصمم المستندات والهوية", "/settings/design", "DESIGN"], ["لوحاتي", "/dashboards", "DESIGN"],
  ["معالج تهيئة الشركة", "/onboarding", "CORE"], ["إدارة منصة SaaS", "/super-admin", "CORE"],
  ["المستخدمون والصلاحيات", "/settings/users", "CORE"], ["إعدادات المؤسسة", "/settings/organization", "CORE"],
] as const;
const money=(value:unknown)=>`${Number(value??0).toLocaleString("ar-SA",{minimumFractionDigits:2,maximumFractionDigits:2})} ر.س`;
const number=(value:unknown)=>Number(value??0).toLocaleString("ar-SA",{maximumFractionDigits:2});
const today=new Date(),initialFrom=`${today.getFullYear()}-01-01`,initialTo=today.toISOString().slice(0,10);

export default function DashboardClient({ enabledModules, companyName, userName }: { enabledModules: string[]; companyName: string; userName: string }) {
  const [filters,setFilters]=useState({from:initialFrom,to:initialTo,inactiveDays:"60"}),[data,setData]=useState<DashboardData|null>(null),[message,setMessage]=useState("");
  const [selectedMaterials,setSelectedMaterials]=useState<[string,string]>(["",""]);
  const [branding,setBranding]=useState<{logoUrl?:string|null;menuOrder?:string[];secondaryColor?:string}|null>(null);
  useEffect(()=>{const controller=new AbortController(),params=new URLSearchParams(filters);fetch(`/api/analytics?${params}`,{cache:"no-store",signal:controller.signal}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setMessage("");setData(body)}).catch(error=>{if(error.name!=="AbortError")setMessage(error.message)});return()=>controller.abort()},[filters]);
  useEffect(()=>{const controller=new AbortController();fetch("/api/design/runtime",{cache:"no-store",signal:controller.signal}).then(response=>response.ok?response.json():null).then(payload=>payload?.theme&&setBranding(payload.theme)).catch(()=>undefined);return()=>controller.abort()},[]);
  const effectiveMaterials:[string,string]=selectedMaterials[0]?selectedMaterials:[String(data?.materials[0]?.itemId??""),String(data?.materials[1]?.itemId??data?.materials[0]?.itemId??"")];
  const materialCards=effectiveMaterials.map(id=>data?.materials.find(row=>String(row.itemId)===id)).filter(Boolean) as Row[];
  const maxMonthly=useMemo(()=>Math.max(1,...(data?.monthly??[]).map(row=>Math.abs(Number(row.netProfit??0)))),[data]);
  const order=new Map((branding?.menuOrder??[]).map((href,index)=>[href,index])),effectiveMenu=menu.filter(([, ,module])=>enabledModules.includes(module)).sort((left,right)=>(order.get(left[1])??999)-(order.get(right[1])??999));
  return <main dir="rtl" className="min-h-screen bg-slate-100 text-slate-900"><div className="flex min-h-screen">
    <aside className="hidden w-72 shrink-0 bg-slate-950 p-5 text-white lg:block" style={{backgroundColor:branding?.secondaryColor}}><div className="mb-8">{branding?.logoUrl?<Image src={branding.logoUrl} width={170} height={70} unoptimized alt={companyName} className="mb-2 object-contain"/>:<div className="text-3xl font-black tracking-wide">NETAJ</div>}<div className="text-sm text-slate-400">نظام إدارة الأعمال</div></div><nav className="space-y-1">{effectiveMenu.map(([label,href])=><Link key={href+label} href={href} className="block rounded-xl px-4 py-2.5 text-slate-300 hover:bg-slate-800 hover:text-white">{label}</Link>)}</nav></aside>
    <section className="min-w-0 flex-1"><header className="border-b bg-white px-5 py-5 md:px-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">لوحة الإدارة التنفيذية</h1><p className="text-sm text-slate-500">{companyName} · بيانات فعلية من دفتر الأستاذ والتشغيل</p></div><div className="rounded-xl bg-slate-900 px-4 py-2 text-white">{userName}</div></div></header>
      <div className="space-y-6 p-5 md:p-8"><section className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-4"><Field label="من" type="date" value={filters.from} onChange={from=>setFilters({...filters,from})}/><Field label="إلى" type="date" value={filters.to} onChange={to=>setFilters({...filters,to})}/><Field label="خمول العميل بالأيام" type="number" value={filters.inactiveDays} onChange={inactiveDays=>setFilters({...filters,inactiveDays})}/><Link href={`/reports?from=${filters.from}&to=${filters.to}`} className="mt-6 rounded-xl bg-blue-700 px-4 py-2.5 text-center font-bold text-white">مركز التقارير والتصدير</Link></section>
      {message&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{message}</div>}{!data?<div className="rounded-2xl border bg-white p-16 text-center">جارٍ احتساب المؤشرات…</div>:<>
        <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["المبيعات",data.kpis.sales,"/sales"],["المشتريات",data.kpis.purchases,"/purchases"],["صافي الربح",data.kpis.netProfit,"/accounting?tab=reports"],["السيولة",data.kpis.liquidity,"/accounting?tab=banks"],["قيمة مخزون الشركة",data.kpis.inventory,"/inventory"],["ذمم العملاء",data.kpis.ar,"/accounting?tab=reports&report=ar-aging"],["ذمم الموردين",data.kpis.ap,"/accounting?tab=reports&report=ap-aging"],["صافي التدفق النقدي",data.kpis.cashFlow,"/accounting?tab=reports&report=cash-flow"]].map(([label,value,href])=><Link key={String(label)} href={String(href)} className="rounded-2xl border bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow"><p className="text-sm text-slate-500">{String(label)}</p><p className={`mt-2 text-2xl font-black ${Number(value)<0?"text-red-700":"text-slate-900"}`}>{money(value)}</p><p className="mt-2 text-xs text-blue-700">عرض التفاصيل ←</p></Link>)}</section>
        <section className="grid gap-5 xl:grid-cols-2"><ProfitCard title="ربحية المصنع" value={data.factory?.netProfit} detail={`إنتاج ${number(data.factory?.tons)} طن · ربح/طن ${money(data.factory?.profitPerTon)}`} href="/reports?report=daily-production"/><ProfitCard title="ربحية النقل" value={data.transport?.netProfit} detail={`${number(data.transport?.tons)} طن · ${number(data.transport?.km)} كم · ربح/كم ${money(data.transport?.profitPerKm)}`} href="/reports?report=customer-vehicle"/></section>
        <section className="rounded-2xl border bg-white p-5"><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-bold">ربحية المواد المختارة</h2><p className="text-sm text-slate-500">الإيراد والتكلفة وصافي الربح مشتقة من المستندات والحركات.</p></div><div className="flex gap-2">{[0,1].map(index=><select key={index} value={effectiveMaterials[index]} onChange={e=>setSelectedMaterials(index===0?[e.target.value,effectiveMaterials[1]]:[effectiveMaterials[0],e.target.value])} className="rounded-lg border px-3 py-2"><option value="">اختر مادة</option>{data.materials.map(row=><option key={String(row.itemId)} value={String(row.itemId)}>{String(row.itemName)}</option>)}</select>)}</div></div><div className="grid gap-4 lg:grid-cols-2">{materialCards.map(row=><Link key={String(row.itemId)} href={`/reports?report=material-profitability&itemIds=${row.itemId}&from=${filters.from}&to=${filters.to}`} className="rounded-xl border bg-slate-50 p-4"><div className="flex justify-between"><b>{String(row.itemName)}</b><span className={Number(row.netProfit)<0?"text-red-700":"text-emerald-700"}>{money(row.netProfit)}</span></div><div className="mt-3 grid grid-cols-3 gap-2 text-sm"><Metric label="الإيراد" value={money(row.revenueExVat)}/><Metric label="COGS" value={money(row.cogs)}/><Metric label="ربح/طن" value={money(row.profitPerTon)}/></div></Link>)}</div></section>
        <section className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">المقارنة الشهرية</h2><p className="mb-5 text-sm text-slate-500">صافي الربح مع MoM ونفس الشهر من العام السابق.</p><div className="flex h-64 items-end gap-2 overflow-x-auto">{data.monthly.map(row=><Link title={`${row.month}: ${money(row.netProfit)}`} href={`/reports?report=monthly-comparison&from=${row.month}-01&to=${row.month}-31`} key={String(row.month)} className="flex min-w-14 flex-1 flex-col items-center justify-end"><span className="mb-1 text-[10px]">{Number(row.momPercent).toFixed(0)}%</span><div className={`w-full rounded-t ${Number(row.netProfit)<0?"bg-red-500":"bg-blue-600"}`} style={{height:`${Math.max(3,Math.abs(Number(row.netProfit))/maxMonthly*100)}%`}}/><span className="mt-2 text-xs">{String(row.month).slice(5)}</span></Link>)}</div></div><div className="rounded-2xl border bg-white p-5"><h2 className="mb-4 font-bold">يحتاج انتباهك</h2>{[["أرصدة عملاء سالبة",data.alerts.negativeCustomerStocks,"/inventory"],["عملاء غير نشطين",data.alerts.inactiveCustomers,"/reports?report=customer-activity"],["عملاء متراجعون",data.alerts.decliningCustomers,"/reports?report=customer-activity"],["فواتير متأخرة",data.alerts.overdueReceivables,"/accounting?tab=reports&report=ar-aging"],["رحلات مفتوحة",data.alerts.openTrips,"/transport?status=OPEN"]].map(([label,value,href])=><Link key={String(label)} href={String(href)} className="mb-2 flex items-center justify-between rounded-xl bg-amber-50 p-3"><span>{String(label)}</span><b>{number(value)}</b></Link>)}</div></section>
        <section className="rounded-2xl border bg-white p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold">نشاط العملاء</h2><p className="text-sm text-slate-500">السحب والقيمة وآخر حركة والتغير مقابل الفترة السابقة.</p></div></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-100"><tr>{["العميل","السحب","القيمة","آخر نشاط","التغير","التصنيف"].map(head=><th key={head} className="p-3 text-right">{head}</th>)}</tr></thead><tbody>{data.customerActivity.slice(0,12).map(row=><tr key={String(row.partyId)} className="border-b"><td className="p-3"><Link className="font-bold text-blue-700" href={String(row.href)}>{String(row.partyName)}</Link></td><td>{number(row.withdrawals)}</td><td>{money(row.value)}</td><td>{row.lastActivity?new Date(String(row.lastActivity)).toLocaleDateString("ar-SA"):"لا توجد حركة"}</td><td className={Number(row.changePercent)<0?"text-red-700":"text-emerald-700"}>{Number(row.changePercent).toFixed(1)}%</td><td>{row.isNew?"جديد":row.stopped?"متوقف":row.declining?"متراجع":row.inactive?"غير نشط":"نشط"}</td></tr>)}</tbody></table></div></section>
      </>}</div></section></div></main>;
}
function Field({label,type,value,onChange}:{label:string;type:string;value:string;onChange:(value:string)=>void}){return <label className="text-sm"><span className="mb-1 block text-slate-500">{label}</span><input type={type} min={type==="number"?1:undefined} value={value} onChange={event=>onChange(event.target.value)} className="w-full rounded-lg border px-3 py-2"/></label>}
function ProfitCard({title,value,detail,href}:{title:string;value:unknown;detail:string;href:string}){return <Link href={href} className="rounded-2xl border bg-slate-950 p-6 text-white"><p className="text-sm text-slate-300">{title}</p><p className={`my-2 text-3xl font-black ${Number(value)<0?"text-red-300":"text-emerald-300"}`}>{money(value)}</p><p className="text-sm text-slate-300">{detail}</p></Link>}
function Metric({label,value}:{label:string;value:string}){return <div><p className="text-xs text-slate-500">{label}</p><b>{value}</b></div>}
