"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { BadgeDollarSign, BellRing, Boxes, Building2, CalendarDays, ChartNoAxesCombined, ChevronLeft, CircleDollarSign, Factory, FileChartColumn, Landmark, Mic2, ReceiptText, RotateCw, ShoppingBag, ShoppingCart, TrendingDown, TrendingUp, TriangleAlert, Truck, Users, WalletCards } from "lucide-react";

type Row = Record<string, unknown>;
type DashboardData = { range:{from:string;to:string}; kpis:Row; executiveFinancial:Row|null; factory:Row|null; transport:Row|null; monthly:Row[]; materials:Row[]; customerActivity:Row[]; latestTransactions:Row[]; alerts:Row };
const money = (value:unknown) => `${Number(value ?? 0).toLocaleString("en-US", { minimumFractionDigits:2, maximumFractionDigits:2 })} SAR`;
const compactMoney = (value:unknown) => new Intl.NumberFormat("en-US", { notation:"compact", maximumFractionDigits:2 }).format(Number(value ?? 0));
const number = (value:unknown) => Number(value ?? 0).toLocaleString("en-US", { maximumFractionDigits:2 });
const today = new Date(), initialFrom = `${today.getFullYear()}-01-01`, initialTo = today.toISOString().slice(0,10);

export default function DashboardClient({ enabledModules, companyName }:{enabledModules:string[];companyName:string}) {
  const [locale] = useState<"ar"|"en">(()=>typeof window!=="undefined"&&window.localStorage.getItem("netaj-language")==="en"?"en":"ar");
  const t=(ar:string,en:string)=>locale==="ar"?ar:en;
  const [filters,setFilters] = useState({from:initialFrom,to:initialTo,inactiveDays:"60"});
  const [data,setData] = useState<DashboardData|null>(null), [message,setMessage] = useState(""), [loading,setLoading] = useState(true), [reload,setReload] = useState(0);
  const [selectedMaterial,setSelectedMaterial] = useState("");
  useEffect(() => { let disposed=false;const controller=new AbortController(),params=new URLSearchParams(filters),timer=window.setTimeout(()=>controller.abort(),20000);fetch(`/api/analytics?${params}`,{cache:"no-store",signal:controller.signal}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error||"Unable to load analytics");if(!disposed)setData(body)}).catch(error=>{if(!disposed)setMessage(error.name==="AbortError"?"Loading timed out. Please retry.":error.message)}).finally(()=>{window.clearTimeout(timer);if(!disposed)setLoading(false)});return()=>{disposed=true;window.clearTimeout(timer);controller.abort()}; },[filters,reload]);
  const updateFilter=(key:keyof typeof filters,value:string)=>{setLoading(true);setMessage("");setFilters(current=>({...current,[key]:value}))};
  const applyPreset=(preset:DatePreset)=>{const range=presetRange(preset);setLoading(true);setMessage("");setFilters(current=>({...current,...range}))};
  const retry=()=>{setLoading(true);setMessage("");setReload(value=>value+1)};
  const enabled=new Set(enabledModules), currentMonth=data?.monthly.at(-1), previousMonth=data?.monthly.at(-2);
  const rangeQuery=`from=${filters.from}&to=${filters.to}`;
  const trend=(key:string)=>{const current=Number(currentMonth?.[key]??0),previous=Number(previousMonth?.[key]??0);return previous?((current-previous)/Math.abs(previous))*100:null};
  const maxMonthly=useMemo(()=>Math.max(1,...(data?.monthly??[]).flatMap(row=>[Number(row.sales??0),Number(row.purchases??0)])),[data]);
  const maxProfit=useMemo(()=>Math.max(1,...(data?.monthly??[]).map(row=>Math.abs(Number(row.netProfit??0)))),[data]);
  const quickActions=[
    [t("إصدار فاتورة","Create invoice"),"/sales?type=SALES_INVOICE&new=1","SALES",ReceiptText],
    [t("إضافة عميل","Add customer"),"/parties?new=1","CORE",Users],
    [t("طلب شراء","Purchase order"),"/purchases?type=PURCHASE_REQUISITION&new=1","PURCHASES",ShoppingBag],
    [t("سند قبض","Receipt voucher"),"/accounting?tab=vouchers&type=RECEIPT","ACCOUNTING",WalletCards],
    [t("سند صرف","Payment voucher"),"/accounting?tab=vouchers&type=PAYMENT","ACCOUNTING",CircleDollarSign],
    [t("مخزون المواد","Item stock"),"/inventory","INVENTORY",Boxes],
    [t("رحلة نقل","Transport trip"),"/transport?new=1","TRANSPORT",Truck],
    [t("تقرير مالي","Financial report"),"/accounting?tab=reports","ACCOUNTING",FileChartColumn],
  ] as const;

  return <main className="reference-dashboard mx-auto max-w-[1700px] space-y-3 p-3 md:p-4">
    <section className="reference-hero relative isolate overflow-hidden rounded-[22px] border">
      <Image src="/media/netaj-industrial-hero-branded-v2.png" alt="NETAJ branded industrial operations" fill priority sizes="(max-width: 1024px) 100vw, 82vw" className="object-cover"/>
      <div className="reference-hero-shade"/>
      <div className="reference-hero-content">
        <div><span className="reference-kicker">NETAJ · ONE BUSINESS PLATFORM</span><h1>{t("معًا نبني مستقبلًا أكبر","BUILDING A BETTER TOMORROW")}</h1><p>{companyName} · {t("المال والتجارة والمصنع والنقل في صورة أعمال واحدة","Finance, trade, factory and transport in one business view")}</p></div>
        <button className="reference-ai-card" aria-label={t("فتح NETAJ ONE","Open NETAJ ONE")} onClick={()=>window.dispatchEvent(new CustomEvent("netaj-one-open"))}><span><Mic2 size={30}/></span><div><b>NETAJ ONE</b><small>{t("المساعد الذكي","Smart assistant")}</small><em>{t("جاهز","Ready")}</em></div></button>
      </div>
    </section>

    {message&&data&&<div role="alert" className="premium-inline-error"><span><TriangleAlert size={17}/>{message}</span><button onClick={retry}><RotateCw size={15}/>{t("إعادة المحاولة","Retry")}</button></div>}
    {!data?(loading?<DashboardSkeleton/>:<DashboardLoadError message={message} retry={retry} locale={locale}/>):<>
      <section className="reference-kpi-grid" aria-label={t("المؤشرات التنفيذية","Executive indicators")}>
        <Kpi label={t("إجمالي المبيعات","Total sales")} value={data.kpis.sales} href={`/sales?${rangeQuery}`} icon={ShoppingCart} trend={trend("sales")} color="blue"/>
        <Kpi label={t("إجمالي المشتريات","Total purchases")} value={data.kpis.purchases} href={`/purchases?${rangeQuery}`} icon={ShoppingBag} trend={trend("purchases")} inverse color="purple"/>
        <Kpi label={t("المصاريف","Expenses")} value={data.kpis.expenses} href={`/accounting?tab=expenses&${rangeQuery}`} icon={ReceiptText} color="amber"/>
        <Kpi label={t("صافي الربح","Net profit")} value={data.kpis.netProfit} href={`/accounting?tab=reports&${rangeQuery}`} icon={CircleDollarSign} trend={trend("netProfit")} color="gold"/>
        <Kpi label={t("السيولة","Liquidity")} value={data.kpis.liquidity} href={`/accounting?tab=banks&${rangeQuery}`} icon={Landmark} color="cyan"/>
        <Kpi label={t("سيولة البنك","Bank liquidity")} value={data.kpis.liquidity} href={`/accounting?tab=banks&${rangeQuery}`} icon={Landmark} color="blue"/>
        <Kpi label={t("ذمم العملاء","Accounts receivable")} value={data.kpis.ar} href={`/accounting?tab=receivables&${rangeQuery}`} icon={WalletCards} color="purple"/>
        <Kpi label={t("ذمم الموردين","Accounts payable")} value={data.kpis.ap} href={`/accounting?tab=payables&${rangeQuery}`} icon={ReceiptText} color="gold"/>
      </section>

      <section className="reference-chart-grid">
        <article className="reference-card reference-bars-card"><CardTitle title={t("المبيعات والمشتريات (آخر 12 شهرًا)","Sales & purchases (last 12 months)")} href="/reports?report=monthly-comparison"/><div className="reference-legend"><span className="sales">{t("المبيعات","Sales")}</span><span className="purchases">{t("المشتريات","Purchases")}</span></div><div className="reference-bars">{data.monthly.map(row=><Link href={`/reports?report=monthly-comparison&from=${row.month}-01`} key={String(row.month)} title={`${money(row.sales)} / ${money(row.purchases)}`}><div><i className="sales" style={{height:`${Math.max(3,Number(row.sales)/maxMonthly*100)}%`}}/><i className="purchases" style={{height:`${Math.max(3,Number(row.purchases)/maxMonthly*100)}%`}}/></div><small>{String(row.month).slice(5)}</small></Link>)}</div></article>
        <article className="reference-card reference-profit-card"><CardTitle title={t("صافي الربح الشهري","Monthly net profit")} href="/accounting?tab=reports"/><strong>{money(currentMonth?.netProfit)}</strong><div className="reference-profit-line">{data.monthly.map((row,index)=><Link key={String(row.month)} href={`/reports?report=monthly-comparison&from=${row.month}-01`} style={{height:`${Math.max(8,Math.abs(Number(row.netProfit))/maxProfit*92)}%`}} title={`${row.month}: ${money(row.netProfit)}`}><i/><span>{index===0||index===data.monthly.length-1?String(row.month).slice(5):""}</span></Link>)}</div></article>
        <article className="reference-card"><CardTitle title={t("توزيع الربح حسب القطاع","Profit by division")} href={`/reports?report=sector-profitability&${rangeQuery}`}/><DivisionDonut divisions={(data.executiveFinancial?.divisions as Row[]|undefined)??[]} rangeQuery={rangeQuery} locale={locale}/></article>
      </section>

      <section className="reference-bottom-grid">
        <article className="reference-card"><CardTitle title={t("المهام والتنبيهات","Tasks & alerts")} href="/notifications"/><div className="reference-alerts">{[[t("فواتير متأخرة","Overdue invoices"),data.alerts.overdueReceivables,"/accounting?tab=reports&report=ar-aging"],[t("أرصدة عملاء سالبة","Negative customer stock"),data.alerts.negativeCustomerStocks,"/inventory"],[t("موافقات معلقة","Pending approvals"),data.alerts.pendingApprovals,"/approvals"],[t("تنبيهات رقابية","Control alerts"),data.alerts.openControlAlerts,"/controls"],[t("تحذيرات الترحيل","Migration warnings"),data.alerts.migrationWarnings,"/imports"]].map(([label,value,href],index)=><Link key={String(label)} href={String(href)}><span className={`alert-icon a${index}`}><BellRing size={16}/></span><b>{String(label)}</b><strong>{number(value)}</strong></Link>)}</div></article>
        <article className="reference-card reference-transactions"><CardTitle title={t("أحدث المعاملات","Latest transactions")} href="/search"/><div className="overflow-x-auto"><table><thead><tr>{[t("التاريخ","Date"),t("النوع","Type"),t("الرقم","Number"),t("الطرف","Party"),t("المبلغ","Amount"),t("الحالة","Status")].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.latestTransactions.slice(0,6).map(row=><tr key={String(row.key)}><td>{new Date(String(row.date)).toLocaleDateString("en-GB")}</td><td>{String(row.type)}</td><td><Link href={String(row.href)}>{String(row.document)}</Link></td><td>{String(row.party)}</td><td>{row.unit?`${number(row.amount)} ${String(row.unit)}`:money(row.amount)}</td><td><span>{String(row.status)}</span></td></tr>)}</tbody></table></div></article>
        <article className="reference-card"><CardTitle title={t("روابط سريعة","Quick links")} href="/settings/design"/><div className="reference-quick-links">{quickActions.filter(([, ,module])=>enabled.has(module)).slice(0,6).map(([label,href,,Icon])=><Link href={href} key={label}><span><Icon size={21}/></span><b>{label}</b></Link>)}</div></article>
      </section>

      <section className="reference-detail-strip">
        <Detail label={t("ربحية المبيعات والمشتريات","Sales & purchase profitability")} value={money(data.kpis.netProfit)} href={`/reports?report=sector-profitability&sector=TRADE&${rangeQuery}`} icon={ShoppingCart}/><Detail label={t("ربحية المصنع","Factory profitability")} value={money(data.factory?.netProfit)} href="/factory" icon={Factory}/><Detail label={t("ربحية النقليات","Transport profitability")} value={money(data.transport?.netProfit)} href="/transport" icon={Truck}/><Detail label={t("ربحية المشاريع","Project profitability")} value={money(data.kpis.projectProfit)} href="/projects" icon={Building2}/><Detail label={t("ربحية أخرى","Other profitability")} value={money(data.executiveFinancial?.managerialNetProfit)} href={`/reports?report=sector-profitability&sector=OTHER&${rangeQuery}`} icon={ChartNoAxesCombined}/><Detail label={t("قيمة الضريبة المستحقة","VAT due")} value={money(data.kpis.vat)} href="/accounting?tab=vatReturns" icon={BadgeDollarSign}/>
      </section>
      <section className="reference-detail-strip">
        <Detail label={t("الربحية الشهرية","Monthly profitability")} value={money(currentMonth?.netProfit)} href={`/reports?report=monthly-comparison&${rangeQuery}`} icon={ChartNoAxesCombined}/><Detail label={t("الربحية الربع سنوية","Quarterly profitability")} value={money((data.monthly??[]).slice(-3).reduce((sum,row)=>sum+Number(row.netProfit??0),0))} href={`/reports?report=monthly-comparison&${rangeQuery}`} icon={ChartNoAxesCombined}/><Detail label={t("الربحية السنوية","Annual profitability")} value={money((data.monthly??[]).reduce((sum,row)=>sum+Number(row.netProfit??0),0))} href={`/reports?report=monthly-comparison&${rangeQuery}`} icon={ChartNoAxesCombined}/><Detail label={t("الربحية المخصصة","Custom profitability")} value={money(data.kpis.netProfit)} href={`/reports?report=sector-profitability&${rangeQuery}`} icon={ChartNoAxesCombined}/>
      </section>
      <MaterialProfitability materials={data.materials} selected={selectedMaterial} onSelect={setSelectedMaterial} locale={locale} rangeQuery={rangeQuery}/>
      <section className="reference-period reference-period-controls"><div className="reference-period-presets">{datePresets.map(([key,ar,en])=><button type="button" key={key} onClick={()=>applyPreset(key)}>{t(ar,en)}</button>)}</div><CompactField label={t("من","From")} value={filters.from} onChange={from=>updateFilter("from",from)}/><CompactField label={t("إلى","To")} value={filters.to} onChange={to=>updateFilter("to",to)}/><span>{t("جميع الأرقام مرتبطة بالمصدر ويمكن فتح تفاصيلها.","Every number is linked to its source and supports drill-down.")}</span></section>
    </>}
  </main>;
}

function CardTitle({title,href}:{title:string;href:string}){return <header className="reference-card-title"><h2>{title}</h2><Link href={href}><ChevronLeft size={17}/></Link></header>}
function Kpi({label,value,href,icon:Icon,trend,inverse=false,numeric=false,color}:{label:string;value:unknown;href:string;icon:typeof Boxes;trend?:number|null;inverse?:boolean;numeric?:boolean;color:string}){const good=trend!=null&&(inverse?trend<=0:trend>=0);return <Link href={href} className={`reference-kpi ${color}`}><span><Icon size={28}/></span><div><p>{label}</p><strong>{numeric?number(value):compactMoney(value)}</strong>{!numeric&&<small>SAR</small>}<em className={trend==null?"neutral":good?"up":"down"}>{trend==null?"LIVE":<>{good?<TrendingUp size={12}/>:<TrendingDown size={12}/>} {Math.abs(trend).toFixed(1)}%</>}</em></div></Link>}
function DivisionDonut({divisions,rangeQuery,locale}:{divisions:Row[];rangeQuery:string;locale:"ar"|"en"}){const positive=divisions.map(x=>Math.max(0,Number(x.netProfit??0))),total=positive.reduce((a,b)=>a+b,0)||1,colors=["#e2a82f","#1765dd","#7143d9","#7c5a31","#b9bec8"],names:Record<string,[string,string]>={TRADE:["التجارة","Trade"],FACTORY:["المصنع","Factory"],TRANSPORT:["النقليات","Transport"],PROJECTS:["المشاريع والمقاولات","Projects"],OTHER:["أخرى","Other"]};const stops=positive.map((value,index)=>{const start=positive.slice(0,index).reduce((sum,item)=>sum+item,0)/total*100,end=start+value/total*100;return `${colors[index%colors.length]} ${start}% ${end}%`}).join(",");return <div className="reference-donut-wrap"><div className="reference-donut" style={{background:`conic-gradient(${stops||"#e4e4e4 0 100%"})`}}><span><b>{compactMoney(total)}</b><small>SAR</small></span></div><div className="reference-donut-legend">{divisions.map((row,index)=>{const code=String(row.code),label=names[code]?.[locale==="ar"?0:1]??code;return <Link href={`/reports?report=sector-profitability&sector=${code}&${rangeQuery}`} key={code} title={`${label}: ${money(row.netProfit)} · ${Number(row.margin??0).toFixed(1)}%`}><i style={{background:colors[index%colors.length]}}/><span>{label}</span><b>{Number(row.margin??0).toFixed(1)}%</b></Link>})}</div></div>}
function Detail({label,value,href,icon:Icon}:{label:string;value:string;href:string;icon:typeof Boxes}){return <Link href={href}><Icon size={18}/><span>{label}</span><b>{value}</b></Link>}
function MaterialProfitability({materials,selected,onSelect,locale,rangeQuery}:{materials:Row[];selected:string;onSelect:(value:string)=>void;locale:"ar"|"en";rangeQuery:string}){const row=materials.find(item=>String(item.itemId)===selected)||materials[0];return <section className="reference-card reference-material-profit"><header className="reference-card-title"><h2>{locale==="ar"?"ربحية المواد":"Material profitability"}</h2><select aria-label={locale==="ar"?"اختيار المادة":"Select material"} value={selected||String(row?.itemId??"")} onChange={event=>onSelect(event.target.value)}><option value="">{locale==="ar"?"اختر مادة":"Select material"}</option>{materials.map(item=><option key={String(item.itemId)} value={String(item.itemId)}>{String(item.itemName??item.itemCode)}</option>)}</select></header>{row?<div className="reference-material-profit-grid"><Detail label={locale==="ar"?"المبيعات":"Sales"} value={money(row.revenueExVat)} href={`/reports?report=material-profitability&itemIds=${row.itemId}&${rangeQuery}`} icon={ShoppingCart}/><Detail label={locale==="ar"?"التكلفة":"Cost"} value={money(row.cogs)} href={`/reports?report=material-profitability&itemIds=${row.itemId}&${rangeQuery}`} icon={ReceiptText}/><Detail label={locale==="ar"?"صافي الربح":"Net profit"} value={money(row.netProfit)} href={`/reports?report=material-profitability&itemIds=${row.itemId}&${rangeQuery}`} icon={CircleDollarSign}/><Detail label={locale==="ar"?"هامش الربح":"Margin"} value={`${Number(row.revenueExVat??0)?(Number(row.netProfit??0)/Number(row.revenueExVat??0)*100).toFixed(1):"0.0"}%`} href={`/reports?report=material-profitability&itemIds=${row.itemId}&${rangeQuery}`} icon={ChartNoAxesCombined}/></div>:<p className="p-4 text-slate-500">{locale==="ar"?"لا توجد مواد متاحة":"No materials available"}</p>}</section>}
function CompactField({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="reference-date"><CalendarDays size={14}/><span>{label}</span><input type="date" value={value} onChange={event=>onChange(event.target.value)}/></label>}
function DashboardSkeleton(){return <div className="reference-kpi-grid" aria-label="Loading">{Array.from({length:5},(_,index)=><div key={index} className="reference-kpi h-24 animate-pulse"/>)}</div>}
function DashboardLoadError({message,retry,locale}:{message:string;retry:()=>void;locale:string}){return <section className="premium-load-error" role="alert"><TriangleAlert size={24}/><div><h2>{locale==="ar"?"تعذر إكمال لوحة التحليلات":"Dashboard could not be loaded"}</h2><p>{message}</p></div><button onClick={retry}><RotateCw size={16}/>{locale==="ar"?"إعادة المحاولة":"Retry"}</button></section>}

type DatePreset="today"|"yesterday"|"week"|"month"|"previousMonth"|"quarter"|"year"|"previousYear";
const datePresets:Array<[DatePreset,string,string]>=[["today","اليوم","Today"],["yesterday","أمس","Yesterday"],["week","هذا الأسبوع","This week"],["month","هذا الشهر","This month"],["previousMonth","الشهر السابق","Previous month"],["quarter","هذا الربع","This quarter"],["year","هذه السنة","This year"],["previousYear","السنة السابقة","Previous year"]];
const localDate=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
function presetRange(preset:DatePreset){const now=new Date(),from=new Date(now),to=new Date(now);if(preset==="yesterday"){from.setDate(from.getDate()-1);to.setDate(to.getDate()-1)}else if(preset==="week"){from.setDate(from.getDate()-((from.getDay()+6)%7))}else if(preset==="month"){from.setDate(1)}else if(preset==="previousMonth"){from.setMonth(from.getMonth()-1,1);to.setDate(0)}else if(preset==="quarter"){from.setMonth(Math.floor(from.getMonth()/3)*3,1)}else if(preset==="year"){from.setMonth(0,1)}else if(preset==="previousYear"){from.setFullYear(from.getFullYear()-1,0,1);to.setFullYear(to.getFullYear()-1,11,31)}return{from:localDate(from),to:localDate(to)}}
