import Image from "next/image";
import { notFound } from "next/navigation";
import { customFieldsForEntity } from "@/lib/configuration";
import { normalizeDesign } from "@/lib/design";
import { barcodeDataUrl, qrDataUrl } from "@/lib/machine-codes";
import { prisma } from "@/lib/prisma";
import PrintButton from "./PrintButton";
import NetajPrintHeader from "@/app/components/NetajPrintHeader";

type ItemView = { id: number; sequence: number; code: string; name: string; unit: string; description: string | null; materialGrade: string | null; orderNumber: string | null; quantity: number; weight: number | null };
type SignatureView = { title: string; name: string | null; signed: boolean; date: string | null };
type NoteView = { id: number; noteNumber: string; noteType: string; noteDate: string; status: string; partyName: string; stockOwnership: string; orderNumber: string | null; referenceNumber: string | null; invoiceNumber: string | null; carrierName: string | null; transportMethod: string | null; vehiclePlate: string | null; driverName: string | null; driverIdNumber: string | null; driverPhone: string | null; source: string | null; loadingPoint: string | null; unloadingPoint: string | null; notes: string | null; items: ItemView[]; signatures: SignatureView[] };
const parse = <T,>(value: string, fallback: T) => { try { return JSON.parse(value) as T; } catch { return fallback; } };

export default async function NotePrintPage({ params }: { params: Promise<{ id: string }> }) {
  const id = Number((await params).id); if (!Number.isInteger(id)) notFound();
  const note = await prisma.deliveryReceiptNote.findUnique({ where: { id }, include: { party: { include: { address: true } }, items: { include: { item: { include: { unit: true } } }, orderBy: { sequence: "asc" } }, truck: true, driver: true, trip: true } }); if (!note) notFound();
  const current: NoteView = { id: note.id, noteNumber: note.noteNumber, noteType: note.noteType, noteDate: note.noteDate.toISOString(), status: note.status, partyName: note.party.nameAr, stockOwnership: note.stockOwnership, orderNumber: note.orderNumber, referenceNumber: note.referenceNumber, invoiceNumber: note.invoiceNumber, carrierName: note.carrierName, transportMethod: note.transportMethod, vehiclePlate: note.truck?.plateNumber ?? note.vehiclePlate, driverName: note.driver?.name ?? note.driverName, driverIdNumber: note.driverIdNumber, driverPhone: note.driverPhone, source: note.source, loadingPoint: note.loadingPoint, unloadingPoint: note.unloadingPoint, notes: note.notes, items: note.items.map((item) => ({ id: item.id, sequence: item.sequence, code: item.item.code, name: item.item.nameAr, unit: item.item.unit.nameAr, description: item.description, materialGrade: item.materialGrade, orderNumber: item.orderNumber, quantity: Number(item.quantity), weight: item.weight === null ? null : Number(item.weight) })), signatures: [["المستلم", note.recipientName, note.recipientSignature, note.recipientSignedAt], ["المشتريات", note.purchasingName, note.purchasingSignature, note.purchasingSignedAt], ["المستودع", note.warehouseName, note.warehouseSignature, note.warehouseSignedAt], ["المحاسب", note.accountantName, note.accountantSignature, note.accountantSignedAt]].map(([title, name, signature, date]) => ({ title: String(title), name: name ? String(name) : null, signed: signature === "SIGNED", date: date instanceof Date ? date.toISOString() : null })) };
  const [issued, company, customFields] = await Promise.all([
    prisma.issuedDocumentPresentation.findFirst({ where: { entityType: "DELIVERY_RECEIPT_NOTE", entityId: id }, include: { templateVersion: { include: { template: true } } } }),
    prisma.company.findFirst({ where: { id: note.companyId }, include: { branches: { where: { isMain: true }, take: 1 } } }),
    prisma.$transaction((tx) => customFieldsForEntity(tx, "DELIVERY_RECEIPT_NOTE", id)),
  ]);
  const fallbackTemplate = issued ? null : await prisma.documentTemplate.findFirst({ where: { documentType: note.noteType === "RECEIPT" ? "RECEIPT_NOTE" : "DELIVERY_NOTE", isActive: true }, include: { versions: { where: { status: "PUBLISHED" }, orderBy: { version: "desc" }, take: 1 } }, orderBy: [{ isDefault: "desc" }, { id: "asc" }] });
  const design = normalizeDesign(issued ? parse(issued.templateVersion.designJson, {}) : parse(fallbackTemplate?.versions[0]?.designJson ?? "{}", {}));
  if (!company) notFound();
  const view = issued ? snapshotView(parse<Record<string, unknown>>(issued.dataSnapshotJson, {}), current) : current;
  const qr = design.features.qr ? await qrDataUrl(JSON.stringify({ type: view.noteType, number: view.noteNumber, date: view.noteDate, company: company?.legalNameAr, vat: company?.vatNumber })) : null;
  const barcode = design.features.barcode ? await barcodeDataUrl(view.noteNumber) : null;
  const receipt=view.noteType==="RECEIPT";
  const blankRows=Array.from({length:Math.max(0,5-view.items.length)},(_,index)=>index);
  return <main dir="rtl" className="netaj-note-print mx-auto min-h-[297mm] max-w-[210mm] bg-white p-[8mm] text-slate-950">
    <div className="mb-5 flex justify-between print:hidden"><a href="/notes" className="text-blue-700">العودة للسندات</a><div className="flex gap-2"><span className="rounded-lg border px-3 py-2 text-xs">{issued ? `قالب v${issued.templateVersion.version} محفوظ تاريخيًا` : "معاينة بالقالب الحالي"}</span><PrintButton /></div></div>
    <NetajPrintHeader company={company} titleAr={receipt?"سند استلام":"سند تسليم"} titleEn={receipt?"Receipt Document":"Delivery Document"}/>
    <section className="netaj-note-meta"><span>Date: ................................</span><strong>({view.noteNumber})</strong><span>التاريخ: {new Date(view.noteDate).toLocaleDateString("en-US")}</span></section>
    <p className="netaj-note-intro">{receipt?"استلمنا من السادة حسب المعلومات التالية:":"تم تسليم المواد للعميل حسب المعلومات التالية:"}</p>
    <BilingualSectionTitle en={receipt?"Supplier Information":"Client Information"} ar={receipt?"معلومات المورد":"معلومات العميل"}/>
    <table className="netaj-reference-table"><thead><tr>{(receipt?[["Supplier Name","اسم المورد"],["Invoice No","رقم الفاتورة"],["Material Source","مصدر المواد"],["Mobile No","رقم الهاتف"]]:[["Client Name","اسم العميل"],["Purchase Order No","رقم أمر الشراء"],["Project name and location","اسم المشروع وموقعه"],["Mobile No","رقم الهاتف"]]).map(([en,ar])=><th key={en}>{en}<small>{ar}</small></th>)}</tr></thead><tbody><tr><td>{view.partyName}</td><td>{view.invoiceNumber??view.orderNumber??""}</td><td>{view.source??view.unloadingPoint??""}</td><td></td></tr></tbody></table>
    <BilingualSectionTitle en="Transporter Information" ar="معلومات الناقل"/>
    <table className="netaj-reference-table"><thead><tr>{[["Transporter Name","اسم الناقل"],["Document No","رقم الوثيقة"],["Car Number","رقم السيارة"],["Driver Name","اسم السائق"],["ID Number","رقم الهوية"],["Mobile No","رقم الهاتف"]].map(([en,ar])=><th key={en}>{en}<small>{ar}</small></th>)}</tr></thead><tbody><tr><td>{view.carrierName??view.transportMethod??""}</td><td>{view.referenceNumber??""}</td><td>{view.vehiclePlate??""}</td><td>{view.driverName??""}</td><td>{view.driverIdNumber??""}</td><td>{view.driverPhone??""}</td></tr></tbody></table>
    <BilingualSectionTitle en="The following materials are listed in the table below" ar="المواد التالية حسب الجدول أدناه"/>
    <table className={`netaj-reference-table netaj-material-table ${receipt?"":"netaj-delivery-materials"}`}><thead><tr>{(receipt?[["S. No.","م"],["Product Code","رمز المنتج"],["Description","الوصف"],["Order No","رقم الطلب"],["Unit","الوحدة"],["Quantity","الكمية"]]:[["S. No.","م"],["Product Code","رمز المنتج"],["Description","الوصف"],["Performance Grade","درجة الأداء"],["Modification Type","نوع المحسن"],["Unit","الوحدة"],["Quantity","الكمية"]]).map(([en,ar])=><th key={en}>{en}<small>{ar}</small></th>)}</tr></thead><tbody>{view.items.map(item=><tr key={item.id}><td>{item.sequence}</td><td>{item.code}</td><td>{item.description??item.name}</td>{receipt?<td>{item.orderNumber??""}</td>:<><td>{item.materialGrade??""}</td><td>{item.orderNumber??""}</td></>}<td>{item.unit}</td><td>{item.quantity.toLocaleString("en-US")}</td></tr>)}{blankRows.map(index=><tr key={`blank-${index}`}><td>{view.items.length+index+1}</td>{Array.from({length:receipt?5:6},(_,cell)=><td key={cell}/>)}</tr>)}</tbody></table>
    {customFields.length>0&&<section className="netaj-note-custom">{customFields.map(field=><span key={field.id}><b>{field.labelAr}:</b> {Array.isArray(field.value)?field.value.join("، "):String(field.value??"—")}</span>)}</section>}
    <footer className="netaj-note-signatures">{orderedSignatures(view.signatures).map(signature=><div key={signature.title}><small>{signature.title==="المشتريات"?(receipt?"Purchasing Officer Name & Signature":"Sales Executive Name & Signature"):signature.title==="المستودع"?"Warehouse Officer's Name & Signature":signature.title==="المحاسب"?"Accountant's Name & Invoice No":"Recipient's Name & Signature"}</small><b>{signature.title==="المشتريات"&&!receipt?"مسؤول المبيعات والتوقيع":`${signature.title} والتوقيع`}</b><span>{signature.name??""}</span></div>)}</footer>
    <div className="netaj-reference-wave"/>
    <div className="netaj-machine-codes">{qr&&<Image src={qr} width={72} height={72} unoptimized alt="QR"/>}{barcode&&<Image src={barcode} width={160} height={50} unoptimized alt="Barcode"/>}</div>
  </main>;
}

function BilingualSectionTitle({en,ar}:{en:string;ar:string}){return <div className="netaj-bilingual-title"><span dir="ltr">{en} :</span><span>{ar} :</span></div>}

function orderedSignatures(signatures:SignatureView[]){
  const byTitle=new Map(signatures.map(signature=>[signature.title,signature]));
  return ["المحاسب","المستلم","المستودع","المشتريات"].map(title=>byTitle.get(title)??{title,name:null,signed:false,date:null});
}

function snapshotView(raw: Record<string, unknown>, fallback: NoteView): NoteView {
  const party = raw.party && typeof raw.party === "object" ? raw.party as Record<string, unknown> : {}, truck = raw.truck && typeof raw.truck === "object" ? raw.truck as Record<string, unknown> : {}, driver = raw.driver && typeof raw.driver === "object" ? raw.driver as Record<string, unknown> : {};
  const items = Array.isArray(raw.items) ? raw.items.map((entry, index) => { const row = entry as Record<string, unknown>, item = row.item && typeof row.item === "object" ? row.item as Record<string, unknown> : {}, unit = item.unit && typeof item.unit === "object" ? item.unit as Record<string, unknown> : {}; return { id: Number(row.id ?? index), sequence: Number(row.sequence ?? index + 1), code: String(item.code ?? ""), name: String(item.nameAr ?? ""), unit: String(unit.nameAr ?? ""), description: row.description ? String(row.description) : null, materialGrade: row.materialGrade ? String(row.materialGrade) : null, orderNumber: row.orderNumber ? String(row.orderNumber) : null, quantity: Number(row.quantity ?? 0), weight: row.weight === null || row.weight === undefined ? null : Number(row.weight) }; }) : fallback.items;
  const value = (key: string, defaultValue: string | null) => raw[key] === null || raw[key] === undefined ? defaultValue : String(raw[key]);
  return { ...fallback, noteNumber: value("noteNumber", fallback.noteNumber) ?? fallback.noteNumber, noteType: value("noteType", fallback.noteType) ?? fallback.noteType, noteDate: value("noteDate", fallback.noteDate) ?? fallback.noteDate, status: value("status", fallback.status) ?? fallback.status, partyName: String(party.nameAr ?? fallback.partyName), stockOwnership: value("stockOwnership", fallback.stockOwnership) ?? fallback.stockOwnership, orderNumber: value("orderNumber", fallback.orderNumber), referenceNumber: value("referenceNumber", fallback.referenceNumber), invoiceNumber: value("invoiceNumber", fallback.invoiceNumber), carrierName: value("carrierName", fallback.carrierName), transportMethod: value("transportMethod", fallback.transportMethod), vehiclePlate: String(truck.plateNumber ?? raw.vehiclePlate ?? fallback.vehiclePlate ?? "") || null, driverName: String(driver.name ?? raw.driverName ?? fallback.driverName ?? "") || null, driverIdNumber: value("driverIdNumber", fallback.driverIdNumber), driverPhone: value("driverPhone", fallback.driverPhone), source: value("source", fallback.source), loadingPoint: value("loadingPoint", fallback.loadingPoint), unloadingPoint: value("unloadingPoint", fallback.unloadingPoint), notes: value("notes", fallback.notes), items };
}
