import Image from "next/image";
import { notFound } from "next/navigation";
import { customFieldsForEntity } from "@/lib/configuration";
import { normalizeDesign } from "@/lib/design";
import { barcodeDataUrl, qrDataUrl } from "@/lib/machine-codes";
import { prisma } from "@/lib/prisma";
import PrintButton from "./PrintButton";

type ItemView = { id: number; sequence: number; code: string; name: string; unit: string; description: string | null; materialGrade: string | null; orderNumber: string | null; quantity: number; weight: number | null };
type SignatureView = { title: string; name: string | null; signed: boolean; date: string | null };
type NoteView = { id: number; noteNumber: string; noteType: string; noteDate: string; status: string; partyName: string; stockOwnership: string; orderNumber: string | null; referenceNumber: string | null; invoiceNumber: string | null; carrierName: string | null; transportMethod: string | null; vehiclePlate: string | null; driverName: string | null; driverIdNumber: string | null; driverPhone: string | null; source: string | null; loadingPoint: string | null; unloadingPoint: string | null; notes: string | null; items: ItemView[]; signatures: SignatureView[] };
const parse = <T,>(value: string, fallback: T) => { try { return JSON.parse(value) as T; } catch { return fallback; } };

export default async function NotePrintPage({ params }: { params: Promise<{ id: string }> }) {
  const id = Number((await params).id); if (!Number.isInteger(id)) notFound();
  const note = await prisma.deliveryReceiptNote.findUnique({ where: { id }, include: { party: { include: { address: true } }, items: { include: { item: { include: { unit: true } } }, orderBy: { sequence: "asc" } }, truck: true, driver: true, trip: true } }); if (!note) notFound();
  const current: NoteView = { id: note.id, noteNumber: note.noteNumber, noteType: note.noteType, noteDate: note.noteDate.toISOString(), status: note.status, partyName: note.party.nameAr, stockOwnership: note.stockOwnership, orderNumber: note.orderNumber, referenceNumber: note.referenceNumber, invoiceNumber: note.invoiceNumber, carrierName: note.carrierName, transportMethod: note.transportMethod, vehiclePlate: note.truck?.plateNumber ?? note.vehiclePlate, driverName: note.driver?.name ?? note.driverName, driverIdNumber: note.driverIdNumber, driverPhone: note.driverPhone, source: note.source, loadingPoint: note.loadingPoint, unloadingPoint: note.unloadingPoint, notes: note.notes, items: note.items.map((item) => ({ id: item.id, sequence: item.sequence, code: item.item.code, name: item.item.nameAr, unit: item.item.unit.nameAr, description: item.description, materialGrade: item.materialGrade, orderNumber: item.orderNumber, quantity: Number(item.quantity), weight: item.weight === null ? null : Number(item.weight) })), signatures: [["المستلم", note.recipientName, note.recipientSignature, note.recipientSignedAt], ["المشتريات", note.purchasingName, note.purchasingSignature, note.purchasingSignedAt], ["المستودع", note.warehouseName, note.warehouseSignature, note.warehouseSignedAt], ["المحاسب", note.accountantName, note.accountantSignature, note.accountantSignedAt]].map(([title, name, signature, date]) => ({ title: String(title), name: name ? String(name) : null, signed: signature === "SIGNED", date: date instanceof Date ? date.toISOString() : null })) };
  const [issued, company, theme, configurations, customFields] = await Promise.all([
    prisma.issuedDocumentPresentation.findFirst({ where: { entityType: "DELIVERY_RECEIPT_NOTE", entityId: id }, include: { templateVersion: { include: { template: true } } } }),
    prisma.company.findFirst({ where: { id: note.companyId }, include: { branches: { where: { isMain: true }, take: 1 } } }),
    prisma.companyThemeProfile.findFirst({ where: { companyId: note.companyId } }),
    prisma.companyConfiguration.findMany({ where: { category: "GENERAL", isActive: true } }),
    prisma.$transaction((tx) => customFieldsForEntity(tx, "DELIVERY_RECEIPT_NOTE", id)),
  ]);
  const fallbackTemplate = issued ? null : await prisma.documentTemplate.findFirst({ where: { documentType: note.noteType === "RECEIPT" ? "RECEIPT_NOTE" : "DELIVERY_NOTE", isActive: true }, include: { versions: { where: { status: "PUBLISHED" }, orderBy: { version: "desc" }, take: 1 } }, orderBy: [{ isDefault: "desc" }, { id: "asc" }] });
  const design = normalizeDesign(issued ? parse(issued.templateVersion.designJson, {}) : parse(fallbackTemplate?.versions[0]?.designJson ?? "{}", {}));
  const view = issued ? snapshotView(parse<Record<string, unknown>>(issued.dataSnapshotJson, {}), current) : current;
  const settings = Object.fromEntries(configurations.map((row) => [row.configKey, parse(row.valueJson, row.valueJson)]));
  const qr = design.features.qr ? await qrDataUrl(JSON.stringify({ type: view.noteType, number: view.noteNumber, date: view.noteDate, company: company?.legalNameAr, vat: company?.vatNumber })) : null;
  const barcode = design.features.barcode ? await barcodeDataUrl(view.noteNumber) : null;
  const pageWidth = design.page.size === "LETTER" ? "216mm" : design.page.size === "CUSTOM" ? `${design.page.widthMm}mm` : "210mm";
  const pageHeight = design.page.size === "LETTER" ? "279mm" : design.page.size === "CUSTOM" ? `${design.page.heightMm}mm` : "297mm";
  return <main dir={design.language === "EN" ? "ltr" : "rtl"} style={{ maxWidth: design.page.orientation === "landscape" ? pageHeight : pageWidth, minHeight: design.page.orientation === "landscape" ? pageWidth : pageHeight, padding: `${design.page.marginMm}mm`, fontFamily: design.language === "EN" ? design.fonts.en : design.fonts.ar }} className="mx-auto bg-white text-slate-950">
    <div className="mb-5 flex justify-between print:hidden"><a href="/notes" className="text-blue-700">العودة للسندات</a><div className="flex gap-2"><span className="rounded-lg border px-3 py-2 text-xs">{issued ? `قالب v${issued.templateVersion.version} محفوظ تاريخيًا` : "معاينة بالقالب الحالي"}</span><PrintButton /></div></div>
    <header className="mb-8 border-b-2 pb-5" style={{ borderColor: design.colors.primary }}>{design.header.showLogo && theme?.logoUrl && <Image src={theme.logoUrl} width={150} height={70} unoptimized alt="شعار الشركة" className="mb-3 object-contain" />}{design.header.showCompany && <div className="text-center"><h1 className="text-3xl font-bold" style={{ color: design.colors.primary }}>{company?.legalNameAr ?? "الشركة"}</h1>{company?.legalNameEn && design.language !== "AR" && <p>{company.legalNameEn}</p>}<p className="text-sm">{company?.vatNumber ? `الرقم الضريبي: ${company.vatNumber}` : ""} {company?.branches[0]?.city ? `· ${company.branches[0].city}` : ""}</p></div>}<h2 className="mt-4 text-center text-xl" style={{ color: design.colors.accent }}>سند {view.noteType === "RECEIPT" ? "استلام" : "تسليم"}</h2>{design.header.customText && <p className="mt-2 text-center text-sm">{design.header.customText}</p>}</header>
    {!design.body.fieldOrder.includes("transport") && <DocumentSection field="transport" view={view} hidden={design.body.hiddenFields} />}{design.body.fieldOrder.map((field) => <DocumentSection key={field} field={field} view={view} hidden={design.body.hiddenFields} />)}
    {design.body.showCustomFields && customFields.length > 0 && <section className="mb-6 grid grid-cols-2 gap-3 rounded-xl border p-4">{customFields.map((field) => <Info key={field.id} label={field.labelAr} value={Array.isArray(field.value) ? field.value.join("، ") : String(field.value ?? "—")} />)}</section>}
    <footer className="mt-8 border-t pt-4">{design.features.signatures && <section className="grid grid-cols-2 gap-4 md:grid-cols-4">{view.signatures.map((signature) => <div key={signature.title} className="min-h-28 rounded-xl border p-3"><b>{signature.title}</b><p>الاسم: {signature.name ?? "—"}</p><p>التوقيع: {signature.signed ? "تم التوقيع" : "غير موقع"}</p><p>التاريخ: {signature.date ? new Date(signature.date).toLocaleString("ar-SA") : "—"}</p></div>)}</section>}<div className="mt-5 grid items-end gap-4 sm:grid-cols-3">{design.features.stamp && <div className="flex h-24 items-center justify-center rounded-full border-2 border-dashed text-sm" style={{ borderColor: design.colors.accent }}>ختم الشركة</div>}{qr && <Image src={qr} width={120} height={120} unoptimized alt="QR" />}{barcode && <Image src={barcode} width={220} height={70} unoptimized alt="Barcode" />}</div>{design.footer.showTerms && (design.terms || settings.TERMS) && <p className="mt-4 text-xs"><b>الشروط:</b> {String(design.terms || settings.TERMS)}</p>}{(design.footer.showBank || design.footer.showIban) && <p className="mt-2 text-xs">{design.footer.showBank && settings.BANK_NAME ? `البنك: ${String(settings.BANK_NAME)} ` : ""}{design.footer.showIban && settings.IBAN ? `· IBAN: ${String(settings.IBAN)}` : ""}</p>}{design.footer.customText && <p className="mt-2 text-center text-xs">{design.footer.customText}</p>}</footer>
  </main>;
}

function snapshotView(raw: Record<string, unknown>, fallback: NoteView): NoteView {
  const party = raw.party && typeof raw.party === "object" ? raw.party as Record<string, unknown> : {}, truck = raw.truck && typeof raw.truck === "object" ? raw.truck as Record<string, unknown> : {}, driver = raw.driver && typeof raw.driver === "object" ? raw.driver as Record<string, unknown> : {};
  const items = Array.isArray(raw.items) ? raw.items.map((entry, index) => { const row = entry as Record<string, unknown>, item = row.item && typeof row.item === "object" ? row.item as Record<string, unknown> : {}, unit = item.unit && typeof item.unit === "object" ? item.unit as Record<string, unknown> : {}; return { id: Number(row.id ?? index), sequence: Number(row.sequence ?? index + 1), code: String(item.code ?? ""), name: String(item.nameAr ?? ""), unit: String(unit.nameAr ?? ""), description: row.description ? String(row.description) : null, materialGrade: row.materialGrade ? String(row.materialGrade) : null, orderNumber: row.orderNumber ? String(row.orderNumber) : null, quantity: Number(row.quantity ?? 0), weight: row.weight === null || row.weight === undefined ? null : Number(row.weight) }; }) : fallback.items;
  const value = (key: string, defaultValue: string | null) => raw[key] === null || raw[key] === undefined ? defaultValue : String(raw[key]);
  return { ...fallback, noteNumber: value("noteNumber", fallback.noteNumber) ?? fallback.noteNumber, noteType: value("noteType", fallback.noteType) ?? fallback.noteType, noteDate: value("noteDate", fallback.noteDate) ?? fallback.noteDate, status: value("status", fallback.status) ?? fallback.status, partyName: String(party.nameAr ?? fallback.partyName), stockOwnership: value("stockOwnership", fallback.stockOwnership) ?? fallback.stockOwnership, orderNumber: value("orderNumber", fallback.orderNumber), referenceNumber: value("referenceNumber", fallback.referenceNumber), invoiceNumber: value("invoiceNumber", fallback.invoiceNumber), carrierName: value("carrierName", fallback.carrierName), transportMethod: value("transportMethod", fallback.transportMethod), vehiclePlate: String(truck.plateNumber ?? raw.vehiclePlate ?? fallback.vehiclePlate ?? "") || null, driverName: String(driver.name ?? raw.driverName ?? fallback.driverName ?? "") || null, driverIdNumber: value("driverIdNumber", fallback.driverIdNumber), driverPhone: value("driverPhone", fallback.driverPhone), source: value("source", fallback.source), loadingPoint: value("loadingPoint", fallback.loadingPoint), unloadingPoint: value("unloadingPoint", fallback.unloadingPoint), notes: value("notes", fallback.notes), items };
}

function DocumentSection({ field, view, hidden }: { field: string; view: NoteView; hidden: string[] }) {
  if (hidden.includes(field)) return null;
  if (["documentNumber", "date", "party", "reference"].includes(field)) return field === "documentNumber" ? <section className="mb-6 grid grid-cols-2 gap-3 md:grid-cols-4"><Info label="رقم السند" value={view.noteNumber} /><Info label="التاريخ" value={new Date(view.noteDate).toLocaleDateString("ar-SA")} /><Info label="الحالة" value={view.status} /><Info label="الجهة" value={view.partyName} /><Info label="رقم الطلب" value={view.orderNumber} /><Info label="المرجع" value={view.referenceNumber} /><Info label="الفاتورة" value={view.invoiceNumber} /><Info label="الملكية" value={view.stockOwnership === "COMPANY" ? "الشركة" : "العميل"} /></section> : null;
  if (field === "items") return <table className="mb-8 w-full border-collapse text-sm"><thead><tr className="bg-slate-100">{["م", "المادة", "الوصف", "الدرجة", "رقم الطلب", "الوحدة", "الكمية", "الوزن"].map((head) => <th key={head} className="border p-2">{head}</th>)}</tr></thead><tbody>{view.items.map((item) => <tr key={item.id}><td className="border p-2">{item.sequence}</td><td className="border p-2">{item.code} — {item.name}</td><td className="border p-2">{item.description ?? "—"}</td><td className="border p-2">{item.materialGrade ?? "—"}</td><td className="border p-2">{item.orderNumber ?? "—"}</td><td className="border p-2">{item.unit}</td><td className="border p-2">{item.quantity.toLocaleString("ar-SA")}</td><td className="border p-2">{item.weight === null ? "—" : item.weight.toLocaleString("ar-SA")}</td></tr>)}</tbody></table>;
  if (field === "notes" && view.notes) return <p className="mb-6 border-t pt-4"><b>ملاحظات:</b> {view.notes}</p>;
  if (field === "totals") return <p className="mb-6 text-left font-bold">إجمالي الكمية: {view.items.reduce((sum, item) => sum + item.quantity, 0).toLocaleString("ar-SA")}</p>;
  return field === "transport" ? <section className="mb-6 rounded-xl border p-4"><h3 className="mb-3 font-bold">بيانات النقل</h3><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Info label="الناقل" value={view.carrierName ?? view.transportMethod} /><Info label="المركبة" value={view.vehiclePlate} /><Info label="السائق" value={view.driverName} /><Info label="هوية السائق" value={view.driverIdNumber} /><Info label="هاتف السائق" value={view.driverPhone} /><Info label="المصدر" value={view.source} /><Info label="التحميل" value={view.loadingPoint} /><Info label="التفريغ" value={view.unloadingPoint} /></div></section> : null;
}
function Info({ label, value }: { label: string; value: string | null | undefined }) { return <div><span className="block text-xs text-slate-500">{label}</span><b>{value || "—"}</b></div>; }
