import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import PrintButton from "./PrintButton";

export default async function NotePrintPage({params}:{params:Promise<{id:string}>}){
  const id=Number((await params).id);if(!Number.isInteger(id))notFound();
  const note=await prisma.deliveryReceiptNote.findUnique({where:{id},include:{party:{include:{address:true}},items:{include:{item:{include:{unit:true}}},orderBy:{sequence:"asc"}},truck:true,driver:true,trip:true}});if(!note)notFound();
  const signatures=[['المستلم',note.recipientName,note.recipientSignature,note.recipientSignedAt],['المشتريات',note.purchasingName,note.purchasingSignature,note.purchasingSignedAt],['المستودع',note.warehouseName,note.warehouseSignature,note.warehouseSignedAt],['المحاسب',note.accountantName,note.accountantSignature,note.accountantSignedAt]] as const;
  return <main dir="rtl" className="mx-auto max-w-5xl bg-white p-8 text-slate-950"><div className="mb-5 flex justify-between print:hidden"><a href="/notes" className="text-blue-700">العودة للسندات</a><PrintButton/></div><header className="mb-8 border-b-2 border-slate-900 pb-5 text-center"><h1 className="text-3xl font-bold">شركة نتاج المتطورة التجارية</h1><h2 className="mt-2 text-xl">سند {note.noteType==='RECEIPT'?'استلام':'تسليم'}</h2></header><section className="mb-6 grid grid-cols-2 gap-3 md:grid-cols-4"><Info label="رقم السند" value={note.noteNumber}/><Info label="التاريخ" value={note.noteDate.toLocaleDateString('ar-SA')}/><Info label="الحالة" value={note.status}/><Info label="الجهة" value={note.party.nameAr}/><Info label="رقم الطلب" value={note.orderNumber}/><Info label="المرجع" value={note.referenceNumber}/><Info label="الفاتورة" value={note.invoiceNumber}/><Info label="الملكية" value={note.stockOwnership==='COMPANY'?'الشركة':'العميل'}/></section><section className="mb-6 rounded-xl border p-4"><h3 className="mb-3 font-bold">بيانات النقل</h3><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Info label="الناقل" value={note.carrierName??note.transportMethod}/><Info label="المركبة" value={note.truck?.plateNumber??note.vehiclePlate}/><Info label="السائق" value={note.driver?.name??note.driverName}/><Info label="هوية السائق" value={note.driverIdNumber}/><Info label="هاتف السائق" value={note.driverPhone}/><Info label="المصدر" value={note.source}/><Info label="التحميل" value={note.loadingPoint}/><Info label="التفريغ" value={note.unloadingPoint}/></div></section><table className="mb-8 w-full border-collapse text-sm"><thead><tr className="bg-slate-100">{['م','المادة','الوصف','الدرجة','رقم الطلب','الوحدة','الكمية','الوزن'].map(x=><th key={x} className="border p-2">{x}</th>)}</tr></thead><tbody>{note.items.map(x=><tr key={x.id}><td className="border p-2">{x.sequence}</td><td className="border p-2">{x.item.code} — {x.item.nameAr}</td><td className="border p-2">{x.description??'—'}</td><td className="border p-2">{x.materialGrade??'—'}</td><td className="border p-2">{x.orderNumber??'—'}</td><td className="border p-2">{x.item.unit.nameAr}</td><td className="border p-2">{Number(x.quantity).toLocaleString('ar-SA')}</td><td className="border p-2">{x.weight==null?'—':Number(x.weight).toLocaleString('ar-SA')}</td></tr>)}</tbody></table><section className="grid grid-cols-2 gap-4 md:grid-cols-4">{signatures.map(([title,name,signature,date])=><div key={title} className="min-h-28 rounded-xl border p-3"><b>{title}</b><p>الاسم: {name??'—'}</p><p>التوقيع: {signature==='SIGNED'?'تم التوقيع':'غير موقع'}</p><p>التاريخ: {date?date.toLocaleString('ar-SA'):'—'}</p></div>)}</section>{note.notes&&<p className="mt-6 border-t pt-4"><b>ملاحظات:</b> {note.notes}</p>}</main>
}
function Info({label,value}:{label:string;value:string|null|undefined}){return <div><span className="block text-xs text-slate-500">{label}</span><b>{value||'—'}</b></div>}
