import { Prisma } from "@prisma/client";
import { audit } from "@/lib/audit";
import { nextDocumentNumber } from "@/lib/document-numbering";
import { postSalesInvoiceJournal, postSupplierInvoiceJournal } from "@/lib/accounting";

type Tx=Prisma.TransactionClient;const d=(v:unknown)=>new Prisma.Decimal(String(v??0));const t=(v:unknown)=>String(v??"").trim();const day=(v:unknown)=>{const x=new Date(String(v??""));if(Number.isNaN(x.getTime()))throw new ProjectError("INVALID_INPUT","التاريخ غير صحيح");return x};
export class ProjectError extends Error{constructor(public code:string,message:string,public status=400){super(message)}}
async function dimensions(tx:Tx,input:Record<string,unknown>){const projectId=Number(input.projectId),costCodeId=Number(input.costCodeId),costCenterId=Number(input.costCenterId);const [project,costCode,costCenter]=await Promise.all([tx.project.findUnique({where:{id:projectId}}),tx.costCode.findUnique({where:{id:costCodeId}}),tx.costCenter.findUnique({where:{id:costCenterId}})]);if(!project||!costCode||!costCenter||project.costCenterId!==costCenterId)throw new ProjectError("INVALID_DIMENSIONS","أبعاد المشروع أو كود التكلفة غير صحيحة");return{project,costCode,costCenter}}

export async function createProject(tx:Tx,input:Record<string,unknown>){const partyId=Number(input.partyId),costCenterId=Number(input.costCenterId),billingItemId=input.billingItemId?Number(input.billingItemId):null;const[party,center,item]=await Promise.all([tx.party.findUnique({where:{id:partyId}}),tx.costCenter.findUnique({where:{id:costCenterId}}),billingItemId?tx.item.findUnique({where:{id:billingItemId}}):null]);if(!party?.isCustomer||!center||billingItemId&&!item)throw new ProjectError("INVALID_INPUT","العميل أو مركز التكلفة أو مادة الفوترة غير صحيحة");const projectNumber=t(input.projectNumber)||await nextDocumentNumber(tx,"PRJ",day(input.startDate));const row=await tx.project.create({data:{projectNumber,name:t(input.name),partyId,costCenterId,billingItemId,projectManager:t(input.projectManager)||null,startDate:day(input.startDate),endDate:input.endDate?day(input.endDate):null,status:t(input.status)||"ACTIVE",contractValue:d(input.contractValue),advanceAmount:d(input.advanceAmount),retentionPercent:d(input.retentionPercent),notes:t(input.notes)||null},include:{customer:true,costCenter:true}});await audit(tx,{action:"CREATE",entityType:"PROJECT",entityId:row.id});return row}

export async function addContract(tx:Tx,projectId:number,input:Record<string,unknown>){const project=await tx.project.findUnique({where:{id:projectId}});if(!project)throw new ProjectError("NOT_FOUND","المشروع غير موجود",404);const row=await tx.projectContract.create({data:{projectId,contractNumber:t(input.contractNumber)||await nextDocumentNumber(tx,"PCT"),contractDate:day(input.contractDate),startDate:day(input.startDate),endDate:input.endDate?day(input.endDate):null,contractValue:d(input.contractValue),advanceAmount:d(input.advanceAmount),retentionPercent:d(input.retentionPercent),status:t(input.status)||"ACTIVE",terms:t(input.terms)||null}});await tx.project.update({where:{id:projectId},data:{contractValue:row.contractValue,advanceAmount:row.advanceAmount,retentionPercent:row.retentionPercent}});await audit(tx,{action:"CREATE",entityType:"PROJECT_CONTRACT",entityId:row.id,metadata:{projectId}});return row}

export async function addBoqItem(tx:Tx,projectId:number,input:Record<string,unknown>){const{costCode}=await dimensions(tx,{...input,projectId,costCenterId:(await tx.project.findUnique({where:{id:projectId}}))?.costCenterId});const quantity=d(input.quantity),rate=d(input.rate);if(quantity.lte(0)||rate.lt(0)||!t(input.description))throw new ProjectError("INVALID_INPUT","بيانات بند BOQ غير صحيحة");const row=await tx.projectBoqItem.create({data:{projectId,contractId:input.contractId?Number(input.contractId):null,costCodeId:costCode.id,itemId:input.itemId?Number(input.itemId):null,boqCode:t(input.boqCode),description:t(input.description),unit:t(input.unit)||"وحدة",quantity,rate,value:quantity.mul(rate)}});await audit(tx,{action:"CREATE",entityType:"PROJECT_BOQ",entityId:row.id,metadata:{projectId}});return row}

export async function upsertCostBudget(tx:Tx,projectId:number,input:Record<string,unknown>){const project=await tx.project.findUnique({where:{id:projectId}});if(!project)throw new ProjectError("NOT_FOUND","المشروع غير موجود",404);const{costCode}=await dimensions(tx,{projectId,costCenterId:project.costCenterId,costCodeId:input.costCodeId});const budget=d(input.budgetAmount),forecast=input.forecastAmount==null?budget:d(input.forecastAmount);const existing=await tx.projectCostBudget.findFirst({where:{projectId,costCodeId:costCode.id}});const data={projectId,costCodeId:costCode.id,costCenterId:project.costCenterId,budgetAmount:budget,forecastAmount:forecast,notes:t(input.notes)||null};const row=existing?await tx.projectCostBudget.update({where:{id:existing.id},data}):await tx.projectCostBudget.create({data});await audit(tx,{action:"UPSERT",entityType:"PROJECT_COST_BUDGET",entityId:row.id,metadata:{projectId}});return row}

export async function addChangeOrder(tx:Tx,projectId:number,input:Record<string,unknown>){const project=await tx.project.findUnique({where:{id:projectId}});if(!project)throw new ProjectError("NOT_FOUND","المشروع غير موجود",404);const lines=Array.isArray(input.lines)?input.lines as Record<string,unknown>[]:[];if(!lines.length)throw new ProjectError("INVALID_INPUT","يلزم بند واحد على الأقل");let value=d(0);const parsed=[];for(const line of lines){const code=await tx.costCode.findUnique({where:{id:Number(line.costCodeId)}});if(!code)throw new ProjectError("INVALID_INPUT","كود تكلفة غير صحيح");const quantity=d(line.quantity||1),rate=d(line.rate),lineValue=quantity.mul(rate);value=value.add(lineValue);parsed.push({costCodeId:code.id,description:t(line.description),quantity,rate,value:lineValue})}const status=t(input.status)||"DRAFT";const row=await tx.projectChangeOrder.create({data:{projectId,contractId:input.contractId?Number(input.contractId):null,changeOrderNumber:t(input.changeOrderNumber)||await nextDocumentNumber(tx,"PCO"),changeDate:day(input.changeDate),description:t(input.description),value,status,approvedAt:status==="APPROVED"?new Date():null,lines:{create:parsed}},include:{lines:true}});if(status==="APPROVED")await tx.project.update({where:{id:projectId},data:{contractValue:{increment:value}}});await audit(tx,{action:status==="APPROVED"?"APPROVE":"CREATE",entityType:"PROJECT_CHANGE_ORDER",entityId:row.id,metadata:{projectId}});return row}

export async function addProgress(tx:Tx,projectId:number,input:Record<string,unknown>){const boqItemId=input.boqItemId?Number(input.boqItemId):null,boq=boqItemId?await tx.projectBoqItem.findFirst({where:{id:boqItemId,projectId}}):null;if(boqItemId&&!boq)throw new ProjectError("INVALID_INPUT","بند BOQ لا يتبع المشروع");const quantity=d(input.quantity),percentage=input.percentage!=null?d(input.percentage):boq&&boq.quantity.gt(0)?quantity.div(boq.quantity).mul(100):d(0),value=input.value!=null?d(input.value):boq?quantity.mul(boq.rate):d(0);const row=await tx.projectProgress.create({data:{projectId,boqItemId,progressDate:day(input.progressDate),quantity,percentage,value,notes:t(input.notes)||null}});const totals=await tx.projectProgress.aggregate({where:{projectId},_sum:{value:true}}),project=await tx.project.findUnique({where:{id:projectId}}),pct=project&&d(project.contractValue).gt(0)?d(totals._sum.value).div(project.contractValue).mul(100):d(0);await tx.project.update({where:{id:projectId},data:{progressPercent:Prisma.Decimal.min(pct,100)}});await audit(tx,{action:"CREATE",entityType:"PROJECT_PROGRESS",entityId:row.id,metadata:{projectId}});return row}

export async function createProgressCertificate(tx:Tx,projectId:number,input:Record<string,unknown>){const project=await tx.project.findUnique({where:{id:projectId},include:{boqItems:true,certificates:true}});if(!project)throw new ProjectError("NOT_FOUND","المشروع غير موجود",404);const lines=Array.isArray(input.lines)?input.lines as Record<string,unknown>[]:[];if(!lines.length)throw new ProjectError("INVALID_INPUT","يلزم بند إنجاز واحد");const prior=project.certificates.filter(x=>x.status!=="CANCELLED").reduce((s,x)=>s.add(x.currentValue),d(0));let current=d(0);const parsed=[];for(const line of lines){const boq=project.boqItems.find(x=>x.id===Number(line.boqItemId));if(!boq)throw new ProjectError("INVALID_INPUT","بند BOQ لا يتبع المشروع");const previous=(await tx.progressCertificateLine.aggregate({where:{boqItemId:boq.id,certificate:{status:{not:"CANCELLED"}}},_sum:{currentQuantity:true}}))._sum.currentQuantity??d(0),qty=d(line.currentQuantity),cumulative=d(previous).add(qty);if(cumulative.gt(boq.quantity))throw new ProjectError("OVER_CERTIFICATION","الكمية التراكمية تتجاوز كمية BOQ");const value=qty.mul(boq.rate);current=current.add(value);parsed.push({boqItemId:boq.id,previousQuantity:previous,currentQuantity:qty,cumulativeQuantity:cumulative,completionPercent:boq.quantity.gt(0)?cumulative.div(boq.quantity).mul(100):d(0),currentValue:value})}const retention=current.mul(d(input.retentionPercent??project.retentionPercent)).div(100),advance=d(input.advanceRecoveryAmount),vat=current.mul(d(input.vatRate??15)).div(100),net=current.add(vat).sub(retention).sub(advance),cumulative=prior.add(current);const row=await tx.progressCertificate.create({data:{projectId,contractId:input.contractId?Number(input.contractId):null,certificateNumber:t(input.certificateNumber)||await nextDocumentNumber(tx,"PPC"),certificateDate:day(input.certificateDate),previousValue:prior,currentValue:current,cumulativeValue:cumulative,completionPercent:project.contractValue.gt(0)?cumulative.div(project.contractValue).mul(100):d(0),retentionAmount:retention,advanceRecoveryAmount:advance,vatAmount:vat,netAmount:net,notes:t(input.notes)||null,lines:{create:parsed}},include:{lines:true}});await audit(tx,{action:"CREATE",entityType:"PROGRESS_CERTIFICATE",entityId:row.id,metadata:{projectId}});return row}

export async function postProgressCertificate(tx:Tx,id:number){const cert=await tx.progressCertificate.findUnique({where:{id},include:{project:true,lines:{include:{boqItem:true}}}});if(!cert)throw new ProjectError("NOT_FOUND","المستخلص غير موجود",404);if(cert.status==="POSTED"&&cert.saleId)return cert;if(!cert.project.billingItemId&&!cert.lines.every(x=>x.boqItem.itemId))throw new ProjectError("BILLING_ITEM_REQUIRED","يجب تحديد مادة فوترة للمشروع أو بنود BOQ");const sale=await tx.sale.create({data:{invoiceNumber:await nextDocumentNumber(tx,"INV",cert.certificateDate),invoiceDate:cert.certificateDate,partyId:cert.project.partyId,projectId:cert.projectId,costCenterId:cert.project.costCenterId,referenceNumber:cert.certificateNumber,subtotal:cert.currentValue,vatAmount:cert.vatAmount,totalAmount:d(cert.currentValue).add(cert.vatAmount),functionalSubtotal:cert.currentValue,functionalVatAmount:cert.vatAmount,functionalTotalAmount:d(cert.currentValue).add(cert.vatAmount),status:"COMPLETED",notes:`مستخلص ${cert.certificateNumber}`,items:{create:cert.lines.map(x=>({itemId:x.boqItem.itemId??Number(cert.project.billingItemId),description:x.boqItem.description,quantity:x.currentQuantity,unitPrice:x.boqItem.rate,vatRate:15,vatAmount:d(x.currentValue).mul(0.15),totalAmount:d(x.currentValue).mul(1.15)}))}}});await postSalesInvoiceJournal(tx,sale.id);const row=await tx.progressCertificate.update({where:{id},data:{status:"POSTED",saleId:sale.id,postedAt:new Date()},include:{sale:true,lines:true}});await audit(tx,{action:"POST",entityType:"PROGRESS_CERTIFICATE",entityId:id,metadata:{saleId:sale.id}});return row}

export async function createSubcontract(tx:Tx,projectId:number,input:Record<string,unknown>){const project=await tx.project.findUnique({where:{id:projectId}}),party=await tx.party.findUnique({where:{id:Number(input.partyId)}}),code=await tx.costCode.findUnique({where:{id:Number(input.costCodeId)}});if(!project||!party?.isSupplier||!code)throw new ProjectError("INVALID_INPUT","بيانات عقد المقاول غير صحيحة");const row=await tx.subcontractorContract.create({data:{projectId,partyId:party.id,costCodeId:code.id,billingItemId:input.billingItemId?Number(input.billingItemId):null,contractNumber:t(input.contractNumber)||await nextDocumentNumber(tx,"SCT"),contractDate:day(input.contractDate),startDate:day(input.startDate),endDate:input.endDate?day(input.endDate):null,contractValue:d(input.contractValue),advanceAmount:d(input.advanceAmount),retentionPercent:d(input.retentionPercent),notes:t(input.notes)||null}});await audit(tx,{action:"CREATE",entityType:"SUBCONTRACT",entityId:row.id,metadata:{projectId}});return row}

export async function createSubcontractCertificate(tx:Tx,contractId:number,input:Record<string,unknown>){const contract=await tx.subcontractorContract.findUnique({where:{id:contractId},include:{certificates:true}});if(!contract)throw new ProjectError("NOT_FOUND","عقد المقاول غير موجود",404);const previous=contract.certificates.filter(x=>x.status!=="CANCELLED").reduce((s,x)=>s.add(x.currentValue),d(0)),current=d(input.currentValue),cumulative=previous.add(current);if(cumulative.gt(contract.contractValue))throw new ProjectError("OVER_CERTIFICATION","المستخلصات تتجاوز قيمة عقد المقاول");const retention=current.mul(contract.retentionPercent).div(100),advance=d(input.advanceRecoveryAmount),vat=current.mul(d(input.vatRate??15)).div(100),net=current.add(vat).sub(retention).sub(advance);const row=await tx.subcontractorCertificate.create({data:{subcontractContractId:contractId,certificateNumber:t(input.certificateNumber)||await nextDocumentNumber(tx,"SCC"),certificateDate:day(input.certificateDate),previousValue:previous,currentValue:current,cumulativeValue:cumulative,retentionAmount:retention,advanceRecoveryAmount:advance,vatAmount:vat,netAmount:net,notes:t(input.notes)||null}});await audit(tx,{action:"CREATE",entityType:"SUBCONTRACT_CERTIFICATE",entityId:row.id,metadata:{projectId:contract.projectId}});return row}

export async function postSubcontractCertificate(tx:Tx,id:number){const cert=await tx.subcontractorCertificate.findUnique({where:{id},include:{subcontractContract:{include:{project:true}}}});if(!cert)throw new ProjectError("NOT_FOUND","مستخلص المقاول غير موجود",404);if(cert.status==="POSTED"&&cert.purchaseId)return cert;const contract=cert.subcontractContract;if(!contract.billingItemId)throw new ProjectError("BILLING_ITEM_REQUIRED","مادة فوترة عقد المقاول مطلوبة");const purchase=await tx.purchase.create({data:{purchaseNumber:await nextDocumentNumber(tx,"INV",cert.certificateDate),purchaseDate:cert.certificateDate,partyId:contract.partyId,projectId:contract.projectId,costCenterId:contract.project.costCenterId,costCodeId:contract.costCodeId,supplierInvoiceNumber:cert.certificateNumber,subtotal:cert.currentValue,vatAmount:cert.vatAmount,totalAmount:d(cert.currentValue).add(cert.vatAmount),functionalSubtotal:cert.currentValue,functionalVatAmount:cert.vatAmount,functionalTotalAmount:d(cert.currentValue).add(cert.vatAmount),status:"COMPLETED",notes:`مستخلص مقاول ${cert.certificateNumber}`,items:{create:{itemId:contract.billingItemId,description:`مستخلص ${contract.contractNumber}`,quantity:1,unitPrice:cert.currentValue,vatRate:15,vatAmount:cert.vatAmount,totalAmount:d(cert.currentValue).add(cert.vatAmount)}}}});await postSupplierInvoiceJournal(tx,purchase.id);const row=await tx.subcontractorCertificate.update({where:{id},data:{status:"POSTED",purchaseId:purchase.id,postedAt:new Date()},include:{purchase:true}});await audit(tx,{action:"POST",entityType:"SUBCONTRACT_CERTIFICATE",entityId:id,metadata:{purchaseId:purchase.id}});return row}

export async function linkProjectCost(tx:Tx,input:Record<string,unknown>){const entityType=t(input.entityType).toUpperCase(),entityId=Number(input.entityId),{project,costCode,costCenter}=await dimensions(tx,input),data={projectId:project.id,costCodeId:costCode.id,costCenterId:costCenter.id};const models:Record<string,{update:(args:never)=>Promise<unknown>}>= {PURCHASE:tx.purchase as never,EXPENSE:tx.expense as never,STOCK_MOVEMENT:tx.stockMovement as never,TRANSPORT_TRIP:tx.transportTrip as never,PAYROLL_LINE:tx.payrollLine as never,BUSINESS_DOCUMENT:tx.businessDocument as never,SALE:tx.sale as never};const model=models[entityType];if(!model)throw new ProjectError("INVALID_INPUT","نوع سجل غير مدعوم");let row;try{row=await model.update({where:{id:entityId},data} as never)}catch{throw new ProjectError("NOT_FOUND","السجل غير موجود",404)}const referenceType=entityType==="PURCHASE"?"SUPPLIER_INVOICE":entityType==="SALE"?"SALES_INVOICE":null;let journalId:number|undefined;if(referenceType)journalId=(await tx.journalEntry.findFirst({where:{referenceType,referenceId:entityId},select:{id:true}}))?.id;if(entityType==="EXPENSE")journalId=(await tx.expense.findUnique({where:{id:entityId},select:{journalEntryId:true}}))?.journalEntryId??undefined;if(journalId)await tx.journalEntryLine.updateMany({where:{journalEntryId:journalId},data:{projectCode:project.projectNumber,costCenterId:costCenter.id,costCodeId:costCode.id}});await audit(tx,{action:"LINK_PROJECT",entityType,entityId,metadata:data});return row}

export async function projectKpis(tx:Tx,projectId:number){
  const project=await tx.project.findUnique({where:{id:projectId},include:{customer:true,costCenter:true,contracts:true,boqItems:{include:{costCode:true}},budgets:{include:{costCode:true}},changeOrders:{include:{lines:true}},progress:true,certificates:{include:{lines:true,sale:{include:{allocations:true}}}},subcontractors:{include:{subcontractor:true,certificates:{include:{purchase:{include:{allocations:true}}}}}},sales:{include:{allocations:true}},purchases:{include:{allocations:true}},expenses:true,stockMovements:true,transportTrips:true,payrollLines:true,documents:true}});
  if(!project)throw new ProjectError("NOT_FOUND","المشروع غير موجود",404);
  const purchases=project.purchases.filter(x=>x.status!=="CANCELLED").reduce((s,x)=>s.add(x.functionalSubtotal||x.subtotal).sub(x.functionalDiscount||x.discount),d(0));
  const expenses=project.expenses.filter(x=>x.status==="POSTED").reduce((s,x)=>s.add(x.functionalAmountBeforeVat||x.amountBeforeVat),d(0));
  const inventory=project.stockMovements.filter(x=>d(x.quantityOut).gt(0)&&!["PURCHASE","SUPPLIER_INVOICE"].includes(x.referenceType??"")).reduce((s,x)=>s.add(x.totalValue),d(0));
  const transport=project.transportTrips.reduce((s,x)=>s.add(x.totalCost),d(0));
  const labor=project.payrollLines.reduce((s,x)=>s.add(x.grossSalary),d(0));
  const actual=purchases.add(expenses).add(inventory).add(transport).add(labor);
  const poCommitted=project.documents.filter(x=>x.documentType==="PURCHASE_ORDER"&&!['CANCELLED','COMPLETED'].includes(x.status)).reduce((s,x)=>s.add(x.subtotal).sub(x.discount),d(0));
  const subCommitted=project.subcontractors.reduce((sum,contract)=>{const certified=contract.certificates.filter(c=>c.status!=="CANCELLED").reduce((s,c)=>s.add(c.currentValue),d(0));return sum.add(Prisma.Decimal.max(d(contract.contractValue).sub(certified),0))},d(0));
  const committed=poCommitted.add(subCommitted),budget=project.budgets.reduce((s,x)=>s.add(x.budgetAmount),d(0)),forecastInput=project.budgets.reduce((s,x)=>s.add(x.forecastAmount),d(0));
  const forecast=Prisma.Decimal.max(forecastInput,budget,actual.add(committed)),costToComplete=Prisma.Decimal.max(forecast.sub(actual),committed,0),estimatedFinalCost=actual.add(costToComplete);
  const revenue=project.sales.filter(x=>x.status!=="CANCELLED").reduce((s,x)=>s.add(x.functionalSubtotal||x.subtotal).sub(x.functionalDiscount||x.discount),d(0)),estimatedFinalProfit=revenue.sub(estimatedFinalCost),margin=revenue.gt(0)?estimatedFinalProfit.div(revenue).mul(100):d(0);
  const cashIn=project.sales.flatMap(x=>x.allocations).reduce((s,x)=>s.add(x.functionalAmount||x.amount),d(0)),cashOut=project.purchases.flatMap(x=>x.allocations).reduce((s,x)=>s.add(x.functionalAmount||x.amount),d(0)).add(project.expenses.filter(x=>x.status==="POSTED"&&x.bankAccountId).reduce((s,x)=>s.add(x.functionalTotalAmount||x.totalAmount),d(0)));
  const byCode=project.budgets.map(b=>{const p=project.purchases.filter(x=>x.costCodeId===b.costCodeId).reduce((s,x)=>s.add(x.functionalSubtotal||x.subtotal),d(0)),e=project.expenses.filter(x=>x.costCodeId===b.costCodeId).reduce((s,x)=>s.add(x.functionalAmountBeforeVat||x.amountBeforeVat),d(0)),i=project.stockMovements.filter(x=>x.costCodeId===b.costCodeId&&d(x.quantityOut).gt(0)).reduce((s,x)=>s.add(x.totalValue),d(0)),tr=project.transportTrips.filter(x=>x.costCodeId===b.costCodeId).reduce((s,x)=>s.add(x.totalCost),d(0)),l=project.payrollLines.filter(x=>x.costCodeId===b.costCodeId).reduce((s,x)=>s.add(x.grossSalary),d(0)),actualCode=p.add(e).add(i).add(tr).add(l);return{costCodeId:b.costCodeId,code:b.costCode.code,name:b.costCode.nameAr,budget:Number(b.budgetAmount),forecast:Number(b.forecastAmount),actual:Number(actualCode),variance:Number(d(b.budgetAmount).sub(actualCode))}});
  return{project,kpis:{budget:Number(budget),actual:Number(actual),committed:Number(committed),forecast:Number(forecast),costToComplete:Number(costToComplete),estimatedFinalCost:Number(estimatedFinalCost),revenue:Number(revenue),estimatedFinalProfit:Number(estimatedFinalProfit),expectedMargin:Number(margin),cashIn:Number(cashIn),cashOut:Number(cashOut),netCashFlow:Number(cashIn.sub(cashOut))},costBreakdown:{purchases:Number(purchases),expenses:Number(expenses),inventory:Number(inventory),transport:Number(transport),labor:Number(labor)},byCode};
}

export async function projectsWorkspace(tx:Tx){const[projects,parties,items,costCenters,costCodes]=await Promise.all([tx.project.findMany({include:{customer:true,costCenter:true},orderBy:{createdAt:"desc"}}),tx.party.findMany({where:{OR:[{isCustomer:true},{isSupplier:true}],isActive:true},orderBy:{nameAr:"asc"}}),tx.item.findMany({where:{isActive:true},orderBy:{nameAr:"asc"}}),tx.costCenter.findMany({where:{isActive:true},orderBy:{nameAr:"asc"}}),tx.costCode.findMany({where:{isActive:true},orderBy:{code:"asc"}})]);const summaries=[];for(const project of projects){const result=await projectKpis(tx,project.id);summaries.push({id:project.id,projectNumber:project.projectNumber,name:project.name,customer:project.customer.nameAr,status:project.status,progressPercent:Number(project.progressPercent),...result.kpis})}return{projects:summaries,parties,items,costCenters,costCodes}}

export function projectErrorResponse(error:unknown){return error instanceof ProjectError?{status:error.status,message:error.message,code:error.code}:{status:500,message:"تعذر تنفيذ عملية المشروع",code:"PROJECT_ERROR"}}
