import { createHash, createHmac } from "node:crypto";
import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import { isAbsolute, join, resolve, sep } from "node:path";

export type StoredObject={location:string;provider:"local"|"s3";key:string};
export class StorageError extends Error{constructor(message:string,public readonly status=500){super(message)}}
const hash=(value:string|Uint8Array)=>createHash("sha256").update(value).digest("hex");
const hmac=(key:Buffer|string,value:string)=>createHmac("sha256",key).update(value).digest();
const encodePath=(value:string)=>value.split("/").map(encodeURIComponent).join("/");
const cleanKey=(value:string)=>{const key=value.replace(/\\/g,"/").replace(/^\/+/,"");if(!key||key.split("/").some(part=>!part||part==="."||part===".."))throw new StorageError("مفتاح التخزين غير صالح",400);return key};

function s3Config(){const endpoint=process.env.S3_ENDPOINT?.trim(),bucket=process.env.S3_BUCKET?.trim(),region=process.env.S3_REGION?.trim()||"us-east-1",accessKey=process.env.S3_ACCESS_KEY_ID?.trim(),secretKey=process.env.S3_SECRET_ACCESS_KEY?.trim();if(!endpoint||!bucket||!accessKey||!secretKey)throw new StorageError("إعدادات التخزين S3 غير مكتملة",503);const parsed=new URL(endpoint);if(parsed.protocol!=="https:"&&process.env.NODE_ENV==="production")throw new StorageError("يجب استخدام HTTPS مع تخزين S3",503);return{endpoint:parsed,bucket,region,accessKey,secretKey}}

export function createS3SignedRequest(method:string,keyValue:string,body:Uint8Array|null,date=new Date()){const config=s3Config(),key=cleanKey(keyValue),timestamp=date.toISOString().replace(/[:-]|\.\d{3}/g,""),day=timestamp.slice(0,8),payloadHash=hash(body??new Uint8Array()),basePath=config.endpoint.pathname.replace(/\/$/,""),canonicalUri=`${basePath}/${encodeURIComponent(config.bucket)}/${encodePath(key)}`.replace(/\/+/g,"/"),host=config.endpoint.host,canonicalHeaders=`host:${host}\nx-amz-content-sha256:${payloadHash}\nx-amz-date:${timestamp}\n`,signedHeaders="host;x-amz-content-sha256;x-amz-date",canonicalRequest=[method,canonicalUri,"",canonicalHeaders,signedHeaders,payloadHash].join("\n"),scope=`${day}/${config.region}/s3/aws4_request`,stringToSign=["AWS4-HMAC-SHA256",timestamp,scope,hash(canonicalRequest)].join("\n"),dateKey=hmac(`AWS4${config.secretKey}`,day),regionKey=hmac(dateKey,config.region),serviceKey=hmac(regionKey,"s3"),signingKey=hmac(serviceKey,"aws4_request"),signature=createHmac("sha256",signingKey).update(stringToSign).digest("hex"),authorization=`AWS4-HMAC-SHA256 Credential=${config.accessKey}/${scope}, SignedHeaders=${signedHeaders}, Signature=${signature}`;return{url:new URL(canonicalUri,config.endpoint.origin),headers:{Authorization:authorization,"x-amz-content-sha256":payloadHash,"x-amz-date":timestamp}}}

async function s3Request(method:string,key:string,body:Uint8Array|null){const signed=createS3SignedRequest(method,key,body),controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),30_000);try{const response=await fetch(signed.url,{method,headers:signed.headers,body:body?Buffer.from(body):undefined,signal:controller.signal});if(!response.ok)throw new StorageError(`فشل مزود التخزين (${response.status})`,502);return response}finally{clearTimeout(timeout)}}
function localRoot(){return resolve(process.env.ATTACHMENT_STORAGE_DIR??join(process.cwd(),"storage","attachments"))}
function localPath(keyValue:string){const key=cleanKey(keyValue),root=localRoot(),path=resolve(root,key);if(path!==root&&!path.startsWith(`${root}${sep}`))throw new StorageError("مسار التخزين غير صالح",400);return{root,path,key}}

export function storageProvider(){return process.env.ATTACHMENT_STORAGE_PROVIDER?.trim().toLowerCase()==="s3"?"s3":"local" as const}
export async function putPrivateObject(keyValue:string,content:Uint8Array):Promise<StoredObject>{const key=cleanKey(keyValue);if(storageProvider()==="s3"){await s3Request("PUT",key,content);return{provider:"s3",key,location:`s3://${process.env.S3_BUCKET}/${key}`}}const{path}=localPath(key);await mkdir(resolve(path,".."),{recursive:true});await writeFile(path,content,{flag:"wx"});return{provider:"local",key,location:`local://${key}`}}
export async function getPrivateObject(location:string){if(location.startsWith("s3://")){const slash=location.indexOf("/",5),key=slash<0?"":location.slice(slash+1);return new Uint8Array(await(await s3Request("GET",key,null)).arrayBuffer())}if(location.startsWith("local://"))return new Uint8Array(await readFile(localPath(location.slice(8)).path));const root=localRoot(),legacy=isAbsolute(location)?resolve(location):resolve(process.cwd(),location);if(legacy!==root&&!legacy.startsWith(`${root}${sep}`))throw new StorageError("مسار المرفق غير صالح",400);return new Uint8Array(await readFile(legacy))}
export async function deletePrivateObject(location:string){if(location.startsWith("s3://")){const slash=location.indexOf("/",5),key=slash<0?"":location.slice(slash+1);await s3Request("DELETE",key,null);return}if(location.startsWith("local://")){await unlink(localPath(location.slice(8)).path).catch(error=>{if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error});return}const root=localRoot(),legacy=isAbsolute(location)?resolve(location):resolve(process.cwd(),location);if(legacy===root||!legacy.startsWith(`${root}${sep}`))throw new StorageError("مسار المرفق غير صالح",400);await unlink(legacy).catch(error=>{if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error})}
