import type {Prisma} from "@prisma/client";
import {authorizeRequest} from "@/lib/api-auth";
import {runWithDataScope} from "@/lib/data-scope";
import {createPdf,createXlsx,type ReportTable} from "@/lib/financial-export";
import {prisma} from "@/lib/prisma";
const date=(value:string|null,end=false)=>value?new Date(`${value}${end?"T23:59:59.999":"T00:00:00.000"}`):null;
export async function GET(request:Request){
 try{const params=new URL(request.url).searchParams,direction=params.get("direction")==="PURCHASE"?"PURCHASE":"SALES",moduleKey=direction==="SALES"?"SALES":"PURCHASES",context=await authorizeRequest(request,{moduleKey,action:"READ"}),format=params.get("format")==="pdf"?"pdf":"xlsx",partyId=Number(params.get("partyId")),itemId=Number(params.get("itemId")),from=date(params.get("from")),to=date(params.get("to"),true),status=params.get("status"),q=params.get("q")?.trim();
 const common={...(partyId>0?{partyId}:{}),...(itemId>0?{items:{some:{itemId}}}:{}),...(status?{status}:{}),...(q?{OR:[{party:{nameAr:{contains:q}}},{party:{nameEn:{contains:q}}}]}:{})};
 const table=await runWithDataScope({tenantId:context.tenantId,companyId:context.companyId},async():Promise<ReportTable>=>{if(direction==="SALES"){const where:Prisma.SaleWhereInput={...common,...(from||to?{invoiceDate:{...(from?{gte:from}:{}),...(to?{lte:to}:{})}}:{})},rows=await prisma.sale.findMany({where,include:{party:true,items:{include:{item:true}}},orderBy:{invoiceDate:"asc"}});return{title:"تقرير فواتير المبيعات",subtitle:`${params.get("from")??"البداية"} — ${params.get("to")??"اليوم"}`,columns:["الفاتورة","التاريخ","العميل","المواد","قبل الضريبة","الخصم","VAT","الإجمالي","العملة","الحالة"],rows:rows.map(row=>[row.invoiceNumber,row.invoiceDate.toISOString().slice(0,10),row.party.nameAr,row.items.map(line=>line.item.nameAr).join("، "),Number(row.subtotal),Number(row.discount),Number(row.vatAmount),Number(row.totalAmount),row.currency,row.status])}}const where:Prisma.PurchaseWhereInput={...common,...(from||to?{purchaseDate:{...(from?{gte:from}:{}),...(to?{lte:to}:{})}}:{})},rows=await prisma.purchase.findMany({where,include:{party:true,items:{include:{item:true}}},orderBy:{purchaseDate:"asc"}});return{title:"تقرير فواتير المشتريات",subtitle:`${params.get("from")??"البداية"} — ${params.get("to")??"اليوم"}`,columns:["الفاتورة","فاتورة المورد","التاريخ","المورد","المواد","قبل الضريبة","الخصم","VAT","الإجمالي","العملة","الحالة"],rows:rows.map(row=>[row.purchaseNumber,row.supplierInvoiceNumber??"",row.purchaseDate.toISOString().slice(0,10),row.party.nameAr,row.items.map(line=>line.item.nameAr).join("، "),Number(row.subtotal),Number(row.discount),Number(row.vatAmount),Number(row.totalAmount),row.currency,row.status])}});
 const body=format==="pdf"?createPdf(table):createXlsx(table);return new Response(new Uint8Array(body),{headers:{"content-type":format==="pdf"?"application/pdf":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","content-disposition":`attachment; filename="${direction.toLowerCase()}-invoices.${format}"`,"cache-control":"no-store"}});
 }catch(error){return Response.json({error:error instanceof Error?error.message:"تعذر التصدير"},{status:403})}
}
