ALTER TABLE "FactoryTransaction" ADD COLUMN "vatRate" DECIMAL NOT NULL DEFAULT 15;
ALTER TABLE "FactoryTransaction" ADD COLUMN "vatAmount" DECIMAL NOT NULL DEFAULT 0;
ALTER TABLE "FactoryTransaction" ADD COLUMN "totalAmount" DECIMAL NOT NULL DEFAULT 0;
