"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Row = Record<string, unknown>;
type Widget = { id: number; widgetType: string; title: string; dataSource: string; width: number; height: number };
type Dashboard = { id: number; name: string; widgets: Widget[] };
const money = (value: unknown) => `${Number(value ?? 0).toLocaleString("en-US", { maximumFractionDigits: 2 })} ر.س`;
const get = (root: Row, path: string) => path.split(".").reduce<unknown>((value, key) => value && typeof value === "object" ? (value as Row)[key] : undefined, root);

export default function DashboardWorkspace() {
  const [dashboards, setDashboards] = useState<Dashboard[]>([]), [selected, setSelected] = useState(0), [analytics, setAnalytics] = useState<Row | null>(null), [message, setMessage] = useState("");
  const today = useMemo(() => new Date(), []), from = `${today.getFullYear()}-01-01`, to = today.toISOString().slice(0, 10);
  useEffect(() => { const controller = new AbortController(); Promise.all([fetch("/api/design/runtime", { signal: controller.signal }).then((response) => response.json()), fetch(`/api/analytics?from=${from}&to=${to}&inactiveDays=60`, { signal: controller.signal }).then((response) => response.json())]).then(([runtime, values]) => { if (runtime.error) throw new Error(runtime.error); if (values.error) throw new Error(values.error); setDashboards(runtime.dashboards ?? []); setSelected(runtime.dashboards?.[0]?.id ?? 0); setAnalytics(values); }).catch((error) => { if (error.name !== "AbortError") setMessage(error.message); }); return () => controller.abort(); }, [from, to]);
  const dashboard = dashboards.find((entry) => entry.id === selected) ?? dashboards[0];
  return <main className="min-h-screen bg-slate-100 p-5 md:p-8"><header className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-black">لوحات المعلومات المخصصة</h1><p className="text-slate-500">عناصر حقيقية من التحليلات التشغيلية والمالية حسب صلاحيات دورك.</p></div><div className="flex gap-2"><select className="rounded-xl border bg-white px-4 py-2" value={selected} onChange={(event) => setSelected(Number(event.target.value))}>{dashboards.map((entry) => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select><Link href="/settings/design" className="rounded-xl bg-slate-900 px-4 py-2 text-white">تخصيص</Link></div></header>{message && <div className="rounded-xl border border-red-200 bg-red-50 p-4">{message}</div>}{!dashboard ? <div className="rounded-2xl border bg-white p-16 text-center">لا توجد لوحة متاحة لدورك.</div> : !analytics ? <div className="rounded-2xl border bg-white p-16 text-center">جارٍ تحميل البيانات…</div> : <section className="grid grid-cols-1 gap-4 md:grid-cols-3">{dashboard.widgets.map((widget) => <WidgetCard key={widget.id} widget={widget} value={get(analytics, widget.dataSource)} />)}</section>}</main>;
}

function WidgetCard({ widget, value }: { widget: Widget; value: unknown }) {
  const width = widget.width === 3 ? "md:col-span-3" : widget.width === 2 ? "md:col-span-2" : "md:col-span-1";
  if (widget.widgetType === "KPI") return <article className={`${width} rounded-2xl border bg-white p-5`}><p className="text-sm text-slate-500">{widget.title}</p><b className={`mt-2 block text-3xl ${Number(value) < 0 ? "text-red-700" : "text-slate-900"}`}>{money(value)}</b></article>;
  if (widget.widgetType === "CHART" && Array.isArray(value)) { const maximum = Math.max(1, ...value.map((row) => Math.abs(Number((row as Row).netProfit ?? 0)))); return <article className={`${width} rounded-2xl border bg-white p-5`}><h2 className="font-bold">{widget.title}</h2><div className="mt-5 flex h-48 items-end gap-2 overflow-x-auto">{value.map((entry, index) => { const row = entry as Row, amount = Number(row.netProfit ?? 0); return <div key={index} className="flex min-w-10 flex-1 flex-col items-center justify-end"><div title={money(amount)} className={`w-full rounded-t ${amount < 0 ? "bg-red-500" : "bg-blue-600"}`} style={{ height: `${Math.max(4, Math.abs(amount) / maximum * 100)}%` }} /><small>{String(row.month ?? index + 1).slice(-2)}</small></div>; })}</div></article>; }
  if (widget.widgetType === "ALERT" && value && typeof value === "object") return <article className={`${width} rounded-2xl border bg-white p-5`}><h2 className="font-bold">{widget.title}</h2><div className="mt-3 space-y-2">{Object.entries(value as Row).map(([key, count]) => <div key={key} className="flex justify-between rounded-lg bg-amber-50 p-2"><span>{key}</span><b>{String(count)}</b></div>)}</div></article>;
  if (["TABLE", "LIST", "COMPARISON"].includes(widget.widgetType) && Array.isArray(value)) { const rows = value.slice(0, 10) as Row[], columns = rows[0] ? Object.keys(rows[0]).filter((key) => !key.startsWith("is") && key !== "href").slice(0, 5) : []; return <article className={`${width} rounded-2xl border bg-white p-5`}><h2 className="font-bold">{widget.title}</h2><div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><thead><tr>{columns.map((column) => <th className="p-2 text-right" key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr className="border-t" key={index}>{columns.map((column) => <td className="p-2" key={column}>{typeof row[column] === "number" ? Number(row[column]).toLocaleString("en-US") : String(row[column] ?? "—")}</td>)}</tr>)}</tbody></table></div></article>; }
  if (value && typeof value === "object") return <article className={`${width} rounded-2xl border bg-white p-5`}><h2 className="font-bold">{widget.title}</h2><pre className="mt-3 overflow-auto text-xs">{JSON.stringify(value, null, 2)}</pre></article>;
  return <article className={`${width} rounded-2xl border bg-white p-5`}><h2 className="font-bold">{widget.title}</h2><p>{String(value ?? "لا توجد بيانات")}</p></article>;
}
