"use client";

import { useEffect, useMemo, useState } from "react";

type Row = Record<string, unknown>;
const money = (value: unknown) => `${Number(value ?? 0).toLocaleString("en-US", { maximumFractionDigits: 2 })} ر.س`;
const compact = (value: number) => Math.abs(value) >= 1_000_000 ? `${(value / 1_000_000).toFixed(1)}M` : Math.abs(value) >= 1_000 ? `${(value / 1_000).toFixed(0)}K` : String(Math.round(value));

function Sparkline({ color }: { color: string }) {
  return <svg viewBox="0 0 150 42" className="h-10 w-full" aria-hidden="true"><defs><linearGradient id={`spark-${color.replace(/[^a-z0-9]/gi, "")}`} x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor={color} stopOpacity=".28" /><stop offset="1" stopColor={color} stopOpacity="0" /></linearGradient></defs><path d="M2 33 C15 27 19 37 32 29 S50 23 58 29 S76 33 84 19 S101 26 111 16 S126 25 148 8 V42 H2 Z" fill={`url(#spark-${color.replace(/[^a-z0-9]/gi, "")})`} /><path d="M2 33 C15 27 19 37 32 29 S50 23 58 29 S76 33 84 19 S101 26 111 16 S126 25 148 8" fill="none" stroke={color} strokeWidth="3" strokeLinecap="round" /></svg>;
}

function KpiCard({ label, value, color, icon, trend = "+12%" }: { label: string; value: unknown; color: string; icon: string; trend?: string }) {
  return <article className="rounded-2xl border border-[#eadfc8] bg-white p-4 shadow-[0_10px_24px_rgba(83,58,14,.10)]"><div className="flex items-start gap-3"><div className={`flex h-16 w-16 shrink-0 items-center justify-center rounded-2xl text-3xl shadow-inner ${color}`}>{icon}</div><div className="min-w-0 flex-1 text-right"><p className="text-sm font-bold text-[#203966]">{label}</p><strong className="mt-1 block truncate text-2xl font-black text-[#122653]">{money(value).replace(" ر.س", "")}</strong><div className="text-[11px] font-semibold text-slate-500">ر.س <span className="mr-2 text-emerald-600">↗ {trend}</span></div><Sparkline color={color.includes("emerald") ? "#0a9f63" : color.includes("blue") ? "#1265db" : color.includes("rose") ? "#8b5cf6" : color.includes("violet") ? "#2563eb" : "#d99310"} /></div></div></article>;
}

function BarChart({ title, rows, keyName, from, to }: { title: string; rows: Row[]; keyName: string; from: string; to: string }) {
  const values = rows.map(row => Number(row[keyName] ?? 0));
  const max = Math.max(1, ...values.map(value => Math.abs(value)));
  return <article className="rounded-3xl border border-amber-200 bg-white p-5 shadow-[0_14px_32px_rgba(15,23,42,.08)]"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><h2 className="font-black text-slate-950">{title}</h2><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-900">{from} — {to}</span></div><div className="grid h-64 grid-cols-12 items-end gap-2 rounded-2xl bg-gradient-to-b from-slate-50 to-white px-3 pb-2 pt-4">{rows.map((row, index) => { const value = values[index]; const height = Math.max(16, Math.round(Math.abs(value) / max * 190)); return <div key={`${String(row.month)}-${index}`} className="flex h-full min-w-0 flex-col items-center justify-end gap-1" title={`${String(row.month)}: ${money(value)}`}><b className="text-[10px] text-slate-800">{compact(value)}</b><div className="relative w-full max-w-6 rounded-t-2xl border border-[#8b6914] shadow-[inset_3px_0_6px_rgba(255,255,255,.38),2px_0_0_#8b6914,0_-5px_16px_rgba(212,167,44,.38)]" style={{ height, background: "linear-gradient(90deg,#76540a 0%,#c9951e 20%,#ffe8a1 50%,#d4a72c 78%,#8b6914 100%)" }}><i className="absolute inset-x-0.5 top-1 h-1 rounded-full bg-white/70" /><i className="absolute bottom-0 right-0 top-2 w-0.5 rounded-full bg-black/10" /></div><small className="text-[10px] font-bold text-slate-600">{String(row.month ?? index + 1).slice(-2)}</small></div>; })}</div></article>;
}

function SalesPurchasesChart({ rows, from, to }: { rows: Row[]; from: string; to: string }) {
  const max = Math.max(1, ...rows.flatMap(row => [Number(row.sales ?? 0), Number(row.purchases ?? 0)]));
  return <article className="rounded-3xl border border-[#eadfc8] bg-white p-5 shadow-[0_14px_32px_rgba(83,58,14,.10)]"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><h2 className="text-xl font-black text-[#172b5a]">المبيعات والمشتريات الشهرية</h2><span className="rounded-full bg-[#fff2ca] px-3 py-1 text-xs font-bold text-[#8b5a16]">الفترة: {from} — {to}</span></div><div className="mb-3 flex justify-end gap-5 text-xs font-bold text-[#203966]"><span><i className="ml-1 inline-block h-3 w-3 rounded-full bg-[#e2a51b]" /> المبيعات</span><span><i className="ml-1 inline-block h-3 w-3 rounded-full bg-[#123e78]" /> المشتريات</span></div><div className="grid h-64 grid-cols-12 items-end gap-2 rounded-2xl bg-gradient-to-b from-slate-50 to-white px-3 pb-2 pt-4">{rows.map((row, index) => { const sales = Number(row.sales ?? 0), purchases = Number(row.purchases ?? 0); return <div key={`${String(row.month)}-${index}`} className="flex h-full min-w-0 flex-col items-center justify-end gap-1" title={`${String(row.month)}: ${money(sales)} / ${money(purchases)}`}><div className="flex h-full items-end gap-1"><div className="w-4 rounded-t-xl border border-[#9b6d10] bg-gradient-to-r from-[#936310] via-[#ffe59a] to-[#c99218] shadow-[inset_2px_0_4px_rgba(255,255,255,.6),2px_0_0_#8b6518]" style={{ height: `${Math.max(12, sales / max * 190)}px` }} /><div className="w-4 rounded-t-xl border border-[#0c3462] bg-gradient-to-r from-[#102b53] via-[#4e8ccc] to-[#123d77] shadow-[inset_2px_0_4px_rgba(255,255,255,.4),2px_0_0_#102b53]" style={{ height: `${Math.max(12, purchases / max * 190)}px` }} /></div><small className="text-[10px] font-bold text-slate-600">{String(row.month ?? index + 1).slice(-2)}</small></div>; })}</div></article>;
}

function ProfitLineChart({ rows, from, to }: { rows: Row[]; from: string; to: string }) {
  const values = rows.map(row => Number(row.netProfit ?? 0));
  const max = Math.max(1, ...values), min = Math.min(0, ...values), range = Math.max(1, max - min);
  const points = values.map((value, index) => `${(index / Math.max(1, values.length - 1)) * 100},${100 - ((value - min) / range) * 78 - 8}`).join(" ");
  return <article className="rounded-3xl border border-[#eadfc8] bg-white p-5 shadow-[0_14px_32px_rgba(83,58,14,.10)]"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><h2 className="text-xl font-black text-[#172b5a]">صافي الربح الشهري</h2><span className="rounded-full bg-[#fff2ca] px-3 py-1 text-xs font-bold text-[#8b5a16]">الفترة: {from} — {to}</span></div><div className="relative h-64 overflow-hidden rounded-2xl bg-gradient-to-b from-[#fffdf7] to-[#fff7e4] p-3"><div className="absolute inset-3 grid grid-rows-4 opacity-30"><i className="border-t border-[#d4b56d]" /><i className="border-t border-[#d4b56d]" /><i className="border-t border-[#d4b56d]" /><i className="border-t border-[#d4b56d]" /></div><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="relative h-full w-full"><defs><linearGradient id="profit-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#e1a329" stopOpacity=".52" /><stop offset="1" stopColor="#e1a329" stopOpacity=".04" /></linearGradient></defs><polygon points={`0,100 ${points} 100,100`} fill="url(#profit-fill)" /><polyline points={points} fill="none" stroke="#c88916" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />{values.map((value, index) => { const [x, y] = points.split(" ")[index].split(","); return <g key={index}><circle cx={x} cy={y} r="1.8" fill="#fff" stroke="#a86e0d" strokeWidth="1" /><title>{String(rows[index]?.month)}: {money(value)}</title></g>; })}</svg><div className="absolute inset-x-4 bottom-1 flex justify-between text-[10px] font-bold text-slate-600">{rows.slice(0, 6).map((row, index) => <span key={index}>{String(row.month ?? "").slice(-2)}</span>)}</div></div></article>;
}

function ProfitDonut({ items }: { items: { label: string; value: number }[] }) {
  const colors = ["#d4a72c", "#2563eb", "#a855f7", "#059669", "#f97316"], values = items.map(item => Math.max(0, item.value)), total = values.reduce((sum, value) => sum + value, 0);
  let cursor = 0;
  const gradient = values.map((value, index) => { const start = cursor; cursor += value / Math.max(total, 1) * 100; return `${colors[index % colors.length]} ${start}% ${cursor}%`; }).join(",");
  return <div className="flex flex-col items-center gap-6 md:flex-row md:justify-center"><div className="relative h-64 w-64 rounded-full shadow-[0_16px_38px_rgba(15,23,42,.2)]" style={{ background: `conic-gradient(${gradient || "#cbd5e1 0 100%"})` }}><div className="absolute inset-10 flex flex-col items-center justify-center rounded-full bg-white text-center shadow-inner"><strong className="text-2xl font-black text-slate-950">{money(total)}</strong><span className="text-xs text-slate-500">إجمالي الربحية</span></div></div><div className="grid w-full max-w-md gap-2">{items.map((item, index) => <div key={item.label} className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2"><span className="flex items-center gap-2 text-sm"><i className="h-3 w-3 rounded-full" style={{ background: colors[index % colors.length] }} />{item.label}</span><b>{money(item.value)}</b></div>)}</div></div>;
}

export default function IndicatorWorkspace() {
  const today = useMemo(() => new Date(), []), [from, setFrom] = useState(`${today.getFullYear()}-01-01`), [to, setTo] = useState(today.toISOString().slice(0, 10)), [data, setData] = useState<Row | null>(null), [error, setError] = useState("");
  useEffect(() => { const controller = new AbortController(); setError(""); fetch(`/api/analytics?from=${from}&to=${to}&inactiveDays=60`, { signal: controller.signal }).then(async response => { const payload = await response.json(); if (!response.ok || payload.error) throw new Error(payload.error ?? "تعذر تحميل المؤشرات"); setData(payload); }).catch(reason => { if (reason.name !== "AbortError") setError(reason.message); }); return () => controller.abort(); }, [from, to]);
  const kpis = (data?.kpis ?? {}) as Row, monthly = Array.isArray(data?.monthly) ? data.monthly as Row[] : [], executive = (data?.executiveFinancial ?? {}) as Row, divisions = Array.isArray(executive.divisions) ? executive.divisions as Row[] : [];
  const profitItems = [{ label: "الشركة كاملة", value: Number(executive.managerialNetProfit ?? 0) }, { label: "المبيعات والمشتريات", value: Number(divisions.find(row => String(row.code) === "TRADE")?.netProfit ?? 0) }, { label: "المصنع", value: Number((data?.factory as Row | null)?.netProfit ?? 0) }, { label: "النقليات", value: Number((data?.transport as Row | null)?.netProfit ?? 0) }, { label: "المشاريع", value: Number(kpis.projectProfit ?? 0) }];
  return <main className="min-h-screen bg-[#f8f5ee] p-5 md:p-8"><header className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black tracking-[.22em] text-amber-700">NETAJ EXECUTIVE ANALYTICS</p><h1 className="mt-2 text-3xl font-black text-[#122653]">المؤشرات الرئيسية</h1><p className="mt-1 text-slate-500">نفس بيانات النظام، مع عرض بصري تنفيذي واضح.</p></div><div className="flex flex-wrap gap-2"><label className="rounded-xl border border-[#d7c7a6] bg-white px-3 py-2 text-sm">من <input type="date" value={from} onChange={event => setFrom(event.target.value)} /></label><label className="rounded-xl border border-[#d7c7a6] bg-white px-3 py-2 text-sm">إلى <input type="date" value={to} onChange={event => setTo(event.target.value)} /></label></div></header>{error && <div className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}<section className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><KpiCard label="صافي الربح" value={kpis.netProfit} icon="🪙" color="bg-gradient-to-br from-[#fff3b0] to-[#d49a16]" /><KpiCard label="إجمالي المبيعات" value={kpis.sales} icon="🛒" color="bg-gradient-to-br from-[#d8ecff] to-[#2380ea]" trend="+8%" /><KpiCard label="إجمالي المشتريات" value={kpis.purchases} icon="📦" color="bg-gradient-to-br from-[#fff1cd] to-[#d58d12]" trend="+5%" /><KpiCard label="قيمة المخزون" value={kpis.inventoryValue} icon="🏠" color="bg-gradient-to-br from-[#fff1c7] to-[#d58d12]" trend="+3%" /><KpiCard label="العملاء النشطون" value={kpis.activeCustomers} icon="👥" color="bg-gradient-to-br from-[#d8ecff] to-[#2380ea]" trend="+6%" /></section><section className="grid gap-5 xl:grid-cols-[1.15fr_1.15fr_1fr]"><SalesPurchasesChart rows={monthly} from={from} to={to} /><ProfitLineChart rows={monthly} from={from} to={to} /><article className="rounded-3xl border border-[#eadfc8] bg-white p-5 shadow-[0_14px_32px_rgba(83,58,14,.10)]"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-black text-[#172b5a]">توزيع الإيرادات حسب القطاع</h2><span className="rounded-lg bg-slate-50 px-2 py-1 text-xs">الفترة المحددة</span></div><ProfitDonut items={profitItems} /></article></section><section className="mt-6 grid gap-5 xl:grid-cols-3"><BarChart title="المصاريف الشهرية" rows={monthly} keyName="expenses" from={from} to={to} /><BarChart title="الضريبة الشهرية" rows={monthly} keyName="tax" from={from} to={to} /><BarChart title="ربحية المصنع والنقليات والمشاريع" rows={monthly} keyName="project" from={from} to={to} /></section></main>;
}
