"use client";

import { useEffect, useMemo, useState } from "react";

type Row = Record<string, unknown>;
const money = (value: unknown) => `${Number(value ?? 0).toLocaleString("en-US", { maximumFractionDigits: 2 })} ر.س`;
const compact = (value: number) => Math.abs(value) >= 1_000_000 ? `${(value / 1_000_000).toFixed(1)}M` : Math.abs(value) >= 1_000 ? `${(value / 1_000).toFixed(0)}K` : String(Math.round(value));

function KpiCard({ label, value, color }: { label: string; value: unknown; color: string }) {
  return <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-[0_10px_25px_rgba(15,23,42,.08)]"><div className={`mb-3 h-2 rounded-full ${color}`} /><p className="text-sm font-bold text-slate-500">{label}</p><strong className="mt-2 block text-2xl font-black text-slate-950">{money(value)}</strong><span className="mt-2 block text-xs text-emerald-600">● بيانات فعلية من النظام</span></article>;
}

function BarChart({ title, rows, keyName, from, to }: { title: string; rows: Row[]; keyName: string; from: string; to: string }) {
  const values = rows.map(row => Number(row[keyName] ?? 0));
  const max = Math.max(1, ...values.map(value => Math.abs(value)));
  return <article className="rounded-3xl border border-amber-200 bg-white p-5 shadow-[0_14px_32px_rgba(15,23,42,.08)]"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><h2 className="font-black text-slate-950">{title}</h2><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-900">{from} — {to}</span></div><div className="grid h-64 grid-cols-12 items-end gap-2 rounded-2xl bg-gradient-to-b from-slate-50 to-white px-3 pb-2 pt-4">{rows.map((row, index) => { const value = values[index]; const height = Math.max(16, Math.round(Math.abs(value) / max * 190)); return <div key={`${String(row.month)}-${index}`} className="flex h-full min-w-0 flex-col items-center justify-end gap-1" title={`${String(row.month)}: ${money(value)}`}><b className="text-[10px] text-slate-800">{compact(value)}</b><div className="relative w-full max-w-10 rounded-t-xl border border-[#8b6914] shadow-[inset_5px_0_8px_rgba(255,255,255,.35),4px_0_0_#8b6914,0_-5px_16px_rgba(212,167,44,.45)]" style={{ height, background: "linear-gradient(90deg,#8b6914 0%,#d4a72c 25%,#ffe7a0 52%,#d4a72c 78%,#9b7418 100%)" }}><i className="absolute inset-x-1 top-1 h-1 rounded-full bg-white/60" /></div><small className="text-[10px] font-bold text-slate-600">{String(row.month ?? index + 1).slice(-2)}</small></div>; })}</div></article>;
}

function ProfitDonut({ items }: { items: { label: string; value: number }[] }) {
  const colors = ["#d4a72c", "#2563eb", "#a855f7", "#059669", "#f97316"], values = items.map(item => Math.max(0, item.value)), total = values.reduce((sum, value) => sum + value, 0);
  let cursor = 0;
  const gradient = values.map((value, index) => { const start = cursor; cursor += value / Math.max(total, 1) * 100; return `${colors[index % colors.length]} ${start}% ${cursor}%`; }).join(",");
  return <div className="flex flex-col items-center gap-6 md:flex-row md:justify-center"><div className="relative h-64 w-64 rounded-full shadow-[0_16px_38px_rgba(15,23,42,.2)]" style={{ background: `conic-gradient(${gradient || "#cbd5e1 0 100%"})` }}><div className="absolute inset-10 flex flex-col items-center justify-center rounded-full bg-white text-center shadow-inner"><strong className="text-2xl font-black text-slate-950">{money(total)}</strong><span className="text-xs text-slate-500">إجمالي الربحية</span></div></div><div className="grid w-full max-w-md gap-2">{items.map((item, index) => <div key={item.label} className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2"><span className="flex items-center gap-2 text-sm"><i className="h-3 w-3 rounded-full" style={{ background: colors[index % colors.length] }} />{item.label}</span><b>{money(item.value)}</b></div>)}</div></div>;
}

export default function IndicatorWorkspace() {
  const today = useMemo(() => new Date(), []), [from, setFrom] = useState(`${today.getFullYear()}-01-01`), [to, setTo] = useState(today.toISOString().slice(0, 10)), [data, setData] = useState<Row | null>(null), [error, setError] = useState("");
  useEffect(() => { const controller = new AbortController(); setError(""); fetch(`/api/analytics?from=${from}&to=${to}&inactiveDays=60`, { signal: controller.signal }).then(async response => { const payload = await response.json(); if (!response.ok || payload.error) throw new Error(payload.error ?? "تعذر تحميل المؤشرات"); setData(payload); }).catch(reason => { if (reason.name !== "AbortError") setError(reason.message); }); return () => controller.abort(); }, [from, to]);
  const kpis = (data?.kpis ?? {}) as Row, monthly = Array.isArray(data?.monthly) ? data.monthly as Row[] : [], executive = (data?.executiveFinancial ?? {}) as Row, divisions = Array.isArray(executive.divisions) ? executive.divisions as Row[] : [];
  const profitItems = [{ label: "الشركة كاملة", value: Number(executive.managerialNetProfit ?? 0) }, { label: "المبيعات والمشتريات", value: Number(divisions.find(row => String(row.code) === "TRADE")?.netProfit ?? 0) }, { label: "المصنع", value: Number((data?.factory as Row | null)?.netProfit ?? 0) }, { label: "النقليات", value: Number((data?.transport as Row | null)?.netProfit ?? 0) }, { label: "المشاريع", value: Number(kpis.projectProfit ?? 0) }];
  return <main className="min-h-screen bg-[#f8f5ee] p-5 md:p-8"><header className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black tracking-[.22em] text-amber-700">NETAJ EXECUTIVE ANALYTICS</p><h1 className="mt-2 text-3xl font-black text-slate-950">المؤشرات الرئيسية</h1><p className="mt-1 text-slate-500">رسومات فعلية من المستندات والقيود والقوائم المالية.</p></div><div className="flex flex-wrap gap-2"><label className="rounded-xl border bg-white px-3 py-2 text-sm">من <input type="date" value={from} onChange={event => setFrom(event.target.value)} /></label><label className="rounded-xl border bg-white px-3 py-2 text-sm">إلى <input type="date" value={to} onChange={event => setTo(event.target.value)} /></label></div></header>{error && <div className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}<section className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><KpiCard label="إجمالي المبيعات" value={kpis.sales} color="bg-emerald-500" /><KpiCard label="إجمالي المشتريات" value={kpis.purchases} color="bg-rose-500" /><KpiCard label="صافي الربح" value={kpis.netProfit} color="bg-blue-500" /><KpiCard label="المصاريف" value={kpis.expenses} color="bg-amber-500" /><KpiCard label="السيولة البنكية" value={kpis.liquidity} color="bg-violet-500" /></section><section className="grid gap-5 xl:grid-cols-2"><BarChart title="المبيعات الشهرية" rows={monthly} keyName="sales" from={from} to={to} /><BarChart title="المشتريات الشهرية" rows={monthly} keyName="purchases" from={from} to={to} /><BarChart title="المصاريف الشهرية" rows={monthly} keyName="expenses" from={from} to={to} /><BarChart title="صافي الربح الشهري" rows={monthly} keyName="netProfit" from={from} to={to} /><BarChart title="الضريبة الشهرية" rows={monthly} keyName="tax" from={from} to={to} /><BarChart title="ربحية المصنع والنقليات والمشاريع" rows={monthly} keyName="project" from={from} to={to} /></section><section className="mt-6 rounded-3xl border border-amber-200 bg-white p-6 shadow-[0_14px_32px_rgba(15,23,42,.08)]"><h2 className="mb-6 text-xl font-black text-slate-950">ربحية الشركة والأقسام</h2><ProfitDonut items={profitItems} /></section></main>;
}
