"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";

type Account = { id: number; code: string; nameAr: string; nameEn: string | null; accountType: string; parentId: number | null; parentName: string | null; allowPosting: boolean; isActive: boolean; level: number; balance: number; balanceCurrency: string; normalBalance: string; currency: string; branchId: number | null; branchName: string; companyName: string; description: string };
type Data = { rows: Account[]; branches: { id: number; nameAr: string }[]; currencies: { code: string; nameAr: string }[]; company: { id: number; nameAr: string; currency: string } };
type Filters = { q: string; code: string; name: string; type: string; parentId: string; branchId: string; currency: string; status: string };
const emptyFilters: Filters = { q: "", code: "", name: "", type: "", parentId: "", branchId: "", currency: "", status: "" };
const types: Record<string, string> = { ASSET: "الأصول", LIABILITY: "الخصوم", EQUITY: "حقوق الملكية", REVENUE: "الإيرادات", EXPENSE: "المصروفات" };
const field = "w-full min-w-0 rounded-lg border bg-white px-3 py-2";
const gold = "rounded-lg border border-[#c9972b] bg-gradient-to-b from-[#ebcf87] to-[#c9972b] px-3 py-2 text-sm font-bold text-[#172033] disabled:opacity-50";
const number = (value: number) => value.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export default function AccountDirectoryPanel({ tree = false, onChanged }: { tree?: boolean; onChanged?: () => Promise<void> }) {
  const [data, setData] = useState<Data | null>(null), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const [filters, setFilters] = useState<Filters>(emptyFilters), [page, setPage] = useState(1), [size, setSize] = useState(10), [sort, setSort] = useState("code"), [descending, setDescending] = useState(false);
  const [selected, setSelected] = useState<Set<number>>(new Set()), [expanded, setExpanded] = useState<Set<number>>(new Set());
  const [editor, setEditor] = useState<Account | "new" | null>(null), [parentForNew, setParentForNew] = useState<Account | null>(null), [deleting, setDeleting] = useState<Account | null>(null);
  const [history, setHistory] = useState<{ account: Account; rows: { id: number; action: string; userId: string; createdAt: string }[] } | null>(null);
  const load = useCallback(async () => { const r = await fetch("/api/finance/accounts", { cache: "no-store" }); const body = await r.json(); if (!r.ok) throw new Error(body.error); setData(body); }, []);
  useEffect(() => { void load().catch(e => setMessage(e.message)); }, [load]);
  const rows = data?.rows ?? [];
  const filtered = useMemo(() => rows.filter(row => (!filters.q || `${row.code} ${row.nameAr} ${row.nameEn ?? ""}`.toLocaleLowerCase().includes(filters.q.toLocaleLowerCase())) && (!filters.code || row.code.includes(filters.code)) && (!filters.name || row.nameAr.includes(filters.name)) && (!filters.type || row.accountType === filters.type) && (!filters.parentId || String(row.parentId) === filters.parentId) && (!filters.branchId || String(row.branchId) === filters.branchId) && (!filters.currency || row.currency === filters.currency) && (!filters.status || row.isActive === (filters.status === "ACTIVE"))).sort((a,b) => (sort === "balance" ? a.balance-b.balance : String(a[sort as keyof Account]).localeCompare(String(b[sort as keyof Account]), "ar", { numeric: true })) * (descending ? -1 : 1)), [rows, filters, sort, descending]);
  const pages = Math.max(1, Math.ceil(filtered.length / size)), currentPage = Math.min(page, pages), current = filtered.slice((currentPage-1)*size, currentPage*size);
  function filter<K extends keyof Filters>(key: K, value: Filters[K]) { setFilters(old => ({ ...old, [key]: value })); setPage(1); setSelected(new Set()); }
  function toggle(id: number) { setSelected(old => { const next = new Set(old); if (next.has(id)) next.delete(id); else next.add(id); return next; }); }
  function exportUrl(format: string) { const params = new URLSearchParams({ ...filters, format }); if (selected.size) params.set("ids", [...selected].join(",")); return `/api/finance/accounts/export?${params}`; }
  async function mutate(method: string, body: Record<string, unknown>) {
    setBusy(true); setMessage("");
    try { const r = await fetch(`/api/finance/accounts${method === "DELETE" ? `?id=${body.id}` : ""}`, { method, headers: { "Content-Type": "application/json" }, ...(method !== "DELETE" ? { body: JSON.stringify(body) } : {}) }); const result = await r.json(); if (!r.ok) throw new Error(result.error); await load(); await onChanged?.(); setMessage(method === "DELETE" ? "تم حذف الحساب غير المستخدم وتسجيل العملية" : "تم حفظ الحساب وتسجيل التعديل"); setEditor(null); setDeleting(null); setSelected(new Set()); }
    catch (e) { setMessage(e instanceof Error ? e.message : "تعذر الحفظ"); } finally { setBusy(false); }
  }
  async function audit(account: Account) { try { const r = await fetch(`/api/finance/accounts?auditAccountId=${account.id}`); const rows = await r.json(); if (!r.ok) throw new Error(rows.error); setHistory({ account, rows }); } catch (e) { setMessage(String(e)); } }
  function actions(row: Account) { return <div className="flex flex-wrap gap-1"><button className={gold} onClick={() => { setMessage(""); setEditor(row); }}>تحرير</button><button className={gold} onClick={() => { setMessage(""); setDeleting(row); }}>حذف</button><Link className="rounded border px-2 py-1 text-xs" href={`/accounting?tab=reports&report=account-statement&accountId=${row.id}`}>كشف الحساب</Link><button className="rounded border px-2 py-1 text-xs" onClick={() => void audit(row)}>سجل التعديلات</button>{!row.allowPosting && <button className="rounded border px-2 py-1 text-xs" onClick={() => { setParentForNew(row); setEditor("new"); }}>إضافة فرعي</button>}</div>; }
  const visibleIds = new Set(filtered.map(row => row.id));
  if (tree) { const byId = new Map(rows.map(r => [r.id, r])); for (const row of filtered) { const seen = new Set<number>(); let parent = byId.get(row.parentId ?? -1); while (parent && !seen.has(parent.id)) { seen.add(parent.id); visibleIds.add(parent.id); parent = byId.get(parent.parentId ?? -1); } } }
  const searching = Object.values(filters).some(Boolean);
  function renderTree(row: Account, depth: number, ancestors = new Set<number>()): React.ReactNode {
    if (ancestors.has(row.id) || !visibleIds.has(row.id)) return null;
    const path = new Set([...ancestors, row.id]), children = rows.filter(child => child.parentId === row.id), open = searching || expanded.has(row.id);
    return <li key={row.id} role="treeitem" aria-expanded={children.length ? open : undefined} className="border-b last:border-b-0"><div className="flex flex-wrap items-center gap-3 py-3" style={{ paddingInlineStart: depth * 20 }}><button type="button" disabled={!children.length} aria-label={`${open ? "طي" : "توسيع"} ${row.nameAr}`} className="h-7 w-7 rounded border disabled:opacity-20" onClick={() => setExpanded(old => { const next = new Set(old); if (next.has(row.id)) next.delete(row.id); else next.add(row.id); return next; })}>{open ? "−" : "+"}</button><div className="min-w-48 flex-1"><b>{row.code} — {row.nameAr}</b><p className="text-xs text-slate-500">{row.nameEn || ""} · {types[row.accountType] ?? row.accountType} · المستوى {row.level} · {row.allowPosting ? "حساب حركة" : "حساب رئيسي"} · {row.normalBalance === "DEBIT" ? "مدين" : "دائن"} · {row.isActive ? "نشط" : "موقوف"}</p></div><span dir="ltr" className="text-sm">{number(row.balance)} {row.balanceCurrency}</span>{actions(row)}</div>{open && <ul role="group">{children.map(child => renderTree(child, depth+1, path))}</ul>}</li>;
  }
  return <section className="rounded-2xl border bg-white p-5" dir="rtl" aria-label={tree ? "شجرة الحسابات" : "الحسابات"}>
    <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">{tree ? "شجرة الحسابات" : "الحسابات"}</h2><p className="text-sm text-slate-500">{data?.company.nameAr} · {filtered.length} حسابًا · الأرصدة المرحلة بعملة {data?.company.currency}</p></div><button className={gold} onClick={() => { setMessage(""); setParentForNew(null); setEditor("new"); }}>+ إضافة حساب</button></div>
    {message && <p role="status" className="mb-3 rounded-lg border border-amber-200 bg-amber-50 p-3">{message}</p>}
    <div className="mb-4 grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-4"><input value={filters.q} onChange={e => filter("q", e.target.value)} className={field} placeholder="رقم الحساب أو اسم الحساب" aria-label="بحث الحسابات"/><select className={field} aria-label="نوع الحساب" value={filters.type} onChange={e => filter("type", e.target.value)}><option value="">كل الأنواع</option>{Object.entries(types).map(([v,t]) => <option key={v} value={v}>{t}</option>)}</select><select className={field} aria-label="الفرع" value={filters.branchId} onChange={e => filter("branchId", e.target.value)}><option value="">كل الفروع</option>{data?.branches.map(b => <option key={b.id} value={b.id}>{b.nameAr}</option>)}</select><select className={field} aria-label="العملة" value={filters.currency} onChange={e => filter("currency", e.target.value)}><option value="">كل العملات</option>{data?.currencies.map(c => <option key={c.code}>{c.code}</option>)}</select></div>
    <div className="mb-4 flex flex-wrap gap-2"><a className="rounded-lg border px-3 py-2" href={exportUrl("xlsx")}>Excel</a><a className="rounded-lg border px-3 py-2" href={exportUrl("pdf")}>PDF</a><a className="rounded-lg border px-3 py-2" href={`${exportUrl("pdf")}&inline=1`} target="_blank">طباعة</a><button className="rounded-lg border px-3 py-2" onClick={() => { localStorage.setItem(`netaj-accounts-filters:${data?.company.id}`, JSON.stringify(filters)); setMessage("تم حفظ الفلاتر على هذا الجهاز"); }}>حفظ الفلاتر</button><button className="rounded-lg border px-3 py-2" onClick={() => { try { const value = JSON.parse(localStorage.getItem(`netaj-accounts-filters:${data?.company.id}`) ?? "null"); if(value) { setFilters({ ...emptyFilters, ...value }); setPage(1); setSelected(new Set()); } } catch { setMessage("تعذر استعادة الفلاتر"); } }}>استعادة الفلاتر</button><button className="rounded-lg border px-3 py-2" onClick={() => { setFilters(emptyFilters); setPage(1); setSelected(new Set()); }}>مسح الفلاتر</button>{tree && <><button className={gold} onClick={() => setExpanded(new Set(rows.map(r => r.id)))}>توسيع الكل</button><button className={gold} onClick={() => setExpanded(new Set())}>طي الكل</button></>}</div>
    {!data ? <p>{message ? "" : "جارٍ تحميل الحسابات…"}</p> : tree ? <ul role="tree" aria-label="الهيكل المحاسبي">{rows.filter(r => !r.parentId || !rows.some(p => p.id === r.parentId)).map(row => renderTree(row,0))}</ul> : <>
      <div className="overflow-x-auto"><table className="account-directory-table w-full text-sm"><thead><tr><th className="p-2"><input type="checkbox" aria-label="تحديد الصفحة الحالية" checked={!!current.length && current.every(r => selected.has(r.id))} onChange={e => setSelected(old => { const next = new Set(old); current.forEach(r => e.target.checked ? next.add(r.id) : next.delete(r.id)); return next; })}/></th>{["رقم الحساب","اسم الحساب","الحساب الرئيسي","التصنيف / النوع","الرصيد الحالي","العملة / الفرع","الحالة","الإجراءات"].map(h => <th key={h} className="p-3 text-right">{h}</th>)}</tr><tr><th/><th className="p-2"><input className={field} aria-label="فلترة رقم الحساب" value={filters.code} onChange={e => filter("code",e.target.value)}/></th><th className="p-2"><input className={field} aria-label="فلترة اسم الحساب" value={filters.name} onChange={e => filter("name",e.target.value)}/></th><th className="p-2"><select className={field} aria-label="فلترة الحساب الرئيسي" value={filters.parentId} onChange={e => filter("parentId",e.target.value)}><option value="">كل الحسابات</option>{rows.filter(r => !r.allowPosting).map(r => <option key={r.id} value={r.id}>{r.code} — {r.nameAr}</option>)}</select></th><th/><th/><th/><th className="p-2"><select className={field} aria-label="فلترة الحالة" value={filters.status} onChange={e => filter("status",e.target.value)}><option value="">كل الحالات</option><option value="ACTIVE">نشط</option><option value="INACTIVE">موقوف</option></select></th><th/></tr></thead><tbody>{current.map(row => <tr key={row.id} className="border-b"><td className="p-2"><input type="checkbox" aria-label={`تحديد ${row.code}`} checked={selected.has(row.id)} onChange={() => toggle(row.id)}/></td><td className="p-3 font-bold">{row.code}</td><td className="p-3">{row.nameAr}<small className="block text-slate-500">{row.nameEn}</small></td><td className="p-3">{row.parentName ?? "—"}</td><td className="p-3">{types[row.accountType] ?? row.accountType}<small className="block">{row.allowPosting ? "حساب حركة" : "حساب رئيسي"} · {row.normalBalance === "DEBIT" ? "مدين" : "دائن"}</small></td><td className="p-3"><Link href={`/accounting?tab=reports&report=account-statement&accountId=${row.id}`}><span dir="ltr">{number(row.balance)} {row.balanceCurrency}</span></Link></td><td className="p-3">{row.currency}<small className="block">{row.branchName}</small></td><td className="p-3">{row.isActive ? "نشط" : "موقوف"}</td><td className="p-3">{actions(row)}</td></tr>)}</tbody></table></div>
      <div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-sm"><span>{filtered.length} حسابًا · المحدد {selected.size}</span><div className="flex gap-2"><select className={field} aria-label="عدد الصفوف" value={size} onChange={e => {setSize(Number(e.target.value));setPage(1);}}>{[10,25,50,100].map(n => <option key={n}>{n}</option>)}</select><select className={field} aria-label="ترتيب الحسابات" value={sort} onChange={e => setSort(e.target.value)}><option value="code">رقم الحساب</option><option value="nameAr">اسم الحساب</option><option value="balance">الرصيد</option></select><button className="rounded border px-3" onClick={() => setDescending(!descending)}>{descending ? "تنازلي" : "تصاعدي"}</button></div><div className="flex items-center gap-2"><button disabled={currentPage <= 1} onClick={() => setPage(currentPage-1)} className="rounded border px-3 py-2 disabled:opacity-40">السابق</button><span>{currentPage} / {pages}</span><button disabled={currentPage >= pages} onClick={() => setPage(currentPage+1)} className="rounded border px-3 py-2 disabled:opacity-40">التالي</button></div></div>
    </>}
    {data && !filtered.length && <p className="p-5 text-center">لا توجد حسابات مطابقة.</p>}
    {editor && data && <AccountEditor key={editor === "new" ? `new-${parentForNew?.id ?? "root"}` : editor.id} data={data} account={editor === "new" ? null : editor} parent={parentForNew} busy={busy} message={message} close={() => setEditor(null)} save={body => mutate(editor === "new" ? "POST" : "PATCH",body)}/>}
    {deleting && <Modal title={`حذف الحساب ${deleting.code}`} close={() => !busy && setDeleting(null)}><p>سيتم حذف الحساب فقط إذا لم يكن له فروع أو حركات أو روابط محاسبية.</p>{message && <p role="alert">{message}</p>}<div className="mt-4 flex gap-2"><button disabled={busy} className={gold} onClick={() => void mutate("DELETE",{id:deleting.id})}>تأكيد الحذف</button><button disabled={busy} className="rounded border px-3" onClick={() => setDeleting(null)}>إلغاء</button></div></Modal>}
    {history && <Modal title={`سجل تعديلات ${history.account.code}`} close={() => setHistory(null)}>{!history.rows.length ? <p>لا توجد تعديلات مسجلة لهذا الحساب.</p> : history.rows.map(r => <p key={r.id} className="border-b py-2">{r.action === "ACCOUNT_CREATE" ? "إنشاء" : r.action === "ACCOUNT_UPDATE" ? "تعديل" : r.action} · المستخدم {r.userId} · {new Date(r.createdAt).toLocaleString("ar-SA")}</p>)}</Modal>}
  </section>;
}

function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}) {
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{ const dialog=ref.current; dialog?.showModal(); return()=>dialog?.close(); },[]);
  return <dialog ref={ref} onCancel={e=>{e.preventDefault();close();}} aria-label={title} className="finance-workspace w-[min(760px,92vw)] rounded-2xl border p-6 shadow-xl" dir="rtl"><div className="mb-5 flex items-center justify-between border-b pb-3"><h2 className="text-xl font-bold">{title}</h2><button type="button" aria-label="إغلاق النافذة" className="rounded border px-3 py-1" onClick={close}>×</button></div>{children}</dialog>;
}
function AccountEditor({data,account,parent,busy,message,close,save}:{data:Data;account:Account|null;parent:Account|null;busy:boolean;message:string;close:()=>void;save:(body:Record<string,unknown>)=>Promise<void>}) {
  const [form,setForm]=useState({code:account?.code??"",nameAr:account?.nameAr??"",nameEn:account?.nameEn??"",accountType:account?.accountType??parent?.accountType??"ASSET",parentId:String(account?.parentId??parent?.id??""),allowPosting:account?.allowPosting??true,isActive:account?.isActive??true,currency:account?.currency??data.company.currency,branchId:String(account?.branchId??""),normalBalance:account?.normalBalance??(["ASSET","EXPENSE"].includes(parent?.accountType??"ASSET")?"DEBIT":"CREDIT"),description:account?.description??""});
  const descendants=new Set<number>(); if(account){ descendants.add(account.id); let changed=true; while(changed){changed=false;for(const row of data.rows)if(row.parentId&&descendants.has(row.parentId)&&!descendants.has(row.id)){descendants.add(row.id);changed=true;}} }
  async function submit(e:FormEvent){e.preventDefault();await save({...form,...(account?{id:account.id}:{})});}
  return <Modal title={account?"تحرير حساب":"إضافة حساب"} close={()=>!busy&&close()}><form onSubmit={submit} className="space-y-4">{message&&<p role="alert" className="rounded border border-amber-200 p-3">{message}</p>}<div className="grid gap-3 sm:grid-cols-2">{([["nameAr","اسم الحساب"],["nameEn","الاسم بالإنجليزية"],["code","رقم الحساب"]] as const).map(([key,label])=><label key={key} className="text-sm">{label}<input className={field} required={key!=="nameEn"} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>التصنيف<select className={field} value={form.accountType} onChange={e=>setForm({...form,accountType:e.target.value,parentId:"",normalBalance:["ASSET","EXPENSE"].includes(e.target.value)?"DEBIT":"CREDIT"})}>{Object.entries(types).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><label>الحساب الرئيسي<select className={field} value={form.parentId} onChange={e=>setForm({...form,parentId:e.target.value})}><option value="">بدون حساب رئيسي</option>{data.rows.filter(r=>!r.allowPosting&&r.isActive&&r.accountType===form.accountType&&!descendants.has(r.id)).map(r=><option key={r.id} value={r.id}>{r.code} — {r.nameAr}</option>)}</select></label><label>نوع الحساب<select className={field} value={form.allowPosting?"POSTING":"GROUP"} onChange={e=>setForm({...form,allowPosting:e.target.value==="POSTING"})}><option value="POSTING">حساب حركة — يسمح بالقيود</option><option value="GROUP">حساب رئيسي — يمنع القيود المباشرة</option></select></label><label>طبيعة الحساب<select className={field} value={form.normalBalance} onChange={e=>setForm({...form,normalBalance:e.target.value})}><option value="DEBIT">مدين</option><option value="CREDIT">دائن</option></select></label><label>الفرع<select className={field} value={form.branchId} onChange={e=>setForm({...form,branchId:e.target.value})}><option value="">كل الفروع</option>{data.branches.map(b=><option key={b.id} value={b.id}>{b.nameAr}</option>)}</select></label><label>العملة<select className={field} value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}>{data.currencies.map(c=><option key={c.code} value={c.code}>{c.code} — {c.nameAr}</option>)}</select></label><label>الحالة<select className={field} value={form.isActive?"ACTIVE":"INACTIVE"} onChange={e=>setForm({...form,isActive:e.target.value==="ACTIVE"})}><option value="ACTIVE">نشط</option><option value="INACTIVE">موقوف</option></select></label></div><label className="block">الوصف<textarea className={field} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><p className="text-sm text-slate-500">الشركة: {data.company.nameAr}. الرصيد يُحتسب من القيود المرحلة.</p><div className="flex gap-2"><button disabled={busy} className={gold}>{busy?"جارٍ الحفظ…":"حفظ الحساب"}</button><button type="button" disabled={busy} className="rounded border px-4 py-2" onClick={close}>إلغاء</button></div></form></Modal>;
}
