"use client";

import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
type Book = { id: number; code: string; bankAccountId: number; issueDate: string; firstNumber: number; lastNumber: number; total: number; reserved: number; used: number; cancelled: number; remaining: number; status: string; createdBy: string };
type Cheque = { id: number; internalNumber: string; chequeNumber: string; direction: string; bankAccountId: number; partyId: number; counterAccountId: number; suspenseAccountId: number; issueDate: string; dueDate: string; amount: string; currency: string; status: string; description: string; referenceNumber: string | null; draweeBank: string; draweeAccount: string; createdBy: string; approvedBy: string | null; cancellationReason: string | null };
type Workspace = { books: Book[]; cheques: Cheque[]; banks: { id: number; name: string; currency: string; bankName: string | null; accountNumber: string | null; isActive: boolean }[]; parties: { id: number; nameAr: string }[]; accounts: { id: number; code: string; nameAr: string; accountType: string }[]; branches: { id: number; nameAr: string }[]; journals: { id: number; entryNumber: string; referenceId: number; referenceType: string; status: string; totalDebit: string; totalCredit: string }[] };
const states: Record<string, string> = { DRAFT: "مسودة", ISSUED: "صادر", RECEIVED: "مستلم", DEPOSITED: "تحت التحصيل", CLEARED: "تم الصرف / التحصيل", RETURNED: "مرتجع", CANCELLED: "ملغي", STOPPED: "موقوف" };
const actionNames: Record<string, string> = { ISSUE: "اعتماد وإثبات الشيك", CLEAR: "إثبات الصرف / التحصيل", RETURN: "تسجيل ارتجاع وعكس القيود", CANCEL: "إلغاء الشيك", STOP: "إيقاف الشيك", RESUME: "استئناف الشيك", DEPOSIT: "إيداع للتحصيل" };
const button = "rounded-xl border border-[#c39843] bg-gradient-to-l from-[#b78a35] to-[#efd68c] px-3 py-2 text-sm font-bold text-[#182238] disabled:opacity-40";
const field = "mt-1 w-full rounded-xl border border-[#e3d8c5] bg-white px-3 py-2 text-sm";
const date = (value: string) => new Date(value).toLocaleDateString("ar-SA", { calendar: "gregory" });
const money = (value: unknown) => Number(value).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export default function ChequesPanel({ mode }: { mode: "books" | "paid" | "received" }) {
  const isBooks = mode === "books", paid = mode === "paid", direction = paid ? "PAID" : "RECEIVED";
  const title = isBooks ? "إدارة دفاتر الشيكات" : paid ? "الشيكات المدفوعة" : "الشيكات المستلمة";
  const [data, setData] = useState<Workspace | null>(null), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const [busy, setBusy] = useState(false), [q, setQ] = useState(""), [status, setStatus] = useState(""), [page, setPage] = useState(1);
  const [bankId, setBankId] = useState(""), [selectedId, setSelectedId] = useState<number | null>(null), [formError, setFormError] = useState("");
  const [pending, setPending] = useState<{ row: Cheque; action: string } | null>(null);
  const createDialog = useRef<HTMLDialogElement>(null), actionDialog = useRef<HTMLDialogElement>(null);
  const load = useCallback(async () => {
    const response = await fetch(`/api/finance/cheques${isBooks ? "" : `?direction=${direction}`}`, { cache: "no-store" }), result = await response.json();
    if (!response.ok) throw new Error(result.error || "تعذر تحميل الشيكات"); setData(result);
  }, [direction, isBooks]);
  useEffect(() => { load().catch(value => setError(value.message)); }, [load]);
  const bank = (id: number) => data?.banks.find(row => row.id === id)?.name ?? String(id);
  const party = (id: number) => data?.parties.find(row => row.id === id)?.nameAr ?? String(id);
  const visibleCheques = data?.cheques.filter(row => (!q || `${row.chequeNumber} ${row.internalNumber} ${party(row.partyId)}`.includes(q)) && (!status || row.status === status)) ?? [];
  const visibleBooks = data?.books.filter(row => !q || `${row.code} ${bank(row.bankAccountId)}`.includes(q)) ?? [];
  const selected = data?.cheques.find(row => row.id === selectedId);
  const pages = Math.max(1, Math.ceil((isBooks ? visibleBooks.length : visibleCheques.length) / 25));
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = event.currentTarget; setBusy(true); setFormError("");
    try {
      const body = { ...Object.fromEntries(new FormData(form)), kind: isBooks ? "BOOK" : "CHEQUE", direction };
      const response = await fetch("/api/finance/cheques", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
      const result = await response.json(); if (!response.ok) throw new Error(result.error);
      createDialog.current?.close(); form.reset(); setBankId("");
      setNotice(isBooks ? "تم إنشاء دفتر الشيكات وتسجيل نطاق أرقامه." : "تم حفظ مسودة الشيك وحجز رقمه. اعتمده لإثباته محاسبيًا."); await load();
    } catch (value) { setFormError(value instanceof Error ? value.message : "تعذر الحفظ"); }
    finally { setBusy(false); }
  }
  function ask(row: Cheque, action: string) { setPending({ row, action }); setFormError(""); actionDialog.current?.showModal(); }
  async function applyAction(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!pending) return; setBusy(true); setFormError("");
    try {
      const body = { ...Object.fromEntries(new FormData(event.currentTarget)), action: pending.action };
      const response = await fetch(`/api/finance/cheques/${pending.row.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
      const result = await response.json(); if (!response.ok) throw new Error(result.error);
      actionDialog.current?.close(); setNotice(`تم ${actionNames[pending.action]} — ${pending.row.chequeNumber}`); setPending(null); await load();
    } catch (value) { setFormError(value instanceof Error ? value.message : "تعذر تنفيذ الإجراء"); }
    finally { setBusy(false); }
  }
  async function toggleBook(book: Book) {
    setBusy(true); setError("");
    try {
      const response = await fetch(`/api/finance/cheques/${book.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind: "BOOK", action: book.status === "ACTIVE" ? "PAUSE" : "ACTIVATE" }) });
      if (!response.ok) throw new Error((await response.json()).error); await load();
    } catch (value) { setError(value instanceof Error ? value.message : "تعذر تحديث الدفتر"); }
    finally { setBusy(false); }
  }
  async function exportFile(format: "xlsx" | "pdf") {
    const endpoint = `/api/finance/cheques/export?${new URLSearchParams({ format, kind: isBooks ? "BOOK" : "CHEQUE", direction, q, status })}`;
    if (format === "pdf") { window.open(endpoint, "_blank", "noopener,noreferrer"); return; }
    setBusy(true); setError("");
    try {
      const response = await fetch(endpoint);
      if (!response.ok) throw new Error((await response.json()).error);
      const url = URL.createObjectURL(await response.blob()), anchor = document.createElement("a"); anchor.href = url; anchor.download = `netaj-cheques.${format}`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
    } catch (value) { setError(value instanceof Error ? value.message : "تعذر التصدير"); }
    finally { setBusy(false); }
  }
  const actionsFor = (row: Cheque) => row.status === "DRAFT" ? ["ISSUE", "CANCEL"] : row.status === "STOPPED" ? ["RESUME", "CANCEL", "RETURN"] : row.status === "CLEARED" ? ["RETURN"] : ["CANCELLED", "RETURNED"].includes(row.status) ? [] : ["CLEAR", ...(row.direction === "PAID" ? ["STOP"] : row.status === "RECEIVED" ? ["DEPOSIT"] : []), "RETURN", "CANCEL"];
  return <section className="space-y-5 rounded-2xl border bg-white p-5" dir="rtl"><header className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-bold">{title}</h2><p className="mt-1 text-sm text-slate-500">{isBooks ? "أرقام دفاتر فعلية، استخدام الأوراق وإيقاف الإصدار." : "إثبات الشيك في حساب الأوراق عند الاعتماد؛ يتأثر البنك عند الصرف أو التحصيل."}</p></div><button className={button} disabled={!data || busy} onClick={() => { setFormError(""); createDialog.current?.showModal(); }}>+ {isBooks ? "دفتر شيكات" : paid ? "شيك صادر" : "شيك مستلم"}</button></header>
    {error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-red-800">{error}</p>}{notice && <p role="status" className="rounded-lg bg-emerald-50 p-3 text-emerald-800">{notice}</p>}
    <div className="flex flex-wrap items-end gap-3"><label className="min-w-48 flex-1">بحث<input className={field} value={q} onChange={event => { setQ(event.target.value); setPage(1); }} placeholder={isBooks ? "رقم الدفتر أو البنك" : "رقم الشيك أو الطرف"}/></label>{!isBooks && <label>الحالة<select className={field} value={status} onChange={event => { setStatus(event.target.value); setPage(1); }}><option value="">كل الحالات</option>{Object.entries(states).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>}<button className={button} disabled={busy || !data} onClick={() => exportFile("xlsx")}>Excel</button><button className={button} disabled={busy || !data} onClick={() => exportFile("pdf")}>PDF / طباعة</button><button className={button} disabled={busy} onClick={() => { setError(""); load().catch(value => setError(value.message)); }}>تحديث</button></div>
    <div className="overflow-x-auto">{isBooks ? <table className="w-full text-right text-sm"><thead className="bg-slate-100"><tr>{["الدفتر / البنك", "الأرقام", "الإجمالي", "المستخدم", "محجوز لمسودة", "الملغي", "المتبقي", "الحالة", "الإجراء"].map(label => <th className="p-3" key={label}>{label}</th>)}</tr></thead><tbody>{visibleBooks.slice((page - 1) * 25, page * 25).map(book => <tr key={book.id} className="border-b"><td className="p-3"><b>{book.code}</b><p>{bank(book.bankAccountId)}</p><small>{date(book.issueDate)} · {book.createdBy}</small></td><td className="p-3">{book.firstNumber} — {book.lastNumber}</td>{[book.total, book.used, book.reserved, book.cancelled, book.remaining].map((n, index) => <td className="p-3" key={index}>{n}</td>)}<td className="p-3">{book.status === "ACTIVE" ? "نشط" : "موقوف"}{book.remaining <= 5 && <p className="text-xs text-amber-800">{book.remaining ? "قارب الدفتر على الانتهاء" : "نفدت الأوراق"}</p>}</td><td className="p-3"><button className={button} disabled={busy} onClick={() => toggleBook(book)}>{book.status === "ACTIVE" ? "إيقاف الإصدار" : "تفعيل الإصدار"}</button></td></tr>)}</tbody></table> : <table className="w-full text-right text-sm"><thead className="bg-slate-100"><tr>{["الشيك", "الطرف", "الحساب البنكي", "التاريخ / الاستحقاق", "المبلغ", "الحالة", "الإجراءات"].map(label => <th className="p-3" key={label}>{label}</th>)}</tr></thead><tbody>{visibleCheques.slice((page - 1) * 25, page * 25).map(row => <tr key={row.id} className="border-b"><td className="p-3"><button className="font-bold text-[#a87923]" onClick={() => setSelectedId(row.id)}>{row.chequeNumber}</button><p className="text-xs">{row.internalNumber}</p></td><td className="p-3">{party(row.partyId)}</td><td className="p-3">{bank(row.bankAccountId)}</td><td className="p-3 whitespace-nowrap">{date(row.issueDate)}<p>{date(row.dueDate)}</p>{["ISSUED", "RECEIVED", "DEPOSITED"].includes(row.status) && new Date(row.dueDate) <= new Date() && <span className="text-amber-800">مستحق</span>}</td><td className="p-3 whitespace-nowrap">{money(row.amount)} {row.currency}</td><td className="p-3">{states[row.status]}</td><td className="p-3"><div className="flex min-w-48 flex-wrap gap-2"><button className={button} onClick={() => setSelectedId(row.id)}>التفاصيل والقيود</button>{actionsFor(row).map(action => <button className={button} disabled={busy} key={action} onClick={() => ask(row, action)}>{actionNames[action]}</button>)}</div></td></tr>)}</tbody></table>}
      {!(isBooks ? visibleBooks.length : visibleCheques.length) && <p className="p-6 text-center text-slate-500">{data ? "لا توجد سجلات مطابقة." : error ? "تعذر تحميل البيانات." : "جارٍ التحميل…"}</p>}
    </div><div className="flex justify-between gap-3 text-sm"><span>{isBooks ? visibleBooks.length : visibleCheques.length} سجل</span><div className="flex gap-2"><button className={button} disabled={page <= 1} onClick={() => setPage(n => n - 1)}>السابق</button><span>{page} / {pages}</span><button className={button} disabled={page >= pages} onClick={() => setPage(n => n + 1)}>التالي</button></div></div>
    {selected && <div className="space-y-3 rounded-xl border p-4"><div className="flex justify-between"><h3 className="font-bold">الشيك {selected.chequeNumber} — {selected.internalNumber}</h3><button className={button} onClick={() => setSelectedId(null)}>إغلاق التفاصيل</button></div><p>{selected.description}</p><p>المرجع: {selected.referenceNumber || "—"} · أنشأه: {selected.createdBy} · اعتمده: {selected.approvedBy || "—"}</p>{selected.direction === "RECEIVED" && <p>البنك المسحوب عليه: {selected.draweeBank} · الحساب: {selected.draweeAccount}</p>}{selected.cancellationReason && <p>سبب الإلغاء / الارتجاع: {selected.cancellationReason}</p>}<table className="w-full text-sm"><thead><tr><th className="p-2">القيد</th><th className="p-2">العملية</th><th className="p-2">الحالة</th><th className="p-2">مدين</th><th className="p-2">دائن</th></tr></thead><tbody>{data?.journals.filter(journal => journal.referenceId === selected.id).map(journal => <tr key={journal.id} className="border-t"><td className="p-2">{journal.entryNumber}</td><td className="p-2">{{ CHEQUE_ISSUE: "إصدار / استلام", CHEQUE_CLEAR: "صرف / تحصيل", CHEQUE_ISSUE_REVERSAL: "عكس الإصدار / الاستلام", CHEQUE_CLEAR_REVERSAL: "عكس الصرف / التحصيل" }[journal.referenceType]}</td><td className="p-2">{journal.status === "REVERSED" ? "معكوس" : "مرحل"}</td><td className="p-2">{money(journal.totalDebit)}</td><td className="p-2">{money(journal.totalCredit)}</td></tr>)}</tbody></table></div>}
    <dialog ref={createDialog} aria-labelledby="cheque-create-title" dir="rtl" className="w-[min(780px,calc(100vw-32px))] max-h-[90vh] overflow-y-auto rounded-2xl border border-[#c39843] bg-[#fffdf8] p-6 text-[#182238]"><form onSubmit={save} className="space-y-4"><div className="flex justify-between"><h3 id="cheque-create-title" className="text-xl font-bold">{isBooks ? "إضافة دفتر شيكات" : paid ? "إضافة شيك صادر" : "إضافة شيك مستلم"}</h3><button type="button" disabled={busy} className={button} onClick={() => createDialog.current?.close()}>إغلاق</button></div>{formError && <p role="alert" className="bg-red-50 p-3 text-red-800">{formError}</p>}<div className="grid gap-3 sm:grid-cols-2"><label>{paid || isBooks ? "الحساب البنكي المصدر" : "حساب الإيداع البنكي"}<select className={field} name="bankAccountId" value={bankId} onChange={event => setBankId(event.target.value)} required><option value="">اختر البنك</option>{data?.banks.filter(row => row.isActive).map(row => <option key={row.id} value={row.id}>{row.name} — {row.currency}</option>)}</select></label><label>{isBooks ? "تاريخ إصدار الدفتر" : "تاريخ الشيك / الاستلام"}<input className={field} name="issueDate" type="date" required defaultValue={new Date().toISOString().slice(0, 10)}/></label>{isBooks ? <><label>أول رقم شيك<input className={field} name="firstNumber" type="number" min="1" step="1" required/></label><label>آخر رقم شيك<input className={field} name="lastNumber" type="number" min="1" step="1" required/></label></> : <>
      {paid && <label>دفتر الشيكات<select className={field} name="chequeBookId" required><option value="">اختر الدفتر</option>{data?.books.filter(book => book.bankAccountId === Number(bankId) && book.status === "ACTIVE" && book.remaining > 0).map(book => <option key={book.id} value={book.id}>{book.code} — متبقي {book.remaining}</option>)}</select></label>}<label>رقم الشيك<input className={field} name="chequeNumber" required={!paid} placeholder={paid ? "تلقائي: أول ورقة متاحة" : "رقم الشيك"}/></label>{!paid && <><label>البنك المسحوب عليه<input className={field} name="draweeBank" required/></label><label>رقم الحساب المسحوب عليه<input className={field} name="draweeAccount" required/></label></>}<label>{paid ? "المستفيد" : "العميل / الطرف"}<select className={field} name="partyId" required><option value="">اختر الطرف</option>{data?.parties.map(row => <option key={row.id} value={row.id}>{row.nameAr}</option>)}</select></label><label>المبلغ ({data?.banks.find(row => row.id === Number(bankId))?.currency || "عملة البنك"})<input className={field} name="amount" type="number" min="0.01" step="0.01" required/></label><label>تاريخ الاستحقاق<input className={field} name="dueDate" type="date" required defaultValue={new Date().toISOString().slice(0, 10)}/></label><label>حساب الطرف المحاسبي<select className={field} name="counterAccountId" required><option value="">اختر الحساب</option>{data?.accounts.map(account => <option key={account.id} value={account.id}>{account.code} — {account.nameAr}</option>)}</select></label><label>{paid ? "حساب أوراق الدفع — خصوم" : "حساب أوراق القبض — أصول"}<select className={field} name="suspenseAccountId" required><option value="">اختر حساب الأوراق</option>{data?.accounts.filter(account => account.accountType === (paid ? "LIABILITY" : "ASSET")).map(account => <option key={account.id} value={account.id}>{account.code} — {account.nameAr}</option>)}</select></label><label>الفرع<select className={field} name="branchId"><option value="">كل الفروع</option>{data?.branches.map(branch => <option key={branch.id} value={branch.id}>{branch.nameAr}</option>)}</select></label><label>المرجع<input className={field} name="referenceNumber"/></label><label className="sm:col-span-2">البيان<input className={field} name="description" required/></label></>}</div><button className={button} disabled={busy}>{isBooks ? "حفظ الدفتر" : "حفظ مسودة الشيك"}</button></form></dialog>
    <dialog ref={actionDialog} aria-labelledby="cheque-action-title" dir="rtl" className="w-[min(580px,calc(100vw-32px))] rounded-2xl border border-[#c39843] bg-[#fffdf8] p-6 text-[#182238]"><form onSubmit={applyAction} className="space-y-4"><h3 id="cheque-action-title" className="text-xl font-bold">{pending && actionNames[pending.action]}</h3>{pending && <p>الشيك {pending.row.chequeNumber} — {party(pending.row.partyId)} — {money(pending.row.amount)} {pending.row.currency}</p>}{formError && <p role="alert" className="bg-red-50 p-3 text-red-800">{formError}</p>}{pending?.action === "CLEAR" && <label className="block">تاريخ الصرف / التحصيل<input className={field} name="date" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required/></label>}{pending && ["CANCEL", "RETURN"].includes(pending.action) && <label className="block">السبب<textarea className={field} name="reason" required/></label>}<div className="flex gap-3"><button className={button} disabled={busy}>تأكيد التنفيذ</button><button type="button" className={button} disabled={busy} onClick={() => actionDialog.current?.close()}>رجوع</button></div></form></dialog>
  </section>;
}
