"use client";

import { Fragment, useCallback, useEffect, useState, type FormEvent } from "react";
import { createPortal } from "react-dom";

type Depreciation = { id: number; periodDate: string; amount: string; accumulatedAfter: string; bookValueAfter: string; journalEntryId: number | null };
type Asset = { id: number; assetNumber: string; name: string; status: string; acquisitionDate: string; acquisitionCost: string; residualValue: string; accumulatedDepreciation: string; costCenterId: number | null; category: { name: string; usefulLifeMonths: number; depreciationMethod: string; depreciationExpenseAccountId: number | null; accumulatedDepreciationAccountId: number | null }; depreciations: Depreciation[] };
type Entry = { entryNumber: string; entryDate: string; description: string; totalDebit: string; totalCredit: string; lines: { id: number; accountCode: string; accountName: string; debit: string; credit: string }[] };
const field = "w-full rounded-xl border border-[#e4d7bf] bg-white px-3 py-2.5 text-sm outline-none focus:border-[#bd913f]";
const button = "rounded-xl border border-[#cba454] bg-gradient-to-l from-[#b98d38] to-[#ebce83] px-4 py-2.5 text-sm font-bold text-slate-900 disabled:opacity-50";
const secondary = "rounded-xl border border-[#dfd2ba] bg-white px-4 py-2.5 text-sm text-slate-800 disabled:opacity-50";
const money = (value: number | string) => Number(value).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export default function DepreciationPanel() {
  const [assets, setAssets] = useState<Asset[]>([]), [currency, setCurrency] = useState("");
  const [loading, setLoading] = useState(true), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const [query, setQuery] = useState(""), [year, setYear] = useState(new Date().getFullYear()), [page, setPage] = useState(1);
  const [selected, setSelected] = useState<Asset | null>(null), [entry, setEntry] = useState<Entry | null>(null);
  const load = useCallback(async () => {
    const response = await fetch("/api/assets?view=depreciation", { cache: "no-store" }), body = await response.json();
    if (!response.ok) throw new Error(body.error ?? "تعذر تحميل سجل الأصول");
    setAssets(body.assets); setCurrency(body.company?.baseCurrencyCode ?? "");
  }, []);
  useEffect(() => { load().catch(error => setMessage(error.message)).finally(() => setLoading(false)); }, [load]);
  useEffect(() => { setPage(1); }, [query]);
  useEffect(() => { if (!selected && !entry) return; const close = (event: KeyboardEvent) => { if (event.key === "Escape" && !busy) { setSelected(null); setEntry(null); } }; document.addEventListener("keydown", close); return () => document.removeEventListener("keydown", close); }, [selected, entry, busy]);
  async function depreciate(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!selected || busy) return; const periodDate = new FormData(event.currentTarget).get("periodDate"); setBusy(true); setMessage("");
    try { const response = await fetch("/api/assets", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "DEPRECIATE", id: selected.id, periodDate }) }), body = await response.json(); if (!response.ok) throw new Error(body.error); await load(); setSelected(null); setMessage(`تم ترحيل إهلاك ${money(body.amount)} ${currency} وتحديث مجمع الإهلاك والقيمة الدفترية`); }
    catch (error) { setMessage(error instanceof Error ? error.message : "تعذر ترحيل الإهلاك"); }
    finally { setBusy(false); }
  }
  async function openJournal(id: number) {
    try { const response = await fetch(`/api/finance/cost-centers?entryId=${id}`, { cache: "no-store" }), body = await response.json(); if (!response.ok) throw new Error(body.error); setEntry(body); }
    catch (error) { setMessage(error instanceof Error ? error.message : "تعذر فتح القيد"); }
  }
  const visible = assets.filter(row => !query || `${row.assetNumber} ${row.name} ${row.category.name}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  const pages = Math.max(1, Math.ceil(visible.length / 20)), currentPage = Math.min(page, pages);
  const modal = selected || entry ? createPortal(<div style={{ position: "fixed", inset: 0, zIndex: 10000, display: "flex", alignItems: "center", justifyContent: "center", padding: 20, background: "rgba(15,23,42,.48)" }}><section role="dialog" aria-modal="true" aria-labelledby="depreciation-dialog-title" dir="rtl" className="w-full max-w-2xl overflow-auto rounded-3xl border border-[#dccba8] bg-[#fffdf8] p-6 shadow-2xl" style={{ maxHeight: "90dvh" }}>
    <header className="mb-5 flex items-center justify-between border-b border-[#e5d8c0] pb-4"><h2 id="depreciation-dialog-title" className="text-xl font-bold">{entry ? `القيد ${entry.entryNumber}` : "احتساب وترحيل إهلاك شهر"}</h2><button aria-label="إغلاق" disabled={busy} className={secondary} onClick={() => { setSelected(null); setEntry(null); }}>×</button></header>
    {message && <p role="status" className="mb-4 rounded-xl bg-amber-50 p-3 text-sm">{message}</p>}
    {selected && <form onSubmit={depreciate} className="space-y-4"><p className="font-bold">{selected.assetNumber} — {selected.name}</p><p>القسط الشهري المتوقع: {money(Math.max(0, Math.min((Number(selected.acquisitionCost) - Number(selected.residualValue)) / selected.category.usefulLifeMonths, Number(selected.acquisitionCost) - Number(selected.residualValue) - Number(selected.accumulatedDepreciation))))} {currency}</p><label className="block">تاريخ ترحيل إهلاك الشهر<input name="periodDate" required type="date" defaultValue={new Date().toISOString().slice(0, 10)} min={selected.acquisitionDate.slice(0, 10)} className={field}/></label><p className="text-sm text-slate-600">يُنشأ قيد مدين لمصروف الإهلاك ودائن لمجمع الإهلاك. يُسمح بقسط واحد لكل أصل في الشهر، ضمن فترة محاسبية مفتوحة.</p><div className="flex gap-3"><button disabled={busy} className={button}>{busy ? "جارٍ الترحيل…" : "احتساب وترحيل القيد"}</button><button type="button" disabled={busy} className={secondary} onClick={() => setSelected(null)}>إلغاء</button></div></form>}
    {entry && <><p className="mb-4">{entry.entryDate.slice(0, 10)} · {entry.description}</p><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#f1e8d7]"><tr>{["الحساب", "الاسم", "مدين", "دائن"].map(label => <th key={label} className="p-3 text-right">{label}</th>)}</tr></thead><tbody>{entry.lines.map(row => <tr key={row.id} className="border-b"><td className="p-3">{row.accountCode}</td><td>{row.accountName}</td><td>{money(row.debit)}</td><td>{money(row.credit)}</td></tr>)}</tbody><tfoot><tr><th colSpan={2} className="p-3 text-right">الإجمالي</th><th>{money(entry.totalDebit)}</th><th>{money(entry.totalCredit)}</th></tr></tfoot></table></div></>}
  </section></div>, document.body) : null;
  if (loading) return <p role="status" className="p-6">جارٍ تحميل إهلاكات الأصول…</p>;
  return <section dir="rtl" className="space-y-5 rounded-3xl border border-[#e3d4b8] bg-white p-5 md:p-6"><header><h2 className="text-xl font-bold">إهلاكات الأصول</h2><p className="mt-1 text-sm text-slate-500">الأصول المسجلة وأقساط الإهلاك المرحلة · {currency}</p></header>{message && <p role="status" className="rounded-xl bg-amber-50 p-3">{message}</p>}<div className="flex flex-wrap items-end gap-3"><label className="min-w-60 flex-1">بحث الأصل<input value={query} onChange={event => setQuery(event.target.value)} placeholder="رقم أو اسم الأصل" className={field}/></label><label>سنة العرض<input type="number" min={1900} max={9999} value={year} onChange={event => setYear(Number(event.target.value))} className={field}/></label><a className={secondary} href={`/api/assets?view=depreciation&format=xlsx&q=${encodeURIComponent(query)}`}>Excel</a><a className={secondary} target="_blank" rel="noreferrer" href={`/api/assets?view=depreciation&format=print&q=${encodeURIComponent(query)}`}>طباعة / حفظ PDF</a><button className={secondary} onClick={() => load().catch(error => setMessage(error.message))}>تحديث</button></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-sm"><thead className="bg-[#f1e8d7]"><tr>{["الأصل", "تاريخ الاقتناء", "التكلفة", "التخريد", "الطريقة / العمر", "إهلاك سنوات سابقة", "إهلاك السنة", "مجمع الإهلاك", "القيمة الدفترية", "الإجراء"].map(label => <th key={label} className="p-3 text-right">{label}</th>)}</tr></thead><tbody>{visible.slice((currentPage - 1) * 20, currentPage * 20).map(asset => {
      const previous = asset.depreciations.filter(row => new Date(row.periodDate).getUTCFullYear() < year).reduce((sum, row) => sum + Number(row.amount), 0);
      const current = asset.depreciations.filter(row => new Date(row.periodDate).getUTCFullYear() === year).reduce((sum, row) => sum + Number(row.amount), 0);
      const remaining = Number(asset.acquisitionCost) - Number(asset.residualValue) - Number(asset.accumulatedDepreciation);
      const configured = !!asset.category.depreciationExpenseAccountId && !!asset.category.accumulatedDepreciationAccountId;
      return <Fragment key={asset.id}><tr className="border-b border-[#eee5d7]"><td className="p-3"><strong>{asset.assetNumber}</strong><br/>{asset.name}</td><td className="p-3 whitespace-nowrap">{asset.acquisitionDate.slice(0, 10)}</td><td>{money(asset.acquisitionCost)}</td><td>{money(asset.residualValue)}</td><td>{asset.category.depreciationMethod === "STRAIGHT_LINE" ? "القسط الثابت" : asset.category.depreciationMethod}<br/>{asset.category.usefulLifeMonths} شهرًا</td><td>{money(previous)}</td><td>{money(current)}</td><td>{money(asset.accumulatedDepreciation)}</td><td>{money(Number(asset.acquisitionCost) - Number(asset.accumulatedDepreciation))}</td><td className="p-3"><button disabled={busy || asset.status !== "ACTIVE" || remaining <= 0 || !configured} className={button} onClick={() => { setMessage(""); setSelected(asset); }}>إهلاك شهر</button>{!configured && <small className="block text-amber-800">حسابات الإهلاك غير مهيأة</small>}{remaining <= 0 && <small className="block text-slate-500">مكتمل الإهلاك</small>}</td></tr><tr className="border-b border-[#eee5d7]"><td colSpan={10} className="px-3 py-2"><details><summary className="cursor-pointer text-[#997126]">سجل الإهلاك ({asset.depreciations.length})</summary>{asset.depreciations.length ? <table className="mt-2 w-full"><thead><tr>{["الفترة", "القسط", "المتراكم", "القيمة الدفترية", "القيد"].map(label => <th key={label} className="p-2 text-right">{label}</th>)}</tr></thead><tbody>{asset.depreciations.map(row => <tr key={row.id}><td className="p-2">{row.periodDate.slice(0, 7)}</td><td>{money(row.amount)}</td><td>{money(row.accumulatedAfter)}</td><td>{money(row.bookValueAfter)}</td><td>{row.journalEntryId ? <button className="text-[#997126] underline" onClick={() => openJournal(row.journalEntryId!)}>فتح القيد #{row.journalEntryId}</button> : "غير مرتبط بقيد"}</td></tr>)}</tbody></table> : <p className="py-3 text-slate-500">لم تسجل أقساط إهلاك لهذا الأصل.</p>}</details></td></tr></Fragment>;
    })}</tbody></table></div>{!visible.length && <p className="py-5 text-center text-slate-500">لا توجد أصول مسجلة تطابق البحث.</p>}<footer className="flex items-center justify-between text-sm"><span>{visible.length} أصلًا · الصفحة {currentPage} من {pages}</span><div className="flex gap-2"><button className={secondary} disabled={currentPage === 1} onClick={() => setPage(currentPage - 1)}>السابق</button><button className={secondary} disabled={currentPage === pages} onClick={() => setPage(currentPage + 1)}>التالي</button></div></footer>{modal}</section>;
}
