"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { createPortal } from "react-dom";

type Balance = { key: string; itemId: number; itemCode: string; itemName: string; categoryName: string; unit: string; ownership: string; partyId: number | null; partyName: string; openingQuantity: number; incoming: number; outgoing: number; closingQuantity: number; openingValue: number; incomingValue: number; outgoingValue: number; closingValue: number; movementCount: number; currentQuantity: number | null; currentAverageCost: number | null; currentStockValue: number | null; quantityDifference: number | null };
type Movement = { id: number; movementNumber: string; date: string; itemCode: string; itemName: string; partyName: string; movementType: string; incoming: number; outgoing: number; unitCost: number; value: number; balance: number; closingValue: number; referenceType: string | null; referenceNumber: string | null; referenceId: number | null; notes: string | null };
type Result = { rows: Balance[]; movements: Movement[]; currentView: boolean; asOf: string; granularity: string; company: { legalNameAr: string; baseCurrencyCode: string } | null; totals: { itemAccounts: number; closingValue: number; partyValue: number; currentStockValue: number | null; unmatchedAccounts: number; quantitiesByUnit: { unit: string; quantity: number }[] }; options: { items: { id: number; code: string; nameAr: string }[]; parties: { id: number; nameAr: string }[]; categories: { id: number; nameAr: string }[] } };
const api = "/api/finance/inventory-balances";
const field = "w-full rounded-xl border border-[#e4d7bf] bg-white px-3 py-2.5 text-sm outline-none focus:border-[#bd913f]";
const button = "rounded-xl border border-[#cba454] bg-gradient-to-l from-[#b98d38] to-[#ebce83] px-4 py-2.5 text-sm font-bold text-slate-900 disabled:opacity-50";
const secondary = "rounded-xl border border-[#dfd2ba] bg-white px-4 py-2.5 text-sm text-slate-800 disabled:opacity-50";
const number = (value: number | null, decimals = 2) => value == null ? "—" : value.toLocaleString("en-US", { minimumFractionDigits: decimals, maximumFractionDigits: Math.max(decimals, 4) });
const movementNames: Record<string, string> = { OPENING: "رصيد افتتاحي", RECEIPT: "استلام", DELIVERY: "تسليم", PURCHASE: "مشتريات", SALE: "مبيعات", TRANSFER_IN: "تحويل وارد", TRANSFER_OUT: "تحويل صادر", PROCESSING_IN: "إنتاج وارد", PROCESSING_OUT: "تصنيع صادر", ADJUSTMENT: "تسوية", MAINTENANCE: "صرف صيانة" };

export default function InventoryBalancesPanel() {
  const [data, setData] = useState<Result | null>(null), [loading, setLoading] = useState(true), [message, setMessage] = useState("");
  const [filters, setFilters] = useState({ q: "", itemId: "", categoryId: "", ownership: "COMPANY", partyId: "", from: "", to: "", showZero: false });
  const [appliedParams, setAppliedParams] = useState("ownership=COMPANY"), [page, setPage] = useState(1);
  const [card, setCard] = useState<{ row: Balance; movements: Movement[]; params: string } | null>(null), [cardBusy, setCardBusy] = useState(false);
  const load = useCallback(async (params: string) => {
    setLoading(true); setMessage("");
    try { const response = await fetch(`${api}?${params}`, { cache: "no-store" }), body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body); setAppliedParams(params); setPage(1); }
    catch (error) { setMessage(error instanceof Error ? error.message : "تعذر تحميل أرصدة الأصناف"); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { void load("ownership=COMPANY"); }, [load]);
  useEffect(() => { if (!card) return; const close = (event: KeyboardEvent) => { if (event.key === "Escape") setCard(null); }; document.addEventListener("keydown", close); return () => document.removeEventListener("keydown", close); }, [card]);
  function apply(event: FormEvent) { event.preventDefault(); const params = new URLSearchParams(); for (const [key, value] of Object.entries(filters)) if (value !== "" && value !== false) params.set(key, String(value)); void load(params.toString()); }
  async function openCard(row: Balance) {
    setCardBusy(true); setMessage(""); const params = new URLSearchParams(appliedParams); params.set("view", "movements"); params.set("itemId", String(row.itemId)); params.set("ownership", row.ownership); params.set("showZero", "true"); if (row.partyId) params.set("partyId", String(row.partyId)); else params.delete("partyId");
    try { const response = await fetch(`${api}?${params}`, { cache: "no-store" }), body = await response.json(); if (!response.ok) throw new Error(body.error); setCard({ row, movements: body.movements, params: params.toString() }); }
    catch (error) { setMessage(error instanceof Error ? error.message : "تعذر تحميل بطاقة الحركة"); }
    finally { setCardBusy(false); }
  }
  const count = data?.rows.length ?? 0, pages = Math.max(1, Math.ceil(count / 25)), currentPage = Math.min(page, pages);
  const modal = card ? createPortal(<div style={{ position: "fixed", inset: 0, zIndex: 10000, display: "flex", alignItems: "center", justifyContent: "center", padding: 20, background: "rgba(15,23,42,.48)" }}><section dir="rtl" role="dialog" aria-modal="true" aria-labelledby="inventory-card-title" className="w-full max-w-6xl overflow-auto rounded-3xl border border-[#dccba8] bg-[#fffdf8] p-6 shadow-2xl" style={{ maxHeight: "90dvh" }}><header className="mb-5 flex items-center justify-between border-b border-[#e5d8c0] pb-4"><div><h2 id="inventory-card-title" className="text-xl font-bold">بطاقة حركة {card.row.itemCode} — {card.row.itemName}</h2><p className="mt-1 text-sm text-slate-500">{card.row.partyName} · {card.row.unit} · رصيد أول الفترة: {number(card.row.openingQuantity, 0)}</p></div><button aria-label="إغلاق بطاقة الحركة" className={secondary} onClick={() => setCard(null)}>×</button></header><div className="mb-4 flex gap-3"><a className={secondary} href={`${api}?${card.params}&format=xlsx`}>Excel</a><a className={secondary} target="_blank" rel="noreferrer" href={`${api}?${card.params}&format=print`}>طباعة / حفظ PDF</a></div><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-sm"><thead className="bg-[#f1e8d7]"><tr>{["التاريخ", "رقم الحركة", "النوع", "وارد", "منصرف", "الرصيد", "تكلفة الوحدة المسجلة", "قيمة الحركة", "المستند المصدر"].map(label => <th key={label} className="p-3 text-right">{label}</th>)}</tr></thead><tbody>{card.movements.map(row => <tr key={row.id} className="border-b border-[#eee5d7]"><td className="p-3 whitespace-nowrap">{row.date}</td><td className="p-3"><details><summary className="cursor-pointer text-[#997126] underline">{row.movementNumber}</summary><div className="mt-2 max-w-xs whitespace-normal rounded-xl bg-[#f4eddf] p-3">رقم الحركة الداخلي: {row.id}<br/>الصنف: {row.itemCode}<br/>الطرف: {row.partyName}<br/>نوع المستند: {row.referenceType ?? "—"}<br/>رقم المستند: {row.referenceNumber ?? "—"}<br/>معرّف المصدر: {row.referenceId ?? "—"}<br/>البيان: {row.notes ?? "—"}<br/>قيمة الرصيد حسب الحركات: {number(row.closingValue)}</div></details></td><td className="p-3">{movementNames[row.movementType] ?? row.movementType}</td><td dir="ltr">{number(row.incoming, 0)}</td><td dir="ltr">{number(row.outgoing, 0)}</td><td dir="ltr">{number(row.balance, 0)}</td><td dir="ltr">{number(row.unitCost)}</td><td dir="ltr">{number(row.value)}</td><td className="p-3">{row.referenceNumber ?? "—"}</td></tr>)}</tbody></table></div>{!card.movements.length && <p className="py-5 text-center text-slate-500">لا توجد حركات للصنف ضمن الفترة المحددة.</p>}</section></div>, document.body) : null;
  return <section dir="rtl" className="space-y-5 rounded-3xl border border-[#e3d4b8] bg-white p-5 md:p-6"><header><h2 className="text-xl font-bold">أرصدة الأصناف</h2><p className="mt-1 text-sm text-slate-500">{data?.company?.legalNameAr ?? ""} · {data?.currentView ? "العرض الحالي ومطابقته مع سجل الحركات" : `أرصدة تاريخية حتى ${data?.asOf.slice(0, 10) ?? "…"}`}</p></header>{message && <p role="alert" className="rounded-xl bg-amber-50 p-3">{message}</p>}
    <form onSubmit={apply} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label>بحث<input value={filters.q} onChange={event => setFilters({ ...filters, q: event.target.value })} placeholder="رقم أو اسم الصنف" className={field}/></label><label>الصنف<select value={filters.itemId} onChange={event => setFilters({ ...filters, itemId: event.target.value })} className={field}><option value="">كل الأصناف</option>{data?.options.items.map(row => <option key={row.id} value={row.id}>{row.code} — {row.nameAr}</option>)}</select></label><label>التصنيف<select value={filters.categoryId} onChange={event => setFilters({ ...filters, categoryId: event.target.value })} className={field}><option value="">كل التصنيفات</option>{data?.options.categories.map(row => <option key={row.id} value={row.id}>{row.nameAr}</option>)}</select></label><label>ملكية المخزون<select value={filters.ownership} onChange={event => setFilters({ ...filters, ownership: event.target.value, partyId: "" })} className={field}><option value="COMPANY">مخزون الشركة</option><option value="PARTY">مخزون الأطراف</option><option value="ALL">كل الملكيات</option></select></label><label>الطرف<select disabled={filters.ownership === "COMPANY"} value={filters.partyId} onChange={event => setFilters({ ...filters, partyId: event.target.value })} className={field}><option value="">كل الأطراف</option>{data?.options.parties.map(row => <option key={row.id} value={row.id}>{row.nameAr}</option>)}</select></label><label>من تاريخ<input value={filters.from} onChange={event => setFilters({ ...filters, from: event.target.value })} type="date" className={field}/></label><label>حتى تاريخ (اتركه فارغًا للحالي)<input value={filters.to} onChange={event => setFilters({ ...filters, to: event.target.value })} type="date" className={field}/></label><label className="flex items-center gap-2"><input type="checkbox" checked={filters.showZero} onChange={event => setFilters({ ...filters, showZero: event.target.checked })}/>إظهار الأرصدة الصفرية</label><div className="flex flex-wrap gap-2 sm:col-span-2 lg:col-span-4"><button disabled={loading} className={button}>{loading ? "جارٍ التحميل…" : "عرض الأرصدة"}</button><a className={secondary} href={`${api}?${appliedParams}&format=xlsx`}>Excel</a><a className={secondary} target="_blank" rel="noreferrer" href={`${api}?${appliedParams}&format=print`}>طباعة / حفظ PDF</a></div></form>
    {data && <><p className="text-sm text-slate-500">{data.granularity}</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><div className="rounded-2xl bg-[#f4eddf] p-4"><p className="text-sm">قيمة مخزون الشركة حسب الحركات</p><strong dir="ltr" className="mt-2 block text-xl">{number(data.totals.closingValue)} {data.company?.baseCurrencyCode}</strong></div><div className="rounded-2xl bg-[#f4eddf] p-4"><p className="text-sm">قيمة مخزون الأطراف المسجلة (ملكية الغير)</p><strong dir="ltr" className="mt-2 block text-xl">{number(data.totals.partyValue)} {data.company?.baseCurrencyCode}</strong></div><div className="rounded-2xl bg-[#f4eddf] p-4"><p className="text-sm">الأرصدة حسب الوحدة</p>{data.totals.quantitiesByUnit.map(row => <strong key={row.unit} className="mt-1 block">{number(row.quantity, 0)} {row.unit}</strong>)}</div></div>{data.totals.unmatchedAccounts > 0 && <p role="status" className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm">توجد {data.totals.unmatchedAccounts} أرصدة حالية تختلف عن مجموع الحركات. راجع الأرصدة الافتتاحية أو الحركات غير المسجلة؛ يعرض الجدول القيمتين للمطابقة.</p>}
    <div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-sm"><thead className="bg-[#f1e8d7]"><tr>{["الصنف", "التصنيف / الوحدة", "الملكية", "رصيد أول المدة", "الوارد", "المنصرف", "الرصيد حسب الحركات", "القيمة حسب الحركات", ...(data.currentView ? ["الرصيد الحالي", "متوسط التكلفة الحالي", "القيمة الحالية"] : []), "التفاصيل"].map(label => <th key={label} className="p-3 text-right">{label}</th>)}</tr></thead><tbody>{data.rows.slice((currentPage - 1) * 25, currentPage * 25).map(row => <tr key={row.key} className="border-b border-[#eee5d7]"><td className="p-3"><strong>{row.itemCode}</strong><br/>{row.itemName}</td><td className="p-3">{row.categoryName}<br/>{row.unit}</td><td className="p-3">{row.partyName}</td><td className="p-3" dir="ltr">{number(row.openingQuantity, 0)}</td><td className="p-3" dir="ltr">{number(row.incoming, 0)}</td><td className="p-3" dir="ltr">{number(row.outgoing, 0)}</td><td className="p-3" dir="ltr">{number(row.closingQuantity, 0)}</td><td className="p-3" dir="ltr">{number(row.closingValue)}</td>{data.currentView && <><td className={`p-3 ${row.quantityDifference ? "text-amber-800" : ""}`} dir="ltr">{number(row.currentQuantity, 0)}</td><td className="p-3" dir="ltr">{number(row.currentAverageCost)}</td><td className="p-3" dir="ltr">{number(row.currentStockValue)}</td></>}<td className="p-3"><button disabled={cardBusy} className={button} onClick={() => openCard(row)}>بطاقة الحركة</button></td></tr>)}</tbody></table></div>{!count && !loading && <p className="py-5 text-center text-slate-500">لا توجد أرصدة تطابق الفلاتر.</p>}<footer className="flex items-center justify-between text-sm"><span>{count} رصيدًا · الصفحة {currentPage} من {pages}</span><div className="flex gap-2"><button className={secondary} disabled={currentPage === 1} onClick={() => setPage(currentPage - 1)}>السابق</button><button className={secondary} disabled={currentPage === pages} onClick={() => setPage(currentPage + 1)}>التالي</button></div></footer></>}{modal}</section>;
}
