"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
type Row = Record<string, unknown>;
type Line = { accountId: string; description: string; debit: string; credit: string; costCenterId: string; projectCode: string };
const field = "w-full min-w-0 rounded-xl border border-[#e4d7be] bg-white px-3 py-2.5 text-sm";
const button = "rounded-xl border border-[#c9972b] bg-gradient-to-b from-[#ebcf87] to-[#c9972b] px-4 py-2 text-sm font-bold disabled:opacity-50";
const blank = (): Line => ({ accountId: "", description: "", debit: "", credit: "", costCenterId: "", projectCode: "" });
const amount = (v: unknown) => Number(v ?? 0).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const states: Record<string, string> = { DRAFT: "مسودة", APPROVED: "معتمد", POSTED: "مرحل", REVERSED: "معكوس", CANCELLED: "ملغي" };

export default function JournalWorkspace() {
  const [data, setData] = useState<{ journals: Row[]; accounts: Row[]; costCenters: Row[]; branches: Row[]; currency: string } | null>(null);
  const [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  const [q, setQ] = useState(""), [status, setStatus] = useState(""), [source, setSource] = useState(""), [from, setFrom] = useState(""), [to, setTo] = useState(""), [branch, setBranch] = useState("");
  const [page, setPage] = useState(1), [id, setId] = useState<number | null>(null), [lines, setLines] = useState<Line[]>([blank(), blank()]);
  const [draft, setDraft] = useState({ entryDate: "", description: "", referenceNumber: "", branchId: "" });
  const [detail, setDetail] = useState<{ journal: Row; audit: Row[]; attachments: Row[] } | null>(null);
  const editor = useRef<HTMLDialogElement>(null), viewer = useRef<HTMLDialogElement>(null);
  async function load() { const r = await fetch("/api/finance/journals", { cache: "no-store" }), j = await r.json(); if (!r.ok) throw new Error(j.error); setData(j); }
  useEffect(() => { void load().catch(e => setMessage(e.message)); }, []);
  const openedSource = useRef(false);
  useEffect(() => { if (!data || openedSource.current) return; const id = new URLSearchParams(window.location.search).get("journalId"); if (id) { openedSource.current = true; const row = data.journals.find(j => String(j.id) === id); if (row) void show(row); else setMessage("القيد المطلوب غير موجود في الشركة الحالية"); } }, [data]);
  useEffect(() => { setPage(1); }, [q, status, source, from, to, branch]);
  function edit(row?: Row) {
    setId(row ? Number(row.id) : null); setMessage("");
    setDraft({ entryDate: row ? String(row.entryDate).slice(0, 10) : new Date().toISOString().slice(0, 10), description: String(row?.description ?? ""), referenceNumber: String(row?.referenceNumber ?? ""), branchId: String(row?.branchId ?? "") });
    setLines(row ? (row.lines as Row[]).map(l => ({ accountId: String(l.accountId ?? ""), description: String(l.description ?? ""), debit: Number(l.debit) ? String(l.debit) : "", credit: Number(l.credit) ? String(l.credit) : "", costCenterId: String(l.costCenterId ?? ""), projectCode: String(l.projectCode ?? "") })) : [blank(), blank()]);
    editor.current?.showModal();
  }
  async function action(action: string, journalId?: unknown, extra: Row = {}) {
    setBusy(true); setMessage("");
    try {
      const r = await fetch("/api/finance/journals", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...extra, action, id: journalId }) }), j = await r.json();
      if (!r.ok) throw new Error(j.error);
      await load(); setMessage(action === "COPY" ? "تم إنشاء نسخة كمسودة بلا أثر مالي" : "تم حفظ العملية وسجل التدقيق");
      if (action === "SAVE") editor.current?.close();
      if (action === "COPY") edit(j);
    } catch (e) { setMessage(e instanceof Error ? e.message : "تعذر تنفيذ العملية"); } finally { setBusy(false); }
  }
  async function show(row: Row) {
    setBusy(true);
    try { const r = await fetch(`/api/finance/journals?id=${row.id}`), j = await r.json(); if (!r.ok) throw new Error(j.error); setDetail(j); viewer.current?.showModal(); } catch (e) { setMessage(e instanceof Error ? e.message : "تعذر فتح القيد"); } finally { setBusy(false); }
  }
  const debit = lines.reduce((n, l) => n + Math.round(Number(l.debit || 0) * 100), 0), credit = lines.reduce((n, l) => n + Math.round(Number(l.credit || 0) * 100), 0);
  function change(index: number, key: keyof Line, value: string) { setLines(rows => rows.map((l, i) => i === index ? { ...l, [key]: value } : l)); }
  if (!data) return <p role="status">{message || "جارٍ تحميل القيود اليومية…"}</p>;
  const rows = data.journals.filter(row => (!q || `${row.entryNumber} ${row.description} ${row.referenceNumber}`.includes(q)) && (!status || row.status === status) && (!source || row.referenceType === source) && (!branch || String(row.branchId) === branch) && (!from || String(row.entryDate).slice(0, 10) >= from) && (!to || String(row.entryDate).slice(0, 10) <= to));
  const pageCount = Math.max(1, Math.ceil(rows.length / 25));
  const manualActions = (row: Row) => <div className="flex flex-wrap gap-2"><button type="button" className={button} disabled={busy} onClick={() => show(row)}>فتح</button><button className={button} disabled={busy} onClick={() => action("COPY", row.id)}>نسخ</button>{row.referenceType === "MANUAL_JOURNAL" && <>{row.status === "DRAFT" && <><button className={button} onClick={() => edit(row)}>تحرير</button><button className={button} disabled={busy} onClick={() => action("APPROVE", row.id)}>اعتماد</button></>}{row.status === "APPROVED" && <button className={button} disabled={busy} onClick={() => action("POST", row.id)}>ترحيل</button>}{["DRAFT", "APPROVED"].includes(String(row.status)) && <button className={button} disabled={busy} onClick={() => show(row)}>إلغاء المسودة…</button>}{row.status === "POSTED" && <button className={button} disabled={busy} onClick={() => show(row)}>عكس…</button>}</>}</div>;
  return <section className="space-y-5 rounded-2xl border border-[#e4d7be] bg-white p-5" dir="rtl">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-black">القيود اليومية</h2><p className="text-sm text-slate-500">قيود فعلية متعددة الأطراف • العملة الوظيفية {data.currency} • المسودة والمعتمد لا يؤثران في الأرصدة قبل الترحيل.</p></div><button className={button} onClick={() => edit()}>+ قيد يومية</button></div>
    {message && <p role="status" className="rounded-xl bg-amber-50 p-3">{message}</p>}
    <div className="grid gap-3 md:grid-cols-3"><input aria-label="بحث القيود" className={field} value={q} onChange={e => setQ(e.target.value)} placeholder="الرقم أو البيان أو المرجع"/><select aria-label="حالة القيد" className={field} value={status} onChange={e => setStatus(e.target.value)}><option value="">كل الحالات</option>{Object.entries(states).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select><select aria-label="مصدر القيد" className={field} value={source} onChange={e => setSource(e.target.value)}><option value="">كل المصادر (يدوية وآلية)</option>{Array.from(new Set(data.journals.map(r => String(r.referenceType ?? "")))).filter(Boolean).map(v => <option key={v}>{v}</option>)}</select><label>من<input aria-label="القيود من تاريخ" type="date" className={field} value={from} onChange={e => setFrom(e.target.value)}/></label><label>إلى<input aria-label="القيود إلى تاريخ" type="date" className={field} value={to} onChange={e => setTo(e.target.value)}/></label><label>الفرع<select className={field} value={branch} onChange={e => setBranch(e.target.value)}><option value="">كل الفروع (يشمل القيود القديمة غير المخصصة)</option>{data.branches.map(b => <option key={String(b.id)} value={String(b.id)}>{String(b.nameAr)}</option>)}</select></label></div>
    <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{["الرقم", "التاريخ", "البيان", "المصدر/المرجع", "مدين", "دائن", "الحالة", "الإجراءات"].map(h => <th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{rows.slice((page - 1) * 25, page * 25).map(row => <tr key={String(row.id)} className="border-b"><td className="p-3">{String(row.entryNumber)}</td><td>{String(row.entryDate).slice(0, 10)}</td><td>{String(row.description ?? "—")}</td><td>{String(row.referenceType ?? "—")}<br/>{String(row.referenceNumber ?? "")}</td><td dir="ltr">{amount(row.totalDebit)}</td><td dir="ltr">{amount(row.totalCredit)}</td><td>{states[String(row.status)] ?? String(row.status)}</td><td className="min-w-52 p-2">{manualActions(row)}</td></tr>)}</tbody></table>{!rows.length && <p className="p-8 text-center">لا توجد قيود مطابقة.</p>}</div>
    <div className="flex justify-between"><span>{rows.length} قيد • {page} / {pageCount}</span><div className="flex gap-2"><button className={button} disabled={page <= 1} onClick={() => setPage(page - 1)}>السابق</button><button className={button} disabled={page >= pageCount} onClick={() => setPage(page + 1)}>التالي</button></div></div>
    <dialog ref={editor} aria-label={id ? "تحرير قيد يومية" : "إضافة قيد يومية"} className="w-[min(1200px,95vw)] max-h-[90dvh] overflow-auto rounded-2xl border border-amber-300 bg-[#fffdf8] p-6 text-slate-900" onCancel={e => { if (busy) e.preventDefault(); }}>
      <form onSubmit={(e: FormEvent) => { e.preventDefault(); void action("SAVE", id, { ...draft, lines }); }} className="space-y-4">
        <div className="flex justify-between"><h3 className="text-xl font-bold">{id ? "تحرير قيد يومية" : "إضافة قيد يومية"}</h3><button type="button" disabled={busy} onClick={() => editor.current?.close()} aria-label="إغلاق">✕</button></div>
        {message && <p role="alert" className="text-red-700">{message}</p>}
        <div className="grid gap-3 md:grid-cols-2"><label>تاريخ القيد<input type="date" className={field} required value={draft.entryDate} onChange={e => setDraft({ ...draft, entryDate: e.target.value })}/></label><label>الفرع<select className={field} value={draft.branchId} onChange={e => setDraft({ ...draft, branchId: e.target.value })}><option value="">غير مخصص لفرع</option>{data.branches.map(b => <option key={String(b.id)} value={String(b.id)}>{String(b.nameAr)}</option>)}</select></label><label>البيان<input required className={field} value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })}/></label><label>المرجع<input className={field} value={draft.referenceNumber} onChange={e => setDraft({ ...draft, referenceNumber: e.target.value })}/></label></div>
        <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{["الحساب", "الوصف", "مدين", "دائن", "مركز التكلفة", "رمز المشروع", "حذف السطر"].map(h => <th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{lines.map((line, i) => <tr key={i}><td className="min-w-52 p-1"><select aria-label={`حساب السطر ${i + 1}`} required className={field} value={line.accountId} onChange={e => change(i, "accountId", e.target.value)}><option value="">اختر حساب حركة</option>{data.accounts.map(a => <option key={String(a.id)} value={String(a.id)}>{String(a.code)} — {String(a.nameAr)}</option>)}</select></td><td><input aria-label={`وصف السطر ${i + 1}`} className={field} value={line.description} onChange={e => change(i, "description", e.target.value)}/></td>{(["debit", "credit"] as const).map(k => <td key={k}><input aria-label={`${k === "debit" ? "مدين" : "دائن"} السطر ${i + 1}`} className={field} type="number" min="0" step="0.01" value={line[k]} onChange={e => change(i, k, e.target.value)}/></td>)}<td><select aria-label={`مركز تكلفة السطر ${i + 1}`} className={field} value={line.costCenterId} onChange={e => change(i, "costCenterId", e.target.value)}><option value="">بدون مركز</option>{data.costCenters.map(c => <option key={String(c.id)} value={String(c.id)}>{String(c.code)} — {String(c.nameAr)}</option>)}</select></td><td><input aria-label={`مشروع السطر ${i + 1}`} className={field} value={line.projectCode} onChange={e => change(i, "projectCode", e.target.value)}/></td><td><button type="button" className={button} disabled={lines.length <= 2} onClick={() => setLines(lines.filter((_, n) => n !== i))}>حذف</button></td></tr>)}</tbody></table></div>
        <div className="flex flex-wrap justify-between gap-3"><button type="button" className={button} onClick={() => setLines([...lines, blank()])}>+ طرف آخر</button><strong className={debit === credit ? "text-emerald-800" : "text-red-700"}>مدين {amount(debit / 100)} • دائن {amount(credit / 100)} • الفرق {amount((debit - credit) / 100)} {data.currency}</strong><button disabled={busy || debit !== credit || debit <= 0} className={button}>حفظ المسودة</button></div>
      </form>
    </dialog>
    <dialog ref={viewer} aria-label="تفاصيل القيد" className="w-[min(1100px,95vw)] max-h-[90dvh] overflow-auto rounded-2xl border border-amber-300 bg-[#fffdf8] p-6 text-slate-900">
      {detail && <div className="space-y-4"><div className="flex justify-between"><h3 className="text-xl font-bold">القيد {String(detail.journal.entryNumber)}</h3><button onClick={() => viewer.current?.close()} aria-label="إغلاق التفاصيل">✕</button></div><p>{String(detail.journal.description)} • {states[String(detail.journal.status)]}</p>
        <div className="overflow-x-auto"><table className="w-full"><thead><tr>{["الحساب", "البيان", "مدين", "دائن", "المشروع"].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{(detail.journal.lines as Row[]).map(l => <tr key={String(l.id)}><td className="p-2"><a className="underline" href={`/accounting?tab=reports&report=account-statement&accountId=${l.accountId}`}>{String(l.accountCode)} — {String(l.accountName)}</a></td><td>{String(l.description ?? "")}</td><td>{amount(l.debit)}</td><td>{amount(l.credit)}</td><td>{String(l.projectCode ?? "—")}</td></tr>)}</tbody></table></div>
        {detail.journal.referenceType === "MANUAL_JOURNAL" && <div className="rounded-xl border border-amber-300 p-4"><p className="mb-2 text-sm">القيد المرحل لا يُحذف؛ العكس ينشئ قيدًا مقابلًا بتاريخ اليوم في فترة مفتوحة ويحتفظ بالأصل وسجل التدقيق.</p>{["DRAFT", "APPROVED", "POSTED"].includes(String(detail.journal.status)) && <button className={button} disabled={busy} onClick={async () => { await action(detail.journal.status === "POSTED" ? "REVERSE" : "CANCEL", detail.journal.id); viewer.current?.close(); }}>{detail.journal.status === "POSTED" ? "تأكيد عكس القيد" : "تأكيد إلغاء المسودة"}</button>}</div>}
        <h4 className="font-bold">المرفقات</h4><input aria-label="إرفاق ملف بالقيد" type="file" accept=".pdf,.jpg,.jpeg,.png,.xlsx" disabled={busy} onChange={async e => { const file = e.target.files?.[0]; if (!file) return; const form = new FormData(); form.set("file", file); form.set("entityType", "JOURNAL_ENTRY"); form.set("entityId", String(detail.journal.id)); setBusy(true); try { const r = await fetch("/api/attachments", { method: "POST", body: form }); const j = await r.json(); if (!r.ok) throw new Error(j.error); await show(detail.journal); } catch (error) { setMessage(error instanceof Error ? error.message : "تعذر الإرفاق"); } finally { setBusy(false); } }}/>{detail.attachments.map(a => <p key={String(a.id)}>{String(a.originalName ?? a.fileName)}</p>)}
        <h4 className="font-bold">سجل الإنشاء والاعتماد والتعديل</h4><ul className="space-y-2">{detail.audit.map(a => <li key={String(a.id)} className="rounded-lg border p-2 text-sm">{String(a.createdAt).slice(0, 19)} • {String(a.action)} • المستخدم: {String(a.userId ?? "النظام")}</li>)}</ul>
      </div>}
    </dialog>
  </section>;
}
