"use client";

import { useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import { createPortal } from "react-dom";
type Row = Record<string, unknown>;
type PartnerData = { partners: Row[]; accounts: Row[]; sources: Row[]; distributions: Row[]; currency: string };
const input = "w-full min-w-0 rounded-xl border border-[#e4d7be] bg-white px-3 py-2.5 text-sm";
const gold = "rounded-xl border border-[#c9972b] bg-gradient-to-b from-[#ebcf87] to-[#c9972b] px-4 py-2 text-sm font-bold text-[#172033] disabled:opacity-50";
const money = (value: unknown) => Number(value ?? 0).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const today = () => new Date().toISOString().slice(0, 10);

export default function PartnersPanel({ mode = "directory" }: { mode?: "directory" | "distributions" }) {
  const [data, setData] = useState<PartnerData | null>(null), [error, setError] = useState(""), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false);
  const [from, setFrom] = useState(""), [to, setTo] = useState(today), [query, setQuery] = useState("");
  const [editing, setEditing] = useState<Row | null>(null), [statement, setStatement] = useState<Row | null>(null), [distribution, setDistribution] = useState<Row | null>(null);
  const [confirmPost, setConfirmPost] = useState<Row | null>(null);
  const request = useRef(0);
  const params = () => new URLSearchParams({ from, to, mode });
  async function load() {
    const token = ++request.current;
    try { const response = await fetch(`/api/finance/partners?${params()}`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error); if (token === request.current) { setData(body); setError(""); } }
    catch (cause) { if (token === request.current) { setError(cause instanceof Error ? cause.message : "تعذر تحميل الشركاء"); setData(null); } }
  }
  useEffect(() => { void load(); return () => { request.current += 1; }; /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [from, to, mode]);
  async function mutate(body: Row, message: string) {
    setBusy(true); setError(""); setNotice("");
    try { const response = await fetch("/api/finance/partners", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "تعذر الحفظ"); await load(); setNotice(message); return result as Row; }
    catch (cause) { setError(cause instanceof Error ? cause.message : "تعذر الحفظ"); return null; }
    finally { setBusy(false); }
  }
  async function save(event: FormEvent<HTMLFormElement>, action: string, id?: unknown) {
    event.preventDefault(); const form = event.currentTarget, fields = Object.fromEntries(new FormData(form));
    const result = await mutate({ ...fields, action, ...(id ? { id } : {}), ...(action === "SAVE_PARTNER" ? { isActive: fields.isActive !== "false" } : {}) }, action === "SAVE_PARTNER" ? "تم حفظ الشريك وربطه بحساباته." : "تم حفظ قرار التوزيع مسودة؛ راجع الأنصبة ثم اعتمده للترحيل.");
    if (result) { setEditing(null); form.reset(); }
  }
  function exportRows(format: "print" | "xlsx", partnerId?: unknown) { const p = params(); p.set("format", format); if (partnerId) p.set("partnerId", String(partnerId)); window.open(`/api/finance/partners?${p}`, "_blank", "noopener,noreferrer"); }
  const partners = data?.partners.filter(row => `${row.code} ${row.name}`.includes(query)) ?? [];
  const distributions = data?.distributions.filter(row => `${row.number} ${row.decisionNumber}`.includes(query)) ?? [];
  return <section className="space-y-5 rounded-2xl border border-[#e4d7be] bg-white p-5" dir="rtl">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">{mode === "directory" ? "جاري الشركاء" : "توزيع الأرباح والخسائر"}</h2><p className="mt-1 text-sm text-slate-500">{mode === "directory" ? "حسابات مستقلة للشركاء وأرصدة مستمدة من دفتر الأستاذ." : "توزيع الأرباح المحتجزة المثبتة على جاري الشركاء بموجب قرار معتمد."} العملة: {data?.currency ?? "—"}</p></div>{mode === "directory" && <button className={gold} onClick={() => { setError(""); setEditing({ isActive: true }); }}>إضافة شريك</button>}</header>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><label className="space-y-1 text-sm">بحث<input className={input} value={query} onChange={event => setQuery(event.target.value)} placeholder={mode === "directory" ? "رمز الشريك أو اسمه" : "رقم القرار أو المرجع"}/></label><label className="space-y-1 text-sm">من<input className={input} type="date" value={from} onChange={event => setFrom(event.target.value)}/></label><label className="space-y-1 text-sm">إلى<input className={input} type="date" value={to} onChange={event => setTo(event.target.value)}/></label><div className="flex items-end gap-2"><button className={gold} disabled={!data} onClick={() => exportRows("xlsx")}>Excel</button><button className={gold} disabled={!data} onClick={() => exportRows("print")}>طباعة / PDF</button></div></div>
    {error && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-red-800">{error}</p>}{notice && <p role="status" className="rounded-xl bg-emerald-50 p-3 text-emerald-800">{notice}</p>}
    {data && mode === "directory" && <><p className="text-sm text-slate-600">مجموع ملكية الشركاء النشطين: {money(data.partners.filter(row => row.isActive).reduce((sum, row) => sum + Number(row.ownershipPercent), 0))}% — الرصيد الموجب دائن لصالح الشريك.</p><Table headers={["الرمز", "الشريك", "الملكية %", "رأس المال", "أول المدة", "الأرباح الموزعة", "آخر المدة", "الحالة", "الإجراءات"]} rows={partners.map(row => [row.code, row.name, money(row.ownershipPercent), money(row.capitalBalance), money(row.openingBalance), money(row.distributedProfits), money(row.closingBalance), row.isActive ? "نشط" : "غير نشط", <div className="flex gap-2" key={String(row.id)}><button className={gold} onClick={() => { setError(""); setEditing(row); }}>تحرير</button><button className={gold} onClick={() => setStatement(row)}>كشف الحساب</button></div>])}/></>}
    {data && mode === "distributions" && <>
      <form onSubmit={event => void save(event, "CREATE_DISTRIBUTION")} className="grid items-end gap-3 rounded-xl border border-[#e4d7be] bg-[#fcfaf5] p-4 sm:grid-cols-2 xl:grid-cols-4">
        <h3 className="font-bold sm:col-span-2 xl:col-span-4">قرار توزيع أرباح جديد</h3><label className="space-y-1 text-sm">تاريخ القرار<input className={input} name="distributionDate" type="date" required defaultValue={today()}/></label><label className="space-y-1 text-sm">رقم القرار<input className={input} name="decisionNumber" required/></label><label className="space-y-1 text-sm">الأرباح المحتجزة<select className={input} name="sourceAccountId" required><option value="">اختر الحساب المرتبط</option>{data.sources.map(row => <option key={String(row.accountId)} value={String(row.accountId)}>{String(row.code)} — {String(row.name)} — الرصيد {money(row.available)}</option>)}</select></label><label className="space-y-1 text-sm">المبلغ الموزع<input className={input} name="amount" type="number" min="0.01" step="0.01" required/></label><p className="text-sm text-slate-600 sm:col-span-2 xl:col-span-3">الأنصبة بحسب ملكية الشركاء النشطين ومجموعها 100%. يُعاد فحص الرصيد عند الترحيل؛ المستند المرحّل غير قابل للتعديل.</p><button className={gold} disabled={busy || !data.sources.length}>حفظ مسودة التوزيع</button>
      </form>
      {!data.sources.length && <p className="text-sm text-amber-800">اربط حساب الأرباح المحتجزة في إعدادات الربط المحاسبي أولًا.</p>}
      <Table headers={["الرقم", "التاريخ", "القرار", "المبلغ", "الحالة", "أنشأه", "اعتمده", "الإجراء"]} rows={distributions.map(row => [row.number, String(row.distributionDate).slice(0, 10), row.decisionNumber, money(row.amount), row.status === "POSTED" ? "مرحّل" : "مسودة", row.createdBy, row.postedBy ?? "—", <div className="flex gap-2" key={String(row.id)}><button className={gold} onClick={() => setDistribution(row)}>الأنصبة</button>{row.status === "DRAFT" && <button className={gold} disabled={busy} onClick={() => { setError(""); setConfirmPost(row); }}>اعتماد وترحيل</button>}</div>])}/>
    </>}
    {editing && data && <Modal title={editing.id ? "تحرير بيانات الشريك" : "إضافة شريك"} close={() => !busy && setEditing(null)}><form onSubmit={event => void save(event, "SAVE_PARTNER", editing.id)} className="grid gap-4 sm:grid-cols-2">
      <Field title="رمز الشريك"><input name="code" className={input} defaultValue={String(editing.code ?? "")} required pattern="[A-Za-z0-9_-]{1,40}"/></Field><Field title="اسم الشريك"><input name="name" className={input} defaultValue={String(editing.name ?? "")} required/></Field><Field title="نسبة الملكية %"><input name="ownershipPercent" className={input} type="number" min="0" max="100" step="0.0001" defaultValue={String(editing.ownershipPercent ?? "0")} required/></Field><Field title="الحالة"><select name="isActive" className={input} defaultValue={editing.isActive === false ? "false" : "true"}><option value="true">نشط</option><option value="false">غير نشط</option></select></Field>
      <Field title="حساب جاري الشريك"><select name="currentAccountId" className={input} required defaultValue={String(editing.currentAccountId ?? "")}><option value="">اختر حسابًا تفصيليًا مستقلًا</option>{data.accounts.map(row => <option key={String(row.id)} value={String(row.id)}>{String(row.code)} — {String(row.nameAr)}</option>)}</select></Field><Field title="حساب رأس المال"><select name="capitalAccountId" className={input} required defaultValue={String(editing.capitalAccountId ?? "")}><option value="">اختر حساب حقوق ملكية</option>{data.accounts.filter(row => row.accountType === "EQUITY").map(row => <option key={String(row.id)} value={String(row.id)}>{String(row.code)} — {String(row.nameAr)}</option>)}</select></Field>
      <label className="flex items-center gap-2 text-sm sm:col-span-2"><input type="checkbox" name="liabilityCurrentApproved" value="true" defaultChecked={Boolean(editing.liabilityCurrentApproved)}/>اعتماد تصنيف الجاري كالتزام إذا كان الحساب المختار من الخصوم.</label><label className="text-sm sm:col-span-2">ملاحظات<textarea name="notes" className={input} defaultValue={String(editing.notes ?? "")}/></label>{error && <p className="text-red-800 sm:col-span-2" role="alert">{error}</p>}<button className={gold} disabled={busy}>{busy ? "جارٍ الحفظ…" : "حفظ الشريك"}</button>
    </form></Modal>}
    {statement && <Modal title={`كشف جاري الشريك — ${String(statement.name)}`} close={() => setStatement(null)}><p className="mb-3">أول الفترة: {money(statement.openingBalance)} — آخر الفترة: {money(statement.closingBalance)}</p><div className="mb-4 flex gap-2"><button className={gold} onClick={() => exportRows("xlsx", statement.id)}>Excel</button><button className={gold} onClick={() => exportRows("print", statement.id)}>طباعة / PDF</button></div><Table headers={["التاريخ", "القيد", "البيان", "مدين", "دائن", "الرصيد"]} rows={(statement.movements as Row[]).map(row => [String(row.date).slice(0, 10), <a className="underline" key={String(row.id)} href={`/accounting?tab=journals&journalId=${row.journalEntryId}`}>{String(row.entryNumber)}</a>, row.description, money(row.debit), money(row.credit), money(row.balance)])}/></Modal>}
    {distribution && <Modal title={`أنصبة القرار ${String(distribution.decisionNumber)}`} close={() => setDistribution(null)}><Table headers={["الشريك", "النسبة %", "المبلغ"]} rows={(distribution.lines as Row[]).map(row => [row.partnerName, money(row.percent), money(row.amount)])}/>{Boolean(distribution.journalEntryId) && <a className="mt-4 inline-block font-bold text-[#8a641b] underline" href={`/accounting?tab=journals&journalId=${distribution.journalEntryId}`}>القيد المحاسبي {String(distribution.journalNumber)}</a>}</Modal>}
    {confirmPost && <Modal title="اعتماد وترحيل توزيع الأرباح" close={() => !busy && setConfirmPost(null)}><p>سيُرحّل مبلغ {money(confirmPost.amount)} من الأرباح المحتجزة إلى حسابات الشركاء وفق القرار {String(confirmPost.decisionNumber)}.</p><p className="my-3 text-sm text-slate-600">يُثبت قيد محاسبي متوازن ويُحفظ اسم المعتمد. لا يمكن تعديل القرار بعد الترحيل.</p>{error && <p className="my-3 text-red-800" role="alert">{error}</p>}<button className={gold} disabled={busy} onClick={async () => { const result = await mutate({ action: "POST_DISTRIBUTION", id: confirmPost.id }, "تم اعتماد التوزيع وترحيل قيده وتحديث حسابات الشركاء."); if (result) setConfirmPost(null); }}>{busy ? "جارٍ الترحيل…" : "تأكيد الاعتماد والترحيل"}</button></Modal>}
  </section>;
}
function Field({ title, children }: { title: string; children: ReactNode }) { return <label className="space-y-1 text-sm">{title}{children}</label>; }
function Table({ headers, rows }: { headers: string[]; rows: unknown[][] }) { return <div className="overflow-x-auto rounded-xl border border-[#e4d7be]"><table className="w-full min-w-[640px] text-sm"><thead className="bg-[#f3ecdf]"><tr>{headers.map(title => <th key={title} className="whitespace-nowrap p-3 text-right">{title}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index} className="border-t border-[#e4d7be] even:bg-[#fcfaf5]">{row.map((cell, column) => <td key={column} className="p-3">{cell as ReactNode}</td>)}</tr>)}{!rows.length && <tr><td colSpan={headers.length} className="p-8 text-center text-slate-500">لا توجد سجلات مطابقة.</td></tr>}</tbody></table></div>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: ReactNode }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const dialog = ref.current; dialog?.showModal(); return () => dialog?.close(); }, []);
  return createPortal(<dialog ref={ref} aria-label={title} dir="rtl" onCancel={event => { event.preventDefault(); close(); }} style={{ position: "fixed", inset: "50% auto auto 50%", transform: "translate(-50%, -50%)", margin: 0, width: "min(960px, calc(100vw - 32px))", maxHeight: "calc(100dvh - 48px)", overflowY: "auto", padding: 0, border: "1px solid #d8bb72", borderRadius: 20, color: "#172033", background: "#fffdf8" }}><div className="p-5"><header className="mb-5 flex items-center justify-between border-b border-[#e4d7be] pb-3"><h3 className="text-lg font-bold">{title}</h3><button type="button" className={gold} onClick={close} aria-label="إغلاق">×</button></header>{children}</div></dialog>, document.body);
}
