"use client";

import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";

type Method = { id: number; code: string; nameAr: string; nameEn: string; type: string; accountId: number | null; bankAccountId: number | null; currency: string | null; branchId: number | null; displayOrder: number; isActive: boolean; showInSales: boolean; showInPurchases: boolean; showInReceipt: boolean; showInPayment: boolean; allowedUserIds: number[]; updatedBy: string; updatedAt: string };
type Workspace = { methods: Method[]; accounts: { id: number; code: string; nameAr: string; accountType: string }[]; banks: { id: number; name: string; currency: string; ledgerAccountId: number }[]; currencies: { code: string; nameAr: string }[]; branches: { id: number; nameAr: string }[]; users: { id: number; name: string }[]; types: string[] };
const types: Record<string, string> = { CASH: "نقد", BANK: "بنك", TRANSFER: "تحويل", CHEQUE: "شيك", CARD: "بطاقة", MADA: "مدى", VISA: "Visa", MASTERCARD: "Mastercard", OTHER: "أخرى" };
const visibility = [{ key: "showInSales", label: "المبيعات" }, { key: "showInPurchases", label: "المشتريات" }, { key: "showInReceipt", label: "سندات القبض" }, { key: "showInPayment", label: "سندات الصرف" }] as const;
const button = "rounded-xl border border-[#c39843] bg-gradient-to-l from-[#b78a35] to-[#efd68c] px-3 py-2 text-sm font-bold text-[#182238] disabled:opacity-40";
const field = "mt-1 w-full rounded-xl border border-[#e3d8c5] bg-white px-3 py-2 text-sm";

export default function PaymentMethodsPanel() {
  const [data, setData] = useState<Workspace | null>(null), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const [busy, setBusy] = useState(false), [editing, setEditing] = useState<Method | null>(null), [formError, setFormError] = useState("");
  const [q, setQ] = useState(""), [active, setActive] = useState(""), [kind, setKind] = useState(""), [page, setPage] = useState(1);
  const [bankId, setBankId] = useState(""), [accountId, setAccountId] = useState(""), [currency, setCurrency] = useState(""), [formKey, setFormKey] = useState(0);
  const dialog = useRef<HTMLDialogElement>(null);
  const load = useCallback(async () => {
    const response = await fetch("/api/finance/payment-methods?workspace=1", { cache: "no-store" }), result = await response.json();
    if (!response.ok) throw new Error(result.error || "تعذر تحميل طرق الدفع"); setData(result);
  }, []);
  useEffect(() => { load().catch(value => setError(value.message)); }, [load]);
  const rows = data?.methods.filter(row => (!q || `${row.code} ${row.nameAr} ${row.nameEn}`.toLowerCase().includes(q.toLowerCase())) && (!active || String(row.isActive) === active) && (!kind || row.type === kind)) ?? [];
  const pages = Math.max(1, Math.ceil(rows.length / 25));
  const account = (id: number | null) => data?.accounts.find(row => row.id === id), bank = (id: number | null) => data?.banks.find(row => row.id === id);
  function open(row: Method | null) {
    setEditing(row); setFormError(""); setBankId(String(row?.bankAccountId ?? "")); setAccountId(String(row?.accountId ?? "")); setCurrency(row?.currency || ""); setFormKey(key => key + 1); dialog.current?.showModal();
  }
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setFormError("");
    const form = new FormData(event.currentTarget), body = { ...Object.fromEntries(form), id: editing?.id, code: editing?.code ?? form.get("code"), bankAccountId: bankId, accountId, currency, isActive: form.has("isActive"), ...Object.fromEntries(visibility.map(item => [item.key, form.has(item.key)])), allowedUserIds: form.getAll("allowedUserIds").map(Number) };
    try {
      const response = await fetch("/api/finance/payment-methods", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }), result = await response.json();
      if (!response.ok) throw new Error(result.error || "تعذر الحفظ");
      dialog.current?.close(); setNotice(`تم حفظ طريقة الدفع «${result.nameAr}» وروابطها وصلاحياتها.`); await load();
    } catch (value) { setFormError(value instanceof Error ? value.message : "تعذر الحفظ"); } finally { setBusy(false); }
  }
  async function toggle(row: Method) {
    setBusy(true); setError("");
    try {
      const response = await fetch("/api/finance/payment-methods", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ code: row.code, isActive: !row.isActive }) });
      if (!response.ok) throw new Error((await response.json()).error); setNotice(row.isActive ? "تم إيقاف الطريقة للعمليات الجديدة مع الاحتفاظ بالسجلات السابقة." : "تم تفعيل طريقة الدفع."); await load();
    } catch (value) { setError(value instanceof Error ? value.message : "تعذر تحديث الطريقة"); } finally { setBusy(false); }
  }
  async function exportFile(format: "xlsx" | "pdf") {
    const url = `/api/finance/payment-methods/export?${new URLSearchParams({ format, q, active, type: kind })}`;
    if (format === "pdf") { window.open(url, "_blank", "noopener,noreferrer"); return; }
    setBusy(true); setError("");
    try {
      const response = await fetch(url); if (!response.ok) throw new Error((await response.json()).error);
      const blob = URL.createObjectURL(await response.blob()), anchor = document.createElement("a"); anchor.href = blob; anchor.download = "netaj-payment-methods.xlsx"; anchor.click(); setTimeout(() => URL.revokeObjectURL(blob), 1000);
    } catch (value) { setError(value instanceof Error ? value.message : "تعذر التصدير"); } finally { setBusy(false); }
  }
  return <section className="space-y-5 rounded-2xl border border-[#e4d5ba] bg-white p-5" dir="rtl">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">طرق الدفع</h2><p className="mt-1 text-sm text-slate-500">إعداد طرق الدفع وحساباتها الافتراضية، الفروع والصلاحيات. لا ينشأ قيد مالي من تغيير الإعدادات.</p></div><button className={button} disabled={!data || busy} onClick={() => open(null)}>+ إضافة طريقة دفع</button></header>
    {error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-red-800">{error}</p>}{notice && <p role="status" className="rounded-xl bg-emerald-50 p-3 text-emerald-800">{notice}</p>}
    <div className="flex flex-wrap items-end gap-3"><label className="min-w-52 flex-1">بحث<input className={field} placeholder="الرمز أو اسم طريقة الدفع" value={q} onChange={event => { setQ(event.target.value); setPage(1); }}/></label><label>النوع<select className={field} value={kind} onChange={event => { setKind(event.target.value); setPage(1); }}><option value="">كل الأنواع</option>{Object.entries(types).map(([code, label]) => <option key={code} value={code}>{label}</option>)}</select></label><label>الحالة<select className={field} value={active} onChange={event => { setActive(event.target.value); setPage(1); }}><option value="">كل الحالات</option><option value="true">نشطة</option><option value="false">موقوفة</option></select></label><button className={button} disabled={!data || busy} onClick={() => exportFile("xlsx")}>Excel</button><button className={button} disabled={!data || busy} onClick={() => exportFile("pdf")}>طباعة / حفظ PDF</button><button className={button} disabled={busy} onClick={() => { setError(""); load().catch(value => setError(value.message)); }}>تحديث</button></div>
    <div className="overflow-x-auto"><table className="w-full text-right text-sm"><thead className="bg-[#f2eadb]"><tr>{["الرقم / الترتيب", "الاسم", "النوع", "الحساب والبنك", "العملة / الفرع", "الظهور", "المستخدمون", "الحالة", "الإجراءات"].map(label => <th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{rows.slice((page - 1) * 25, page * 25).map(row => <tr key={row.id} className="border-b"><td className="p-3"><b>{row.code}</b><p className="text-slate-500">#{row.id} · ترتيب {row.displayOrder}</p></td><td className="p-3"><b>{row.nameAr}</b><p>{row.nameEn || "—"}</p></td><td className="p-3">{types[row.type] || row.type}</td><td className="p-3">{row.accountId ? `${account(row.accountId)?.code ?? row.accountId} — ${account(row.accountId)?.nameAr ?? "حساب غير متاح"}` : "حسب البنك المختار بالمستند"}<p className="text-slate-500">{row.bankAccountId ? bank(row.bankAccountId)?.name || "بنك غير متاح" : "بدون بنك افتراضي"}</p></td><td className="p-3">{row.currency || "حسب المستند"}<p>{row.branchId ? data?.branches.find(branch => branch.id === row.branchId)?.nameAr || row.branchId : "جميع الفروع"}</p></td><td className="p-3">{visibility.filter(item => row[item.key]).map(item => item.label).join("، ") || "غير ظاهرة"}</td><td className="p-3">{row.allowedUserIds.length ? row.allowedUserIds.map(id => data?.users.find(user => user.id === id)?.name || id).join("، ") : "كل المخولين"}</td><td className="p-3">{row.isActive ? "نشطة" : "موقوفة"}</td><td className="p-3"><div className="flex gap-2"><button className={button} disabled={busy} onClick={() => open(row)}>تحرير</button><button className={button} disabled={busy} onClick={() => toggle(row)}>{row.isActive ? "إيقاف" : "تفعيل"}</button></div><p className="mt-2 text-xs text-slate-500">آخر تعديل: {row.updatedBy || "—"}</p></td></tr>)}</tbody></table>{!rows.length && <p className="p-6 text-center text-slate-500">{data ? "لا توجد طرق دفع مطابقة. أضف طريقة لتخصيص الربط والظهور." : error ? "تعذر تحميل البيانات." : "جارٍ التحميل…"}</p>}</div>
    <footer className="flex items-center justify-between text-sm"><span>{rows.length} طريقة · {data?.methods.filter(row => row.isActive).length ?? 0} نشطة</span><div className="flex items-center gap-3"><button className={button} disabled={page <= 1} onClick={() => setPage(value => value - 1)}>السابق</button><span>{page} / {pages}</span><button className={button} disabled={page >= pages} onClick={() => setPage(value => value + 1)}>التالي</button></div></footer>
    <dialog ref={dialog} aria-labelledby="payment-method-title" dir="rtl" className="m-auto w-[min(800px,calc(100vw-32px))] max-h-[90vh] overflow-y-auto rounded-2xl border border-[#c39843] bg-[#fffdf8] p-6 text-[#182238]"><form key={formKey} onSubmit={save} className="space-y-4"><div className="flex items-center justify-between gap-3"><h3 id="payment-method-title" className="text-xl font-bold">{editing ? `تحرير طريقة الدفع — ${editing.code}` : "إضافة طريقة دفع"}</h3><button type="button" className={button} disabled={busy} onClick={() => dialog.current?.close()}>إغلاق</button></div>{formError && <p role="alert" className="rounded-xl bg-red-50 p-3 text-red-800">{formError}</p>}
      <div className="grid gap-4 sm:grid-cols-2"><label>الرمز / رقم الطريقة<input className={field} name="code" required maxLength={50} pattern="[A-Za-z0-9][A-Za-z0-9_.-]*" dir="ltr" defaultValue={editing?.code || ""} readOnly={!!editing}/></label><label>ترتيب العرض<input className={field} name="displayOrder" type="number" min={0} max={9999} step={1} defaultValue={editing?.displayOrder ?? 0} required/></label><label>الاسم العربي<input className={field} name="nameAr" required maxLength={200} defaultValue={editing?.nameAr || ""}/></label><label>الاسم الإنجليزي<input className={field} name="nameEn" maxLength={200} dir="ltr" defaultValue={editing?.nameEn || ""}/></label><label>نوع طريقة الدفع<select className={field} name="type" defaultValue={editing?.type || "CASH"}>{Object.entries(types).map(([code, label]) => <option key={code} value={code}>{label}</option>)}</select></label><label>الفرع<select className={field} name="branchId" defaultValue={editing?.branchId || ""}><option value="">جميع الفروع</option>{data?.branches.map(branch => <option key={branch.id} value={branch.id}>{branch.nameAr}</option>)}</select></label>
      <label>البنك أو الصندوق الافتراضي<select className={field} value={bankId} onChange={event => { setBankId(event.target.value); const selected = data?.banks.find(row => row.id === Number(event.target.value)); if (selected) { setAccountId(String(selected.ledgerAccountId)); setCurrency(selected.currency); } }}><option value="">يحدد عند إنشاء المستند</option>{data?.banks.map(bank => <option key={bank.id} value={bank.id}>{bank.name} — {bank.currency}</option>)}</select></label><label>الحساب المحاسبي المرتبط<select className={field} value={accountId} onChange={event => setAccountId(event.target.value)}><option value="">حسب حساب البنك المختار</option>{data?.accounts.filter(account => account.accountType === "ASSET").map(account => <option key={account.id} value={account.id}>{account.code} — {account.nameAr}</option>)}</select></label><label>العملة<select className={field} value={currency} onChange={event => setCurrency(event.target.value)}><option value="">حسب المستند</option>{data?.currencies.map(currency => <option key={currency.code} value={currency.code}>{currency.code} — {currency.nameAr}</option>)}</select></label><label className="flex items-center gap-2 self-end pb-2"><input name="isActive" type="checkbox" defaultChecked={editing?.isActive ?? true}/>طريقة فعّالة</label></div>
      <fieldset className="rounded-xl border border-[#e4d5ba] p-3"><legend className="px-2 font-bold">تظهر وتُستخدم في</legend><div className="flex flex-wrap gap-4">{visibility.map(item => <label className="flex items-center gap-2" key={item.key}><input type="checkbox" name={item.key} defaultChecked={editing?.[item.key] ?? true}/>{item.label}</label>)}</div></fieldset>
      <fieldset className="rounded-xl border border-[#e4d5ba] p-3"><legend className="px-2 font-bold">صلاحيات استخدام الطريقة</legend><p className="mb-2 text-xs text-slate-500">بدون تحديد مستخدمين: متاحة لكل المخولين في الشركة. تحديد مستخدمين يقصر استخدامها عليهم ولا يمنحهم صلاحيات إضافية.</p><div className="flex max-h-40 flex-wrap gap-4 overflow-y-auto">{data?.users.map(user => <label className="flex items-center gap-2" key={user.id}><input name="allowedUserIds" type="checkbox" value={user.id} defaultChecked={editing?.allowedUserIds.includes(user.id) ?? false}/>{user.name}</label>)}</div></fieldset>
      <div className="flex gap-3"><button className={button} disabled={busy}>{busy ? "جارٍ الحفظ…" : "حفظ طريقة الدفع"}</button><button type="button" className={button} disabled={busy} onClick={() => dialog.current?.close()}>إلغاء</button></div>
    </form></dialog>
  </section>;
}
