"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
type Row = Record<string, unknown>;
type Data = { vouchers: Row[]; banks: Row[]; parties: Row[]; accounts: Row[]; costCenters: Row[]; branches: Row[]; transfers: Row[]; invoices: Row[] };
const field = "w-full min-w-0 rounded-xl border border-[#e4d7be] bg-white px-3 py-2.5 text-sm";
const button = "rounded-xl border border-[#c9972b] bg-gradient-to-b from-[#ebcf87] to-[#c9972b] px-4 py-2.5 text-sm font-bold disabled:opacity-50";
const number = (v: unknown) => Number(v ?? 0).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const types: Record<string, string> = { CUSTOMER_RECEIPT: "قبض", SUPPLIER_PAYMENT: "صرف", TRANSFER: "تحويل" };
const statuses: Record<string, string> = { DRAFT: "مسودة", POSTED: "مرحل", CANCELLED: "ملغي" };
export default function VoucherWorkspace({ mode }: { mode: "receipt" | "payment" | "all" }) {
  const type = mode === "payment" ? "SUPPLIER_PAYMENT" : "CUSTOMER_RECEIPT", title = mode === "all" ? "كل السندات" : mode === "payment" ? "سندات الصرف" : "سندات القبض";
  const [data, setData] = useState<Data | null>(null), [methods, setMethods] = useState<Row[]>([]), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  const [q, setQ] = useState(""), [status, setStatus] = useState(""), [from, setFrom] = useState(""), [to, setTo] = useState(""), [typeFilter, setTypeFilter] = useState(""), [page, setPage] = useState(1);
  const [partyId, setPartyId] = useState(""), [bankId, setBankId] = useState(""), [counter, setCounter] = useState(""), [allocations, setAllocations] = useState<Record<string, string>>({});
  const [methodCode, setMethodCode] = useState(""), [branchId, setBranchId] = useState(""), [methodsLoading, setMethodsLoading] = useState(false), [methodsRevision, setMethodsRevision] = useState(0);
  const [detail, setDetail] = useState<Row | null>(null);
  const editor = useRef<HTMLDialogElement>(null), viewer = useRef<HTMLDialogElement>(null);
  const openedSource = useRef(false);
  useEffect(() => { if (!data || openedSource.current) return; const id = new URLSearchParams(window.location.search).get("voucherId"); if (id) { openedSource.current = true; const v = data.vouchers.find(r => String(r.id) === id); if (v) { setDetail({ ...v, kind: v.voucherType, number: v.voucherNumber, date: String(v.voucherDate).slice(0, 10), partyName: (v.party as Row | null)?.nameAr ?? v.beneficiaryName ?? "—" }); viewer.current?.showModal(); } else setMessage("السند المطلوب غير موجود في الشركة الحالية"); } }, [data]);
  async function load() { const r = await fetch("/api/finance/vouchers?workspace=1", { cache: "no-store" }), j = await r.json(); if (!r.ok) throw new Error(j.error); setData(j); }
  useEffect(() => { void load().catch(e => setMessage(e.message)); }, []);
  useEffect(() => {
    const controller = new AbortController(); setMethodsLoading(true);
    const params = new URLSearchParams({ use: mode === "payment" ? "PAYMENT" : "RECEIPT", branchId, bankAccountId: bankId });
    fetch(`/api/finance/payment-methods?${params}`, { signal: controller.signal, cache: "no-store" }).then(async response => {
      const result = await response.json(); if (!response.ok) throw new Error(result.error || "تعذر تحميل طرق الدفع");
      const choices: Row[] = result.filter((row: Row) => row.type !== "CHEQUE" && row.code !== "CHEQUE");
      setMethods(choices); setMethodCode(code => choices.some(row => row.code === code) ? code : "");
    }).catch(error => { if (error.name !== "AbortError") { setMethods([]); setMethodCode(""); setMessage(error.message); } }).finally(() => { if (!controller.signal.aborted) setMethodsLoading(false); });
    return () => controller.abort();
  }, [mode, branchId, bankId, methodsRevision]);
  useEffect(() => { setPage(1); }, [q, status, from, to, typeFilter]);
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); if (methodsLoading || !methodCode || !methods.some(method => method.code === methodCode)) { setMessage("اختر طريقة دفع متاحة للفرع والبنك والمستخدم الحالي"); return; } setBusy(true); setMessage(""); const f = new FormData(e.currentTarget), file = f.get("attachment");
    const body: Row = { ...Object.fromEntries(f), partyId, bankAccountId: bankId, counterAccountId: counter, voucherType: type, allocations: counter ? [] : Object.entries(allocations).filter(([, v]) => Number(v) > 0).map(([id, amount]) => ({ [type === "CUSTOMER_RECEIPT" ? "saleId" : "purchaseId"]: Number(id), amount })) }; delete body.attachment;
    try {
      const r = await fetch("/api/finance/vouchers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }), j = await r.json(); if (!r.ok) throw new Error(j.error);
      let note = "تم حفظ المسودة. رحّل السند من سجله لإثبات القيد وتسوية الفواتير.";
      if (file instanceof File && file.size) { const a = new FormData(); a.set("file", file); a.set("entityType", "FINANCIAL_VOUCHER"); a.set("entityId", String(j.id)); const upload = await fetch("/api/attachments", { method: "POST", body: a }); if (!upload.ok) note += " لم يُرفع المرفق؛ السند محفوظ ولا تعاود إنشاءه."; }
      await load(); setMessage(note); editor.current?.close();
    } catch (e) { setMessage(e instanceof Error ? e.message : "تعذر حفظ السند"); } finally { setBusy(false); }
  }
  async function action(row: Row, action: string, reason?: string) { setBusy(true); setMessage(""); try { const r = await fetch(`/api/finance/vouchers/${row.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, reason }) }), j = await r.json(); if (!r.ok) throw new Error(j.error); await load(); viewer.current?.close(); setMessage(action === "POST" ? "تم الترحيل وإنشاء القيد وتسوية التخصيصات" : "تم إلغاء السند وعكس أثره البنكي والمحاسبي"); } catch (e) { setMessage(e instanceof Error ? e.message : "تعذر التنفيذ"); } finally { setBusy(false); } }
  if (!data) return <p>{message || "جارٍ تحميل السندات…"}</p>;
  const bank = data.banks.find(b => String(b.id) === bankId), currency = String(bank?.currency ?? "");
  const available = data.invoices.filter(i => i.type === type && String(i.partyId) === partyId && i.currency === currency && Number(i.outstanding) > 0);
  const vouchers: Row[] = data.vouchers.map(v => ({ ...v, key: `v${v.id}`, number: v.voucherNumber, date: String(v.voucherDate).slice(0, 10), kind: String(v.voucherType), partyName: (v.party as Row | null)?.nameAr ?? v.beneficiaryName ?? "—", bankName: (v.bankAccount as Row).name }));
  const transfers: Row[] = mode === "all" ? data.transfers.map(t => ({ ...t, key: `t${t.id}`, number: t.transferNumber, date: String(t.transferDate).slice(0, 10), kind: "TRANSFER", partyName: `${String((t.fromBankAccount as Row).name)} ← ${String((t.toBankAccount as Row).name)}`, bankName: (t.fromBankAccount as Row).name, currency: (t.fromBankAccount as Row).currency })) : [];
  const rows: Row[] = [...vouchers, ...transfers].filter(row => (mode === "all" || row.kind === type) && (!q || `${row.number} ${row.partyName} ${row.referenceNumber}`.includes(q)) && (!status || row.status === status) && (!typeFilter || row.kind === typeFilter) && (!from || String(row.date) >= from) && (!to || String(row.date) <= to)).sort((a, b) => String(b.date).localeCompare(String(a.date)));
  const totals = new Map<string, { receipt: number; payment: number }>(); for (const row of rows.filter(r => r.status === "POSTED" && r.kind !== "TRANSFER")) { const c = String(row.currency), t = totals.get(c) ?? { receipt: 0, payment: 0 }; if (row.kind === "CUSTOMER_RECEIPT") t.receipt += Math.round(Number(row.amount) * 100); else t.payment += Math.round(Number(row.amount) * 100); totals.set(c, t); }
  const params = new URLSearchParams({ q, status, from, to, type: mode === "all" ? typeFilter : type });
  return <section dir="rtl" className="space-y-5 rounded-2xl border border-[#e4d7be] bg-white p-5">
    <div className="flex justify-between gap-3"><h2 className="text-2xl font-black">{title}</h2>{mode !== "all" ? <button className={button} onClick={() => { setPartyId(""); setBankId(""); setCounter(""); setAllocations({}); setBranchId(""); setMethodCode(""); setMethodsRevision(value => value + 1); setMessage(""); editor.current?.showModal(); }}>+ {mode === "payment" ? "سند صرف" : "سند قبض"}</button> : <div className="flex gap-2"><a href="/accounting?tab=receipt" className={button}>القبض</a><a href="/accounting?tab=payment" className={button}>الصرف</a><a href="/accounting?tab=transfer" className={button}>التحويل</a></div>}</div>
    {message && <p role="status" className="rounded-xl bg-amber-50 p-3">{message}</p>}
    <div className="grid gap-3 md:grid-cols-3"><input className={field} value={q} onChange={e => setQ(e.target.value)} aria-label="بحث السندات" placeholder="رقم السند أو الطرف أو المرجع"/><select className={field} value={status} onChange={e => setStatus(e.target.value)} aria-label="حالة السند"><option value="">كل الحالات</option>{Object.entries(statuses).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select>{mode === "all" && <select className={field} aria-label="نوع السند" value={typeFilter} onChange={e => setTypeFilter(e.target.value)}><option value="">كل الأنواع</option>{Object.entries(types).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select>}<label>من<input className={field} type="date" value={from} onChange={e => setFrom(e.target.value)}/></label><label>إلى<input className={field} type="date" value={to} onChange={e => setTo(e.target.value)}/></label><div className="flex items-end gap-2"><a className={button} href={`/api/finance/vouchers/export?${params}&format=xlsx`}>Excel</a><a className={button} target="_blank" href={`/api/finance/vouchers/export?${params}&format=print`}>طباعة / PDF</a></div></div>
    {[...totals].map(([c, t]) => <p key={c} className="rounded-xl bg-[#f4ede1] p-3">{c} • إجمالي القبض المرحل {number(t.receipt / 100)} • الصرف {number(t.payment / 100)} • صافي الحركة {number((t.receipt - t.payment) / 100)} (التحويل الداخلي لا يدخل في الصافي)</p>)}
    <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{["رقم السند", "النوع", "التاريخ", "الطرف", "الحساب", "المبلغ", "الطريقة", "الحالة", "المرجع", "إجراءات"].map(h => <th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{rows.slice((page - 1) * 25, page * 25).map(row => <tr className="border-b" key={String(row.key)}><td className="p-3">{String(row.number)}</td><td>{types[String(row.kind)]}</td><td>{String(row.date)}</td><td>{String(row.partyName)}</td><td>{String(row.bankName)}</td><td dir="ltr">{number(row.amount)} {String(row.currency)}</td><td>{String(row.paymentMethod ?? "تحويل")}</td><td>{statuses[String(row.status)] ?? String(row.status)}</td><td>{String(row.referenceNumber ?? "—")}</td><td><div className="flex gap-2"><button className={button} onClick={() => { setDetail(row); viewer.current?.showModal(); }}>فتح</button>{row.kind !== "TRANSFER" && <><a target="_blank" className={button} href={`/accounting/vouchers/${row.id}/print`}>طباعة</a>{row.status === "DRAFT" && <button className={button} disabled={busy} onClick={() => action(row, "POST")}>ترحيل</button>}</>}</div></td></tr>)}</tbody></table>{!rows.length && <p className="p-8 text-center">لا توجد سندات مطابقة.</p>}</div>
    <div className="flex justify-between"><span>{rows.length} سند • صفحة {page}</span><div className="flex gap-2"><button className={button} disabled={page === 1} onClick={() => setPage(page - 1)}>السابق</button><button className={button} disabled={page * 25 >= rows.length} onClick={() => setPage(page + 1)}>التالي</button></div></div>
    <dialog ref={editor} aria-label={mode === "payment" ? "إضافة سند صرف" : "إضافة سند قبض"} className="w-[min(850px,95vw)] max-h-[90dvh] overflow-auto rounded-2xl border border-amber-300 bg-[#fffdf8] p-6 text-slate-900">
      <form onSubmit={submit} className="space-y-4"><div className="flex justify-between"><h3 className="text-xl font-bold">{mode === "payment" ? "إضافة سند صرف" : "إضافة سند قبض"}</h3><button type="button" disabled={busy} onClick={() => editor.current?.close()} aria-label="إغلاق">✕</button></div>{message && <p role="alert" className="text-red-700">{message}</p>}
        <div className="grid gap-3 md:grid-cols-2"><label>التاريخ<input className={field} name="voucherDate" type="date" required defaultValue={new Date().toISOString().slice(0, 10)}/></label><label>الفرع<select className={field} name="branchId" value={branchId} onChange={event => { setBranchId(event.target.value); setMethodCode(""); }}><option value="">غير مخصص لفرع</option>{data.branches.map(b => <option key={String(b.id)} value={String(b.id)}>{String(b.nameAr)}</option>)}</select></label>
        <label>{mode === "payment" ? "المستفيد / المورد" : "استلام من / العميل"}<select className={field} value={partyId} onChange={e => { setPartyId(e.target.value); setAllocations({}); }}><option value="">طرف آخر — حدد الاسم والحساب المقابل</option>{data.parties.map(p => <option key={String(p.id)} value={String(p.id)}>{String(p.nameAr)}</option>)}</select></label><label>اسم المستفيد / الدافع<input name="beneficiaryName" required={!partyId} className={field}/></label>
        <label>نوع الطرف<select name="beneficiaryType" className={field}><option value="PARTY">عميل / مورد</option><option value="EMPLOYEE">موظف</option><option value="PARTNER">شريك</option><option value="OTHER">آخر</option></select></label><label>الحساب المحاسبي المقابل<select required={!partyId} className={field} value={counter} onChange={e => { setCounter(e.target.value); setAllocations({}); }}><option value="">حساب الذمم الافتراضي للعميل/المورد</option>{data.accounts.map(a => <option key={String(a.id)} value={String(a.id)}>{String(a.code)} — {String(a.nameAr)}</option>)}</select></label>
        <label>البنك أو الصندوق<select className={field} required value={bankId} onChange={e => { setBankId(e.target.value); setAllocations({}); }}><option value="">اختر حساب النقد</option>{data.banks.map(b => <option key={String(b.id)} value={String(b.id)}>{String(b.name)} — {String(b.currency)}</option>)}</select></label><label>المبلغ {currency}<input className={field} name="amount" type="number" required min="0.01" step="0.01"/></label>
        <label>طريقة الدفع<select className={field} name="paymentMethod" required disabled={methodsLoading} value={methodCode} onChange={event => { const code = event.target.value; setMethodCode(code); const method = methods.find(row => row.code === code); if (method?.bankAccountId) { setBankId(String(method.bankAccountId)); setAllocations({}); } }}><option value="">{methodsLoading ? "جارٍ تحميل الطرق المتاحة…" : "اختر طريقة الدفع"}</option>{methods.map(method => <option key={String(method.code)} value={String(method.code)}>{String(method.nameAr)}{method.currency ? ` — ${method.currency}` : ""}</option>)}</select>{!methodsLoading && !methods.length && <small className="text-amber-800">لا توجد طريقة متاحة لهذه الاختيارات. راجع الفرع والبنك وإعدادات طرق الدفع وصلاحياتك.</small>}</label><label>رقم التحويل / المرجع<input className={field} name="referenceNumber"/></label>
        <label>مركز التكلفة<select name="costCenterId" className={field}><option value="">بدون مركز</option>{data.costCenters.map(c => <option key={String(c.id)} value={String(c.id)}>{String(c.code)} — {String(c.nameAr)}</option>)}</select></label><label>مرفق<input className={field} type="file" name="attachment" accept=".pdf,.jpg,.jpeg,.png,.xlsx"/></label><label className="md:col-span-2">البيان<textarea className={field} name="description" required/></label></div>
        <p className="text-sm text-slate-500">الشيكات الآجلة تُسجل من صفحة الشيكات حتى لا يُخصم البنك قبل الصرف أو التحصيل. الخصم التجاري يُعالج بإشعار محاسبي مرتبط بالفاتورة.</p>
        {!counter && !!available.length && <div><h4 className="font-bold">توزيع المبلغ على فاتورة أو أكثر</h4>{available.map(i => <label key={String(i.id)} className="my-2 grid grid-cols-2 items-center gap-3"><span>{String(i.number)} • المستحق {number(i.outstanding)} {String(i.currency)}</span><input aria-label={`تخصيص ${i.number}`} className={field} type="number" min="0" max={Number(i.outstanding)} step="0.01" value={allocations[String(i.id)] ?? ""} onChange={e => setAllocations({ ...allocations, [String(i.id)]: e.target.value })}/></label>)}</div>}
        <button className={button} disabled={busy || methodsLoading || !methodCode}>حفظ {mode === "payment" ? "سند الصرف" : "سند القبض"} كمسودة</button>
      </form>
    </dialog>
    <dialog ref={viewer} aria-label="تفاصيل السند" className="w-[min(800px,95vw)] max-h-[90dvh] overflow-auto rounded-2xl border border-amber-300 bg-[#fffdf8] p-6 text-slate-900">{detail && <div className="space-y-4"><div className="flex justify-between"><h3 className="text-xl font-bold">{types[String(detail.kind)]} {String(detail.number)}</h3><button onClick={() => viewer.current?.close()} aria-label="إغلاق التفاصيل">✕</button></div><p>{String(detail.partyName)} • {number(detail.amount)} {String(detail.currency)} • {statuses[String(detail.status)]}</p><p>{String(detail.description ?? detail.notes ?? "")}</p><p>التاريخ {String(detail.date)} • المرجع {String(detail.referenceNumber ?? "—")}</p>{!!detail.journalEntryId && <a className={button} href={`/accounting?tab=journals&journalId=${detail.journalEntryId}`}>فتح القيد المحاسبي</a>}{detail.kind !== "TRANSFER" && (detail.allocations as Row[]).map(a => <p key={String(a.id)}>الفاتورة {String((a.sale as Row | null)?.invoiceNumber ?? (a.purchase as Row | null)?.purchaseNumber)}: {number(a.amount)}</p>)}{detail.kind !== "TRANSFER" && detail.status === "POSTED" && <form onSubmit={e => { e.preventDefault(); void action(detail, "CANCEL", String(new FormData(e.currentTarget).get("reason"))); }} className="space-y-3 border-t pt-4"><p>الإلغاء يعكس القيد وحركة البنك ويعيد المبالغ المستحقة للفواتير. يحتفظ النظام بالسند وسجل العملية.</p><input name="reason" required className={field} placeholder="سبب الإلغاء"/><button className={button} disabled={busy}>تأكيد الإلغاء والعكس</button></form>}</div>}</dialog>
  </section>;
}
